# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("organization", "0001_initial"),
        ("procedures", "0001_initial"),
        ("sales", "0001_initial"),
        ("technology", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrillBit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                (
                    "bit_type",
                    models.CharField(
                        choices=[("FC", "Fixed Cutter (PDC)"), ("RC", "Roller Cone")],
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=3, help_text="Size in inches", max_digits=6
                    ),
                ),
                ("iadc_code", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_STOCK", "In Stock"),
                            ("ASSIGNED", "Assigned to WO"),
                            ("IN_PRODUCTION", "In Production"),
                            ("QC_PENDING", "QC Pending"),
                            ("READY", "Ready for Dispatch"),
                            ("DISPATCHED", "Dispatched"),
                            ("IN_FIELD", "In Field"),
                            ("RETURNED", "Returned"),
                            ("SCRAPPED", "Scrapped"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_footage",
                    models.IntegerField(default=0, help_text="Total feet drilled"),
                ),
                (
                    "run_count",
                    models.IntegerField(default=0, help_text="Number of runs"),
                ),
                ("qr_code", models.CharField(blank=True, max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stored_bits",
                        to="sales.warehouse",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drill_bits",
                        to="sales.customer",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drill_bits",
                        to="technology.design",
                    ),
                ),
                (
                    "rig",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.rig",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.well",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drill Bit",
                "verbose_name_plural": "Drill Bits",
                "db_table": "drill_bits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wo_number", models.CharField(max_length=30, unique=True)),
                (
                    "wo_type",
                    models.CharField(
                        choices=[
                            ("FC_NEW", "FC New Build"),
                            ("FC_REWORK", "FC Rework"),
                            ("FC_REPAIR", "FC Repair"),
                            ("RC_NEW", "RC New Build"),
                            ("RC_REWORK", "RC Rework"),
                            ("RC_REPAIR", "RC Repair"),
                            ("RERUN", "Rerun"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("RELEASED", "Released"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("QC_PENDING", "QC Pending"),
                            ("QC_PASSED", "QC Passed"),
                            ("QC_FAILED", "QC Failed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="technology.bom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="sales.customer",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.department",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="technology.design",
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="procedures.procedure",
                    ),
                ),
                (
                    "rig",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.rig",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.well",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
                "db_table": "work_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BitEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_number", models.IntegerField(blank=True, null=True)),
                (
                    "hours_run",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("footage_drilled", models.IntegerField(blank=True, null=True)),
                (
                    "depth_in",
                    models.IntegerField(blank=True, help_text="Feet", null=True),
                ),
                (
                    "depth_out",
                    models.IntegerField(blank=True, help_text="Feet", null=True),
                ),
                ("evaluation_date", models.DateField()),
                ("inner_rows", models.CharField(blank=True, max_length=10)),
                ("outer_rows", models.CharField(blank=True, max_length=10)),
                (
                    "dull_char",
                    models.CharField(
                        blank=True, help_text="Dull characteristic", max_length=10
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=10)),
                ("bearing_seal", models.CharField(blank=True, max_length=10)),
                ("gauge", models.CharField(blank=True, max_length=10)),
                ("other_char", models.CharField(blank=True, max_length=10)),
                ("reason_pulled", models.CharField(blank=True, max_length=100)),
                (
                    "overall_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("SCRAPPED", "Scrapped"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STOCK", "Return to Stock"),
                            ("REWORK", "Rework Required"),
                            ("REPAIR", "Repair Required"),
                            ("RERUN", "Rerun as-is"),
                            ("SCRAP", "Scrap"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("findings", models.TextField(blank=True)),
                ("recommendations_detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_evaluations",
                        to="technology.design",
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rig",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.rig",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.well",
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "resulting_work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_evaluations",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bit Evaluation",
                "verbose_name_plural": "Bit Evaluations",
                "db_table": "bit_evaluations",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DRAWING", "Drawing"),
                            ("SPECIFICATION", "Specification"),
                            ("PROCEDURE", "Procedure"),
                            ("INSPECTION", "Inspection Report"),
                            ("CERTIFICATE", "Certificate"),
                            ("CUSTOMER", "Customer Document"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="wo_documents/")),
                ("version", models.CharField(blank=True, max_length=20)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order Document",
                "verbose_name_plural": "Work Order Documents",
                "db_table": "work_order_documents",
                "ordering": ["work_order", "document_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "issued_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "consumed_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "returned_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bom_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="technology.bomline",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wo_consumptions",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order Material",
                "verbose_name_plural": "Work Order Materials",
                "db_table": "work_order_materials",
                "ordering": ["work_order", "inventory_item__name"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="wo_photos/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "stage",
                    models.CharField(
                        blank=True, help_text="Production stage", max_length=50
                    ),
                ),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                (
                    "taken_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order Photo",
                "verbose_name_plural": "Work Order Photos",
                "db_table": "work_order_photos",
                "ordering": ["work_order", "-taken_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderTimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("activity_type", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procedures.procedurestep",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wo_time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order Time Log",
                "verbose_name_plural": "Work Order Time Logs",
                "db_table": "work_order_time_logs",
                "ordering": ["work_order", "-start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="drillbit",
            index=models.Index(fields=["serial_number"], name="db_serial_idx"),
        ),
        migrations.AddIndex(
            model_name="drillbit",
            index=models.Index(fields=["status"], name="db_status_idx"),
        ),
        migrations.AddIndex(
            model_name="drillbit",
            index=models.Index(fields=["bit_type"], name="db_type_idx"),
        ),
        migrations.AddIndex(
            model_name="drillbit",
            index=models.Index(
                fields=["customer", "status"], name="db_customer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["wo_number"], name="wo_wo_number_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["status"], name="wo_status_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["status", "priority"], name="wo_status_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["status", "due_date"], name="wo_status_due_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["customer", "status"], name="wo_customer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["assigned_to", "status"], name="wo_assigned_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["due_date"], name="wo_due_date_idx"),
        ),
    ]
