# Generated by Django 5.2.8 on 2025-12-05 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0004_materiallot_materialconsumption"),
        ("sales", "0002_initial"),
        ("technology", "0001_initial"),
        ("workorders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderCost",
            fields=[
                (
                    "work_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cost_summary",
                        serialize=False,
                        to="workorders.workorder",
                    ),
                ),
                (
                    "estimated_labor_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "actual_labor_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "labor_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "estimated_material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "actual_material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "overhead_rate_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "subcontractor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_actual_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Order Cost",
                "verbose_name_plural": "Work Order Costs",
                "db_table": "work_order_costs",
            },
        ),
        migrations.AddField(
            model_name="drillbit",
            name="accounting_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ARDT_OWNED", "ARDT Owned"),
                    ("CUSTOMER_OWNED", "Customer Owned"),
                    ("ON_CONSIGNMENT", "On Consignment"),
                    ("SOLD", "Sold"),
                    ("WRITTEN_OFF", "Written Off"),
                ],
                default="ARDT_OWNED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="base_serial_number",
            field=models.CharField(
                blank=True,
                help_text="Original serial number before any repairs (for Aramco: stays same)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="current_book_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current accounting book value",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="current_display_serial",
            field=models.CharField(
                blank=True,
                help_text="Current display serial (e.g., SN-R1, SN-R2 for Aramco)",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="is_aramco_contract",
            field=models.BooleanField(
                default=False,
                help_text="If true, serial increments on repair (R1, R2, R3)",
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="last_repair_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="last_repair_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="original_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Original purchase/manufacturing cost",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="physical_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AT_ARDT", "At ARDT Facility"),
                    ("AT_CUSTOMER", "At Customer Site"),
                    ("IN_TRANSIT", "In Transit"),
                    ("AT_RIG", "At Rig Site"),
                    ("SCRAPPED", "Scrapped"),
                ],
                default="AT_ARDT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="revision_number",
            field=models.IntegerField(
                default=0,
                help_text="Number of repairs/revisions (0=new, 1=R1, 2=R2, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="total_repair_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total cost of all repairs",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="total_repairs",
            field=models.IntegerField(
                default=0, help_text="Total number of repairs performed"
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="actual_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual total cost after completion",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_work_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="disposition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RETURN_TO_STOCK", "Return to Stock"),
                    ("SHIP_TO_CUSTOMER", "Ship to Customer"),
                    ("SCRAP", "Scrap"),
                    ("PENDING", "Pending Decision"),
                ],
                help_text="Final disposition of the bit",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="disposition_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated total cost before work starts",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="repair_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REDRESS", "Redress"),
                    ("MAJOR_REPAIR", "Major Repair"),
                    ("MINOR_REPAIR", "Minor Repair"),
                    ("REBUILD", "Rebuild"),
                    ("REFURBISH", "Refurbish"),
                ],
                help_text="Type of repair for repair work orders",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="True if work order requires management approval",
            ),
        ),
        migrations.CreateModel(
            name="ProcessRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_number", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "repair_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REDRESS", "Redress"),
                            ("MAJOR_REPAIR", "Major Repair"),
                            ("MINOR_REPAIR", "Minor Repair"),
                            ("REBUILD", "Rebuild"),
                            ("REFURBISH", "Refurbish"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "bit_types",
                    models.JSONField(
                        blank=True,
                        help_text="List of applicable bit types, e.g., ['FC', 'RC']",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "estimated_duration_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "estimated_labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Route",
                "verbose_name_plural": "Process Routes",
                "db_table": "process_routes",
                "ordering": ["route_number"],
            },
        ),
        migrations.CreateModel(
            name="ProcessRouteOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        help_text="Operation sequence number (10, 20, 30...)"
                    ),
                ),
                ("operation_code", models.CharField(max_length=20)),
                ("operation_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("work_center", models.CharField(blank=True, max_length=50)),
                (
                    "standard_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "labor_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("requires_qc", models.BooleanField(default=False)),
                ("qc_checklist", models.TextField(blank=True)),
                ("safety_requirements", models.TextField(blank=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="workorders.processroute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Route Operation",
                "verbose_name_plural": "Process Route Operations",
                "db_table": "process_route_operations",
                "ordering": ["route", "sequence"],
                "unique_together": {("route", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="RepairApprovalAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("requires_justification", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "authorized_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approval_authorities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Repair Approval Authority",
                "verbose_name_plural": "Repair Approval Authorities",
                "db_table": "repair_approval_authorities",
                "ordering": ["min_amount"],
            },
        ),
        migrations.CreateModel(
            name="RepairBOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("ISSUED", "Issued"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "actual_material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_repair_boms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master_bom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repair_boms",
                        to="technology.bom",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_boms",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repair BOM",
                "verbose_name_plural": "Repair BOMs",
                "db_table": "repair_boms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BitRepairHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repair_number",
                    models.IntegerField(
                        help_text="Repair sequence number for this bit"
                    ),
                ),
                ("repair_date", models.DateField()),
                (
                    "repair_type",
                    models.CharField(
                        choices=[
                            ("REDRESS", "Redress"),
                            ("MAJOR_REPAIR", "Major Repair"),
                            ("MINOR_REPAIR", "Minor Repair"),
                            ("REBUILD", "Rebuild"),
                            ("REFURBISH", "Refurbish"),
                        ],
                        max_length=20,
                    ),
                ),
                ("work_performed", models.TextField(blank=True)),
                ("parts_replaced", models.TextField(blank=True)),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("condition_before", models.CharField(blank=True, max_length=50)),
                ("condition_after", models.CharField(blank=True, max_length=50)),
                ("serial_before", models.CharField(blank=True, max_length=60)),
                ("serial_after", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_repair_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_history",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_repair_records",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bit Repair History",
                "verbose_name_plural": "Bit Repair Histories",
                "db_table": "bit_repair_history",
                "ordering": ["drill_bit", "-repair_number"],
                "unique_together": {("drill_bit", "repair_number")},
            },
        ),
        migrations.CreateModel(
            name="OperationExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("qc_performed", models.BooleanField(default=False)),
                ("qc_passed", models.BooleanField(blank=True, null=True)),
                ("qc_notes", models.TextField(blank=True)),
                ("operator_notes", models.TextField(blank=True)),
                ("issues_encountered", models.TextField(blank=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_executions",
                        to="workorders.workorder",
                    ),
                ),
                (
                    "route_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="workorders.processrouteoperation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Execution",
                "verbose_name_plural": "Operation Executions",
                "db_table": "operation_executions",
                "ordering": ["work_order", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["work_order", "status"],
                        name="operation_e_work_or_b1e0c2_idx",
                    ),
                    models.Index(
                        fields=["status"], name="operation_e_status_e1d660_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RepairBOMLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField()),
                (
                    "quantity_required",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "quantity_issued",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "quantity_consumed",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "quantity_returned",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repair_bom_lines",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "repair_bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="workorders.repairbom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repair BOM Line",
                "verbose_name_plural": "Repair BOM Lines",
                "db_table": "repair_bom_lines",
                "ordering": ["repair_bom", "line_number"],
                "unique_together": {("repair_bom", "line_number")},
            },
        ),
        migrations.CreateModel(
            name="RepairEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation_number", models.CharField(max_length=30, unique=True)),
                ("inner_rows_grade", models.CharField(blank=True, max_length=10)),
                ("outer_rows_grade", models.CharField(blank=True, max_length=10)),
                ("dull_characteristic", models.CharField(blank=True, max_length=20)),
                ("location_code", models.CharField(blank=True, max_length=10)),
                ("gauge_condition", models.CharField(blank=True, max_length=20)),
                ("damage_assessment", models.TextField()),
                ("recommended_repair", models.TextField(blank=True)),
                (
                    "estimated_labor_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "estimated_labor_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estimated_material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "estimated_overhead",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("repair_recommended", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="workorders.repairapprovalauthority",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_evaluations",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resulting_work_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repair_evaluation",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repair Evaluation",
                "verbose_name_plural": "Repair Evaluations",
                "db_table": "repair_evaluations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="repair_eval_status_cb653c_idx"
                    ),
                    models.Index(
                        fields=["drill_bit", "status"],
                        name="repair_eval_drill_b_4f41a9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalvageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salvage_number", models.CharField(max_length=30, unique=True)),
                (
                    "salvage_type",
                    models.CharField(
                        choices=[
                            ("BODY", "Bit Body"),
                            ("CUTTER", "Cutter"),
                            ("NOZZLE", "Nozzle"),
                            ("BEARING", "Bearing"),
                            ("CONE", "Cone"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available for Reuse"),
                            ("RESERVED", "Reserved"),
                            ("CONSUMED", "Consumed in Repair"),
                            ("SCRAPPED", "Scrapped"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "condition_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Condition rating 1-10 (10=excellent)",
                        null=True,
                    ),
                ),
                ("reuse_potential", models.CharField(blank=True, max_length=100)),
                ("storage_location", models.CharField(blank=True, max_length=100)),
                ("salvage_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("reused_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="salvage_photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_salvage_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salvaged_items",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "reused_in_work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reused_salvage_items",
                        to="workorders.workorder",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salvage_items",
                        to="sales.warehouse",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salvaged_items",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salvage Item",
                "verbose_name_plural": "Salvage Items",
                "db_table": "salvage_items",
                "ordering": ["-salvage_date"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="salvage_ite_status_2549ce_idx"
                    ),
                    models.Index(
                        fields=["salvage_type"], name="salvage_ite_salvage_26e1d9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StatusTransitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(max_length=30)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for status change"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Transition Log",
                "verbose_name_plural": "Status Transition Logs",
                "db_table": "status_transition_logs",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="status_tran_content_929386_idx",
                    ),
                    models.Index(
                        fields=["changed_at"], name="status_tran_changed_8c17d1_idx"
                    ),
                ],
            },
        ),
    ]
