# Generated by Django 5.2.8 on 2025-12-05 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("procedures", "0001_initial"),
        ("sales", "0002_initial"),
        ("technology", "0001_initial"),
        ("workorders", "0002_workordercost_drillbit_accounting_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitevaluation",
            name="rig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bit_evaluations",
                to="sales.rig",
            ),
        ),
        migrations.AlterField(
            model_name="bitevaluation",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bit_evaluations",
                to="sales.well",
            ),
        ),
        migrations.AlterField(
            model_name="drillbit",
            name="rig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drill_bits",
                to="sales.rig",
            ),
        ),
        migrations.AlterField(
            model_name="drillbit",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drill_bits",
                to="sales.well",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="organization.department",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="rig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="sales.rig",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="sales.well",
            ),
        ),
        migrations.AlterField(
            model_name="workorderdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_wo_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workordermaterial",
            name="bom_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wo_materials",
                to="technology.bomline",
            ),
        ),
        migrations.AlterField(
            model_name="workorderphoto",
            name="taken_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taken_wo_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workordertimelog",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wo_time_logs",
                to="procedures.procedurestep",
            ),
        ),
    ]
