# Generated by Django 5.1.15 on 2025-12-12 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_week3_field_data_capture"),
        ("workorders", "0004_add_related_name_to_status_transition_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BitSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., '8.500'", max_length=20, unique=True
                    ),
                ),
                (
                    "size_decimal",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Size in decimal inches (e.g., 8.500)",
                        max_digits=6,
                    ),
                ),
                (
                    "size_display",
                    models.CharField(
                        help_text="Display format (e.g., '8 1/2\"')", max_length=20
                    ),
                ),
                (
                    "size_inches",
                    models.CharField(
                        help_text="Fraction format (e.g., '8 1/2')", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bit Size",
                "verbose_name_plural": "Bit Sizes",
                "db_table": "bit_sizes",
                "ordering": ["size_decimal"],
            },
        ),
        migrations.CreateModel(
            name="BitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Model code (e.g., 'GT65RHS')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "series",
                    models.CharField(
                        blank=True,
                        help_text="Series (GT, HD, MM, FX, etc.)",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bit Type",
                "verbose_name_plural": "Bit Types",
                "db_table": "bit_types",
                "ordering": ["series", "code"],
            },
        ),
        migrations.AddField(
            model_name="drillbit",
            name="backload_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Times returned to factory"
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="deployment_count",
            field=models.PositiveIntegerField(default=0, help_text="Times deployed"),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="last_backload_date",
            field=models.DateField(
                blank=True, help_text="Last backload date", null=True
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="last_deployed_date",
            field=models.DateField(
                blank=True, help_text="Last deployment date", null=True
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("DEPLOYED", "Deployed"),
                    ("BACKLOADED", "Backloaded"),
                    ("EVALUATION", "In Evaluation"),
                    ("HOLD", "On Hold"),
                    ("IN_REPAIR", "In Repair"),
                    ("REPAIRED", "Repaired"),
                    ("USA_REPAIR", "USA Repair"),
                    ("RERUN", "Rerun Ready"),
                    ("SCRAP", "Scrapped"),
                    ("SAVED_BODY", "Saved Body"),
                ],
                default="NEW",
                help_text="Phase 2 lifecycle tracking status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="mat_number",
            field=models.CharField(
                blank=True, help_text="MAT number for inventory", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="received_date",
            field=models.DateField(
                blank=True, help_text="Date bit was received", null=True
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="repair_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Repairs completed at ARDT"
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="repair_count_usa",
            field=models.PositiveIntegerField(
                default=0, help_text="Repairs completed in USA"
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="rerun_count_factory",
            field=models.PositiveIntegerField(
                default=0, help_text="Factory reruns (charged)"
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="rerun_count_field",
            field=models.PositiveIntegerField(
                default=0, help_text="Field reruns (no charge)"
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="scrap_date",
            field=models.DateField(
                blank=True, help_text="Date bit was scrapped", null=True
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="bit_size_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Standard bit size reference",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drill_bits",
                to="workorders.bitsize",
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Product model (e.g., GT65RHS)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drill_bits",
                to="workorders.bittype",
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("WAREHOUSE", "Warehouse"),
                            ("REPAIR_SHOP", "Repair Shop"),
                            ("RIG", "Rig Site"),
                            ("EVALUATION", "Evaluation Area"),
                            ("QC", "QC Area"),
                            ("SCRAP", "Scrap Yard"),
                            ("USA", "USA Facility"),
                            ("TRANSIT", "In Transit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rig",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to rig if location_type is RIG",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_locations",
                        to="sales.rig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "locations",
                "ordering": ["location_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="drillbit",
            name="bit_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Current physical location (Phase 2)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_bits",
                to="workorders.location",
            ),
        ),
        migrations.CreateModel(
            name="BitEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received (New)"),
                            ("DEPLOYED", "Deployed to Rig"),
                            ("BACKLOADED", "Backloaded to Factory"),
                            ("EVALUATION_START", "Evaluation Started"),
                            ("EVALUATION_COMPLETE", "Evaluation Complete"),
                            ("REPAIR_DECISION", "Decision: Repair"),
                            ("RERUN_DECISION_FACTORY", "Decision: Rerun (Factory)"),
                            ("RERUN_DECISION_FIELD", "Decision: Rerun (Field)"),
                            ("USA_REPAIR_DECISION", "Decision: USA Repair"),
                            ("SCRAP_DECISION", "Decision: Scrap"),
                            ("HOLD_DECISION", "Decision: Hold"),
                            ("REPAIR_START", "Repair Started"),
                            ("REPAIR_COMPLETE", "Repair Complete"),
                            ("USA_REPAIR_SENT", "Sent to USA"),
                            ("USA_REPAIR_RECEIVED", "Received from USA"),
                            ("QC_PASS", "QC Passed"),
                            ("QC_FAIL", "QC Failed"),
                            ("TRANSFER", "Stock Transfer"),
                            ("RELOCATION", "Relocation (Rig to Rig)"),
                            ("SCRAPPED", "Scrapped"),
                            ("BODY_SAVED", "Body Saved"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bit_events",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_bit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rig",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_events",
                        to="sales.rig",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_events",
                        to="sales.well",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_events",
                        to="workorders.workorder",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_events_from",
                        to="workorders.location",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bit_events",
                        to="workorders.location",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_events_to",
                        to="workorders.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bit Event",
                "verbose_name_plural": "Bit Events",
                "db_table": "bit_events",
                "ordering": ["-event_date"],
                "indexes": [
                    models.Index(
                        fields=["bit", "event_date"],
                        name="bit_events_bit_id_201c1f_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="bit_events_event_t_1b7af6_idx"
                    ),
                    models.Index(
                        fields=["performed_by", "event_date"],
                        name="bit_events_perform_6e3064_idx",
                    ),
                ],
            },
        ),
    ]
