# Generated by Django 5.1.15 on 2025-12-22
# Custom migration to move BitSize and BitType from workorders to technology
# Uses SeparateDatabaseAndState because tables are being transferred, not deleted

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0014_bitsize_alter_breakerslot_compatible_sizes_and_more"),
        ("workorders", "0006_bittype_phase2_fields"),
    ]

    operations = [
        # Remove BitType.size FK before deleting model (state-only)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="bittype",
                    name="size",
                ),
            ],
            database_operations=[],
        ),
        # Update DrillBit FKs to point to technology models (state-only - same tables)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="drillbit",
                    name="bit_size_ref",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Standard bit size reference",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drill_bits",
                        to="technology.bitsize",
                    ),
                ),
                migrations.AlterField(
                    model_name="drillbit",
                    name="product_type",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Product model (e.g., GT65RHS)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drill_bits",
                        to="technology.bittype",
                    ),
                ),
            ],
            database_operations=[],
        ),
        # Delete models from workorders state (state-only - tables stay for technology)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="BitSize",
                ),
                migrations.DeleteModel(
                    name="BitType",
                ),
            ],
            database_operations=[],
        ),
    ]
