# Generated by Django 5.1.15 on 2026-01-18 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_landingcosttype_grnline_variant_and_more"),
        ("workorders", "0008_alter_drillbit_bit_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="bit_received_date",
            field=models.DateField(
                blank=True,
                help_text="Date bit was received for this work order",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="brazing_mat_no",
            field=models.CharField(
                blank=True,
                help_text="Brazing MAT# - Free text (e.g., 123456M1, 3251477-Testing Trifex)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="contract_no",
            field=models.CharField(
                blank=True, help_text="Contract Number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="drss_no",
            field=models.CharField(
                blank=True, help_text="DRSS Request Number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="eng_review_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="evaluated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wo_evaluations_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="from_location_text",
            field=models.CharField(
                blank=True,
                help_text="Source location text (e.g., ARAMCO, LSTK, ARDT-LV4)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="qc_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="qc_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wo_qc_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="reference_po_no",
            field=models.CharField(
                blank=True, help_text="Reference/PO Number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="reviewed_by_eng",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wo_eng_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="system_mat_no",
            field=models.CharField(
                blank=True,
                help_text="System L5 MAT# - Fixed, shared with client/sales",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="APIThreadInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_number", models.CharField(max_length=30, unique=True)),
                ("pin_size", models.CharField(blank=True, max_length=50)),
                ("pin_face_ok", models.BooleanField(blank=True, null=True)),
                ("pin_face_remarks", models.CharField(blank=True, max_length=200)),
                ("thread_ok", models.BooleanField(blank=True, null=True)),
                ("thread_remarks", models.CharField(blank=True, max_length=200)),
                ("pitch_gauge_ok", models.BooleanField(blank=True, null=True)),
                ("pitch_gauge_remarks", models.CharField(blank=True, max_length=200)),
                ("mud_seal_ok", models.BooleanField(blank=True, null=True)),
                ("mud_seal_remarks", models.CharField(blank=True, max_length=200)),
                ("other_observation", models.TextField(blank=True)),
                ("pin_height", models.CharField(blank=True, max_length=50)),
                (
                    "thread_repair_required",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Required"), ("NO", "Not Required")],
                        max_length=10,
                    ),
                ),
                ("repair_brush_selected", models.BooleanField(default=False)),
                ("upper_section_replacement", models.BooleanField(default=False)),
                ("after_pin_face_ok", models.BooleanField(blank=True, null=True)),
                (
                    "after_pin_face_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                ("after_thread_ok", models.BooleanField(blank=True, null=True)),
                ("after_thread_remarks", models.CharField(blank=True, max_length=200)),
                ("after_pitch_gauge_ok", models.BooleanField(blank=True, null=True)),
                (
                    "after_pitch_gauge_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                ("after_mud_seal_ok", models.BooleanField(blank=True, null=True)),
                (
                    "after_mud_seal_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "initial_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL", "Conditional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "final_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL", "Conditional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inspection_date", models.DateField(blank=True, null=True)),
                ("qc_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_inspections_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_inspections_qc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_thread_inspections",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Thread Inspection",
                "verbose_name_plural": "API Thread Inspections",
                "db_table": "api_thread_inspections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CutterEvaluationMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[
                            ("ARDT", "ARDT Evaluation"),
                            ("ENGINEER", "Engineer Evaluation"),
                            ("REWORK", "Rework Evaluation"),
                            ("DIE_CHECK", "Die Check"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "evaluation_number",
                    models.IntegerField(
                        default=1,
                        help_text="Evaluation sequence (for multiple evaluations)",
                    ),
                ),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("qc_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ardt_remark",
                    models.TextField(blank=True, help_text="ARDT evaluation remarks"),
                ),
                (
                    "eng_remark",
                    models.TextField(
                        blank=True, help_text="Engineer evaluation remarks"
                    ),
                ),
                ("general_remark", models.TextField(blank=True)),
                (
                    "ardt_matrix_buildup",
                    models.BooleanField(
                        default=False, help_text="ARDT Matrix Build up required"
                    ),
                ),
                (
                    "eng_matrix_buildup",
                    models.BooleanField(
                        default=False, help_text="Engineer Matrix Build up required"
                    ),
                ),
                (
                    "ncr_ref_no",
                    models.CharField(
                        blank=True,
                        help_text="NCR Reference Number for rework",
                        max_length=50,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cutter_evaluations_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cutter_evaluations_qc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutter_evaluations",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Evaluation Matrix",
                "verbose_name_plural": "Cutter Evaluation Matrices",
                "db_table": "cutter_evaluation_matrices",
                "ordering": ["work_order", "evaluation_type", "evaluation_number"],
                "unique_together": {
                    ("work_order", "evaluation_type", "evaluation_number")
                },
            },
        ),
        migrations.CreateModel(
            name="EvaluationChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bit_cleanliness",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                (
                    "bit_cleanliness_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "paperwork",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                ("paperwork_remarks", models.CharField(blank=True, max_length=200)),
                (
                    "bit_stamping",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                ("bit_stamping_remarks", models.CharField(blank=True, max_length=200)),
                (
                    "die_check",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                ("die_check_remarks", models.CharField(blank=True, max_length=200)),
                (
                    "ring_gauge_go",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                ("ring_gauge_go_remarks", models.CharField(blank=True, max_length=200)),
                (
                    "ring_gauge_no_go",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                (
                    "ring_gauge_no_go_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "nozzle_bore_liner",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                (
                    "nozzle_bore_liner_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "nozzle_threads",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                (
                    "nozzle_threads_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "apex",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                ("apex_remarks", models.CharField(blank=True, max_length=200)),
                (
                    "junk_slot",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                ("junk_slot_remarks", models.CharField(blank=True, max_length=200)),
                (
                    "breaker_slot",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                ("breaker_slot_remarks", models.CharField(blank=True, max_length=200)),
                (
                    "body_condition",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                (
                    "body_condition_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "mud_seal_surface",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                (
                    "mud_seal_surface_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "api_pin",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                ("api_pin_remarks", models.CharField(blank=True, max_length=200)),
                (
                    "inner_diameter",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        max_length=10,
                    ),
                ),
                (
                    "inner_diameter_remarks",
                    models.CharField(blank=True, max_length=200),
                ),
                ("overall_pass", models.BooleanField(blank=True, null=True)),
                ("general_remarks", models.TextField(blank=True)),
                ("inspection_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_checklists_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_checklist",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Checklist",
                "verbose_name_plural": "Evaluation Checklists",
                "db_table": "evaluation_checklists",
            },
        ),
        migrations.CreateModel(
            name="InstructionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "instruction_text",
                    models.TextField(
                        help_text="The instruction to display when conditions match"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (5, "Normal"),
                            (8, "High"),
                            (10, "Critical"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "applies_to_wo_types",
                    models.JSONField(
                        blank=True,
                        help_text="List of WO types this applies to, e.g., ['FC_REPAIR', 'FC_REWORK']",
                        null=True,
                    ),
                ),
                (
                    "applies_to_bit_types",
                    models.JSONField(
                        blank=True,
                        help_text="List of bit types, e.g., ['FC', 'RC']",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_instruction_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_instruction_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction Rule",
                "verbose_name_plural": "Instruction Rules",
                "db_table": "instruction_rules",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="InstructionRuleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_source",
                    models.CharField(
                        choices=[
                            ("wo", "Work Order"),
                            ("bit", "Drill Bit"),
                            ("design", "Design"),
                            ("customer", "Customer"),
                            ("bom", "BOM"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field name to check (e.g., 'mat_number', 'size')",
                        max_length=100,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("ne", "Not Equals"),
                            ("contains", "Contains"),
                            ("starts", "Starts With"),
                            ("ends", "Ends With"),
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("in", "In List"),
                            ("not_in", "Not In List"),
                            ("null", "Is Null"),
                            ("not_null", "Is Not Null"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value to compare against (comma-separated for IN/NOT_IN)",
                        max_length=500,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="workorders.instructionrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction Rule Condition",
                "verbose_name_plural": "Instruction Rule Conditions",
                "db_table": "instruction_rule_conditions",
                "ordering": ["rule", "id"],
            },
        ),
        migrations.CreateModel(
            name="LPTReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.CharField(max_length=30, unique=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("NEW_CUTTER", "New Cutters"),
                            ("RECLAIM_CUTTER", "Reclaimed Cutters"),
                            ("NEW_BIT", "New Bit"),
                            ("REPAIR_BEFORE", "Before Repair"),
                            ("REPAIR_AFTER", "After Repair (Tip Grinding)"),
                            ("DEBRAZED", "Debrazed Cutters"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "technique",
                    models.CharField(
                        default="Fluorescent - Washable Technique",
                        help_text="Testing technique used",
                        max_length=100,
                    ),
                ),
                (
                    "procedure_ref",
                    models.CharField(
                        default="SA-PP-1013 Liquid Penetrant Testing",
                        help_text="Procedure reference",
                        max_length=100,
                    ),
                ),
                ("cleaner_product", models.CharField(default="Water", max_length=100)),
                ("cleaner_batch", models.CharField(blank=True, max_length=50)),
                ("cleaner_expiry", models.DateField(blank=True, null=True)),
                ("penetrant_product", models.CharField(blank=True, max_length=100)),
                ("penetrant_batch", models.CharField(blank=True, max_length=50)),
                ("penetrant_expiry", models.DateField(blank=True, null=True)),
                ("developer_product", models.CharField(blank=True, max_length=100)),
                ("developer_batch", models.CharField(blank=True, max_length=50)),
                ("developer_expiry", models.DateField(blank=True, null=True)),
                ("surface_temperature", models.CharField(blank=True, max_length=50)),
                ("penetrant_dwell_time", models.CharField(blank=True, max_length=50)),
                ("light_intensity", models.CharField(blank=True, max_length=50)),
                ("developer_dwell_time", models.CharField(blank=True, max_length=50)),
                ("operator_date", models.DateField(blank=True, null=True)),
                ("evaluator_date", models.DateField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL", "Conditional Pass"),
                            ("PENDING", "Pending Evaluation"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "disposition",
                    models.TextField(blank=True, help_text="Disposition/Remarks"),
                ),
                (
                    "cutter_details",
                    models.JSONField(
                        blank=True,
                        help_text="Array of cutter details: [{size, type, sap_no, qty, category, remark}]",
                        null=True,
                    ),
                ),
                (
                    "photo_before",
                    models.ImageField(blank=True, null=True, upload_to="lpt_photos/"),
                ),
                (
                    "photo_after",
                    models.ImageField(blank=True, null=True, upload_to="lpt_photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lpt_evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lpt_reports_evaluated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lpt_operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lpt_reports_operated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lpt_reports",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "LPT Report",
                "verbose_name_plural": "LPT Reports",
                "db_table": "lpt_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CutterEvaluationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blade_number", models.IntegerField(help_text="Blade number (1-12)")),
                (
                    "cutter_position",
                    models.IntegerField(
                        help_text="Cutter position from ID to Gauge (1-15+)"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("O", "OK - No action needed"),
                            ("X", "Replace"),
                            ("R", "Rotate"),
                            ("S", "Spin"),
                            ("D", "Damaged"),
                            ("M", "Missing"),
                            ("", "Not evaluated"),
                        ],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "cutter_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New Cutter"),
                            ("RECLAIM", "Reclaim Cutter"),
                            ("EXISTING", "Existing (no change)"),
                        ],
                        help_text="Source of replacement cutter",
                        max_length=10,
                    ),
                ),
                (
                    "cutter_size",
                    models.CharField(
                        blank=True,
                        help_text="Cutter size code (e.g., 1313, 1608)",
                        max_length=10,
                    ),
                ),
                (
                    "cutter_type",
                    models.CharField(
                        blank=True, help_text="Cutter type/HDBS code", max_length=20
                    ),
                ),
                ("cutter_chamfer", models.CharField(blank=True, max_length=10)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "cutter_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Replacement cutter from inventory",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_entries",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="workorders.cutterevaluationmatrix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Evaluation Entry",
                "verbose_name_plural": "Cutter Evaluation Entries",
                "db_table": "cutter_evaluation_entries",
                "ordering": ["matrix", "blade_number", "cutter_position"],
                "unique_together": {("matrix", "blade_number", "cutter_position")},
            },
        ),
        migrations.CreateModel(
            name="RouterSheetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("step_description", models.CharField(max_length=200)),
                (
                    "qr_scan_start",
                    models.DateTimeField(
                        blank=True, help_text="QR scan timestamp for start", null=True
                    ),
                ),
                (
                    "qr_scan_end",
                    models.DateTimeField(
                        blank=True, help_text="QR scan timestamp for end", null=True
                    ),
                ),
                (
                    "station_qr",
                    models.CharField(
                        blank=True, help_text="Station QR code scanned", max_length=100
                    ),
                ),
                ("manual_date", models.DateField(blank=True, null=True)),
                ("manual_time_receipt", models.TimeField(blank=True, null=True)),
                (
                    "operator_signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "cerebro_removal",
                    models.BooleanField(
                        blank=True, help_text="Cerebro Removal: Yes/No/NA", null=True
                    ),
                ),
                (
                    "oring_removal",
                    models.BooleanField(
                        blank=True,
                        help_text="Cer. O-Ring Removal: Yes/No/NA",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation_execution",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="router_entry",
                        to="workorders.operationexecution",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="router_entries_operated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="router_entries",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Router Sheet Entry",
                "verbose_name_plural": "Router Sheet Entries",
                "db_table": "router_sheet_entries",
                "ordering": ["work_order", "step_number"],
                "unique_together": {("work_order", "step_number")},
            },
        ),
    ]
