# Generated by Django 5.1.15 on 2026-01-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0011_add_bom_type_and_bom_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("WAREHOUSE", "Warehouse"),
                    ("RECEIVING", "Receiving Area"),
                    ("WIP", "Work In Progress"),
                    ("DISPATCH", "Dispatch Area"),
                    ("INSPECTION", "Inspection Area"),
                    ("REPAIR_SHOP", "Repair Shop"),
                    ("RIG", "Rig Site"),
                    ("EVALUATION", "Evaluation Area"),
                    ("QC", "QC Area"),
                    ("SCRAP", "Scrap Yard"),
                    ("USA", "USA Facility"),
                    ("FACTORY", "Factory"),
                    ("TRANSIT", "In Transit"),
                ],
                max_length=20,
            ),
        ),
    ]
