# Generated by Django 5.1.15 on 2026-02-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0016_add_due_date_to_productionplanentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(help_text="Holiday name", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_holidays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planner Holiday",
                "verbose_name_plural": "Planner Holidays",
                "db_table": "planner_holidays",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="PlannerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_due_days",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Default working days for due date calculation",
                    ),
                ),
                (
                    "ur_due_days",
                    models.PositiveIntegerField(
                        default=4, help_text="Working days for UR account due date"
                    ),
                ),
                (
                    "weekend_days",
                    models.JSONField(
                        default=list,
                        help_text="Days of the week that are weekends (0=Mon, 4=Fri, 5=Sat, 6=Sun)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planner Settings",
                "verbose_name_plural": "Planner Settings",
                "db_table": "planner_settings",
            },
        ),
    ]
