# Generated by Django 5.1.15 on 2026-02-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0017_add_planner_settings_and_holidays"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationchecklist",
            name="item_timestamps",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Timestamps when each item was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationchecklist",
            name="overall_pass",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productionplanentry",
            name="drill_bit",
            field=models.ForeignKey(
                help_text="Drill bit to be planned for production",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_entries",
                to="workorders.drillbit",
            ),
        ),
    ]
