# Generated by Django 5.1.15 on 2026-02-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0034_remove_dead_models_statustransitionlog_bitrepairhistory_operationexecution",
        ),
        ("workorders", "0019_add_evaluation_routes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationexecution",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="operationexecution",
            name="qc_by",
        ),
        migrations.RemoveField(
            model_name="operationexecution",
            name="route_operation",
        ),
        migrations.RemoveField(
            model_name="operationexecution",
            name="work_order",
        ),
        migrations.RemoveField(
            model_name="routersheetentry",
            name="operation_execution",
        ),
        migrations.RemoveField(
            model_name="statustransitionlog",
            name="changed_by",
        ),
        migrations.RemoveField(
            model_name="statustransitionlog",
            name="content_type",
        ),
        migrations.DeleteModel(
            name="BitRepairHistory",
        ),
        migrations.DeleteModel(
            name="OperationExecution",
        ),
        migrations.DeleteModel(
            name="StatusTransitionLog",
        ),
    ]
