# Generated by Django 5.1.15 on 2026-02-27 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workorders",
            "0020_remove_dead_models_statustransitionlog_bitrepairhistory_operationexecution",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivingInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_date", models.DateField(blank=True, null=True)),
                ("po_number", models.CharField(blank=True, max_length=50)),
                ("client_name", models.CharField(blank=True, max_length=100)),
                (
                    "vi_pin_connection",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        default="NA",
                        max_length=6,
                        verbose_name="Pin Connection",
                    ),
                ),
                (
                    "vi_bit_body",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        default="NA",
                        max_length=6,
                        verbose_name="Bit Body",
                    ),
                ),
                (
                    "vi_bit_breaker",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        default="NA",
                        max_length=6,
                        verbose_name="Bit Breaker",
                    ),
                ),
                (
                    "vi_blades",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        default="NA",
                        max_length=6,
                        verbose_name="Blades",
                    ),
                ),
                (
                    "vi_nozzles",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        default="NA",
                        max_length=6,
                        verbose_name="Nozzles",
                    ),
                ),
                (
                    "vi_junk_slot",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        default="NA",
                        max_length=6,
                        verbose_name="Junk Slot",
                    ),
                ),
                (
                    "vi_gauge_pads",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        default="NA",
                        max_length=6,
                        verbose_name="Gauge Pads",
                    ),
                ),
                (
                    "vi_bit_face",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        default="NA",
                        max_length=6,
                        verbose_name="Bit Face",
                    ),
                ),
                (
                    "vi_general",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "N/A")],
                        default="NA",
                        max_length=6,
                        verbose_name="General Condition",
                    ),
                ),
                (
                    "cutters_total",
                    models.IntegerField(default=0, verbose_name="Total Cutters"),
                ),
                (
                    "cutters_chipped",
                    models.IntegerField(default=0, verbose_name="Chipped"),
                ),
                (
                    "cutters_broken",
                    models.IntegerField(default=0, verbose_name="Broken"),
                ),
                ("cutters_worn", models.IntegerField(default=0, verbose_name="Worn")),
                (
                    "cutters_missing",
                    models.IntegerField(default=0, verbose_name="Missing"),
                ),
                (
                    "tfa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Total Flow Area",
                        max_digits=6,
                        null=True,
                        verbose_name="TFA",
                    ),
                ),
                (
                    "gauge_reading_1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Gauge Reading 1",
                    ),
                ),
                (
                    "gauge_reading_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Gauge Reading 2",
                    ),
                ),
                (
                    "gauge_reading_3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Gauge Reading 3",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CONDITIONAL", "Conditional Accept"),
                        ],
                        default="PENDING",
                        max_length=12,
                        verbose_name="Inspection Result",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("qc_approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drill_bit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiving_inspections",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_inspections_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_inspections_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_inspections",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receiving Inspection",
                "verbose_name_plural": "Receiving Inspections",
                "db_table": "receiving_inspections",
                "ordering": ["-inspection_date", "-created_at"],
            },
        ),
    ]
