# Generated by Django 5.1.15 on 2026-02-27 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_account_options_account_contract_number_and_more"),
        ("workorders", "0021_add_receiving_inspection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackloadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "batch_reference",
                    models.CharField(
                        blank=True,
                        help_text="Email reference, backload paper number, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(
                        blank=True,
                        help_text="When bits are expected to arrive",
                        null=True,
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, help_text="When batch physically arrived", null=True
                    ),
                ),
                (
                    "item_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total items in batch (auto from items.count())",
                    ),
                ),
                (
                    "received_count",
                    models.PositiveIntegerField(
                        default=0, help_text="How many confirmed arrived"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ARRIVED", "Arrived"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Repair account (LSTK, ARAMCO, etc.)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="backload_batches",
                        to="sales.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_backload_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-filled from account.customer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backload_batches",
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backload Batch",
                "verbose_name_plural": "Backload Batches",
                "db_table": "backload_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BOMPendingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSIGNED", "BOM Assigned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bom_requests_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_pending_requests",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bom_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM Pending Request",
                "verbose_name_plural": "BOM Pending Requests",
                "db_table": "bom_pending_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackloadItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EXPECTED", "Expected"),
                            ("RECEIVED", "Received"),
                            ("EVALUATED", "Evaluated"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="EXPECTED",
                        max_length=20,
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MATCHED", "Matched"),
                            ("UNMATCHED", "Not Found"),
                            ("NEW_REGISTERED", "New Registered"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this specific bit was confirmed arrived",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="workorders.backloadbatch",
                    ),
                ),
                (
                    "bit_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backload_items",
                        to="workorders.bitevent",
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backload_items",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_backload_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backload_items",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backload Item",
                "verbose_name_plural": "Backload Items",
                "db_table": "backload_items",
                "ordering": ["sort_order", "id"],
                "unique_together": {("batch", "serial_number")},
            },
        ),
    ]
