# Generated by Django 5.1.15 on 2026-02-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0022_backloadbatch_backloaditem_bompendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="backloadbatch",
            name="reference_file",
            field=models.FileField(
                blank=True,
                help_text="Attachment: email (.msg/.eml), PDF, Excel, image, etc.",
                null=True,
                upload_to="backload_references/%Y/%m/",
            ),
        ),
    ]
