# Generated by Django 5.1.15 on 2026-02-27 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_account_options_account_contract_number_and_more"),
        ("workorders", "0024_backloadbatchattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="backloadbatch",
            name="batch_type",
            field=models.CharField(
                choices=[
                    ("REPAIR", "Repair Bits (Backload)"),
                    ("NEW", "New Bits (Received)"),
                ],
                default="REPAIR",
                help_text="Classify bits — mixing NEW and REPAIR not allowed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="backloadbatch",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Auto-populated from matched drill bits",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backload_batches",
                to="sales.account",
            ),
        ),
    ]
