# Generated by Django 5.1.15 on 2026-02-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0025_add_batch_type_make_account_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backloaditem",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("MATCHED", "Matched"),
                    ("UNMATCHED", "Not Found"),
                    ("NEW_REGISTERED", "Unregistered"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="drillbit",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNREGISTERED", "Unregistered"),
                    ("NEW", "New"),
                    ("IN_STOCK", "In Stock"),
                    ("ASSIGNED", "Assigned to WO"),
                    ("IN_PRODUCTION", "In Production"),
                    ("QC_PENDING", "QC Pending"),
                    ("READY", "Ready for Dispatch"),
                    ("DISPATCHED", "Dispatched"),
                    ("IN_FIELD", "In Field"),
                    ("RETURNED", "Returned"),
                    ("SCRAPPED", "Scrapped"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
