# Generated by Django 5.1.15 on 2026-02-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0026_add_unregistered_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="drillbit",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPONENTS", "Components"),
                    ("FINISHED_GOOD", "Finished Good"),
                    ("REPAIRED", "Repaired"),
                    ("RERUN", "Rerun"),
                    ("RETROFITTED", "Retrofitted"),
                    ("USED", "Used"),
                    ("NOT_USED", "Not Used"),
                    ("DE_BRAZED", "De-Brazed"),
                    ("SAVED_BODY", "Saved Body"),
                    ("SCRAPPED", "Scrapped"),
                ],
                default="COMPONENTS",
                help_text="What IS this bit right now? (Finished Good, Used, Repaired, etc.)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="is_trial",
            field=models.BooleanField(
                default=False, help_text="Trial/test bit — always ARDT-owned"
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="ownership",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RENTAL", "Rental"),
                    ("CUSTOMER", "Customer"),
                    ("MANUFACTURE", "Manufacture"),
                    ("TRIAL", "Trial"),
                    ("ARDT", "ARDT"),
                ],
                default="ARDT",
                help_text="Commercial arrangement (Rental, Customer, Manufacture, Trial, ARDT)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="drillbit",
            name="lifecycle_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "New"),
                    ("DEPLOYED", "Deployed"),
                    ("BACKLOADED", "Backloaded"),
                    ("EVALUATION", "In Evaluation"),
                    ("HOLD", "On Hold"),
                    ("IN_REPAIR", "In Repair"),
                    ("REPAIRED", "Repaired"),
                    ("USA_REPAIR", "USA Repair"),
                    ("RERUN", "Rerun Ready"),
                    ("SCRAP", "Scrapped"),
                    ("SAVED_BODY", "Saved Body"),
                ],
                default="NEW",
                help_text="LEGACY — use status + condition instead",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="drillbit",
            name="status",
            field=models.CharField(
                choices=[
                    ("ORDERED", "Ordered"),
                    ("IN_TRANSIT", "In Transit"),
                    ("UNREGISTERED", "Unregistered"),
                    ("RECEIVING", "Receiving"),
                    ("IN_COMPONENTS", "In Components"),
                    ("IN_EVALUATION", "In Evaluation"),
                    ("IN_PRODUCTION", "In Production"),
                    ("IN_REPAIR", "In Repair"),
                    ("IN_STOCK", "In Stock"),
                    ("DISPATCHED", "Dispatched"),
                    ("IN_FIELD", "In Field"),
                    ("BACKLOADED", "Backloaded"),
                    ("HOLD", "On Hold"),
                    ("USA_REPAIR", "USA Repair"),
                    ("DE_BRAZED", "De-Brazed"),
                    ("SAVED_BODY", "Saved Body"),
                    ("SCRAPPED", "Scrapped"),
                ],
                default="UNREGISTERED",
                max_length=20,
            ),
        ),
    ]
