# Generated by Django 5.1.15 on 2026-02-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0028_migrate_status_condition_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="drillbit",
            name="level",
            field=models.CharField(
                blank=True,
                help_text="Order level: 3=Design only, 4=Design welded, 5=With BOM/cutters",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="backloadbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("ARRIVED", "Arrived"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                ],
                default="ARRIVED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="backloaditem",
            name="status",
            field=models.CharField(
                choices=[
                    ("ARRIVED", "Arrived"),
                    ("UNREGISTERED", "Unregistered"),
                    ("PROCESSING", "Processing"),
                    ("RECEIVED", "Received"),
                    ("HOLD", "Hold"),
                ],
                default="ARRIVED",
                max_length=20,
            ),
        ),
    ]
