# Generated by Django 5.1.15 on 2026-03-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0033_drillbitphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivinginspection",
            name="cutter_auto_remarks",
            field=models.TextField(
                blank=True, help_text="Auto-generated cutter remarks text"
            ),
        ),
        migrations.AddField(
            model_name="receivinginspection",
            name="cutter_remark_annotations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User annotations per cutter remark segment: {segKey: text}",
            ),
        ),
        migrations.AddField(
            model_name="receivinginspection",
            name="pocket_auto_remarks",
            field=models.TextField(
                blank=True, help_text="Auto-generated pocket remarks text"
            ),
        ),
        migrations.AddField(
            model_name="receivinginspection",
            name="pocket_remark_annotations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User annotations per pocket remark segment: {segKey: text}",
            ),
        ),
    ]
