# Generated by Django 5.1.15 on 2026-03-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0039_add_remark_fields_to_evaluation_matrix"),
    ]

    operations = [
        migrations.AddField(
            model_name="diecheckreport",
            name="materials_data",
            field=models.JSONField(
                blank=True,
                help_text="LPT materials: penetrant & developer product, batch, expiry",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diecheckreport",
            name="stage",
            field=models.CharField(
                choices=[
                    ("BEFORE_BRAZE", "Before Braze"),
                    ("AFTER_REPAIR", "After Repair"),
                    ("OTHER", "Other"),
                ],
                default="BEFORE_BRAZE",
                help_text="Stage in the repair process when this die check was performed",
                max_length=20,
            ),
        ),
    ]
