# Generated by Django 5.1.15 on 2026-03-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0040_die_check_stage_and_materials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drillbit",
            name="status",
            field=models.CharField(
                choices=[
                    ("ORDERED", "Ordered"),
                    ("IN_TRANSIT", "In Transit"),
                    ("UNREGISTERED", "Unregistered"),
                    ("RECEIVING", "Receiving"),
                    ("RECEIVED", "Received"),
                    ("IN_COMPONENTS", "In Components"),
                    ("IN_EVALUATION", "In Evaluation"),
                    ("IN_PRODUCTION", "In Production"),
                    ("IN_REPAIR", "In Repair"),
                    ("IN_STOCK", "In Stock"),
                    ("DISPATCHED", "Dispatched"),
                    ("IN_FIELD", "In Field"),
                    ("BACKLOADED", "Backloaded"),
                    ("HOLD", "On Hold"),
                    ("USA_REPAIR", "USA Repair"),
                    ("DE_BRAZED", "De-Brazed"),
                    ("SAVED_BODY", "Saved Body"),
                    ("SCRAPPED", "Scrapped"),
                ],
                default="UNREGISTERED",
                max_length=20,
            ),
        ),
    ]
