# Generated by Django 5.1.15 on 2026-03-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0044_planentry_brazing_and_due_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionplanentry",
            name="due_date_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="History of due date changes [{old, new, reason, changed_by, changed_at}]",
            ),
        ),
        migrations.AlterField(
            model_name="productionplanentry",
            name="planned_brazing_date",
            field=models.DateField(
                blank=True,
                help_text="Estimated brazing date (auto-calculated from due date rules)",
                null=True,
            ),
        ),
    ]
