# Generated by Django 5.1.15 on 2026-03-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0045_planentry_brazing_due_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionplanentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("RELEASED", "Released"),
                    ("WO_CREATED", "WO Created"),
                    ("REMOVED", "Removed"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
    ]
