# Generated by Django 5.1.15 on 2026-03-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0046_add_released_status_to_plan_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="drillbit",
            name="change_log",
            field=models.JSONField(
                blank=True, default=list, help_text="Audit trail of field changes"
            ),
        ),
    ]
