# Generated by Django 5.1.15 on 2026-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0047_add_change_log_to_drillbit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionplanentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("PENDING_RELEASE", "Pending Release"),
                    ("RELEASED", "Released"),
                    ("WO_CREATED", "WO Created"),
                    ("REMOVED", "Removed"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
    ]
