# Generated by Django 5.1.15 on 2026-03-22 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0048_add_pending_release_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="processrouteoperation",
            name="checklist_template",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="QC checklist items: [{text, required}]",
            ),
        ),
        migrations.AddField(
            model_name="processrouteoperation",
            name="estimated_minutes",
            field=models.IntegerField(
                blank=True, help_text="Expected duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="processrouteoperation",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Step-by-step instructions for the operator. Shown on the work page.",
            ),
        ),
        migrations.AddField(
            model_name="processrouteoperation",
            name="parameters_template",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Parameters to collect: [{name, type, unit, required, min, max}]",
            ),
        ),
        migrations.AddField(
            model_name="processrouteoperation",
            name="procedure_reference",
            field=models.CharField(
                blank=True,
                help_text='Reference to procedure document, e.g., "QAS/1006 Rev L, Section 4.11"',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="processrouteoperation",
            name="procedure_text",
            field=models.TextField(
                blank=True,
                help_text="Relevant procedure text to display on the work page",
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who added this step (if non-standard)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="router_steps_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="added_reason",
            field=models.TextField(blank=True, help_text="Why this step was added"),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="checklist_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Recorded checklist checks: {item_index: true/false}",
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="checklist_template",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="instructions",
            field=models.TextField(blank=True, help_text="Instructions for this step"),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="parameters_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Recorded parameter values: {param_name: value}",
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="parameters_template",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="procedure_reference",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="qc_passed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="qc_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="safety_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="source_operation",
            field=models.ForeignKey(
                blank=True,
                help_text="The ProcessRouteOperation this step was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="router_entries",
                to="workorders.processrouteoperation",
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard (from route template)"),
                    ("ADDED", "Added (by evaluator/engineer)"),
                    ("CONDITIONAL", "Conditional (if applicable)"),
                ],
                default="STANDARD",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="total_paused_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
