# Generated by Django 5.1.15 on 2026-03-22 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0036_add_level_5_5_order_level"),
        ("workorders", "0049_add_step_detail_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique process code, e.g., BRAZE-L1, BUILDUP, PRESSURE-TEST",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RECEIVING", "Receiving & Setup"),
                            ("EVALUATION", "Evaluation & Inspection"),
                            ("PREPARATION", "Preparation"),
                            ("BRAZING", "Brazing"),
                            ("GRINDING", "Grinding & Finishing"),
                            ("ASSEMBLY", "Assembly"),
                            ("THREADING", "Threading & Connection"),
                            ("QC", "Quality Control"),
                            ("FINISHING", "Finishing & Coating"),
                            ("DISPATCH", "Pack & Dispatch"),
                            ("SPECIAL", "Special Operations"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "instructions_general",
                    models.TextField(
                        blank=True, help_text="General instructions from the procedure"
                    ),
                ),
                (
                    "procedure_reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g., QAS/1006 Rev L, Section 4.11",
                        max_length=200,
                    ),
                ),
                (
                    "procedure_doc_url",
                    models.URLField(blank=True, help_text="Link to procedure document"),
                ),
                ("safety_notes", models.TextField(blank=True)),
                ("default_estimated_minutes", models.IntegerField(default=30)),
                (
                    "time_factors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Time adjustment factors: {per_cutter, per_blade, size_factor: {size: multiplier}}",
                    ),
                ),
                (
                    "parameters_spec",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Parameter specs with size-dependent ranges",
                    ),
                ),
                (
                    "checklist_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="QC checklist: [{text, required}]",
                    ),
                ),
                ("requires_qc", models.BooleanField(default=False)),
                (
                    "is_default_included",
                    models.BooleanField(
                        default=True,
                        help_text="Included in all routes by default (unless excluded by a rule)",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=100, help_text="Default sequence position"
                    ),
                ),
                (
                    "applies_to_new",
                    models.BooleanField(
                        default=True, help_text="Applies to new bit manufacture"
                    ),
                ),
                (
                    "applies_to_repair",
                    models.BooleanField(
                        default=True, help_text="Applies to bit repair"
                    ),
                ),
                (
                    "applies_to_levels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Which levels: ["3","4","5.5"] or empty for all',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Master Process",
                "verbose_name_plural": "Master Processes",
                "db_table": "master_processes",
                "ordering": ["sort_order", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProcessInclusionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("INCLUDE_IF", "Include if condition is true"),
                            ("EXCLUDE_IF", "Exclude if condition is true"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "field_path",
                    models.CharField(
                        help_text="Field to evaluate: design.port_count, design.body_material, bit.level, tech.cerebro_force, tech.has_cerebro, eval.needs_buildup, bom.has_dynamic_cutters",
                        max_length=100,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("EQUALS", "equals"),
                            ("NOT_EQUALS", "does not equal"),
                            ("GT", "greater than"),
                            ("LT", "less than"),
                            ("CONTAINS", "contains"),
                            ("EXISTS", "exists / is not empty"),
                            ("NOT_EXISTS", "does not exist / is empty"),
                            ("IN_LIST", "is one of (comma-separated)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Value to compare against. For EXISTS/NOT_EXISTS, leave empty.",
                        max_length=200,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=10, help_text="Higher priority rules evaluated first"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable rule description",
                        max_length=200,
                    ),
                ),
                (
                    "master_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inclusion_rules",
                        to="workorders.masterprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Inclusion Rule",
                "db_table": "process_inclusion_rules",
                "ordering": ["-priority", "master_process"],
            },
        ),
        migrations.CreateModel(
            name="SpecialInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instruction_text",
                    models.TextField(help_text="The instruction to display"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("HIGH", "High — operator must acknowledge"),
                            ("CRITICAL", "Critical — blocks step completion"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("ALL", "All bits"),
                            ("DESIGN", "Specific design MAT"),
                            ("SERIAL", "Specific serial number"),
                            ("SIZE", "Size range"),
                            ("MATERIAL", "Body material"),
                            ("COMBINATION", "Multiple criteria"),
                        ],
                        default="ALL",
                        max_length=15,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Specific serial (e.g., for SN Z hold and call technical team)",
                        max_length=20,
                    ),
                ),
                (
                    "size_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "size_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "body_material",
                    models.CharField(
                        blank=True,
                        help_text="Body material filter (e.g., M for Matrix, S for Steel)",
                        max_length=50,
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True, help_text="Active from this date", null=True
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, help_text="Active until this date", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="special_instructions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific design MAT (e.g., for MAT X undercut gauge by Y)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_instructions",
                        to="technology.design",
                    ),
                ),
                (
                    "target_process",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which step this appears on. Blank = appears on all steps.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_instructions",
                        to="workorders.masterprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Instruction",
                "db_table": "special_instructions",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
