# Generated by Django 5.1.15 on 2026-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0050_add_smart_route_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterprocess",
            name="step_mode",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active — operator performs work"),
                    (
                        "PASSIVE",
                        "Passive — wait/cooling, system tracks time and notifies next operator",
                    ),
                    (
                        "MULTI",
                        "Multi-instance — can appear multiple times (e.g., Die Check)",
                    ),
                ],
                default="ACTIVE",
                help_text="How this step is executed by the operator",
                max_length=10,
            ),
        ),
    ]
