# Generated by Django 5.1.15 on 2026-03-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0051_add_step_mode_to_master_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterprocess",
            name="dedicated_url_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Button label (e.g., "Open Die Check Report", "Open LPT Report")',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="masterprocess",
            name="dedicated_url_name",
            field=models.CharField(
                blank=True,
                help_text="Django URL name for dedicated page (e.g., workorders:lpt_report_create). If set, step detail shows a link instead of inline parameters.",
                max_length=100,
            ),
        ),
    ]
