# Generated by Django 5.1.15 on 2026-03-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0052_add_dedicated_url_to_master_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="routersheetentry",
            name="hold_notes",
            field=models.TextField(
                blank=True, help_text="Additional details about the hold"
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="hold_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("EQUIPMENT", "Equipment Failure"),
                    ("MAINTENANCE", "Maintenance Required"),
                    ("MATERIAL", "Lack of Material"),
                    ("SAFETY", "Safety Issue"),
                    ("MEETING", "Meeting / Break"),
                    ("QUALITY", "Quality Hold"),
                    ("TECH_REVIEW", "Technical Review Required"),
                    ("APPROVAL", "Approval Needed"),
                    ("NCR", "NCR Open"),
                    ("REWORK", "Rework Required"),
                    ("PARTS", "Waiting for Parts"),
                    ("OTHER", "Other (see remarks)"),
                ],
                default="",
                help_text="Why this step is on hold or waiting",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="hold_since",
            field=models.DateTimeField(
                blank=True, help_text="When the step was put on hold", null=True
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="step_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PAUSED", "Paused"),
                    ("ON_HOLD", "On Hold"),
                    ("WAITING_QC", "Waiting QC"),
                    ("WAITING_APPROVAL", "Waiting Approval"),
                    ("WAITING_TECH", "Waiting Technical Team"),
                    ("SKIPPED", "Skipped"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
