# Generated by Django 5.1.15 on 2026-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0053_add_step_status_and_hold_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterprocess",
            name="dedicated_icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Lucide icon name (e.g., search, shield-check, droplet, clipboard-check)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="masterprocess",
            name="dedicated_page",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— No dedicated page (use inline parameters)"),
                    ("die_check", "Die Check Report"),
                    ("cutter_eval", "Cutter Evaluation"),
                    ("lpt_report", "LPT Pressure Test Report"),
                    ("thread_insp", "API Thread Inspection"),
                    ("e_checklist", "E-Checklist"),
                    ("receiving_insp", "Receiving Inspection"),
                ],
                default="",
                help_text="Select the dedicated page for technical data entry. The step detail will show a large icon linking to this page.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="masterprocess",
            name="dedicated_url_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="masterprocess",
            name="dedicated_url_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
