# Generated by Django 5.1.15 on 2026-03-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0054_add_dedicated_page_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterprocess",
            name="insertion_points",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="For MULTI mode: where to insert instances. [{context, label, after_process_code, rules: [{field, op, val}]}]",
            ),
        ),
    ]
