# Generated by Django 5.1.15 on 2026-03-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0055_add_insertion_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterprocess",
            name="rule_expression",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Inclusion/exclusion rule as nested AND/OR/NOT expression",
            ),
        ),
        migrations.AlterField(
            model_name="masterprocess",
            name="insertion_points",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="For MULTI mode: where to insert instances with per-point rules",
            ),
        ),
    ]
