# Generated by Django 5.1.15 on 2026-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0056_add_rule_expression"),
    ]

    operations = [
        migrations.AddField(
            model_name="drillbit",
            name="has_cerebro_installed",
            field=models.BooleanField(
                default=False, help_text="Cerebro device currently installed"
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="has_erosion_sleeve_installed",
            field=models.BooleanField(
                default=False, help_text="Erosion sleeve currently installed"
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="has_nozzles_installed",
            field=models.BooleanField(
                default=False, help_text="Nozzles currently installed"
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="is_painted",
            field=models.BooleanField(
                default=False, help_text="Bit is currently painted"
            ),
        ),
    ]
