# Generated by Django 5.1.15 on 2026-03-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0057_add_component_tracking_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RELEASED", "Released"),
                    ("ACTIVE", "Active"),
                    ("IN_PROGRESS", "In Progress"),
                    ("ON_HOLD", "On Hold"),
                    ("QC_PENDING", "QC Pending"),
                    ("QC_PASSED", "QC Passed"),
                    ("QC_FAILED", "QC Failed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("DRAFT", "Draft"),
                    ("PLANNED", "Planned"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
