# Generated by Django 5.1.15 on 2026-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0058_add_pending_active_wo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Received (New)"),
                    ("DEPLOYED", "Deployed to Rig"),
                    ("BACKLOADED", "Backloaded to Factory"),
                    ("EVALUATION_START", "Evaluation Started"),
                    ("EVALUATION_COMPLETE", "Evaluation Complete"),
                    ("REPAIR_DECISION", "Decision: Repair"),
                    ("RERUN_DECISION_FACTORY", "Decision: Rerun (Factory)"),
                    ("RERUN_DECISION_FIELD", "Decision: Rerun (Field)"),
                    ("USA_REPAIR_DECISION", "Decision: USA Repair"),
                    ("SCRAP_DECISION", "Decision: Scrap"),
                    ("HOLD_DECISION", "Decision: Hold"),
                    ("REPAIR_START", "Repair Started"),
                    ("REPAIR_COMPLETE", "Repair Complete"),
                    ("USA_REPAIR_SENT", "Sent to USA"),
                    ("USA_REPAIR_RECEIVED", "Received from USA"),
                    ("QC_PASS", "QC Passed"),
                    ("QC_FAIL", "QC Failed"),
                    ("TRANSFER", "Stock Transfer"),
                    ("RELOCATION", "Relocation (Rig to Rig)"),
                    ("SCRAPPED", "Scrapped"),
                    ("BODY_SAVED", "Body Saved"),
                    ("NOTE", "Note"),
                    ("WO_CANCELLED", "Work Order Cancelled"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="productionplanentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("PENDING_RELEASE", "Pending Release"),
                    ("RELEASED", "Released"),
                    ("WO_CREATED", "WO Created"),
                    ("CANCELLED", "Production Cancelled"),
                    ("REMOVED", "Removed"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
    ]
