# Generated by Django 5.1.15 on 2026-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0059_alter_bitevent_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Received (New)"),
                    ("DEPLOYED", "Deployed to Rig"),
                    ("BACKLOADED", "Backloaded to Factory"),
                    ("EVALUATION_START", "Evaluation Started"),
                    ("EVALUATION_COMPLETE", "Evaluation Complete"),
                    ("REPAIR_DECISION", "Decision: Repair"),
                    ("RERUN_DECISION_FACTORY", "Decision: Rerun (Factory)"),
                    ("RERUN_DECISION_FIELD", "Decision: Rerun (Field)"),
                    ("USA_REPAIR_DECISION", "Decision: USA Repair"),
                    ("SCRAP_DECISION", "Decision: Scrap"),
                    ("HOLD_DECISION", "Decision: Hold"),
                    ("REPAIR_START", "Repair Started"),
                    ("REPAIR_COMPLETE", "Repair Complete"),
                    ("USA_REPAIR_SENT", "Sent to USA"),
                    ("USA_REPAIR_RECEIVED", "Received from USA"),
                    ("QC_PASS", "QC Passed"),
                    ("QC_FAIL", "QC Failed"),
                    ("TRANSFER", "Stock Transfer"),
                    ("RELOCATION", "Relocation (Rig to Rig)"),
                    ("SCRAPPED", "Scrapped"),
                    ("BODY_SAVED", "Body Saved"),
                    ("RELEASED_TO_PROD", "Released to Production"),
                    ("NOTE", "Note"),
                    ("WO_CANCELLED", "Work Order Cancelled"),
                ],
                max_length=30,
            ),
        ),
    ]
