# Generated by Django 5.1.15 on 2026-03-23 15:26

import apps.workorders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0060_alter_bitevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Checklist item text shown to operator",
                        max_length=200,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Must be checked before step completion"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "condition_field",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Route context field (e.g., design.body_material, bit.is_new, bit.level)",
                        max_length=50,
                    ),
                ),
                (
                    "condition_operator",
                    models.CharField(
                        blank=True,
                        default="EQUALS",
                        help_text="EQUALS, NOT_EQUALS, IN_LIST, CONTAINS, GT, LT",
                        max_length=20,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Value to compare against",
                        max_length=100,
                    ),
                ),
                (
                    "master_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_checklist_items",
                        to="workorders.masterprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Checklist Item",
                "db_table": "process_checklist_items",
                "ordering": ["master_process", "sort_order"],
            },
            bases=(apps.workorders.models._ConditionalItemMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProcessParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Parameter name shown to operator", max_length=100
                    ),
                ),
                (
                    "param_type",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("text", "Text"),
                            ("choice", "Choice (dropdown)"),
                            ("boolean", "Yes/No"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unit of measurement",
                        max_length=30,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "choices_list",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Options for choice type: ["Good","Fair","Poor"]',
                    ),
                ),
                (
                    "condition_field",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "condition_operator",
                    models.CharField(blank=True, default="EQUALS", max_length=20),
                ),
                (
                    "condition_value",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "master_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_parameters",
                        to="workorders.masterprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Parameter",
                "db_table": "process_parameters",
                "ordering": ["master_process", "sort_order"],
            },
            bases=(apps.workorders.models._ConditionalItemMixin, models.Model),
        ),
    ]
