# Generated by Django 5.1.15 on 2026-03-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0061_add_checklist_parameter_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="masterprocess",
            name="checklist_items",
        ),
        migrations.RemoveField(
            model_name="masterprocess",
            name="parameters_spec",
        ),
        migrations.AddField(
            model_name="masterprocess",
            name="parent_process",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent process — this instance inherits procedure details from parent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="workorders.masterprocess",
            ),
        ),
    ]
