# Generated by Django 5.1.15 on 2026-03-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0062_add_parent_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="routersheetentry",
            name="duration_gross_seconds",
            field=models.IntegerField(
                blank=True,
                help_text="Total wall-clock seconds from start to end (includes pauses)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="duration_net_seconds",
            field=models.IntegerField(
                blank=True,
                help_text="Active seconds = gross - paused (operator work time for active steps)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="kpi_account",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Business unit code (denormalized for KPI)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="kpi_bit_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Bit size at execution time (denormalized for KPI)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="kpi_body_material",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S=Steel, M=Matrix (denormalized for KPI)",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="kpi_is_core_head",
            field=models.BooleanField(
                blank=True,
                help_text="Core head vs drill bit (denormalized for KPI)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="kpi_is_passive",
            field=models.BooleanField(
                default=False,
                help_text="Passive step (not operator-dependent) — heating, cooling, soaking",
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="kpi_is_repair",
            field=models.BooleanField(
                blank=True,
                help_text="Was this a repair job? (denormalized for KPI)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="kpi_level",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Order level: 3, 4, 5, 5.5 (denormalized for KPI)",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="master_process",
            field=models.ForeignKey(
                blank=True,
                help_text="The MasterProcess this step was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="execution_entries",
                to="workorders.masterprocess",
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="parent_process_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Parent process family code (e.g., _BASE_DIE_CHECK) for KPI grouping",
                max_length=30,
            ),
        ),
    ]
