# Generated by Django 5.1.15 on 2026-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0063_add_kpi_fields_to_router_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routersheetentry",
            name="kpi_level",
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="kpi_design_mat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Design MAT number (denormalized for KPI — identifies the design)",
                max_length=20,
            ),
        ),
    ]
