# Generated by Django 5.1.15 on 2026-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0064_rename_kpi_level_to_design_mat"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterprocess",
            name="attach_to_previous",
            field=models.BooleanField(
                default=False,
                help_text="Show as a sub-action of the previous step (not a separate row). The step still exists for KPI tracking.",
            ),
        ),
    ]
