# Generated by Django 5.1.15 on 2026-03-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0065_add_attach_to_previous"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="route_built_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the router sheet was last built/rebuilt from MasterProcess rules",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="route_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Route position choices: {l3_pt_position, usr_pt_position, ...}",
            ),
        ),
    ]
