# Generated by Django 5.1.15 on 2026-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0067_router_step_eval_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterprocess",
            name="min_required_photos",
            field=models.IntegerField(
                default=0,
                help_text="Minimum number of photos required (0 = no photo requirement)",
            ),
        ),
        migrations.AddField(
            model_name="masterprocess",
            name="requires_evaluation",
            field=models.BooleanField(
                default=False,
                help_text="Requires linked evaluation to be completed before step can be completed",
            ),
        ),
        migrations.AddField(
            model_name="masterprocess",
            name="requires_photos",
            field=models.BooleanField(
                default=False,
                help_text="Requires photo upload before step can be completed",
            ),
        ),
    ]
