# Generated by Django 5.1.15 on 2026-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0068_add_step_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterprocess",
            name="photo_requirement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No photos required"),
                    ("ADG", "ADG sequence (3 per blade + top + side = blades*3 + 2)"),
                    (
                        "BEFORE_AFTER",
                        "Before & After (blades*3 + 2, x2 = before + after)",
                    ),
                    ("FIXED", "Fixed count (use min_required_photos)"),
                ],
                default="",
                help_text="How to calculate minimum photos. ADG = 3 per blade + 2. BEFORE_AFTER = ADG x2.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="masterprocess",
            name="min_required_photos",
            field=models.IntegerField(
                default=0,
                help_text="Fixed minimum photos (only used when photo_requirement=FIXED)",
            ),
        ),
    ]
