# Generated by Django 5.1.15 on 2026-04-03 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0069_update_photo_requirement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StepDurationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_code",
                    models.CharField(
                        db_index=True,
                        help_text="MasterProcess.code or step description slug",
                        max_length=50,
                    ),
                ),
                ("process_name", models.CharField(max_length=200)),
                (
                    "process_category",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                (
                    "parent_process_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Parent process family for grouping",
                        max_length=50,
                    ),
                ),
                (
                    "duration_gross_seconds",
                    models.IntegerField(
                        default=0, help_text="Total wall-clock time from start to end"
                    ),
                ),
                (
                    "duration_net_seconds",
                    models.IntegerField(
                        default=0, help_text="Active time (gross minus pauses)"
                    ),
                ),
                ("paused_seconds", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("serial_number", models.CharField(db_index=True, max_length=20)),
                (
                    "design_mat",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "bit_size",
                    models.DecimalField(
                        db_index=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "body_material",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="M=Matrix, S=Steel",
                        max_length=10,
                    ),
                ),
                ("is_repair", models.BooleanField(db_index=True, default=True)),
                ("is_core_head", models.BooleanField(default=False)),
                (
                    "account_code",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                (
                    "operator_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized name for queries after user deletion",
                        max_length=100,
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("was_skipped", models.BooleanField(default=False)),
                (
                    "is_passive",
                    models.BooleanField(
                        default=False,
                        help_text="PASSIVE mode steps (heating, cooldown) — waiting time, not work time",
                    ),
                ),
                ("requires_qc", models.BooleanField(default=False)),
                ("qc_passed", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_durations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "router_entry",
                    models.OneToOneField(
                        help_text="Source RouterSheetEntry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duration_record",
                        to="workorders.routersheetentry",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duration_records",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "step_duration_records",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["process_code", "bit_size", "body_material"],
                        name="idx_sdr_process_size_mat",
                    ),
                    models.Index(
                        fields=["design_mat", "process_code"],
                        name="idx_sdr_design_process",
                    ),
                    models.Index(
                        fields=["operator", "process_code"],
                        name="idx_sdr_operator_process",
                    ),
                    models.Index(
                        fields=["account_code", "process_code"],
                        name="idx_sdr_account_process",
                    ),
                    models.Index(fields=["completed_at"], name="idx_sdr_completed"),
                ],
            },
        ),
    ]
