# Generated by Django 5.1.15 on 2026-04-03 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0070_add_step_duration_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="routersheetentry",
            name="skip_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("N/A", "Not Applicable (N/A)"),
                    ("IN_SPEC", "Within specification — no action needed"),
                    ("ACCEPTED", "Accepted as-is"),
                    ("APPROVED_BY", "Approved to skip by supervisor"),
                    ("NOT_REQ", "Not required for this bit type"),
                    ("DONE_EXT", "Done externally / previously completed"),
                    ("DEFERRED", "Deferred to next cycle"),
                    ("OTHER", "Other (see remarks)"),
                ],
                default="",
                help_text="Why this step was skipped",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="routersheetentry",
            name="skipped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="steps_skipped",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
