# Generated by Django 5.1.15 on 2026-04-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0071_add_skip_reason_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routersheetentry",
            name="skip_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("N/A", "Not Applicable (N/A)"),
                    ("IN_SPEC", "Within specification — no action needed"),
                    ("ACCEPTED", "Accepted as-is"),
                    ("APPROVED_BY", "Approved to skip by supervisor"),
                    ("NOT_REQ", "Not required for this bit type"),
                    ("DONE_EXT", "Done externally / previously completed"),
                    ("DEFERRED", "Deferred to next cycle"),
                    ("REORDERED", "Reordered — will execute later"),
                    ("OTHER", "Other (see remarks)"),
                ],
                default="",
                help_text="Why this step was skipped",
                max_length=15,
            ),
        ),
    ]
