# Generated by Django 5.2.8 on 2025-12-05 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_servicesite_fieldtechnician_fieldservicerequest_and_more"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique schedule number (auto-generated: SCH-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(db_index=True, help_text="Scheduled service date"),
                ),
                (
                    "scheduled_start_time",
                    models.TimeField(help_text="Scheduled start time"),
                ),
                (
                    "scheduled_end_time",
                    models.TimeField(help_text="Scheduled end time"),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated duration in hours",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Current schedule status",
                        max_length=20,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the schedule was confirmed",
                        null=True,
                    ),
                ),
                (
                    "customer_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether customer confirmed the schedule",
                    ),
                ),
                (
                    "customer_confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="When customer confirmed", null=True
                    ),
                ),
                (
                    "reschedule_reason",
                    models.TextField(blank=True, help_text="Reason for rescheduling"),
                ),
                (
                    "reschedule_count",
                    models.IntegerField(
                        default=0, help_text="Number of times rescheduled"
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, help_text="Whether notification was sent"
                    ),
                ),
                (
                    "notification_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was sent", null=True
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, help_text="Whether reminder was sent"
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When reminder was sent", null=True
                    ),
                ),
                (
                    "scheduling_notes",
                    models.TextField(blank=True, help_text="Internal scheduling notes"),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, help_text="Special requirements for this visit"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who confirmed the schedule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this schedule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original schedule if this is a reschedule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_versions",
                        to="sales.serviceschedule",
                    ),
                ),
                (
                    "rescheduled_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="New schedule if this was rescheduled",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_from",
                        to="sales.serviceschedule",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        help_text="Related field service request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="sales.fieldservicerequest",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        help_text="Service site location",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        help_text="Assigned technician",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="sales.fieldtechnician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Schedule",
                "verbose_name_plural": "Service Schedules",
                "db_table": "service_schedules",
                "ordering": ["scheduled_date", "scheduled_start_time"],
                "permissions": [
                    ("can_create_schedules", "Can create service schedules"),
                    ("can_confirm_schedules", "Can confirm service schedules"),
                    ("can_reschedule", "Can reschedule service appointments"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique visit number (auto-generated: VIS-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(db_index=True, help_text="Date of the visit"),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True, help_text="When technician checked in", null=True
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, help_text="When technician checked out", null=True
                    ),
                ),
                (
                    "actual_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual visit duration in hours",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled Service"),
                            ("EMERGENCY", "Emergency Call"),
                            ("FOLLOW_UP", "Follow-up Visit"),
                            ("INSPECTION", "Inspection"),
                            ("TRAINING", "Training"),
                            ("OTHER", "Other"),
                        ],
                        default="SCHEDULED",
                        help_text="Type of visit",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("EN_ROUTE", "En Route"),
                            ("ARRIVED", "Arrived"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("INCOMPLETE", "Incomplete"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        help_text="Current visit status",
                        max_length=20,
                    ),
                ),
                (
                    "work_performed",
                    models.TextField(
                        blank=True, help_text="Description of work performed"
                    ),
                ),
                (
                    "issues_found",
                    models.TextField(blank=True, help_text="Issues found during visit"),
                ),
                (
                    "parts_used",
                    models.TextField(blank=True, help_text="Parts/materials used"),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations for future work"
                    ),
                ),
                (
                    "visit_successful",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the visit was successful",
                        null=True,
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, help_text="Whether follow-up is required"
                    ),
                ),
                (
                    "follow_up_reason",
                    models.TextField(blank=True, help_text="Reason for follow-up"),
                ),
                (
                    "customer_signature",
                    models.CharField(
                        blank=True,
                        help_text="Customer signature (name)",
                        max_length=200,
                    ),
                ),
                (
                    "customer_signed_at",
                    models.DateTimeField(
                        blank=True, help_text="When customer signed", null=True
                    ),
                ),
                (
                    "customer_satisfaction_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Customer satisfaction rating (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "customer_comments",
                    models.TextField(
                        blank=True, help_text="Customer comments/feedback"
                    ),
                ),
                (
                    "has_photos",
                    models.BooleanField(
                        default=False, help_text="Whether photos were taken"
                    ),
                ),
                (
                    "photo_count",
                    models.IntegerField(default=0, help_text="Number of photos"),
                ),
                (
                    "has_documents",
                    models.BooleanField(
                        default=False, help_text="Whether documents were attached"
                    ),
                ),
                (
                    "document_count",
                    models.IntegerField(default=0, help_text="Number of documents"),
                ),
                (
                    "check_in_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Check-in GPS latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "check_in_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Check-in GPS longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "check_out_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Check-out GPS latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "check_out_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Check-out GPS longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related schedule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_visits",
                        to="sales.serviceschedule",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        help_text="Related field service request",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_visits",
                        to="sales.fieldservicerequest",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        help_text="Site visited",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_visits",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        help_text="Technician who performed the visit",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_visits",
                        to="sales.fieldtechnician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Visit",
                "verbose_name_plural": "Site Visits",
                "db_table": "site_visits",
                "ordering": ["-visit_date", "-check_in_time"],
                "permissions": [
                    ("can_check_in_visit", "Can check in to site visit"),
                    ("can_complete_visit", "Can complete site visit"),
                    ("can_view_all_visits", "Can view all site visits"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique report number (auto-generated: RPT-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("report_date", models.DateField(help_text="Report date")),
                (
                    "report_title",
                    models.CharField(help_text="Report title", max_length=200),
                ),
                (
                    "executive_summary",
                    models.TextField(help_text="Executive summary of the service"),
                ),
                (
                    "work_performed_detail",
                    models.TextField(
                        help_text="Detailed description of work performed"
                    ),
                ),
                (
                    "findings",
                    models.TextField(blank=True, help_text="Findings during service"),
                ),
                (
                    "issues_identified",
                    models.TextField(blank=True, help_text="Issues identified"),
                ),
                (
                    "corrective_actions",
                    models.TextField(blank=True, help_text="Corrective actions taken"),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations for future"
                    ),
                ),
                (
                    "parts_used_detail",
                    models.TextField(
                        blank=True, help_text="Detailed parts/materials used"
                    ),
                ),
                (
                    "parts_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total parts cost",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "labor_hours",
                    models.DecimalField(
                        decimal_places=2, help_text="Total labor hours", max_digits=5
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total labor cost",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cost (parts + labor)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "has_photos",
                    models.BooleanField(
                        default=False, help_text="Report includes photos"
                    ),
                ),
                (
                    "has_diagrams",
                    models.BooleanField(
                        default=False, help_text="Report includes diagrams"
                    ),
                ),
                (
                    "has_test_results",
                    models.BooleanField(
                        default=False, help_text="Report includes test results"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("SENT", "Sent to Customer"),
                            ("ACKNOWLEDGED", "Customer Acknowledged"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Report status",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_for_review_at",
                    models.DateTimeField(
                        blank=True, help_text="When submitted for review", null=True
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was approved", null=True
                    ),
                ),
                (
                    "sent_to_customer_at",
                    models.DateTimeField(
                        blank=True, help_text="When sent to customer", null=True
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, help_text="Email sent to", max_length=254
                    ),
                ),
                (
                    "customer_acknowledged_at",
                    models.DateTimeField(
                        blank=True, help_text="When customer acknowledged", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_service_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_service_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bits_serviced",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Drill bits serviced",
                        related_name="service_reports",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        help_text="Related field service request",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_reports",
                        to="sales.fieldservicerequest",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        help_text="Related site visit",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_reports",
                        to="sales.sitevisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Report",
                "verbose_name_plural": "Service Reports",
                "db_table": "service_reports",
                "ordering": ["-report_date"],
                "permissions": [
                    ("can_approve_service_reports", "Can approve service reports"),
                    ("can_send_to_customer", "Can send reports to customers"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="serviceschedule",
            index=models.Index(
                fields=["schedule_number"], name="service_sch_schedul_0f033c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceschedule",
            index=models.Index(
                fields=["scheduled_date", "status"],
                name="service_sch_schedul_e7810d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceschedule",
            index=models.Index(
                fields=["technician", "scheduled_date"],
                name="service_sch_technic_0d54fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceschedule",
            index=models.Index(
                fields=["service_request", "status"],
                name="service_sch_service_213763_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["visit_number"], name="site_visits_visit_n_89d2d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["visit_date", "status"], name="site_visits_visit_d_300044_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["technician", "visit_date"],
                name="site_visits_technic_8eb88c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["service_site", "visit_date"],
                name="site_visits_service_395d05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicereport",
            index=models.Index(
                fields=["report_number"], name="service_rep_report__ad7fa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicereport",
            index=models.Index(
                fields=["report_date", "status"], name="service_rep_report__84c8c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicereport",
            index=models.Index(
                fields=["service_request"], name="service_rep_service_4b9c88_idx"
            ),
        ),
    ]
