# Generated by Django 5.1.15 on 2026-01-31 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_account"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["sort_order", "code"],
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="contract_number",
            field=models.CharField(
                blank=True,
                help_text="Contract number (e.g., 960031408 for LSTK, 6600048646 for ARAMCO)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Default customer for this account (e.g., Halliburton for LSTK)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_accounts",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="delivery_location",
            field=models.CharField(
                blank=True,
                default="HDBS Warehouse",
                help_text="Default delivery destination",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="legacy_wo_format",
            field=models.CharField(
                blank=True,
                help_text="Legacy display format description (for reference)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="max_repairs",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum allowed repairs (null = unlimited, 2 for ARAMCO)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard (Book Stock)"),
                    ("LSTK", "LSTK Pricing"),
                    ("ARAMCO", "ARAMCO Contract Pricing"),
                    ("ZERO", "Zero (Internal / Partner)"),
                    ("REGIONAL", "Regional Pricing"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="repair_suffix_format",
            field=models.CharField(
                blank=True,
                help_text='Repair suffix display format (e.g., "R{n}" for ARAMCO → R, R2)',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="reviewer_label",
            field=models.CharField(
                blank=True,
                default="Reviewed by Eng.",
                help_text='Label for reviewer field (e.g., "DTD/TSSD:" for ARAMCO)',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="Display order in dropdowns"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="vendor_number",
            field=models.CharField(
                blank=True,
                default="10012130",
                help_text="ARDT vendor number for this account",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="wo_format",
            field=models.CharField(
                choices=[
                    ("STANDARD", "YYYY-CODE-NNN"),
                    ("NUMERIC", "YYYYNNNN"),
                    ("SUFFIX", "YYYYNNNN-SUFFIX"),
                ],
                default="STANDARD",
                help_text="WO number format template",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="wo_prefix",
            field=models.CharField(
                blank=True,
                help_text="WO number prefix code (e.g., AR, ARDT-LV3, RC). Used in STANDARD format.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="wo_seq_padding",
            field=models.IntegerField(
                default=3, help_text="Sequence number padding (3 → 001, 4 → 0001)"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="wo_seq_start",
            field=models.IntegerField(
                default=1,
                help_text="Sequence start number (1 for most accounts, 1001 for UR/WFD)",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="wo_suffix",
            field=models.CharField(
                blank=True,
                help_text="WO number suffix (e.g., HDBSC, REG). Used in SUFFIX format.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("REPAIR", "Repair / Rework"),
                    ("MANUFACTURE", "New Build (L3/L4)"),
                    ("BOTH", "Both Repair and Manufacture"),
                ],
                default="REPAIR",
                help_text="Primary workflow type for this account",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(
                help_text="Short code (e.g., LSTK, ARAMCO, UR)",
                max_length=20,
                unique=True,
                verbose_name="Account Code",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(
                help_text="Full display name",
                max_length=100,
                verbose_name="Account Name",
            ),
        ),
    ]
