# Generated by Django 5.2.8 on 2025-12-06 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0002_sprint6_models"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="capa",
            name="capa_number",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="costallocation",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Work order to allocate cost to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_allocations",
                to="workorders.workorder",
            ),
        ),
    ]
