# Generated by Django 5.1.15 on 2025-12-24 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_rolepermission_permission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="User-friendly device name",
                        max_length=100,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, help_text="mobile, tablet, desktop", max_length=50
                    ),
                ),
                (
                    "device_os",
                    models.CharField(
                        blank=True,
                        help_text="iOS, Android, Windows, etc.",
                        max_length=50,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "fingerprint_hash",
                    models.CharField(
                        blank=True, help_text="Browser fingerprint hash", max_length=64
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "trust_level",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Access"),
                            ("LIMITED", "Limited Access (view only)"),
                            ("PENDING", "Pending Approval"),
                        ],
                        default="FULL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiration", null=True
                    ),
                ),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_location", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trusted Device",
                "verbose_name_plural": "Trusted Devices",
                "db_table": "trusted_devices",
                "ordering": ["-last_used_at", "-created_at"],
            },
        ),
    ]
