# Generated by Django 5.1.15 on 2026-04-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_trusted_device_model"),
        ("organization", "0002_alter_systemsetting_updated_by"),
        ("sales", "0008_alter_account_options_account_contract_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="has_full_visibility",
            field=models.BooleanField(
                default=False,
                help_text="GM/Director level — sees all workflow actions in overview",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_workflow_admin",
            field=models.BooleanField(
                default=False, help_text="Can configure workflow rules and capabilities"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="positions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users assigned to these positions auto-receive this role",
                related_name="default_roles",
                to="organization.position",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="account_scope",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict workflow routing to specific accounts. Empty = all.",
                related_name="scoped_user_roles",
                to="sales.account",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to pause workflow routing (leave, Ramadan hours)",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="is_position_derived",
            field=models.BooleanField(
                default=False,
                help_text="True = auto-assigned from position. False = manually granted.",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Acting Operations Manager — temporary"',
                max_length=200,
            ),
        ),
    ]
