# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "bit_type",
                    models.CharField(
                        choices=[("FC", "Fixed Cutter (PDC)"), ("RC", "Roller Cone")],
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=3, help_text="Size in inches", max_digits=6
                    ),
                ),
                ("iadc_code", models.CharField(blank=True, max_length=20)),
                (
                    "blade_count",
                    models.IntegerField(blank=True, help_text="For FC bits", null=True),
                ),
                (
                    "cone_count",
                    models.IntegerField(blank=True, help_text="For RC bits", null=True),
                ),
                ("connection_type", models.CharField(blank=True, max_length=50)),
                ("connection_size", models.CharField(blank=True, max_length=20)),
                (
                    "formation_type",
                    models.CharField(
                        blank=True, help_text="Target formation", max_length=100
                    ),
                ),
                ("application", models.CharField(blank=True, max_length=100)),
                ("gauge_protection", models.CharField(blank=True, max_length=100)),
                ("nozzle_config", models.CharField(blank=True, max_length=100)),
                (
                    "tfa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Total Flow Area",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "drawing_file",
                    models.FileField(
                        blank=True, null=True, upload_to="designs/drawings/"
                    ),
                ),
                (
                    "specification_file",
                    models.FileField(blank=True, null=True, upload_to="designs/specs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("OBSOLETE", "Obsolete"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("revision", models.CharField(default="A", max_length=10)),
                ("revision_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "designed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designed_bits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Design",
                "verbose_name_plural": "Designs",
                "db_table": "designs",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("revision", models.CharField(default="A", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("OBSOLETE", "Obsolete"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_boms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boms",
                        to="technology.design",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill of Materials",
                "verbose_name_plural": "Bills of Materials",
                "db_table": "boms",
                "ordering": ["design", "code"],
            },
        ),
        migrations.CreateModel(
            name="BOMLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, help_text="Assembly position", max_length=50
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "is_phantom",
                    models.BooleanField(
                        default=False, help_text="Sub-assembly to be exploded"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="technology.bom",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_lines",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM Line",
                "verbose_name_plural": "BOM Lines",
                "db_table": "bom_lines",
                "ordering": ["bom", "line_number"],
                "unique_together": {("bom", "line_number")},
            },
        ),
        migrations.CreateModel(
            name="DesignCutterLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blade_number", models.IntegerField()),
                ("position_number", models.IntegerField()),
                ("cutter_type", models.CharField(max_length=50)),
                (
                    "cutter_size",
                    models.DecimalField(decimal_places=2, help_text="mm", max_digits=6),
                ),
                ("cutter_grade", models.CharField(blank=True, max_length=50)),
                (
                    "radial_position",
                    models.DecimalField(
                        decimal_places=3, help_text="mm from center", max_digits=8
                    ),
                ),
                (
                    "backrake",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="degrees",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "siderake",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="degrees",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "exposure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutter_layouts",
                        to="technology.design",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Layout",
                "verbose_name_plural": "Cutter Layouts",
                "db_table": "design_cutter_layouts",
                "ordering": ["design", "blade_number", "position_number"],
                "unique_together": {("design", "blade_number", "position_number")},
            },
        ),
    ]
