# Generated by Django 5.1.15 on 2025-12-13 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0003_update_design_model_phase2"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Special Technology",
                "verbose_name_plural": "Special Technologies",
                "db_table": "special_technologies",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="design",
            name="gauge_protection",
        ),
        migrations.RemoveField(
            model_name="design",
            name="nozzle_size",
        ),
        migrations.AddField(
            model_name="design",
            name="connection_mat_no",
            field=models.CharField(
                blank=True,
                help_text="Material number of the connection",
                max_length=20,
                verbose_name="Connection MAT No.",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="erosion_sleeve",
            field=models.BooleanField(
                default=False,
                help_text="Has erosion sleeve protection",
                verbose_name="Erosion Sleeve",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="milling_drawing",
            field=models.FileField(
                blank=True,
                help_text="PDF of milling/nozzle layout drawing",
                null=True,
                upload_to="designs/milling/",
                verbose_name="Milling Drawing",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="nozzle_bore_size",
            field=models.CharField(
                blank=True,
                help_text="Fixed bore size in design (e.g., 12/32, 14/32)",
                max_length=50,
                verbose_name="Nozzle Bore Size",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="cutter_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cutter size grade (from HDBS Type 2nd digit)",
                null=True,
                verbose_name="Cutter Size Grade",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="gage_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Gage length in inches (positive values only)",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Gage Length (in)",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="gage_relief",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Gage relief in inch thou (positive values only)",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Gage Relief (thou)",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="nozzle_config",
            field=models.CharField(
                blank=True,
                help_text="Layout of nozzles (reference Milling drawing)",
                max_length=100,
                verbose_name="Nozzle Configuration",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="port_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Port size - positive values only",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Port Size",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="tfa",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Total Flow Area - positive values only",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="TFA (sq.in)",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="special_technologies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select one or more special technologies (Cerebro Puck, Torpedo, etc.)",
                related_name="designs",
                to="technology.specialtechnology",
                verbose_name="Special Technologies",
            ),
        ),
    ]
