# Generated by Django 5.1.15 on 2025-12-13 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0005_uppersectiontype_design_upper_section_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mat_no",
                    models.CharField(
                        help_text="Connection material number",
                        max_length=20,
                        unique=True,
                        verbose_name="MAT No.",
                    ),
                ),
                (
                    "special_features",
                    models.TextField(
                        blank=True,
                        help_text="Any special features or modifications",
                        verbose_name="Special Features",
                    ),
                ),
                (
                    "can_replace_in_ksa",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this connection can be replaced/repaired in Saudi Arabia",
                        verbose_name="Can Replace in KSA",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connections",
                        to="technology.connectionsize",
                        verbose_name="Size",
                    ),
                ),
                (
                    "connection_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connections",
                        to="technology.connectiontype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "upper_section_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connections",
                        to="technology.uppersectiontype",
                        verbose_name="Upper Section Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
                "db_table": "connections",
                "ordering": ["mat_no"],
            },
        ),
        migrations.AddField(
            model_name="design",
            name="connection_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a pre-defined connection from the connections table",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="technology.connection",
                verbose_name="Connection",
            ),
        ),
    ]
