# Generated by Django 5.1.15 on 2025-12-15 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0006_connection_model"),
        ("workorders", "0006_bittype_phase2_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakerSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mat_no",
                    models.CharField(
                        help_text="Breaker slot material number",
                        max_length=20,
                        unique=True,
                        verbose_name="MAT No.",
                    ),
                ),
                (
                    "slot_width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Width of the slot opening in millimeters",
                        max_digits=6,
                        verbose_name="Slot Width (mm)",
                    ),
                ),
                (
                    "slot_depth",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Depth of the slot in millimeters",
                        max_digits=6,
                        verbose_name="Slot Depth (mm)",
                    ),
                ),
                (
                    "slot_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Length of the slot along the shank in millimeters",
                        max_digits=6,
                        null=True,
                        verbose_name="Slot Length (mm)",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("ALLOY", "Alloy Steel"),
                            ("4140", "AISI 4140 Steel"),
                            ("4145", "AISI 4145H Steel"),
                            ("4340", "AISI 4340 Steel"),
                            ("CrMo", "Chrome-Moly Steel"),
                            ("OTHER", "Other"),
                        ],
                        default="ALLOY",
                        help_text="Material of the breaker slot / shank",
                        max_length=10,
                        verbose_name="Material",
                    ),
                ),
                (
                    "hardness",
                    models.CharField(
                        blank=True,
                        help_text="Rockwell hardness rating (e.g., 28-32 HRC)",
                        max_length=20,
                        verbose_name="Hardness (HRC)",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compatible_sizes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Bit sizes this breaker slot is compatible with",
                        related_name="breaker_slots",
                        to="workorders.bitsize",
                        verbose_name="Compatible Bit Sizes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breaker Slot",
                "verbose_name_plural": "Breaker Slots",
                "db_table": "breaker_slots",
                "ordering": ["mat_no"],
            },
        ),
        migrations.AddField(
            model_name="design",
            name="breaker_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="Breaker slot specification for this design",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="technology.breakerslot",
                verbose_name="Breaker Slot",
            ),
        ),
    ]
