# Generated by Django 5.1.15 on 2025-12-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0008_merge_20251215_1008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakerslot",
            name="slot_depth",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Depth of the slot in inches",
                max_digits=6,
                verbose_name="Slot Depth (in)",
            ),
        ),
        migrations.AlterField(
            model_name="breakerslot",
            name="slot_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Length of the slot along the shank in inches",
                max_digits=6,
                null=True,
                verbose_name="Slot Length (in)",
            ),
        ),
        migrations.AlterField(
            model_name="breakerslot",
            name="slot_width",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Width of the slot opening in inches",
                max_digits=6,
                verbose_name="Slot Width (in)",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="breaker_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a breaker slot specification for this design",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="technology.breakerslot",
                verbose_name="Breaker Slot",
            ),
        ),
    ]
