# Generated by Django 5.1.15 on 2025-12-15 10:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0009_alter_breakerslot_slot_depth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PocketShape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional technical information about this shape",
                        verbose_name="Technical Notes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pocket Shape",
                "verbose_name_plural": "Pocket Shapes",
                "db_table": "pocket_shapes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PocketSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Pocket size code (e.g., 1608, 1613, 19)",
                        max_length=20,
                        unique=True,
                        verbose_name="Size Code",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name",
                        max_length=50,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "diameter_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pocket diameter in millimeters",
                        max_digits=6,
                        null=True,
                        verbose_name="Diameter (mm)",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pocket Size",
                "verbose_name_plural": "Pocket Sizes",
                "db_table": "pocket_sizes",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="design",
            name="pocket_rows_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of pocket rows (1-4)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Pocket Rows Count",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="total_pockets_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total number of cutter pockets in the design",
                null=True,
                verbose_name="Total Pockets Count",
            ),
        ),
        migrations.CreateModel(
            name="DesignPocketConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Display order (1, 2, 3...)", verbose_name="Order"
                    ),
                ),
                (
                    "length_type",
                    models.CharField(
                        choices=[("L", "Long"), ("M", "Medium"), ("S", "Short")],
                        default="L",
                        help_text="Long, Medium, or Short",
                        max_length=1,
                        verbose_name="L/M/S",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        help_text="Number of pockets with this configuration",
                        verbose_name="Count",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color for visual identification (e.g., #FF5733)",
                        max_length=7,
                        verbose_name="Color Code",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pocket_configs",
                        to="technology.design",
                    ),
                ),
                (
                    "pocket_shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="design_configs",
                        to="technology.pocketshape",
                    ),
                ),
                (
                    "pocket_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="design_configs",
                        to="technology.pocketsize",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Pocket Config",
                "verbose_name_plural": "Design Pocket Configs",
                "db_table": "design_pocket_configs",
                "ordering": ["design", "order"],
                "unique_together": {("design", "order")},
            },
        ),
        migrations.CreateModel(
            name="DesignPocket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blade_number",
                    models.PositiveIntegerField(
                        help_text="Blade number (1 to no_of_blades)",
                        verbose_name="Blade",
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Row number (1 to pocket_rows_count)",
                        verbose_name="Row",
                    ),
                ),
                (
                    "position_in_row",
                    models.PositiveIntegerField(
                        help_text="Position within this blade and row",
                        verbose_name="Position in Row",
                    ),
                ),
                (
                    "position_in_blade",
                    models.PositiveIntegerField(
                        help_text="Sequential position within entire blade (across all rows)",
                        verbose_name="Position in Blade",
                    ),
                ),
                (
                    "engagement_order",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Full engagement sequence order (set in separate tab)",
                        null=True,
                        verbose_name="Engagement Order",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pockets",
                        to="technology.design",
                    ),
                ),
                (
                    "pocket_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pockets",
                        to="technology.designpocketconfig",
                        verbose_name="Pocket Configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Pocket",
                "verbose_name_plural": "Design Pockets",
                "db_table": "design_pockets",
                "ordering": ["design", "blade_number", "row_number", "position_in_row"],
                "unique_together": {
                    ("design", "blade_number", "row_number", "position_in_row")
                },
            },
        ),
    ]
