# Generated by Django 5.1.15 on 2025-12-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0011_add_pocket_layout_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="designpocketconfig",
            name="row_number",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Which row this configuration belongs to (1-4)",
                verbose_name="Row Number",
            ),
        ),
    ]
