# Generated by Django 5.1.15 on 2025-12-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0012_add_row_number_to_pocket_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="designpocket",
            name="blade_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Cone"),
                    ("N", "Nose"),
                    ("T", "Taper"),
                    ("S", "Shoulder"),
                    ("G", "Gage"),
                ],
                help_text="Location zone on blade: Cone, Nose, Taper, Shoulder, Gage",
                max_length=1,
                null=True,
                verbose_name="Blade Location",
            ),
        ),
    ]
