# Generated by Django 5.1.15 on 2025-12-27 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_account"),
        ("technology", "0019_alter_hdbstype_sizes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignHDBS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current HDBS type for this design",
                        verbose_name="Is Current",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigned At"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hdbs_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned By",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hdbs_assignments",
                        to="technology.design",
                        verbose_name="Design",
                    ),
                ),
                (
                    "hdbs_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_assignments",
                        to="technology.hdbstype",
                        verbose_name="HDBS Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design HDBS Assignment",
                "verbose_name_plural": "Design HDBS Assignments",
                "db_table": "design_hdbs",
                "ordering": ["design", "-assigned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("design",),
                        name="unique_current_hdbs_per_design",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DesignSMI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current SMI type for this design/account",
                        verbose_name="Is Current",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigned At"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aramco division (leave blank for global SMI)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smi_assignments",
                        to="sales.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smi_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned By",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smi_assignments",
                        to="technology.design",
                        verbose_name="Design",
                    ),
                ),
                (
                    "smi_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_assignments",
                        to="technology.smitype",
                        verbose_name="SMI Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design SMI Assignment",
                "verbose_name_plural": "Design SMI Assignments",
                "db_table": "design_smi",
                "ordering": ["design", "account", "-assigned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("design", "account"),
                        name="unique_current_smi_per_design_account",
                    )
                ],
            },
        ),
    ]
