# Generated by Django 5.1.15 on 2026-01-01 21:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_add_account_to_itemvariant"),
        ("technology", "0020_designhdbs_designsmi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bomline",
            options={
                "ordering": ["bom", "order_number", "line_number"],
                "verbose_name": "BOM Line",
                "verbose_name_plural": "BOM Lines",
            },
        ),
        migrations.AddField(
            model_name="bom",
            name="source_date_created",
            field=models.DateTimeField(
                blank=True, help_text="Date Created from PDF", null=True
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="source_mat_number",
            field=models.CharField(
                blank=True,
                help_text="Mat Number from PDF (e.g., 2020054)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="source_pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Original uploaded PDF file",
                null=True,
                upload_to="bom_pdfs/",
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="source_revision_level",
            field=models.CharField(
                blank=True,
                help_text="Revision Level from PDF (e.g., D - 390254)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="source_sn_number",
            field=models.CharField(
                blank=True, help_text="SN Number from PDF", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="source_software_version",
            field=models.CharField(
                blank=True, help_text="ADesc Software Version from PDF", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual Entry"),
                    ("PDF_IMPORT", "PDF Import"),
                    ("ERP_SYNC", "ERP Sync"),
                ],
                default="MANUAL",
                help_text="How this BOM was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="color_code",
            field=models.CharField(
                default="#4A4A4A",
                help_text="Hex color code for visual identification (e.g., #4A4A4A)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="cutter_chamfer",
            field=models.CharField(
                blank=True,
                help_text="Chamfer type (e.g., 18C-60, U-60, DROP-IN, NA)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="cutter_size",
            field=models.CharField(
                blank=True,
                help_text="Cutter size code (e.g., 1313, 1613, 8MM)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="cutter_type",
            field=models.CharField(
                blank=True,
                help_text="Cutter type/model (e.g., CT418, CT170, WC-MAT400)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="family_number",
            field=models.CharField(
                blank=True, help_text="Family # from PDF", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="hdbs_code",
            field=models.CharField(
                blank=True,
                help_text="HDBS Code / Mat # for item identification (e.g., 871781)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="order_number",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Display order (1, 2, 3...) - used for grouping and color coding",
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked inventory item (matched by HDBS Code)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bom_lines",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of cutters (must be positive integer)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="unit",
            field=models.CharField(blank=True, default="EA", max_length=20),
        ),
        migrations.CreateModel(
            name="BOMCutterPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blade_number",
                    models.PositiveIntegerField(
                        help_text="Blade number (1-7, representing B1-B7)"
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Row number (1-4, representing R1-R4)"
                    ),
                ),
                (
                    "blade_location",
                    models.CharField(
                        choices=[
                            ("CONE", "Cone"),
                            ("NOSE", "Nose"),
                            ("SHOULDER", "Shoulder"),
                            ("GAUGE", "Gauge"),
                            ("PAD", "Pad"),
                        ],
                        help_text="Location on blade: CONE, NOSE, SHOULDER, GAUGE, PAD",
                        max_length=10,
                    ),
                ),
                (
                    "position_in_location",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Position within the location (for multiple cutters in same location)",
                    ),
                ),
                (
                    "cutter_type_display",
                    models.CharField(
                        blank=True,
                        help_text="Cutter type as displayed in PDF cell (e.g., CT418)",
                        max_length=50,
                    ),
                ),
                (
                    "order_number_display",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Order number displayed in cell (colored circle)",
                        null=True,
                    ),
                ),
                (
                    "chamfer_display",
                    models.CharField(
                        blank=True,
                        help_text="Chamfer as displayed in PDF cell",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bom",
                    models.ForeignKey(
                        help_text="Parent BOM",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutter_positions",
                        to="technology.bom",
                    ),
                ),
                (
                    "bom_line",
                    models.ForeignKey(
                        help_text="BOM line this position belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grid_positions",
                        to="technology.bomline",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM Cutter Position",
                "verbose_name_plural": "BOM Cutter Positions",
                "db_table": "bom_cutter_positions",
                "ordering": [
                    "bom",
                    "blade_number",
                    "row_number",
                    "blade_location",
                    "position_in_location",
                ],
                "unique_together": {
                    (
                        "bom",
                        "blade_number",
                        "row_number",
                        "blade_location",
                        "position_in_location",
                    )
                },
            },
        ),
    ]
