# Generated by Django 5.1.15 on 2026-01-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0025_add_source_data_to_bom"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="bom_type",
            field=models.CharField(
                choices=[("BRAZING", "Brazing BOM"), ("SYSTEM", "System BOM")],
                default="SYSTEM",
                help_text="Brazing BOM (internal/production) or System BOM (client-facing)",
                max_length=20,
                verbose_name="BOM Type",
            ),
        ),
    ]
