# Generated by Django 5.1.15 on 2026-01-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0026_add_bom_type_and_bom_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="system_mat_no",
            field=models.CharField(
                blank=True,
                help_text="Client-facing MAT number (for Brazing BOMs with alternate client reference)",
                max_length=50,
                verbose_name="System MAT#",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="bom_type",
            field=models.CharField(
                choices=[("BRAZING", "Brazing BOM"), ("SYSTEM", "System BOM")],
                default="BRAZING",
                help_text="Brazing BOM (internal/production) or System BOM (client-facing)",
                max_length=20,
                verbose_name="BOM Type",
            ),
        ),
    ]
