# Generated by Django 5.1.15 on 2026-01-31 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0031_add_bom_is_original_serial_parent"),
        ("workorders", "0012_add_bom_work_order_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Work order this BOM was created/modified for (build, repair, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bom_copies",
                to="workorders.workorder",
            ),
        ),
    ]
