# Generated by Django 5.1.15 on 2026-01-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0032_add_bom_work_order_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bom",
            name="work_order",
        ),
    ]
