# Generated by Django 5.1.15 on 2026-01-10 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("technology", "0022_add_smi_type_to_bom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CutterMapDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_pdf",
                    models.FileField(
                        upload_to="cutter_maps/originals/%Y/%m/",
                        verbose_name="Original PDF",
                    ),
                ),
                (
                    "generated_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cutter_maps/generated/%Y/%m/",
                        verbose_name="Generated PDF",
                    ),
                ),
                (
                    "generated_ppt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cutter_maps/generated/%Y/%m/",
                        verbose_name="Generated PPT",
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data extracted from the original PDF",
                        verbose_name="Extracted Data",
                    ),
                ),
                (
                    "edited_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data after user edits",
                        verbose_name="Edited Data",
                    ),
                ),
                (
                    "mat_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="MAT Number"
                    ),
                ),
                (
                    "sn_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="SN Number"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Original Filename"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("EXTRACTED", "Data Extracted"),
                            ("EDITED", "Edited"),
                            ("GENERATED", "PDF Generated"),
                            ("SYNCED", "Synced to ERP"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Validated"),
                ),
                (
                    "validation_messages",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Validation Messages"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cutter_map_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cutter_map_documents",
                        to="technology.design",
                        verbose_name="Linked Design",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Map Document",
                "verbose_name_plural": "Cutter Map Documents",
                "db_table": "cutter_map_documents",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_upload_cutter_map", "Can upload cutter map PDFs"),
                    ("can_edit_cutter_map", "Can edit cutter map data"),
                    ("can_generate_cutter_map", "Can generate cutter map PDFs"),
                    ("can_sync_cutter_map", "Can sync cutter map to ERP"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CutterMapHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "Uploaded"),
                            ("EXTRACT", "Data Extracted"),
                            ("EDIT", "Data Edited"),
                            ("GEN_PDF", "PDF Generated"),
                            ("GEN_PPT", "PPT Generated"),
                            ("VALIDATE", "Validated"),
                            ("SYNC", "Synced to ERP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="cutter_map.cuttermapdocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Map History",
                "verbose_name_plural": "Cutter Map History",
                "db_table": "cutter_map_history",
                "ordering": ["-timestamp"],
            },
        ),
    ]
