# Generated by Django 5.2.8 on 2025-12-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BranchEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_met", models.BooleanField()),
                ("evaluated_value", models.CharField(blank=True, max_length=500)),
                ("action_taken", models.CharField(blank=True, max_length=30)),
                ("target_step_id", models.BigIntegerField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Branch Evaluation",
                "verbose_name_plural": "Branch Evaluations",
                "db_table": "branch_evaluations",
            },
        ),
        migrations.CreateModel(
            name="CheckpointResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("NA", "Not Applicable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actual_value", models.CharField(blank=True, max_length=200)),
                (
                    "measured_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("is_within_tolerance", models.BooleanField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="checkpoint_photos/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Checkpoint Result",
                "verbose_name_plural": "Checkpoint Results",
                "db_table": "checkpoint_results",
                "ordering": ["step_execution", "checkpoint__sequence"],
            },
        ),
        migrations.CreateModel(
            name="FormFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="form_files/"),
                ),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_message", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "Form Field Value",
                "verbose_name_plural": "Form Field Values",
                "db_table": "form_field_values",
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_version", models.CharField(blank=True, max_length=10)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_errors", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
                "db_table": "form_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedure_version", models.CharField(blank=True, max_length=10)),
                (
                    "procedure_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of procedure at execution time",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("total_pause_duration", models.DurationField(blank=True, null=True)),
                ("result_summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Procedure Execution",
                "verbose_name_plural": "Procedure Executions",
                "db_table": "procedure_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StepExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("NA", "Not Applicable"),
                            ("PARTIAL", "Partial"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("qr_scanned", models.BooleanField(default=False)),
                ("qr_scan_time", models.DateTimeField(blank=True, null=True)),
                ("scanned_code", models.CharField(blank=True, max_length=200)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="step_photos/"),
                ),
                ("photo_taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="step_signatures/"
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("skip_reason", models.TextField(blank=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Step Execution",
                "verbose_name_plural": "Step Executions",
                "db_table": "step_executions",
                "ordering": ["execution", "step__step_number"],
            },
        ),
    ]
