# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("execution", "0001_initial"),
        ("procedures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="branchevaluation",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="procedures.stepbranch"
            ),
        ),
        migrations.AddField(
            model_name="checkpointresult",
            name="checkpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="procedures.stepcheckpoint",
            ),
        ),
        migrations.AddField(
            model_name="checkpointresult",
            name="evaluated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
