# Generated by Django 5.2.8 on 2025-12-05 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0004_initial"),
        ("forms_engine", "0002_alter_formfield_field_type_and_more"),
        ("procedures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchevaluation",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluations",
                to="procedures.stepbranch",
            ),
        ),
        migrations.AlterField(
            model_name="checkpointresult",
            name="checkpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="procedures.stepcheckpoint",
            ),
        ),
        migrations.AlterField(
            model_name="checkpointresult",
            name="evaluated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluated_checkpoints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="formfieldvalue",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_values",
                to="forms_engine.formfield",
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="form_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="forms_engine.formtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="submitted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
