# Generated by Django 5.1.15 on 2025-12-12 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_rolepermission_permission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="layout-dashboard", max_length=50)),
                (
                    "widget_config",
                    models.JSONField(
                        default=list, help_text="Widget layout configuration"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private (only me)"),
                            ("SHARED", "Shared with roles"),
                            ("PUBLIC", "Public (all users)"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Make this dashboard the default for users with access",
                    ),
                ),
                (
                    "show_in_sidebar",
                    models.BooleanField(
                        default=True, help_text="Show this dashboard in the sidebar"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Roles that can view this dashboard",
                        related_name="shared_dashboards",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Dashboard",
                "verbose_name_plural": "Saved Dashboards",
                "db_table": "dashboard_saved",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="dashboard.saveddashboard",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_favorites",
                "ordering": ["order", "created_at"],
                "unique_together": {("user", "dashboard")},
            },
        ),
    ]
