# Generated by Django 5.2.8 on 2025-12-06 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="statustransitionlog",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_transition_logs",
                to="contenttypes.contenttype",
            ),
        ),
    ]
