# Generated by Django 5.1.15 on 2025-12-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0005_phase2_bit_tracking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bittype",
            options={
                "ordering": ["category", "series", "smi_name", "code"],
                "verbose_name": "Bit Type",
                "verbose_name_plural": "Bit Types",
            },
        ),
        migrations.AddField(
            model_name="bittype",
            name="ardt_item_number",
            field=models.CharField(
                blank=True, help_text="ARDT ERP Item Number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="body_material",
            field=models.CharField(
                blank=True,
                choices=[("M", "Matrix"), ("S", "Steel"), ("", "N/A")],
                default="",
                help_text="Body material: M=Matrix, S=Steel",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="category",
            field=models.CharField(
                choices=[
                    ("FC", "Fixed Cutter"),
                    ("MT", "Mill Tooth"),
                    ("TCI", "Tri Cone Inserts"),
                ],
                default="FC",
                help_text="FC=Fixed Cutter, MT=Mill Tooth, TCI=Tri Cone Inserts",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="cutter_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="Cutter size in mm (FC only)", null=True
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="gage_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Gage length in inches (FC only)",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="hdbs_mn",
            field=models.CharField(
                blank=True, help_text="HDBS SAP Material Number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="hdbs_name",
            field=models.CharField(
                blank=True, help_text="Internal HDBS name", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="no_of_blades",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of blades (FC only)", null=True
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="order_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3", "Level 3 - No cutters, upper section separate"),
                    ("4", "Level 4 - No cutters, upper section welded/machined"),
                    ("5", "Level 5 - With cutters brazed"),
                    ("6", "Level 6 - Painted and ready for use"),
                ],
                help_text="JV Production Level: 3-6",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="ref_hdbs_mn",
            field=models.CharField(
                blank=True,
                help_text="Parent/Reference HDBS Material Number",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="size",
            field=models.ForeignKey(
                blank=True,
                help_text="Standard bit size",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bit_types",
                to="workorders.bitsize",
            ),
        ),
        migrations.AddField(
            model_name="bittype",
            name="smi_name",
            field=models.CharField(
                blank=True,
                help_text="SMI/Client-facing name (e.g., 'GT65RHs-1')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="bittype",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="bittype",
            name="series",
            field=models.CharField(
                blank=True, help_text="Series (GT, HD, MM, FX, EM, etc.)", max_length=20
            ),
        ),
    ]
