# Generated by Django 5.1.15 on 2025-12-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0007_remove_bittype_size_alter_drillbit_bit_size_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drillbit",
            name="bit_type",
            field=models.CharField(
                choices=[("FC", "Fixed Cutter (PDC)"), ("RC", "Roller Cone")],
                default="FC",
                help_text="Bit category: FC (Fixed Cutter) or RC (Roller Cone)",
                max_length=20,
            ),
        ),
    ]
