# Generated by Django 5.1.15 on 2026-01-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0022_add_smi_type_to_bom"),
        ("workorders", "0009_job_card_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="drillbit",
            name="bom",
            field=models.ForeignKey(
                blank=True,
                help_text="L5 BOM used to manufacture this drill bit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drill_bits",
                to="technology.bom",
            ),
        ),
    ]
