# Generated by Django 5.1.15 on 2026-01-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0026_add_bom_type_and_bom_fks"),
        ("workorders", "0010_add_bom_to_drillbit"),
    ]

    operations = [
        migrations.AddField(
            model_name="drillbit",
            name="brazing_bom",
            field=models.ForeignKey(
                blank=True,
                help_text="L5 Brazing BOM - internal/production (may have cutter suffix)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drillbits_brazing",
                to="technology.bom",
                verbose_name="Brazing BOM",
            ),
        ),
        migrations.AddField(
            model_name="drillbit",
            name="system_bom",
            field=models.ForeignKey(
                blank=True,
                help_text="L5 System BOM - client-facing (fixed MAT#)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drillbits_system",
                to="technology.bom",
                verbose_name="System BOM",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="brazing_bom",
            field=models.ForeignKey(
                blank=True,
                help_text="L5 Brazing BOM - internal/production",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorders_brazing",
                to="technology.bom",
                verbose_name="Brazing BOM",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="system_bom",
            field=models.ForeignKey(
                blank=True,
                help_text="L5 System BOM - client-facing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorders_system",
                to="technology.bom",
                verbose_name="System BOM",
            ),
        ),
        migrations.AlterField(
            model_name="drillbit",
            name="bom",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy: L5 BOM (use brazing_bom/system_bom instead)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drill_bits",
                to="technology.bom",
            ),
        ),
    ]
