# Generated by Django 5.1.15 on 2026-01-31 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_account_options_account_contract_number_and_more"),
        ("workorders", "0012_add_bom_work_order_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="drillbit",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account this bit belongs to (LSTK, ARAMCO, UR, L3, L4, ARDT, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drill_bits",
                to="sales.account",
            ),
        ),
        migrations.AddField(
            model_name="processroute",
            name="accounts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Accounts this route applies to (empty = all accounts)",
                related_name="process_routes",
                to="sales.account",
            ),
        ),
        migrations.AddField(
            model_name="processroute",
            name="workflow_type",
            field=models.CharField(
                blank=True,
                default="REPAIR",
                help_text="REPAIR or MANUFACTURE — determines which route template to use",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="processrouteoperation",
            name="has_yes_no",
            field=models.BooleanField(
                default=False,
                help_text="Step requires Yes/No answer (e.g., Cerebro Removal: Yes/No)",
            ),
        ),
        migrations.AddField(
            model_name="processrouteoperation",
            name="is_conditional",
            field=models.BooleanField(
                default=False, help_text='Step marked "If Applicable" — may be skipped'
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account driving WO number, pricing, and workflow rules",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="sales.account",
            ),
        ),
        migrations.AlterField(
            model_name="drillbit",
            name="is_aramco_contract",
            field=models.BooleanField(
                default=False,
                help_text="Legacy: use account instead. If true, serial increments on repair.",
            ),
        ),
    ]
