# Generated by Django 5.1.15 on 2026-02-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0013_drillbit_account_processroute_accounts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cutterevaluationmatrix",
            name="cutters_details",
            field=models.JSONField(
                blank=True,
                help_text="Cutters details for plant use: [{qty, size_mm, part_no, description, remarks}]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cutterevaluationmatrix",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REPAIR", "For Repair"),
                    ("RERUN", "For Rerun"),
                    ("SCRAP", "For Scrap"),
                    ("DEBRAZE", "De-braze"),
                    ("CUTTER_RETROFIT", "Cutter Retrofit"),
                    ("NEW_BUILD", "New Build"),
                    ("BODY_RETROFIT", "Body Retrofit"),
                ],
                help_text="Evaluation outcome decision",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cutterevaluationentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("O", "OK - No action needed"),
                    ("X", "Replace"),
                    ("R", "Rotate"),
                    ("S", "Spin"),
                    ("F", "Fill"),
                    ("L", "Lost"),
                    ("P", "Pocket Build Up"),
                    ("I", "Impact Arrestor Build Up"),
                    ("V", "Fin Build Up"),
                    ("", "Not evaluated"),
                ],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="cutterevaluationmatrix",
            name="evaluation_type",
            field=models.CharField(
                choices=[
                    ("RECEIVING", "Receiving Evaluation"),
                    ("ARDT", "ARDT Evaluation"),
                    ("ENGINEER", "Technical Rep. Evaluation"),
                    ("QC", "QC Evaluation"),
                    ("DIE_CHECK", "Die Check"),
                    ("FINAL_DIE_CHECK", "Final Die Check"),
                    ("FINAL_QC", "Final QC Evaluation"),
                    ("FINAL_INSPECTION", "Final Inspection"),
                    ("REWORK", "Rework Evaluation"),
                ],
                max_length=20,
            ),
        ),
    ]
