# Generated by Django 5.1.15 on 2026-02-06 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_account_options_account_contract_number_and_more"),
        ("workorders", "0014_cutterevaluationmatrix_cutters_details_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(
                        blank=True, help_text="Target date for starting work", null=True
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0, help_text="Sequence order in the plan"
                    ),
                ),
                (
                    "intended_wo_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FC_NEW", "FC New Build"),
                            ("FC_REWORK", "FC Rework"),
                            ("FC_REPAIR", "FC Repair"),
                            ("RC_NEW", "RC New Build"),
                            ("RC_REWORK", "RC Rework"),
                            ("RC_REPAIR", "RC Repair"),
                            ("RERUN", "Rerun"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Intended work order type when WO is created",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("WO_CREATED", "WO Created"),
                            ("REMOVED", "Removed"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Planning notes or remarks"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account for this planned work",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_entries",
                        to="sales.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_plan_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        help_text="Drill bit to be planned for production",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_entries",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "work_order",
                    models.OneToOneField(
                        blank=True,
                        help_text="Work Order created from this plan entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_entry",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Plan Entry",
                "verbose_name_plural": "Production Plan Entries",
                "db_table": "production_plan_entries",
                "ordering": ["sequence", "-priority", "planned_date", "created_at"],
            },
        ),
    ]
