# Generated by Django 5.1.15 on 2026-02-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0015_add_production_plan_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplanentry",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Target date for completing work (auto-calculated: 6 days, 4 for UR)",
                null=True,
            ),
        ),
    ]
