# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dispatch", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("journey_number", models.CharField(max_length=30, unique=True)),
                ("purpose", models.CharField(max_length=200)),
                ("departure_location", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                ("planned_departure", models.DateTimeField()),
                ("planned_arrival", models.DateTimeField()),
                ("actual_departure", models.DateTimeField(blank=True, null=True)),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("APPROVED", "Approved"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_journeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journeys_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dispatch.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey",
                "verbose_name_plural": "Journeys",
                "db_table": "journeys",
                "ordering": ["-planned_departure"],
            },
        ),
        migrations.CreateModel(
            name="HOCReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hoc_number", models.CharField(max_length=30, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("UNSAFE_ACT", "Unsafe Act"),
                            ("UNSAFE_CONDITION", "Unsafe Condition"),
                            ("NEAR_MISS", "Near Miss"),
                            ("POSITIVE", "Positive Observation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("immediate_action", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "HOC Report",
                "verbose_name_plural": "HOC Reports",
                "db_table": "hoc_reports",
                "ordering": ["-reported_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "reported_by"],
                        name="hoc_reports_status_81a0ba_idx",
                    ),
                    models.Index(
                        fields=["category"], name="hoc_reports_categor_a39c12_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_number", models.CharField(max_length=30, unique=True)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("INJURY", "Injury"),
                            ("ILLNESS", "Illness"),
                            ("PROPERTY_DAMAGE", "Property Damage"),
                            ("ENVIRONMENTAL", "Environmental"),
                            ("FIRE", "Fire"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MODERATE", "Moderate"),
                            ("MAJOR", "Major"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("immediate_action", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REPORTED", "Reported"),
                            ("INVESTIGATING", "Under Investigation"),
                            ("CLOSED", "Closed"),
                        ],
                        default="REPORTED",
                        max_length=20,
                    ),
                ),
                ("investigation_findings", models.TextField(blank=True)),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_actions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "db_table": "incidents",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "reported_by"],
                        name="incidents_status_0542ab_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="incidents_severit_667686_idx"
                    ),
                    models.Index(
                        fields=["occurred_at"], name="incidents_occurre_33c506_idx"
                    ),
                ],
            },
        ),
    ]
