# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderline",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_order_lines",
                to="workorders.workorder",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouses",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="delivery_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_orders",
                to="sales.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wells",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="rig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wells",
                to="sales.rig",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders",
                to="sales.well",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesorderline",
            unique_together={("sales_order", "line_number")},
        ),
    ]
