# Generated by Django 5.2.8 on 2025-12-05 22:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_initial"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique site code (e.g., SITE-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Site name", max_length=200)),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, help_text="Site name in Arabic", max_length=200
                    ),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("RIG_SITE", "Rig Site"),
                            ("WAREHOUSE", "Warehouse"),
                            ("FIELD_OFFICE", "Field Office"),
                            ("CUSTOMER_FACILITY", "Customer Facility"),
                            ("SERVICE_CENTER", "Service Center"),
                            ("OTHER", "Other"),
                        ],
                        default="RIG_SITE",
                        help_text="Type of service site",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("UNDER_CONSTRUCTION", "Under Construction"),
                            ("TEMPORARILY_CLOSED", "Temporarily Closed"),
                        ],
                        default="ACTIVE",
                        help_text="Current site status",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Site description and notes"
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(help_text="Primary address line", max_length=200),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, help_text="Secondary address line", max_length=200
                    ),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                (
                    "state_province",
                    models.CharField(
                        blank=True, help_text="State or province", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal/ZIP code", max_length=20
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Saudi Arabia", help_text="Country", max_length=100
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS latitude coordinate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS longitude coordinate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "elevation_meters",
                    models.IntegerField(
                        blank=True,
                        help_text="Elevation in meters above sea level",
                        null=True,
                    ),
                ),
                (
                    "primary_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact person name",
                        max_length=200,
                    ),
                ),
                (
                    "primary_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number",
                        max_length=50,
                    ),
                ),
                (
                    "primary_contact_email",
                    models.EmailField(
                        blank=True, help_text="Primary contact email", max_length=254
                    ),
                ),
                (
                    "alternate_contact_name",
                    models.CharField(
                        blank=True, help_text="Alternate contact person", max_length=200
                    ),
                ),
                (
                    "alternate_contact_phone",
                    models.CharField(
                        blank=True, help_text="Alternate contact phone", max_length=50
                    ),
                ),
                (
                    "access_instructions",
                    models.TextField(
                        blank=True, help_text="Instructions for accessing the site"
                    ),
                ),
                (
                    "security_requirements",
                    models.TextField(
                        blank=True, help_text="Security clearance or requirements"
                    ),
                ),
                (
                    "requires_escort",
                    models.BooleanField(
                        default=False, help_text="Whether visitors require an escort"
                    ),
                ),
                (
                    "requires_ppe",
                    models.BooleanField(
                        default=True, help_text="Whether PPE is required on site"
                    ),
                ),
                (
                    "ppe_requirements",
                    models.TextField(blank=True, help_text="Specific PPE requirements"),
                ),
                (
                    "operating_hours_start",
                    models.TimeField(
                        blank=True, help_text="Site operating hours start", null=True
                    ),
                ),
                (
                    "operating_hours_end",
                    models.TimeField(
                        blank=True, help_text="Site operating hours end", null=True
                    ),
                ),
                (
                    "is_24_hour",
                    models.BooleanField(
                        default=False, help_text="Whether site operates 24 hours"
                    ),
                ),
                (
                    "weekend_operations",
                    models.BooleanField(
                        default=False, help_text="Whether site operates on weekends"
                    ),
                ),
                ("has_parking", models.BooleanField(default=True)),
                ("has_loading_dock", models.BooleanField(default=False)),
                ("has_storage_area", models.BooleanField(default=False)),
                ("has_workshop", models.BooleanField(default=False)),
                (
                    "facility_notes",
                    models.TextField(
                        blank=True, help_text="Additional facility information"
                    ),
                ),
                (
                    "first_service_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of first service at this site",
                        null=True,
                    ),
                ),
                (
                    "last_service_date",
                    models.DateField(
                        blank=True, help_text="Date of most recent service", null=True
                    ),
                ),
                (
                    "total_service_visits",
                    models.IntegerField(
                        default=0, help_text="Total number of service visits"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether site is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_service_sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who owns/operates this site",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_sites",
                        to="sales.customer",
                    ),
                ),
                (
                    "rig",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated rig (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_sites",
                        to="sales.rig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Site",
                "verbose_name_plural": "Service Sites",
                "db_table": "service_sites",
                "ordering": ["customer", "name"],
                "permissions": [
                    ("can_view_all_sites", "Can view all service sites"),
                    ("can_manage_sites", "Can manage service sites"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldTechnician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique employee ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Full name", max_length=200)),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, help_text="Name in Arabic", max_length=200
                    ),
                ),
                ("email", models.EmailField(help_text="Email address", max_length=254)),
                ("phone", models.CharField(help_text="Phone number", max_length=50)),
                (
                    "mobile",
                    models.CharField(
                        blank=True, help_text="Mobile phone number", max_length=50
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, help_text="Emergency contact name", max_length=200
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, help_text="Emergency contact phone", max_length=50
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, help_text="Date of hire", null=True),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("INACTIVE", "Inactive"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="ACTIVE",
                        help_text="Current employment status",
                        max_length=20,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, help_text="Job title", max_length=100),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department", max_length=100
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("SENIOR", "Senior"),
                            ("EXPERT", "Expert"),
                        ],
                        default="INTERMEDIATE",
                        help_text="Skill level",
                        max_length=20,
                    ),
                ),
                (
                    "specializations",
                    models.TextField(
                        blank=True,
                        help_text="List of specializations (comma-separated)",
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True, help_text="List of certifications (comma-separated)"
                    ),
                ),
                (
                    "can_perform_inspections",
                    models.BooleanField(
                        default=True, help_text="Can perform equipment inspections"
                    ),
                ),
                (
                    "can_perform_repairs",
                    models.BooleanField(
                        default=True, help_text="Can perform equipment repairs"
                    ),
                ),
                (
                    "can_perform_training",
                    models.BooleanField(
                        default=False, help_text="Can perform customer training"
                    ),
                ),
                (
                    "home_base_location",
                    models.CharField(
                        blank=True, help_text="Home base location", max_length=200
                    ),
                ),
                (
                    "service_radius_km",
                    models.IntegerField(
                        default=100, help_text="Maximum service radius in kilometers"
                    ),
                ),
                (
                    "available_for_travel",
                    models.BooleanField(
                        default=True, help_text="Available for travel assignments"
                    ),
                ),
                (
                    "has_valid_drivers_license",
                    models.BooleanField(
                        default=True, help_text="Has valid driver's license"
                    ),
                ),
                (
                    "has_valid_passport",
                    models.BooleanField(
                        default=False,
                        help_text="Has valid passport for international travel",
                    ),
                ),
                (
                    "is_currently_assigned",
                    models.BooleanField(
                        default=False, help_text="Currently assigned to a job"
                    ),
                ),
                (
                    "total_service_calls",
                    models.IntegerField(
                        default=0, help_text="Total service calls completed"
                    ),
                ),
                (
                    "completed_calls",
                    models.IntegerField(
                        default=0, help_text="Successfully completed service calls"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average customer rating (1-5)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "on_time_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of on-time arrivals",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked user account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_technician_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current location if on assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_technicians",
                        to="sales.servicesite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Technician",
                "verbose_name_plural": "Field Technicians",
                "db_table": "field_technicians",
                "ordering": ["name"],
                "permissions": [
                    ("can_assign_technicians", "Can assign technicians to requests"),
                    (
                        "can_view_technician_performance",
                        "Can view technician performance",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique request number (auto-generated: FSR-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("DRILL_BIT_INSPECTION", "Drill Bit Inspection"),
                            ("DRILL_BIT_REPAIR", "Drill Bit Repair"),
                            ("DRILL_STRING_SERVICE", "Drill String Service"),
                            ("DRILL_STRING_INSPECTION", "Drill String Inspection"),
                            ("EMERGENCY_REPAIR", "Emergency Repair"),
                            ("SCHEDULED_MAINTENANCE", "Scheduled Maintenance"),
                            ("TECHNICAL_SUPPORT", "Technical Support"),
                            ("TRAINING", "Training"),
                            ("CONSULTATION", "Consultation"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of service requested",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        help_text="Request priority level",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Current request status",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title/summary of the request", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of service needed"
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes from customer"
                    ),
                ),
                (
                    "requested_date",
                    models.DateField(help_text="Date customer wants service performed"),
                ),
                (
                    "requested_time_slot",
                    models.CharField(
                        blank=True, help_text="Preferred time slot", max_length=50
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated service duration in hours",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "flexible_scheduling",
                    models.BooleanField(
                        default=False,
                        help_text="Whether customer is flexible with scheduling",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        blank=True, help_text="When technician was assigned", null=True
                    ),
                ),
                (
                    "auto_create_work_order",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create work order upon approval",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="On-site contact person name", max_length=200
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        help_text="On-site contact phone number", max_length=50
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="On-site contact email address",
                        max_length=254,
                    ),
                ),
                (
                    "alternate_contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Alternate contact person name",
                        max_length=200,
                    ),
                ),
                (
                    "alternate_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Alternate contact phone number",
                        max_length=50,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was reviewed", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Notes from the reviewer"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was approved", null=True
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(blank=True, help_text="Notes from approver"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When work actually started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When work was completed", null=True
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(blank=True, help_text="Notes upon completion"),
                ),
                (
                    "actual_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual service duration in hours",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was cancelled",
                        null=True,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this request was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this request was last updated"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_field_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who assigned the technician",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_requests_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who cancelled this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_field_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_field_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer requesting the service",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_service_requests",
                        to="sales.customer",
                    ),
                ),
                (
                    "drill_bits",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Drill bits involved in this request",
                        related_name="field_service_requests",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_field_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Work order generated from this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_service_requests",
                        to="workorders.workorder",
                    ),
                ),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician assigned to this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        help_text="Location where service is needed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="sales.servicesite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Service Request",
                "verbose_name_plural": "Field Service Requests",
                "db_table": "field_service_requests",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_review_field_request", "Can review field service requests"),
                    ("can_approve_field_request", "Can approve field service requests"),
                    ("can_assign_technician", "Can assign technicians to requests"),
                    ("can_cancel_field_request", "Can cancel field service requests"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="servicesite",
            index=models.Index(
                fields=["site_code"], name="service_sit_site_co_6cb59a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicesite",
            index=models.Index(
                fields=["customer", "is_active"], name="service_sit_custome_2caaa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicesite",
            index=models.Index(
                fields=["site_type", "status"], name="service_sit_site_ty_cddb06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldtechnician",
            index=models.Index(
                fields=["employee_id"], name="field_techn_employe_32aab2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldtechnician",
            index=models.Index(
                fields=["employment_status"], name="field_techn_employm_64d603_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldtechnician",
            index=models.Index(
                fields=["skill_level"], name="field_techn_skill_l_adb89b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldservicerequest",
            index=models.Index(
                fields=["request_number"], name="field_servi_request_e2e640_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldservicerequest",
            index=models.Index(
                fields=["status", "priority"], name="field_servi_status_df991e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldservicerequest",
            index=models.Index(
                fields=["requested_date"], name="field_servi_request_967768_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldservicerequest",
            index=models.Index(
                fields=["customer", "status"], name="field_servi_custome_89880a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldservicerequest",
            index=models.Index(
                fields=["service_site", "status"], name="field_servi_service_d7ca4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldservicerequest",
            index=models.Index(
                fields=["assigned_technician", "status"],
                name="field_servi_assigne_6eaee8_idx",
            ),
        ),
    ]
