# Generated by Django 5.2.8 on 2025-12-05 23:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_serviceschedule_sitevisit_servicereport_and_more"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldDrillStringRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique run identifier (auto-generated: RUN-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "run_sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Sequence number for this bit (1st run, 2nd run, etc.)",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("SURFACE", "Surface Hole"),
                            ("INTERMEDIATE", "Intermediate Hole"),
                            ("PRODUCTION", "Production Hole"),
                            ("SIDETRACK", "Sidetrack"),
                            ("REAMING", "Reaming"),
                            ("CORING", "Coring"),
                            ("OTHER", "Other"),
                        ],
                        default="PRODUCTION",
                        help_text="Type of drilling run",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("MOBILIZED", "Mobilized to Site"),
                            ("RIG_UP", "Rigging Up"),
                            ("IN_HOLE", "In Hole"),
                            ("DRILLING", "Drilling"),
                            ("TRIPPING", "Tripping"),
                            ("OUT_OF_HOLE", "Out of Hole"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        help_text="Current run status",
                        max_length=20,
                    ),
                ),
                (
                    "depth_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Depth when bit went in hole (feet)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "depth_out",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Depth when bit came out (feet)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "footage_drilled",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total footage drilled (calculated or entered)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "planned_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Planned target depth (feet)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(
                        blank=True, help_text="Planned start date", null=True
                    ),
                ),
                (
                    "spud_time",
                    models.DateTimeField(
                        blank=True, help_text="Time bit entered hole", null=True
                    ),
                ),
                (
                    "out_of_hole_time",
                    models.DateTimeField(
                        blank=True, help_text="Time bit came out of hole", null=True
                    ),
                ),
                (
                    "total_rotating_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total rotating hours",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "total_circulating_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total circulating hours",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "total_on_bottom_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total on-bottom hours (actual drilling)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "non_productive_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Non-productive time (repairs, waiting, etc.)",
                        max_digits=8,
                    ),
                ),
                (
                    "avg_wob",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average Weight on Bit (klbs)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "max_wob",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum Weight on Bit (klbs)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "avg_rpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Average RPM",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "max_rpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Maximum RPM",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "avg_torque",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average torque (ft-lbs)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "max_torque",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum torque (ft-lbs)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "avg_flow_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average flow rate (GPM)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "avg_standpipe_pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average standpipe pressure (PSI)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "mud_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mud weight (PPG)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "formation_name",
                    models.CharField(
                        blank=True, help_text="Formation(s) drilled", max_length=200
                    ),
                ),
                (
                    "formation_description",
                    models.TextField(
                        blank=True, help_text="Detailed formation description"
                    ),
                ),
                (
                    "lithology",
                    models.CharField(
                        blank=True, help_text="Rock type(s) encountered", max_length=200
                    ),
                ),
                (
                    "formation_hardness",
                    models.CharField(
                        blank=True,
                        help_text="Formation hardness classification",
                        max_length=50,
                    ),
                ),
                (
                    "avg_rop",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average Rate of Penetration (ft/hr)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "max_rop",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum Rate of Penetration (ft/hr)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cost_per_foot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per foot drilled",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dull_grade_in",
                    models.CharField(
                        blank=True,
                        help_text="IADC dull grade going in hole",
                        max_length=50,
                    ),
                ),
                (
                    "dull_grade_out",
                    models.CharField(
                        blank=True,
                        help_text="IADC dull grade coming out of hole",
                        max_length=50,
                    ),
                ),
                (
                    "bit_condition_notes",
                    models.TextField(blank=True, help_text="Notes on bit condition"),
                ),
                (
                    "termination_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TD_REACHED", "TD Reached"),
                            ("CASING_POINT", "Casing Point"),
                            ("BIT_WORN", "Bit Worn"),
                            ("BIT_DAMAGED", "Bit Damaged"),
                            ("FORMATION_CHANGE", "Formation Change"),
                            ("MECHANICAL_ISSUE", "Mechanical Issue"),
                            ("CUSTOMER_REQUEST", "Customer Request"),
                            ("TRIP_FOR_LOGGING", "Trip for Logging"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Reason run was terminated",
                        max_length=30,
                    ),
                ),
                (
                    "termination_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes on run termination"
                    ),
                ),
                (
                    "operational_notes",
                    models.TextField(
                        blank=True, help_text="Operational notes and observations"
                    ),
                ),
                (
                    "issues_encountered",
                    models.TextField(
                        blank=True, help_text="Issues or problems during run"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations for future runs"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this run record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this run was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this run record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_field_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer for this run",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drill_string_runs",
                        to="sales.customer",
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        help_text="Drill bit being run",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_runs",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "field_technician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Field technician supervising the run",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_runs",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "rig",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rig performing the drilling",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drill_string_runs",
                        to="sales.rig",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated field service request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drill_string_runs",
                        to="sales.fieldservicerequest",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Service site location",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drill_string_runs",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        help_text="Well where run takes place",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drill_string_runs",
                        to="sales.well",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Drill String Run",
                "verbose_name_plural": "Field Drill String Runs",
                "db_table": "field_drill_string_runs",
                "ordering": ["-spud_time", "-created_at"],
                "permissions": [
                    ("can_start_field_run", "Can start field drill string runs"),
                    ("can_complete_field_run", "Can complete field drill string runs"),
                    ("can_view_run_performance", "Can view run performance data"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique incident identifier (auto-generated: INC-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SAFETY", "Safety Incident"),
                            ("ENVIRONMENTAL", "Environmental Incident"),
                            ("EQUIPMENT_FAILURE", "Equipment Failure"),
                            ("NEAR_MISS", "Near Miss"),
                            ("QUALITY", "Quality Issue"),
                            ("PROCEDURAL", "Procedural Violation"),
                            ("PROPERTY_DAMAGE", "Property Damage"),
                            ("DOWNHOLE", "Downhole Incident"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Incident category",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor - No Injury/Minimal Impact"),
                            ("MODERATE", "Moderate - First Aid/Limited Impact"),
                            (
                                "SERIOUS",
                                "Serious - Medical Treatment/Significant Impact",
                            ),
                            ("SEVERE", "Severe - Lost Time/Major Impact"),
                            ("CRITICAL", "Critical - Life Threatening/Catastrophic"),
                        ],
                        default="MINOR",
                        help_text="Severity level",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REPORTED", "Reported"),
                            ("UNDER_INVESTIGATION", "Under Investigation"),
                            ("ROOT_CAUSE_IDENTIFIED", "Root Cause Identified"),
                            ("CORRECTIVE_ACTION", "Corrective Action in Progress"),
                            ("CLOSED", "Closed"),
                            ("REOPENED", "Reopened"),
                        ],
                        db_index=True,
                        default="REPORTED",
                        help_text="Current status",
                        max_length=30,
                    ),
                ),
                (
                    "incident_title",
                    models.CharField(
                        help_text="Brief title describing incident", max_length=200
                    ),
                ),
                ("incident_date", models.DateField(help_text="Date incident occurred")),
                (
                    "incident_time",
                    models.TimeField(
                        blank=True, help_text="Time incident occurred", null=True
                    ),
                ),
                (
                    "location_description",
                    models.CharField(
                        blank=True,
                        help_text="Specific location (e.g., rig floor, pipe deck)",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of what happened"),
                ),
                (
                    "immediate_actions",
                    models.TextField(blank=True, help_text="Immediate actions taken"),
                ),
                (
                    "conditions_at_time",
                    models.TextField(
                        blank=True,
                        help_text="Conditions at time of incident (weather, visibility, etc.)",
                    ),
                ),
                (
                    "equipment_involved",
                    models.TextField(
                        blank=True, help_text="Equipment involved in incident"
                    ),
                ),
                (
                    "injury_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No Injury"),
                            ("FIRST_AID", "First Aid Case"),
                            ("MEDICAL_TREATMENT", "Medical Treatment Case"),
                            ("RESTRICTED_WORK", "Restricted Work Case"),
                            ("LOST_TIME", "Lost Time Injury"),
                            ("FATALITY", "Fatality"),
                        ],
                        default="NONE",
                        help_text="Type of injury if applicable",
                        max_length=30,
                    ),
                ),
                (
                    "persons_injured",
                    models.IntegerField(
                        default=0, help_text="Number of persons injured"
                    ),
                ),
                (
                    "injury_description",
                    models.TextField(blank=True, help_text="Description of injuries"),
                ),
                (
                    "body_parts_affected",
                    models.CharField(
                        blank=True, help_text="Body parts affected", max_length=200
                    ),
                ),
                (
                    "medical_treatment_provided",
                    models.TextField(
                        blank=True, help_text="Medical treatment provided"
                    ),
                ),
                (
                    "days_lost",
                    models.IntegerField(default=0, help_text="Days lost due to injury"),
                ),
                (
                    "property_damage",
                    models.BooleanField(
                        default=False, help_text="Property damage occurred"
                    ),
                ),
                (
                    "damage_description",
                    models.TextField(blank=True, help_text="Description of damage"),
                ),
                (
                    "estimated_damage_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cost of damage",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "investigation_started",
                    models.DateTimeField(
                        blank=True, help_text="When investigation began", null=True
                    ),
                ),
                (
                    "root_cause",
                    models.TextField(
                        blank=True, help_text="Root cause analysis findings"
                    ),
                ),
                (
                    "contributing_factors",
                    models.TextField(
                        blank=True, help_text="Contributing factors identified"
                    ),
                ),
                (
                    "lessons_learned",
                    models.TextField(
                        blank=True, help_text="Lessons learned from incident"
                    ),
                ),
                (
                    "corrective_actions",
                    models.TextField(
                        blank=True, help_text="Corrective actions required"
                    ),
                ),
                (
                    "preventive_actions",
                    models.TextField(
                        blank=True, help_text="Preventive actions to avoid recurrence"
                    ),
                ),
                (
                    "corrective_action_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date for corrective actions",
                        null=True,
                    ),
                ),
                (
                    "corrective_action_completed",
                    models.BooleanField(
                        default=False, help_text="Corrective actions completed"
                    ),
                ),
                (
                    "corrective_action_completed_date",
                    models.DateField(
                        blank=True,
                        help_text="Date corrective actions completed",
                        null=True,
                    ),
                ),
                (
                    "reportable_to_client",
                    models.BooleanField(
                        default=False, help_text="Incident is reportable to client"
                    ),
                ),
                (
                    "reported_to_client",
                    models.BooleanField(
                        default=False, help_text="Incident has been reported to client"
                    ),
                ),
                (
                    "reported_to_client_date",
                    models.DateField(
                        blank=True, help_text="Date reported to client", null=True
                    ),
                ),
                (
                    "reportable_to_authority",
                    models.BooleanField(
                        default=False,
                        help_text="Incident is reportable to regulatory authority",
                    ),
                ),
                (
                    "reported_to_authority",
                    models.BooleanField(
                        default=False,
                        help_text="Incident has been reported to authority",
                    ),
                ),
                (
                    "authority_report_number",
                    models.CharField(
                        blank=True,
                        help_text="Regulatory authority report number",
                        max_length=100,
                    ),
                ),
                (
                    "closed_date",
                    models.DateField(
                        blank=True, help_text="Date incident was closed", null=True
                    ),
                ),
                (
                    "closure_notes",
                    models.TextField(blank=True, help_text="Notes on incident closure"),
                ),
                (
                    "has_photos",
                    models.BooleanField(default=False, help_text="Photos are attached"),
                ),
                (
                    "photo_count",
                    models.IntegerField(default=0, help_text="Number of photos"),
                ),
                (
                    "has_documents",
                    models.BooleanField(
                        default=False, help_text="Documents are attached"
                    ),
                ),
                (
                    "witnesses",
                    models.TextField(blank=True, help_text="Names of witnesses"),
                ),
                (
                    "witness_statements",
                    models.TextField(
                        blank=True, help_text="Summary of witness statements"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who closed the incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_field_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer at time of incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_incidents",
                        to="sales.customer",
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equipment involved in incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_incidents",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "field_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Drilling run during incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="sales.fielddrillstringrun",
                    ),
                ),
                (
                    "investigation_lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person leading investigation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_investigations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="Person who reported the incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location of incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site visit during which incident occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="sales.sitevisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Incident",
                "verbose_name_plural": "Field Incidents",
                "db_table": "field_incidents",
                "ordering": ["-incident_date", "-incident_time"],
                "permissions": [
                    ("can_report_incidents", "Can report field incidents"),
                    ("can_investigate_incidents", "Can investigate incidents"),
                    ("can_close_incidents", "Can close incidents"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique inspection identifier (auto-generated: INSP-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("PRE_RUN", "Pre-Run Inspection"),
                            ("MID_RUN", "Mid-Run Inspection"),
                            ("POST_RUN", "Post-Run Inspection"),
                            ("DULL_GRADING", "Dull Grading"),
                            ("DAMAGE_ASSESSMENT", "Damage Assessment"),
                            ("RECEIVING", "Receiving Inspection"),
                            ("ROUTINE", "Routine Inspection"),
                        ],
                        default="POST_RUN",
                        help_text="Type of inspection",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        help_text="Inspection status",
                        max_length=20,
                    ),
                ),
                ("inspection_date", models.DateField(help_text="Date of inspection")),
                (
                    "inspection_time",
                    models.TimeField(
                        blank=True, help_text="Time inspection started", null=True
                    ),
                ),
                (
                    "completion_time",
                    models.TimeField(
                        blank=True, help_text="Time inspection completed", null=True
                    ),
                ),
                (
                    "dull_grade",
                    models.CharField(
                        blank=True,
                        help_text="IADC dull grade (e.g., 2-2-WT-A-X-I-NO-TD)",
                        max_length=50,
                    ),
                ),
                (
                    "inner_rows",
                    models.CharField(
                        blank=True,
                        help_text="Inner rows condition (0-8)",
                        max_length=10,
                    ),
                ),
                (
                    "outer_rows",
                    models.CharField(
                        blank=True,
                        help_text="Outer rows condition (0-8)",
                        max_length=10,
                    ),
                ),
                (
                    "dull_characteristic",
                    models.CharField(
                        blank=True,
                        help_text="Primary dull characteristic",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Location of wear/damage", max_length=20
                    ),
                ),
                (
                    "bearing_seal",
                    models.CharField(
                        blank=True, help_text="Bearing/seal condition", max_length=20
                    ),
                ),
                (
                    "gauge",
                    models.CharField(
                        blank=True, help_text="Gauge condition", max_length=20
                    ),
                ),
                (
                    "other_characteristic",
                    models.CharField(
                        blank=True, help_text="Other dull characteristic", max_length=50
                    ),
                ),
                (
                    "reason_pulled",
                    models.CharField(
                        blank=True, help_text="Reason pulled from hole", max_length=50
                    ),
                ),
                (
                    "gauge_measurement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gauge measurement (inches)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "gauge_wear",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gauge wear amount (inches)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "body_od",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Body outer diameter (inches)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "cutter_count_damaged",
                    models.IntegerField(
                        blank=True, help_text="Number of damaged cutters", null=True
                    ),
                ),
                (
                    "cutter_count_missing",
                    models.IntegerField(
                        blank=True, help_text="Number of missing cutters", null=True
                    ),
                ),
                (
                    "nozzle_condition",
                    models.CharField(
                        blank=True,
                        help_text="Nozzle condition and sizes",
                        max_length=200,
                    ),
                ),
                (
                    "overall_condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent - Ready for Use"),
                            ("GOOD", "Good - Minor Wear"),
                            ("FAIR", "Fair - Significant Wear"),
                            ("POOR", "Poor - Requires Repair"),
                            ("DAMAGED", "Damaged - May Not Be Repairable"),
                            ("SCRAPPED", "Scrapped - Beyond Repair"),
                        ],
                        default="GOOD",
                        help_text="Overall condition rating",
                        max_length=20,
                    ),
                ),
                (
                    "blade_condition",
                    models.TextField(blank=True, help_text="Blade condition details"),
                ),
                (
                    "cutter_condition",
                    models.TextField(blank=True, help_text="Cutter condition details"),
                ),
                (
                    "body_condition",
                    models.TextField(blank=True, help_text="Body condition details"),
                ),
                (
                    "connection_condition",
                    models.TextField(
                        blank=True, help_text="Connection/thread condition"
                    ),
                ),
                (
                    "junk_damage",
                    models.BooleanField(
                        default=False, help_text="Evidence of junk damage"
                    ),
                ),
                (
                    "junk_damage_description",
                    models.TextField(
                        blank=True, help_text="Description of junk damage"
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("RUN_AS_IS", "Run As-Is"),
                            ("MINOR_REPAIR", "Minor Repair Needed"),
                            ("MAJOR_REPAIR", "Major Repair Needed"),
                            ("REWORK", "Rework Required"),
                            ("SCRAP", "Scrap Recommended"),
                            ("FURTHER_EVALUATION", "Further Evaluation Needed"),
                        ],
                        default="FURTHER_EVALUATION",
                        help_text="Recommended action",
                        max_length=30,
                    ),
                ),
                (
                    "recommendation_notes",
                    models.TextField(
                        blank=True, help_text="Detailed recommendation notes"
                    ),
                ),
                (
                    "estimated_remaining_life",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated remaining footage (feet)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "has_photos",
                    models.BooleanField(
                        default=False, help_text="Photos were taken during inspection"
                    ),
                ),
                (
                    "photo_count",
                    models.IntegerField(default=0, help_text="Number of photos taken"),
                ),
                (
                    "photo_notes",
                    models.TextField(blank=True, help_text="Notes about photos"),
                ),
                (
                    "findings",
                    models.TextField(
                        blank=True, help_text="Detailed inspection findings"
                    ),
                ),
                (
                    "customer_representative",
                    models.CharField(
                        blank=True,
                        help_text="Customer representative present",
                        max_length=200,
                    ),
                ),
                (
                    "customer_signature",
                    models.BooleanField(
                        default=False, help_text="Customer signed inspection report"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_field_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        help_text="Drill bit being inspected",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_inspections",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "field_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated drilling run",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="sales.fielddrillstringrun",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        help_text="Technician who performed inspection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_inspections",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location of inspection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site visit during which inspection occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="sales.sitevisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Inspection",
                "verbose_name_plural": "Field Inspections",
                "db_table": "field_inspections",
                "ordering": ["-inspection_date", "-inspection_time"],
                "permissions": [
                    ("can_conduct_inspections", "Can conduct field inspections"),
                    ("can_approve_inspections", "Can approve inspection reports"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldPerformanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique log identifier (auto-generated: PERF-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "interval_type",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("SHIFT", "Per Shift"),
                            ("DAILY", "Daily"),
                            ("STAND", "Per Stand"),
                            ("FORMATION", "Per Formation"),
                            ("COMPLETE", "Complete Run"),
                        ],
                        default="DAILY",
                        help_text="Type of interval this log covers",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="Start of logging interval"),
                ),
                ("end_time", models.DateTimeField(help_text="End of logging interval")),
                (
                    "start_depth",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Depth at start of interval (feet)",
                        max_digits=10,
                    ),
                ),
                (
                    "end_depth",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Depth at end of interval (feet)",
                        max_digits=10,
                    ),
                ),
                (
                    "footage_drilled",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Footage drilled in this interval",
                        max_digits=10,
                    ),
                ),
                (
                    "rotating_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rotating hours in interval",
                        max_digits=6,
                    ),
                ),
                (
                    "on_bottom_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="On-bottom hours in interval",
                        max_digits=6,
                    ),
                ),
                (
                    "avg_rop",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average ROP for interval (ft/hr)",
                        max_digits=8,
                    ),
                ),
                (
                    "max_rop",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum ROP achieved (ft/hr)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "min_rop",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum ROP (ft/hr)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "target_rop",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target ROP for this formation (ft/hr)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "rop_variance_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ROP variance from target (%)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "target_footage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target footage for interval",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "footage_variance_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Footage variance from target (%)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "avg_wob",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average WOB (klbs)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "avg_rpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Average RPM",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "avg_torque",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average torque (ft-lbs)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "avg_flow_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average flow rate (GPM)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "avg_mse",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average MSE (PSI)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "formation_name",
                    models.CharField(
                        blank=True,
                        help_text="Formation(s) drilled in interval",
                        max_length=200,
                    ),
                ),
                (
                    "formation_hardness",
                    models.CharField(
                        blank=True, help_text="Formation hardness", max_length=50
                    ),
                ),
                (
                    "drilling_efficiency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Drilling efficiency (on-bottom/rotating) %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "connection_time_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average connection time (minutes)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "trip_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trip speed (ft/hr)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "performance_rating",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("AVERAGE", "Average"),
                            ("BELOW_AVERAGE", "Below Average"),
                            ("POOR", "Poor"),
                        ],
                        default="AVERAGE",
                        help_text="Overall performance rating",
                        max_length=20,
                    ),
                ),
                (
                    "performance_notes",
                    models.TextField(
                        blank=True, help_text="Performance analysis notes"
                    ),
                ),
                (
                    "optimization_recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations for optimization"
                    ),
                ),
                (
                    "offset_well_comparison",
                    models.TextField(
                        blank=True, help_text="Comparison to offset wells"
                    ),
                ),
                (
                    "historical_comparison",
                    models.TextField(
                        blank=True, help_text="Comparison to historical runs"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this log was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this log was last updated"
                    ),
                ),
                (
                    "field_run",
                    models.ForeignKey(
                        help_text="Associated drilling run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_logs",
                        to="sales.fielddrillstringrun",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician who created this log",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_logs",
                        to="sales.fieldtechnician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Performance Log",
                "verbose_name_plural": "Field Performance Logs",
                "db_table": "field_performance_logs",
                "ordering": ["-start_time"],
                "permissions": [
                    ("can_create_performance_logs", "Can create performance logs"),
                    ("can_analyze_performance", "Can analyze performance data"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldRunData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="When this data was recorded"
                    ),
                ),
                (
                    "bit_depth",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="Bit depth at time of recording (feet)",
                        max_digits=10,
                    ),
                ),
                (
                    "hole_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total hole depth (feet)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "wob",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight on Bit (klbs)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "rpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Rotary speed (RPM)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "torque",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rotary torque (ft-lbs)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "rop",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate of Penetration (ft/hr)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "flow_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Flow rate (GPM)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "standpipe_pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standpipe pressure (PSI)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "differential_pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Differential pressure (PSI)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "ecd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Equivalent Circulating Density (PPG)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "mud_weight_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mud weight in (PPG)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "mud_weight_out",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mud weight out (PPG)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "mud_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Mud temperature (F)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "funnel_viscosity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Funnel viscosity (sec/qt)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "hook_load",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hook load (klbs)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "block_position",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Block position (feet)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "mse",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mechanical Specific Energy (PSI)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bit_hydraulic_power",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Bit hydraulic horsepower (HP)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "formation",
                    models.CharField(
                        blank=True,
                        help_text="Current formation being drilled",
                        max_length=100,
                    ),
                ),
                (
                    "gamma_ray",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Gamma ray reading (API)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("EDR", "Electronic Drilling Recorder"),
                            ("WITS", "WITS Transfer"),
                            ("MWD", "MWD System"),
                            ("SENSOR", "Direct Sensor"),
                            ("CALCULATED", "Calculated"),
                        ],
                        default="MANUAL",
                        help_text="Source of this data",
                        max_length=20,
                    ),
                ),
                (
                    "data_quality",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good Quality"),
                            ("QUESTIONABLE", "Questionable"),
                            ("POOR", "Poor Quality"),
                            ("INTERPOLATED", "Interpolated"),
                            ("ESTIMATED", "Estimated"),
                        ],
                        default="GOOD",
                        help_text="Data quality indicator",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this data point"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "field_run",
                    models.ForeignKey(
                        help_text="Parent drilling run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_data_points",
                        to="sales.fielddrillstringrun",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician who recorded this data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_data_points",
                        to="sales.fieldtechnician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Run Data Point",
                "verbose_name_plural": "Field Run Data Points",
                "db_table": "field_run_data",
                "ordering": ["field_run", "timestamp"],
                "permissions": [
                    ("can_record_run_data", "Can record field run data"),
                    ("can_edit_run_data", "Can edit field run data"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RunHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hour_type",
                    models.CharField(
                        choices=[
                            ("ROTATING", "Rotating Hours"),
                            ("CIRCULATING", "Circulating Hours"),
                            ("ON_BOTTOM", "On Bottom Hours"),
                            ("TOTAL", "Total Hours"),
                            ("REAMING", "Reaming Hours"),
                            ("TRIPPING", "Tripping Hours"),
                        ],
                        default="TOTAL",
                        help_text="Type of hours",
                        max_length=20,
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, help_text="Hours to add", max_digits=8
                    ),
                ),
                (
                    "cumulative_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cumulative hours after this entry",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "record_date",
                    models.DateField(help_text="Date hours were accumulated"),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="Start time of operation", null=True
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="End time of operation", null=True
                    ),
                ),
                (
                    "entry_source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("EDR", "EDR System"),
                            ("CALCULATED", "Calculated from Run"),
                            ("IMPORTED", "Imported Data"),
                        ],
                        default="MANUAL",
                        help_text="Source of this entry",
                        max_length=20,
                    ),
                ),
                (
                    "depth_at_start",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Depth at start of period (feet)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "depth_at_end",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Depth at end of period (feet)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this hour entry"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_run_hours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        help_text="Drill bit being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hour_logs",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "field_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated drilling run",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hour_logs",
                        to="sales.fielddrillstringrun",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician who recorded hours",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_hours",
                        to="sales.fieldtechnician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run Hours",
                "verbose_name_plural": "Run Hours",
                "db_table": "run_hours",
                "ordering": ["-record_date", "-created_at"],
                "permissions": [
                    ("can_record_run_hours", "Can record run hours"),
                    ("can_adjust_hours", "Can adjust hour entries"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="fielddrillstringrun",
            index=models.Index(
                fields=["run_number"], name="field_drill_run_num_c8526e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fielddrillstringrun",
            index=models.Index(
                fields=["drill_bit", "status"], name="field_drill_drill_b_11a25a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fielddrillstringrun",
            index=models.Index(
                fields=["well", "status"], name="field_drill_well_id_17376c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fielddrillstringrun",
            index=models.Index(
                fields=["customer", "status"], name="field_drill_custome_949329_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fielddrillstringrun",
            index=models.Index(
                fields=["spud_time"], name="field_drill_spud_ti_59eb95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldincident",
            index=models.Index(
                fields=["incident_number"], name="field_incid_inciden_44e717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldincident",
            index=models.Index(
                fields=["incident_date", "severity"],
                name="field_incid_inciden_633d12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldincident",
            index=models.Index(
                fields=["category", "status"], name="field_incid_categor_4b7c5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldincident",
            index=models.Index(
                fields=["service_site", "incident_date"],
                name="field_incid_service_db13da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldinspection",
            index=models.Index(
                fields=["inspection_number"], name="field_inspe_inspect_3e6edc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldinspection",
            index=models.Index(
                fields=["drill_bit", "inspection_type"],
                name="field_inspe_drill_b_d4365f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldinspection",
            index=models.Index(
                fields=["inspection_date", "status"],
                name="field_inspe_inspect_7e611d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldinspection",
            index=models.Index(
                fields=["overall_condition"], name="field_inspe_overall_ba9efd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldperformancelog",
            index=models.Index(
                fields=["log_number"], name="field_perfo_log_num_757008_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldperformancelog",
            index=models.Index(
                fields=["field_run", "start_time"],
                name="field_perfo_field_r_37fca8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldperformancelog",
            index=models.Index(
                fields=["performance_rating"], name="field_perfo_perform_54ddc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldrundata",
            index=models.Index(
                fields=["field_run", "timestamp"], name="field_run_d_field_r_afc1d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldrundata",
            index=models.Index(
                fields=["field_run", "bit_depth"], name="field_run_d_field_r_42b0af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldrundata",
            index=models.Index(
                fields=["timestamp"], name="field_run_d_timesta_3086f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runhours",
            index=models.Index(
                fields=["drill_bit", "hour_type"], name="run_hours_drill_b_540b8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runhours",
            index=models.Index(
                fields=["drill_bit", "record_date"], name="run_hours_drill_b_20d0c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runhours",
            index=models.Index(
                fields=["field_run"], name="run_hours_field_r_1a8d52_idx"
            ),
        ),
    ]
