# Generated by Django 5.2.8 on 2025-12-05 23:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_week2_field_operations"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldWorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_order_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique work order identifier (auto-generated: FWO-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("INSPECTION", "Inspection"),
                            ("REPAIR", "Repair"),
                            ("MAINTENANCE", "Maintenance"),
                            ("INSTALLATION", "Installation"),
                            ("REPLACEMENT", "Replacement"),
                            ("CALIBRATION", "Calibration"),
                            ("TRAINING", "Training"),
                            ("CONSULTATION", "Consultation"),
                            ("OTHER", "Other"),
                        ],
                        default="MAINTENANCE",
                        help_text="Type of work",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Work order status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="NORMAL",
                        help_text="Priority level",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Work order title", max_length=300),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of work"),
                ),
                (
                    "scope_of_work",
                    models.TextField(
                        blank=True, help_text="Scope of work to be performed"
                    ),
                ),
                (
                    "requested_date",
                    models.DateField(
                        blank=True, help_text="Requested completion date", null=True
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(
                        blank=True, help_text="Scheduled start time", null=True
                    ),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(
                        blank=True, help_text="Scheduled end time", null=True
                    ),
                ),
                (
                    "actual_start",
                    models.DateTimeField(
                        blank=True, help_text="Actual start time", null=True
                    ),
                ),
                (
                    "actual_end",
                    models.DateTimeField(
                        blank=True, help_text="Actual end time", null=True
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated hours",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual hours worked",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "estimated_labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated labor cost",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "estimated_material_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated material cost",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "actual_labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual labor cost",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "actual_material_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual material cost",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "work_performed",
                    models.TextField(
                        blank=True, help_text="Description of work performed"
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(blank=True, help_text="Completion notes"),
                ),
                (
                    "issues_found",
                    models.TextField(blank=True, help_text="Issues found during work"),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations for follow-up"
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, help_text="Follow-up work is required"
                    ),
                ),
                (
                    "customer_signoff",
                    models.BooleanField(
                        default=False, help_text="Customer has signed off"
                    ),
                ),
                (
                    "customer_signoff_name",
                    models.CharField(
                        blank=True, help_text="Customer signatory name", max_length=200
                    ),
                ),
                (
                    "customer_signoff_at",
                    models.DateTimeField(
                        blank=True, help_text="When customer signed off", null=True
                    ),
                ),
                (
                    "customer_feedback",
                    models.TextField(blank=True, help_text="Customer feedback"),
                ),
                (
                    "customer_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Customer satisfaction rating (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When work order was approved", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "additional_technicians",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional technicians",
                        related_name="supporting_work_orders",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved the work order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_field_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary assigned technician",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work_orders",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_field_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_work_orders",
                        to="sales.customer",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent service request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="sales.fieldservicerequest",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        help_text="Work location",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated site visit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="sales.sitevisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Work Order",
                "verbose_name_plural": "Field Work Orders",
                "db_table": "field_work_orders",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_create_field_work_orders", "Can create field work orders"),
                    ("can_approve_field_work_orders", "Can approve field work orders"),
                    ("can_assign_technicians", "Can assign technicians to work orders"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldAssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique assignment identifier (auto-generated: ASSIGN-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("DRILL_BIT", "Drill Bit"),
                            ("TOOL", "Tool"),
                            ("EQUIPMENT", "Equipment"),
                            ("VEHICLE", "Vehicle"),
                            ("INSTRUMENT", "Instrument"),
                            ("SAFETY_EQUIPMENT", "Safety Equipment"),
                            ("CONSUMABLE", "Consumable"),
                            ("OTHER", "Other"),
                        ],
                        default="EQUIPMENT",
                        help_text="Type of asset",
                        max_length=20,
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(
                        help_text="Name/description of asset", max_length=200
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(
                        blank=True, help_text="Asset code/serial number", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved"),
                            ("CHECKED_OUT", "Checked Out"),
                            ("IN_USE", "In Use"),
                            ("RETURNED", "Returned"),
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                        ],
                        db_index=True,
                        default="RESERVED",
                        help_text="Assignment status",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, help_text="Quantity assigned"),
                ),
                (
                    "checkout_date",
                    models.DateField(help_text="Date asset was checked out"),
                ),
                (
                    "checkout_time",
                    models.TimeField(
                        blank=True, help_text="Time asset was checked out", null=True
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateField(
                        blank=True, help_text="Expected return date", null=True
                    ),
                ),
                (
                    "checkout_condition",
                    models.TextField(blank=True, help_text="Condition at checkout"),
                ),
                (
                    "checkout_notes",
                    models.TextField(blank=True, help_text="Notes at checkout"),
                ),
                (
                    "return_date",
                    models.DateField(
                        blank=True, help_text="Date asset was returned", null=True
                    ),
                ),
                (
                    "return_time",
                    models.TimeField(
                        blank=True, help_text="Time asset was returned", null=True
                    ),
                ),
                (
                    "condition_on_return",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("DAMAGED", "Damaged"),
                            ("NOT_RETURNED", "Not Returned"),
                        ],
                        help_text="Condition when returned",
                        max_length=20,
                    ),
                ),
                (
                    "return_notes",
                    models.TextField(blank=True, help_text="Notes at return"),
                ),
                (
                    "hours_used",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hours used",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("usage_notes", models.TextField(blank=True, help_text="Usage notes")),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Daily rental/usage rate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cost for assignment",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "billable",
                    models.BooleanField(
                        default=True, help_text="Assignment is billable"
                    ),
                ),
                (
                    "requires_maintenance",
                    models.BooleanField(
                        default=False, help_text="Asset requires maintenance after use"
                    ),
                ),
                (
                    "maintenance_notes",
                    models.TextField(blank=True, help_text="Maintenance requirements"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="Technician holding the asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who processed checkin",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        help_text="User who processed checkout",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_out_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_asset_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned drill bit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_assignments",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destination site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated site visit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments",
                        to="sales.sitevisit",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated work order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments",
                        to="sales.fieldworkorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Asset Assignment",
                "verbose_name_plural": "Field Asset Assignments",
                "db_table": "field_asset_assignments",
                "ordering": ["-checkout_date", "-created_at"],
                "permissions": [
                    ("can_checkout_assets", "Can check out assets"),
                    ("can_checkin_assets", "Can check in assets"),
                    ("can_manage_assignments", "Can manage asset assignments"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GPSLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=7,
                        help_text="GPS latitude",
                        max_digits=10,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=7,
                        help_text="GPS longitude",
                        max_digits=10,
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Altitude in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Horizontal accuracy in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "altitude_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vertical accuracy in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Speed in km/h",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Heading in degrees (0-360)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True, help_text="When location was recorded"
                    ),
                ),
                (
                    "device_timestamp",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp from device", null=True
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("AUTOMATIC", "Automatic Update"),
                            ("MANUAL", "Manual Check-in"),
                            ("CHECK_IN", "Site Check-in"),
                            ("CHECK_OUT", "Site Check-out"),
                            ("WAYPOINT", "Waypoint"),
                            ("ALERT", "Alert Location"),
                        ],
                        default="AUTOMATIC",
                        help_text="Type of location record",
                        max_length=20,
                    ),
                ),
                (
                    "source_device",
                    models.CharField(
                        choices=[
                            ("PHONE", "Mobile Phone"),
                            ("TABLET", "Tablet"),
                            ("GPS_TRACKER", "GPS Tracker Device"),
                            ("VEHICLE", "Vehicle GPS"),
                            ("MANUAL", "Manual Entry"),
                        ],
                        default="PHONE",
                        help_text="Source of GPS data",
                        max_length=20,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, help_text="Device identifier", max_length=100
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True, help_text="Battery level percentage", null=True
                    ),
                ),
                (
                    "signal_strength",
                    models.IntegerField(
                        blank=True, help_text="Signal strength (dBm)", null=True
                    ),
                ),
                (
                    "satellites_used",
                    models.IntegerField(
                        blank=True, help_text="Number of satellites used", null=True
                    ),
                ),
                (
                    "is_inside_geofence",
                    models.BooleanField(
                        blank=True,
                        help_text="Location is inside designated geofence",
                        null=True,
                    ),
                ),
                (
                    "geofence_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of geofence if applicable",
                        max_length=100,
                    ),
                ),
                (
                    "distance_from_site",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance from service site in meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Reverse geocoded address", max_length=500
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this location"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "field_technician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician being tracked",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gps_locations",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nearby service site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gps_locations",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated site visit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gps_locations",
                        to="sales.sitevisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPS Location",
                "verbose_name_plural": "GPS Locations",
                "db_table": "gps_locations",
                "ordering": ["-recorded_at"],
                "permissions": [
                    ("can_view_gps_tracking", "Can view GPS tracking data"),
                    ("can_manage_geofencing", "Can manage geofencing"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldDataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique entry identifier (auto-generated: DATA-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("NUMERIC", "Numeric Value"),
                            ("TEXT", "Text/String"),
                            ("BOOLEAN", "Yes/No"),
                            ("DATE", "Date"),
                            ("DATETIME", "Date and Time"),
                            ("SELECTION", "Selection from List"),
                            ("MEASUREMENT", "Measurement with Unit"),
                            ("COORDINATES", "GPS Coordinates"),
                            ("PERCENTAGE", "Percentage"),
                            ("CURRENCY", "Currency Amount"),
                        ],
                        default="TEXT",
                        help_text="Type of data",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational Data"),
                            ("SAFETY", "Safety Observation"),
                            ("QUALITY", "Quality Check"),
                            ("ENVIRONMENTAL", "Environmental Data"),
                            ("EQUIPMENT", "Equipment Reading"),
                            ("INSPECTION", "Inspection Finding"),
                            ("MEASUREMENT", "Measurement"),
                            ("OBSERVATION", "General Observation"),
                            ("CUSTOMER", "Customer Feedback"),
                            ("OTHER", "Other"),
                        ],
                        default="OBSERVATION",
                        help_text="Category of entry",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("VALIDATED", "Validated"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Entry status",
                        max_length=20,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Name/label of the data field", max_length=200
                    ),
                ),
                (
                    "field_code",
                    models.CharField(
                        blank=True, help_text="Short code for the field", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this data represents"
                    ),
                ),
                ("value_text", models.TextField(blank=True, help_text="Text value")),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Numeric value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "value_boolean",
                    models.BooleanField(
                        blank=True, help_text="Boolean value", null=True
                    ),
                ),
                (
                    "value_date",
                    models.DateField(blank=True, help_text="Date value", null=True),
                ),
                (
                    "value_datetime",
                    models.DateTimeField(
                        blank=True, help_text="DateTime value", null=True
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (e.g., ft, psi, rpm)",
                        max_length=50,
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Minimum acceptable value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Maximum acceptable value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Target/expected value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "location_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPS accuracy in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("entry_date", models.DateField(help_text="Date data was collected")),
                (
                    "entry_time",
                    models.TimeField(
                        blank=True, help_text="Time data was collected", null=True
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False, help_text="Entry has been validated"
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, help_text="When entry was validated", null=True
                    ),
                ),
                (
                    "validation_notes",
                    models.TextField(blank=True, help_text="Notes from validation"),
                ),
                (
                    "is_out_of_range",
                    models.BooleanField(
                        default=False, help_text="Value is outside acceptable range"
                    ),
                ),
                (
                    "out_of_range_reason",
                    models.TextField(
                        blank=True, help_text="Explanation for out-of-range value"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this entry was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this entry was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_data_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        help_text="Technician who entered the data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_entries",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "field_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated drilling run",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_entries",
                        to="sales.fielddrillstringrun",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location where data was collected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_entries",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site visit during which data was collected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_entries",
                        to="sales.sitevisit",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who validated the entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_data_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Data Entry",
                "verbose_name_plural": "Field Data Entries",
                "db_table": "field_data_entries",
                "ordering": ["-entry_date", "-entry_time"],
                "permissions": [
                    ("can_enter_field_data", "Can enter field data"),
                    ("can_validate_field_data", "Can validate field data"),
                ],
                "indexes": [
                    models.Index(
                        fields=["entry_number"], name="field_data__entry_n_113508_idx"
                    ),
                    models.Index(
                        fields=["site_visit", "entry_date"],
                        name="field_data__site_vi_c564b0_idx",
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="field_data__categor_a42a7b_idx",
                    ),
                    models.Index(
                        fields=["field_name"], name="field_data__field_n_527e55_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique document identifier (auto-generated: DOC-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("REPORT", "Report"),
                            ("FORM", "Form"),
                            ("CERTIFICATE", "Certificate"),
                            ("PERMIT", "Permit"),
                            ("PROCEDURE", "Procedure"),
                            ("CHECKLIST", "Checklist"),
                            ("DRAWING", "Drawing/Diagram"),
                            ("SPECIFICATION", "Specification"),
                            ("INVOICE", "Invoice"),
                            ("DELIVERY_NOTE", "Delivery Note"),
                            ("SIGN_OFF", "Sign-Off Document"),
                            ("OTHER", "Other"),
                        ],
                        default="REPORT",
                        help_text="Type of document",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUPERSEDED", "Superseded"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Document status",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Document title", max_length=300)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Document description"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, help_text="Path to document file", max_length=500
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, help_text="Original file name", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "file_type",
                    models.CharField(blank=True, help_text="MIME type", max_length=100),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", help_text="Document version", max_length=20
                    ),
                ),
                (
                    "revision_number",
                    models.IntegerField(default=1, help_text="Revision number"),
                ),
                ("document_date", models.DateField(help_text="Date on the document")),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="When document becomes effective",
                        null=True,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="When document expires", null=True
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When document was approved", null=True
                    ),
                ),
                (
                    "requires_signature",
                    models.BooleanField(
                        default=False, help_text="Document requires signature"
                    ),
                ),
                (
                    "is_signed",
                    models.BooleanField(
                        default=False, help_text="Document has been signed"
                    ),
                ),
                (
                    "signed_by",
                    models.CharField(
                        blank=True, help_text="Who signed the document", max_length=200
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, help_text="When document was signed", null=True
                    ),
                ),
                (
                    "customer_signed",
                    models.BooleanField(default=False, help_text="Customer has signed"),
                ),
                (
                    "customer_signature_name",
                    models.CharField(
                        blank=True, help_text="Customer signatory name", max_length=200
                    ),
                ),
                (
                    "customer_signed_at",
                    models.DateTimeField(
                        blank=True, help_text="When customer signed", null=True
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False, help_text="Document is confidential"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        blank=True, help_text="Required access level", max_length=50
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Notes from review"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_field_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_field_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_technician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician who created the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_documents",
                        to="sales.fieldtechnician",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous version of this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newer_versions",
                        to="sales.fielddocument",
                    ),
                ),
                (
                    "service_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated service report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="sales.servicereport",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated service request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="sales.fieldservicerequest",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated service site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated site visit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="sales.sitevisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Document",
                "verbose_name_plural": "Field Documents",
                "db_table": "field_documents",
                "ordering": ["-document_date", "-created_at"],
                "permissions": [
                    ("can_create_documents", "Can create field documents"),
                    ("can_approve_documents", "Can approve field documents"),
                    ("can_view_confidential", "Can view confidential documents"),
                ],
                "indexes": [
                    models.Index(
                        fields=["document_number"],
                        name="field_docum_documen_4c87f2_idx",
                    ),
                    models.Index(
                        fields=["document_type", "status"],
                        name="field_docum_documen_df34f3_idx",
                    ),
                    models.Index(
                        fields=["site_visit"], name="field_docum_site_vi_920b8e_idx"
                    ),
                    models.Index(
                        fields=["document_date"], name="field_docum_documen_eb03e3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique photo identifier (auto-generated: PHOTO-YYYY-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EQUIPMENT", "Equipment"),
                            ("BIT_CONDITION", "Bit Condition"),
                            ("DULL_GRADE", "Dull Grade Documentation"),
                            ("DAMAGE", "Damage Documentation"),
                            ("SITE", "Site/Location"),
                            ("SAFETY", "Safety Related"),
                            ("INCIDENT", "Incident Documentation"),
                            ("BEFORE_AFTER", "Before/After Comparison"),
                            ("MEASUREMENT", "Measurement/Reading"),
                            ("GENERAL", "General"),
                            ("CUSTOMER_SIGN", "Customer Signature"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        help_text="Photo category",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Upload"),
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSED", "Processed"),
                            ("ARCHIVED", "Archived"),
                            ("DELETED", "Marked for Deletion"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Photo status",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Photo title", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Photo description"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, help_text="Path to photo file", max_length=500
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, help_text="Original file name", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "file_type",
                    models.CharField(blank=True, help_text="MIME type", max_length=50),
                ),
                (
                    "thumbnail_path",
                    models.CharField(
                        blank=True, help_text="Path to thumbnail", max_length=500
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, help_text="Image width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, help_text="Image height in pixels", null=True
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        blank=True, help_text="Image orientation", max_length=20
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS latitude where photo was taken",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS longitude where photo was taken",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "location_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPS accuracy in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("taken_at", models.DateTimeField(help_text="When photo was taken")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True, help_text="When photo was uploaded", null=True
                    ),
                ),
                (
                    "has_annotations",
                    models.BooleanField(
                        default=False, help_text="Photo has annotations"
                    ),
                ),
                (
                    "annotations",
                    models.TextField(blank=True, help_text="JSON-encoded annotations"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(
                        default=1,
                        help_text="Order in sequence (for before/after, etc.)",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary photo for the entity"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_field_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Drill bit in photo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_photos",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "field_incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="sales.fieldincident",
                    ),
                ),
                (
                    "field_inspection",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated inspection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="sales.fieldinspection",
                    ),
                ),
                (
                    "service_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location where photo was taken",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="sales.servicesite",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site visit during which photo was taken",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="sales.sitevisit",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        help_text="Technician who took the photo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos_taken",
                        to="sales.fieldtechnician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Photo",
                "verbose_name_plural": "Field Photos",
                "db_table": "field_photos",
                "ordering": ["-taken_at"],
                "permissions": [
                    ("can_upload_photos", "Can upload field photos"),
                    ("can_delete_photos", "Can delete field photos"),
                    ("can_annotate_photos", "Can annotate photos"),
                ],
                "indexes": [
                    models.Index(
                        fields=["photo_number"], name="field_photo_photo_n_a6c1f0_idx"
                    ),
                    models.Index(
                        fields=["site_visit", "category"],
                        name="field_photo_site_vi_09ffd7_idx",
                    ),
                    models.Index(
                        fields=["drill_bit"], name="field_photo_drill_b_ab4f96_idx"
                    ),
                    models.Index(
                        fields=["taken_at"], name="field_photo_taken_a_dde657_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="fieldworkorder",
            index=models.Index(
                fields=["work_order_number"], name="field_work__work_or_0ec05a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldworkorder",
            index=models.Index(
                fields=["status", "priority"], name="field_work__status_36215c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldworkorder",
            index=models.Index(
                fields=["customer", "status"], name="field_work__custome_e04f92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldworkorder",
            index=models.Index(
                fields=["assigned_technician", "status"],
                name="field_work__assigne_f669e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldworkorder",
            index=models.Index(
                fields=["scheduled_start"], name="field_work__schedul_0be71a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldassetassignment",
            index=models.Index(
                fields=["assignment_number"], name="field_asset_assignm_568abf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldassetassignment",
            index=models.Index(
                fields=["drill_bit"], name="field_asset_drill_b_6f340e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldassetassignment",
            index=models.Index(
                fields=["assigned_to", "status"], name="field_asset_assigne_e04034_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldassetassignment",
            index=models.Index(
                fields=["checkout_date"], name="field_asset_checkou_add82c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldassetassignment",
            index=models.Index(fields=["status"], name="field_asset_status_fcb63d_idx"),
        ),
        migrations.AddIndex(
            model_name="gpslocation",
            index=models.Index(
                fields=["field_technician", "recorded_at"],
                name="gps_locatio_field_t_61a965_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gpslocation",
            index=models.Index(
                fields=["site_visit"], name="gps_locatio_site_vi_585c5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gpslocation",
            index=models.Index(
                fields=["recorded_at"], name="gps_locatio_recorde_933f68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gpslocation",
            index=models.Index(
                fields=["latitude", "longitude"], name="gps_locatio_latitud_b2b332_idx"
            ),
        ),
    ]
