# Generated by Django 5.1.15 on 2025-12-27 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_week3_field_data_capture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., OIL, GAS, LSTK, OFFSHORE)",
                        max_length=20,
                        unique=True,
                        verbose_name="Account Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (e.g., Oil Division, Gas Division)",
                        max_length=100,
                        verbose_name="Account Name",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True,
                        help_text="Name in Arabic",
                        max_length=100,
                        verbose_name="Arabic Name",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sales_leader",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary sales contact for this account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sales Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "accounts",
                "ordering": ["code"],
            },
        ),
    ]
