# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningItemLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "planning_item_labels",
            },
        ),
        migrations.CreateModel(
            name="PlanningItemWatcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "planning_item_watchers",
            },
        ),
        migrations.CreateModel(
            name="PlanningLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#6b7280", max_length=20)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Planning Label",
                "verbose_name_plural": "Planning Labels",
                "db_table": "planning_labels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., SPRINT-01", max_length=20, unique=True
                    ),
                ),
                ("goal", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                (
                    "capacity_points",
                    models.IntegerField(
                        default=0, help_text="Total story points available"
                    ),
                ),
                ("completed_points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
                "db_table": "sprints",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="wiki/covers/"),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "sequence",
                    models.IntegerField(default=0, help_text="Order within parent"),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("is_template", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wiki Page",
                "verbose_name_plural": "Wiki Pages",
                "db_table": "wiki_pages",
                "ordering": ["space", "sequence", "title"],
            },
        ),
        migrations.CreateModel(
            name="WikiPageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("change_summary", models.CharField(blank=True, max_length=500)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Wiki Page Version",
                "verbose_name_plural": "Wiki Page Versions",
                "db_table": "wiki_page_versions",
                "ordering": ["page", "-version_number"],
            },
        ),
        migrations.CreateModel(
            name="WikiSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Visible to all users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wiki Space",
                "verbose_name_plural": "Wiki Spaces",
                "db_table": "wiki_spaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlanningBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                (
                    "default_wip_limit",
                    models.IntegerField(default=0, help_text="0 = no limit"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planning Board",
                "verbose_name_plural": "Planning Boards",
                "db_table": "planning_boards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlanningColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=20)),
                ("sequence", models.IntegerField(default=0)),
                ("wip_limit", models.IntegerField(default=0, help_text="0 = no limit")),
                ("color", models.CharField(blank=True, max_length=20)),
                (
                    "is_done_column",
                    models.BooleanField(
                        default=False, help_text="Items here count as completed"
                    ),
                ),
                (
                    "is_backlog_column",
                    models.BooleanField(
                        default=False, help_text="Items here are not started"
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="planning.planningboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planning Column",
                "verbose_name_plural": "Planning Columns",
                "db_table": "planning_columns",
                "ordering": ["board", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PlanningItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., ARDT-123", max_length=20, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Markdown supported"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("EPIC", "Epic"),
                            ("STORY", "Story"),
                            ("TASK", "Task"),
                            ("BUG", "Bug"),
                            ("SUBTASK", "Subtask"),
                        ],
                        default="TASK",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOWEST", "Lowest"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("HIGHEST", "Highest"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(default=0, help_text="Order within column"),
                ),
                ("story_points", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="planning.planningboard",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="planning.planningcolumn",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_planning_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="planning.planningitem",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planning Item",
                "verbose_name_plural": "Planning Items",
                "db_table": "planning_items",
                "ordering": ["column", "position"],
            },
        ),
    ]
