# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planning", "0001_initial"),
        ("workorders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planningitem",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planning_items",
                to="workorders.workorder",
            ),
        ),
        migrations.AddField(
            model_name="planningitemlabel",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_labels",
                to="planning.planningitem",
            ),
        ),
        migrations.AddField(
            model_name="planningitemwatcher",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchers",
                to="planning.planningitem",
            ),
        ),
        migrations.AddField(
            model_name="planningitemwatcher",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watched_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planningitemlabel",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label_items",
                to="planning.planninglabel",
            ),
        ),
        migrations.AddField(
            model_name="planningitem",
            name="labels",
            field=models.ManyToManyField(
                related_name="items",
                through="planning.PlanningItemLabel",
                to="planning.planninglabel",
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sprints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_sprints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planningitem",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="planning.sprint",
            ),
        ),
        migrations.AddField(
            model_name="planningboard",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boards",
                to="planning.sprint",
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_wiki_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_edited_wiki_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="planning.wikipage",
            ),
        ),
        migrations.AddField(
            model_name="wikipageversion",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wikipageversion",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="planning.wikipage",
            ),
        ),
        migrations.AddField(
            model_name="wikispace",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_wiki_spaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="planning.wikispace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planningcolumn",
            unique_together={("board", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="planningitemwatcher",
            unique_together={("item", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="planningitemlabel",
            unique_together={("item", "label")},
        ),
        migrations.AlterUniqueTogether(
            name="wikipageversion",
            unique_together={("page", "version_number")},
        ),
        migrations.AlterUniqueTogether(
            name="wikipage",
            unique_together={("space", "slug")},
        ),
    ]
