# Generated by Django 5.1.15 on 2025-12-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dispatch",
            "0003_alter_dispatch_created_by_alter_dispatch_destination_and_more",
        ),
        ("inventory", "0019_add_uom_conversion_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryreservation",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatch_reservations",
                to="inventory.inventoryitem",
            ),
        ),
    ]
