# Generated by Django 5.2.8 on 2025-12-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ERPSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("erp_system", models.CharField(max_length=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[("OUTBOUND", "ARDT → ERP"), ("INBOUND", "ERP → ARDT")],
                        max_length=10,
                    ),
                ),
                ("entity_type", models.CharField(max_length=30)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ERP Sync Log",
                "verbose_name_plural": "ERP Sync Logs",
                "db_table": "erp_sync_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ERPMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("ITEM", "Inventory Item"),
                            ("WORK_ORDER", "Work Order"),
                            ("SALES_ORDER", "Sales Order"),
                            ("PURCHASE_ORDER", "Purchase Order"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ardt_id", models.BigIntegerField()),
                (
                    "erp_system",
                    models.CharField(help_text="SAP, Oracle, etc.", max_length=50),
                ),
                ("erp_id", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ERP Mapping",
                "verbose_name_plural": "ERP Mappings",
                "db_table": "erp_mappings",
                "unique_together": {("entity_type", "ardt_id", "erp_system")},
            },
        ),
    ]
