# Generated by Django 5.2.8 on 2025-12-06 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0006_week3_field_data_capture"),
        ("supplychain", "0003_sprint6_fixes"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("DELETED", "Deleted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.IntegerField(db_index=True)),
                ("object_repr", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("changes", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_trail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_trail",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement_code",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("ISO_STANDARD", "ISO Standard"),
                            ("API_SPECIFICATION", "API Specification"),
                            ("GOVERNMENT_REGULATION", "Government Regulation"),
                            ("CUSTOMER_REQUIREMENT", "Customer Requirement"),
                            ("INDUSTRY_STANDARD", "Industry Standard"),
                            ("INTERNAL_POLICY", "Internal Policy"),
                            ("ENVIRONMENTAL", "Environmental Requirement"),
                            ("SAFETY", "Safety Requirement"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("source_document", models.CharField(max_length=200)),
                ("clause_number", models.CharField(blank=True, max_length=50)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("issuing_authority", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("applicable_scope", models.TextField(blank=True)),
                ("compliance_criteria", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending"),
                            ("SUPERSEDED", "Superseded"),
                            ("INACTIVE", "Inactive"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("PARTIAL", "Partially Compliant"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                            ("NOT_ASSESSED", "Not Yet Assessed"),
                        ],
                        db_index=True,
                        default="NOT_ASSESSED",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("review_date", models.DateField(blank=True, null=True)),
                ("last_assessment_date", models.DateField(blank=True, null=True)),
                ("superseded_date", models.DateField(blank=True, null=True)),
                (
                    "responsible_department",
                    models.CharField(blank=True, max_length=100),
                ),
                ("implementation_notes", models.TextField(blank=True)),
                ("verification_method", models.TextField(blank=True)),
                ("documentation_required", models.TextField(blank=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("consequences_of_non_compliance", models.TextField(blank=True)),
                ("assessment_frequency", models.CharField(blank=True, max_length=50)),
                ("assessment_notes", models.TextField(blank=True)),
                ("reference_url", models.URLField(blank=True)),
                ("internal_procedure", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_compliance_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessed_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_requirements",
                    models.ManyToManyField(
                        blank=True, to="compliance.compliancerequirement"
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by_requirements",
                        to="compliance.compliancerequirement",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_requirements",
                "ordering": ["requirement_code"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                            ("AUDIT", "Audit"),
                            ("AD_HOC", "Ad-Hoc"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("reporting_period_start", models.DateField()),
                ("reporting_period_end", models.DateField()),
                ("approved_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Review"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("non_conformances_count", models.IntegerField(default=0)),
                ("requirements_assessed", models.IntegerField(default=0)),
                ("requirements_compliant", models.IntegerField(default=0)),
                ("executive_summary", models.TextField(blank=True)),
                ("findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("report_file", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_compliance_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_compliance_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compliance_requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compliance_reports",
                        to="compliance.compliancerequirement",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_reports",
                "ordering": ["-reporting_period_end"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification_name", models.CharField(max_length=500)),
                ("certification_body", models.CharField(max_length=200)),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                            ("PENDING", "Pending"),
                        ],
                        db_index=True,
                        default="CURRENT",
                        max_length=20,
                    ),
                ),
                ("renewal_required", models.BooleanField(default=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("renewal_requirements", models.TextField(blank=True)),
                ("verification_url", models.URLField(blank=True)),
                ("certificate_file", models.CharField(blank=True, max_length=500)),
                ("verified", models.BooleanField(default=False)),
                ("verified_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compliance_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications",
                        to="compliance.compliancerequirement",
                    ),
                ),
            ],
            options={
                "db_table": "certifications",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="InspectionChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checklist_code", models.CharField(max_length=50, unique=True)),
                ("checklist_name", models.CharField(max_length=500)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("INCOMING", "Incoming"),
                            ("IN_PROCESS", "In-Process"),
                            ("FINAL", "Final"),
                            ("FIELD", "Field"),
                        ],
                        max_length=25,
                    ),
                ),
                ("applicable_to", models.TextField()),
                ("checklist_items", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compliance_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_checklists",
                        to="compliance.compliancerequirement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inspection_checklists",
                "ordering": ["checklist_code"],
            },
        ),
        migrations.CreateModel(
            name="NonConformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ncr_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("QUALITY_INSPECTION", "Quality Inspection"),
                            ("CUSTOMER_COMPLAINT", "Customer Complaint"),
                            ("INTERNAL_AUDIT", "Internal Audit"),
                            ("SUPPLIER_ISSUE", "Supplier Issue"),
                            ("PROCESS_DEVIATION", "Process Deviation"),
                            ("EMPLOYEE_REPORT", "Employee Report"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("MAJOR", "Major"),
                            ("MINOR", "Minor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("CORRECTIVE_ACTION", "Corrective Action"),
                            ("VERIFICATION", "Verification"),
                            ("CLOSED", "Closed"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=25,
                    ),
                ),
                ("description", models.TextField()),
                ("defect_description", models.TextField()),
                ("detected_date", models.DateField()),
                ("reported_date", models.DateField(auto_now_add=True)),
                ("root_cause_analysis", models.TextField(blank=True)),
                ("contributing_factors", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("target_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("closure_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_ncrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "capa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="non_conformances",
                        to="supplychain.capa",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_compliance_ncrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_ncrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="non_conformances",
                        to="supplychain.vendor",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_ncrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="non_conformances",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "non_conformances",
                "ordering": ["-detected_date", "-ncr_number"],
            },
        ),
        migrations.CreateModel(
            name="QualityControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("INCOMING", "Incoming Inspection"),
                            ("IN_PROCESS", "In-Process Inspection"),
                            ("FINAL", "Final Inspection"),
                            ("FIELD_INSPECTION", "Field Inspection"),
                            ("SUPPLIER_AUDIT", "Supplier Audit"),
                            ("CUSTOMER_WITNESS", "Customer Witness Point"),
                            ("CALIBRATION", "Calibration Verification"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("CONDITIONAL_PASS", "Conditional Pass"),
                            ("FAIL", "Fail"),
                            ("PENDING", "Pending"),
                            ("WAIVED", "Waived"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("inspection_time", models.TimeField(blank=True, null=True)),
                ("findings", models.TextField(blank=True)),
                ("defects_found", models.TextField(blank=True)),
                ("measurements", models.JSONField(blank=True, null=True)),
                ("passed_criteria", models.TextField(blank=True)),
                ("failed_criteria", models.TextField(blank=True)),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCEPT", "Accept"),
                            ("REWORK", "Rework"),
                            ("REPAIR", "Repair"),
                            ("SCRAP", "Scrap"),
                            ("RETURN", "Return"),
                            ("CONDITIONAL", "Conditional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("disposition_notes", models.TextField(blank=True)),
                ("corrective_action_required", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("photos_attached", models.BooleanField(default=False)),
                ("report_file", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_quality_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compliance_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_controls",
                        to="compliance.compliancerequirement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quality_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_controls",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "inspection_checklist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_controls",
                        to="compliance.inspectionchecklist",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "non_conformance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_controls",
                        to="compliance.nonconformance",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_controls",
                        to="supplychain.receipt",
                    ),
                ),
                (
                    "site_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_controls",
                        to="sales.sitevisit",
                    ),
                ),
                (
                    "witness",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="witnessed_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_controls",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "quality_controls",
                "ordering": ["-inspection_date", "-inspection_number"],
            },
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="quality_control",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_ncrs",
                to="compliance.qualitycontrol",
            ),
        ),
        migrations.CreateModel(
            name="QualityMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=200)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("DEFECT_RATE", "Defect Rate"),
                            ("ON_TIME_DELIVERY", "On-Time Delivery"),
                            ("CUSTOMER_SATISFACTION", "Customer Satisfaction"),
                            ("NCR_RATE", "NCR Rate"),
                            ("FIRST_PASS_YIELD", "First Pass Yield"),
                            ("REWORK_RATE", "Rework Rate"),
                            ("SCRAP_RATE", "Scrap Rate"),
                            ("SUPPLIER_QUALITY", "Supplier Quality"),
                            ("AUDIT_SCORE", "Audit Score"),
                            ("TRAINING_COMPLETION", "Training Completion"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("measurement_period", models.DateField()),
                (
                    "measured_value",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("unit_of_measure", models.CharField(default="%", max_length=50)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "threshold_warning",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "threshold_critical",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IMPROVING", "Improving"),
                            ("STABLE", "Stable"),
                            ("DECLINING", "Declining"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("data_source", models.CharField(blank=True, max_length=200)),
                ("calculation_method", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quality_metrics",
                "ordering": ["-measurement_period", "metric_name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("ORIENTATION", "Orientation"),
                            ("SAFETY", "Safety"),
                            ("TECHNICAL", "Technical"),
                            ("QUALITY", "Quality"),
                            ("COMPLIANCE", "Compliance"),
                            ("SOFTWARE", "Software"),
                            ("ON_THE_JOB", "On-the-Job"),
                            ("CERTIFICATION", "Certification"),
                            ("REFRESHER", "Refresher"),
                        ],
                        max_length=20,
                    ),
                ),
                ("training_title", models.CharField(max_length=500)),
                ("training_description", models.TextField(blank=True)),
                ("training_provider", models.CharField(max_length=200)),
                ("instructor_name", models.CharField(blank=True, max_length=200)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("duration_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("passed", models.BooleanField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("certificate_issued_date", models.DateField(blank=True, null=True)),
                ("certificate_expiry_date", models.DateField(blank=True, null=True)),
                ("required_for_position", models.BooleanField(default=False)),
                ("training_materials", models.CharField(blank=True, max_length=500)),
                (
                    "completion_certificate_file",
                    models.CharField(blank=True, max_length=500),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compliance_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_records",
                        to="compliance.compliancerequirement",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_training",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "training_records",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DocumentControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(max_length=500)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PROCEDURE", "Procedure"),
                            ("WORK_INSTRUCTION", "Work Instruction"),
                            ("FORM", "Form"),
                            ("SPECIFICATION", "Specification"),
                            ("DRAWING", "Drawing"),
                            ("CERTIFICATE", "Certificate"),
                            ("REPORT", "Report"),
                            ("POLICY", "Policy"),
                            ("MANUAL", "Manual"),
                            ("OTHER", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("revision_date", models.DateField()),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Review"),
                            ("APPROVED", "Approved"),
                            ("OBSOLETE", "Obsolete"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("reviewed_date", models.DateField(blank=True, null=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("scope", models.TextField(blank=True)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("file_checksum", models.CharField(blank=True, max_length=64)),
                ("change_summary", models.TextField(blank=True)),
                ("controlled_copy", models.BooleanField(default=True)),
                ("distribution_list", models.TextField(blank=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("review_frequency_months", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_controlled_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compliance_requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="compliance.compliancerequirement",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by_documents",
                        to="compliance.documentcontrol",
                    ),
                ),
            ],
            options={
                "db_table": "document_control",
                "ordering": ["document_number", "-version"],
                "unique_together": {("document_number", "version")},
            },
        ),
    ]
