# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("execution", "0004_initial"),
        ("inventory", "0003_initial"),
        ("workorders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200, unique=True)),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("QR", "QR Code"),
                            ("BARCODE", "Barcode"),
                            ("DATAMATRIX", "Data Matrix"),
                        ],
                        default="QR",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("DRILL_BIT", "Drill Bit"),
                            ("WORK_ORDER", "Work Order"),
                            ("INVENTORY_ITEM", "Inventory Item"),
                            ("EQUIPMENT", "Equipment"),
                            ("LOCATION", "Location"),
                            ("DOCUMENT", "Document"),
                            ("USER", "User Badge"),
                            ("EXTERNAL", "External"),
                        ],
                        max_length=30,
                    ),
                ),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("is_external", models.BooleanField(default=False)),
                (
                    "external_source",
                    models.CharField(
                        blank=True, help_text="ARAMCO, Supplier, etc.", max_length=100
                    ),
                ),
                ("encoded_data", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scan_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Code",
                "verbose_name_plural": "Scan Codes",
                "db_table": "scan_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_code",
                    models.CharField(help_text="Raw scanned value", max_length=500),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("IDENTIFY", "Identification"),
                            ("VERIFY", "Verification"),
                            ("CHECK_IN", "Check In"),
                            ("CHECK_OUT", "Check Out"),
                            ("STEP_COMPLETE", "Step Completion"),
                            ("TRANSFER", "Transfer"),
                        ],
                        default="IDENTIFY",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_message", models.CharField(blank=True, max_length=500)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("device_info", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventorylocation",
                    ),
                ),
                (
                    "scan_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_logs",
                        to="scancodes.scancode",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="execution.stepexecution",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Log",
                "verbose_name_plural": "Scan Logs",
                "db_table": "scan_logs",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="scancode",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="scan_codes_entity__552acd_idx",
            ),
        ),
    ]
