# Generated by Django 5.2.8 on 2025-12-05 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0005_alter_branchevaluation_branch_and_more"),
        ("inventory", "0005_materialconsumption_operation_execution_and_more"),
        ("scancodes", "0001_initial"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanlog",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scan_logs",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AlterField(
            model_name="scanlog",
            name="scanned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scanned_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="scanlog",
            name="step_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scan_logs",
                to="execution.stepexecution",
            ),
        ),
        migrations.AlterField(
            model_name="scanlog",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scan_logs",
                to="workorders.workorder",
            ),
        ),
    ]
