# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("aisle", models.CharField(blank=True, max_length=20)),
                ("rack", models.CharField(blank=True, max_length=20)),
                ("shelf", models.CharField(blank=True, max_length=20)),
                ("bin", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Inventory Location",
                "verbose_name_plural": "Inventory Locations",
                "db_table": "inventory_locations",
                "ordering": ["warehouse", "code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "quantity_available",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("lot_number", models.CharField(blank=True, max_length=50)),
                ("serial_number", models.CharField(blank=True, max_length=50)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("last_count_date", models.DateField(blank=True, null=True)),
                ("last_movement_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Inventory Stock",
                "verbose_name_plural": "Inventory Stock",
                "db_table": "inventory_stock",
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_number", models.CharField(max_length=30, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("ISSUE", "Issue"),
                            ("TRANSFER", "Transfer"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("RETURN", "Return"),
                            ("SCRAP", "Scrap"),
                            ("CYCLE_COUNT", "Cycle Count"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_date", models.DateTimeField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                ("unit", models.CharField(max_length=20)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("lot_number", models.CharField(blank=True, max_length=50)),
                ("serial_number", models.CharField(blank=True, max_length=50)),
                (
                    "link_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WORK_ORDER", "Work Order"),
                            ("PURCHASE_ORDER", "Purchase Order"),
                            ("SALES_ORDER", "Sales Order"),
                            ("MWO", "Maintenance Work Order"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("link_id", models.BigIntegerField(blank=True, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Inventory Transaction",
                "verbose_name_plural": "Inventory Transactions",
                "db_table": "inventory_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="inventory.inventorycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Category",
                "verbose_name_plural": "Inventory Categories",
                "db_table": "inventory_categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("RAW_MATERIAL", "Raw Material"),
                            ("COMPONENT", "Component"),
                            ("CONSUMABLE", "Consumable"),
                            ("TOOL", "Tool"),
                            ("SPARE_PART", "Spare Part"),
                            ("FINISHED_GOOD", "Finished Good"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="EA", help_text="EA, KG, M, etc.", max_length=20
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "last_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "min_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("lead_time_days", models.IntegerField(default=0)),
                ("specifications", models.JSONField(blank=True, null=True)),
                ("supplier_part_number", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_serialized",
                    models.BooleanField(
                        default=False, help_text="Track by serial number"
                    ),
                ),
                (
                    "is_lot_controlled",
                    models.BooleanField(default=False, help_text="Track by lot/batch"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="inventory/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.inventorycategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "db_table": "inventory_items",
                "ordering": ["code"],
            },
        ),
    ]
