# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylocation",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="sales.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="inventorystock",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_records",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="inventorystock",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_records",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="from_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outbound_transactions",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="to_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbound_transactions",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventorylocation",
            unique_together={("warehouse", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="inventorystock",
            unique_together={("item", "location", "lot_number", "serial_number")},
        ),
    ]
