# Generated by Django 5.1.15 on 2025-12-18 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_seed_categories"),
        ("sales", "0006_week3_field_data_capture"),
        ("supplychain", "0003_sprint6_fixes"),
        ("workorders", "0006_bittype_phase2_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g., size, color, material)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., Size, Color, Material)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this attribute"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
                "db_table": "attributes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (EA, KG, M, etc.)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (Each, Kilogram, Meter)", max_length=50
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("QUANTITY", "Quantity (Count)"),
                            ("LENGTH", "Length"),
                            ("WEIGHT", "Weight/Mass"),
                            ("VOLUME", "Volume"),
                            ("AREA", "Area"),
                            ("TIME", "Time"),
                            ("OTHER", "Other"),
                        ],
                        default="QUANTITY",
                        max_length=20,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Symbol for display (kg, m, L)",
                        max_length=10,
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        help_text="Multiply by this to convert to base unit",
                        max_digits=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "db_table": "units_of_measure",
                "ordering": ["unit_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="VariantCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique case code (e.g., NEW-PUR, USED-RET)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this variant case", max_length=100
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("NEW", "New"), ("USED", "Used")],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("RETURN", "Return"),
                            ("REPAIR", "Repair"),
                            ("RERUN", "Rerun"),
                        ],
                        default="PURCHASE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Variant Case",
                "verbose_name_plural": "Variant Cases",
                "db_table": "variant_cases",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("SELECT", "Select (Dropdown)"),
                            ("BOOLEAN", "Yes/No"),
                            ("DATE", "Date"),
                        ],
                        default="TEXT",
                        help_text="How this attribute is used in this category",
                        max_length=20,
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text='Options for SELECT type: ["Option1", "Option2"] or [{"value": "opt1", "label": "Option 1"}]',
                        null=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "is_used_in_name",
                    models.BooleanField(
                        default=False, help_text="Include in auto-generated item name"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_inherited", models.BooleanField(default=False)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_usages",
                        to="inventory.attribute",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_attributes",
                        to="inventory.inventorycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Attribute",
                "verbose_name_plural": "Category Attributes",
                "db_table": "category_attributes",
                "ordering": ["category", "display_order"],
                "unique_together": {("category", "attribute")},
            },
        ),
        migrations.CreateModel(
            name="ItemBitSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tfa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Total Flow Area (sq in)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("blade_count", models.IntegerField(blank=True, null=True)),
                ("cutter_count", models.IntegerField(blank=True, null=True)),
                ("nozzle_count", models.IntegerField(blank=True, null=True)),
                ("iadc_code", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bit_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_specs",
                        to="workorders.bitsize",
                    ),
                ),
                (
                    "bit_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bit_specs",
                        to="workorders.bittype",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bit_spec",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Bit Specification",
                "verbose_name_plural": "Item Bit Specifications",
                "db_table": "item_bit_specs",
            },
        ),
        migrations.CreateModel(
            name="ItemCutterSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cutter_type",
                    models.CharField(
                        choices=[
                            ("PDC", "PDC"),
                            ("TSP", "TSP"),
                            ("NATURAL_DIAMOND", "Natural Diamond"),
                            ("IMPREGNATED", "Impregnated"),
                            ("OTHER", "Other"),
                        ],
                        default="PDC",
                        max_length=20,
                    ),
                ),
                (
                    "cutter_shape",
                    models.CharField(
                        choices=[
                            ("ROUND", "Round"),
                            ("OVAL", "Oval"),
                            ("CONICAL", "Conical"),
                            ("DOME", "Dome"),
                            ("CHISEL", "Chisel"),
                            ("OTHER", "Other"),
                        ],
                        default="ROUND",
                        max_length=20,
                    ),
                ),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "thickness",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "chamfer_size",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("substrate", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutter_spec",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Cutter Specification",
                "verbose_name_plural": "Item Cutter Specifications",
                "db_table": "item_cutter_specs",
            },
        ),
        migrations.CreateModel(
            name="ItemVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "client_code",
                    models.CharField(
                        blank=True, help_text="Client-specific item code", max_length=50
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "last_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "legacy_mat_no",
                    models.CharField(
                        blank=True, help_text="Legacy MAT number", max_length=50
                    ),
                ),
                (
                    "erp_item_no",
                    models.CharField(
                        blank=True, help_text="ERP Item number", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client-specific variant (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_variants",
                        to="sales.customer",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_variants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_variants",
                        to="inventory.variantcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Variant",
                "verbose_name_plural": "Item Variants",
                "db_table": "item_variants",
                "ordering": ["base_item", "variant_case"],
                "unique_together": {("base_item", "variant_case", "client")},
            },
        ),
        migrations.CreateModel(
            name="ItemAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_value", models.CharField(blank=True, max_length=500)),
                (
                    "number_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("date_value", models.DateField(blank=True, null=True)),
                (
                    "category_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="inventory.categoryattribute",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Attribute Value",
                "verbose_name_plural": "Item Attribute Values",
                "db_table": "item_attribute_values",
                "unique_together": {("item", "category_attribute")},
            },
        ),
        migrations.CreateModel(
            name="ItemIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("BARCODE", "Barcode"),
                            ("QR_CODE", "QR Code"),
                            ("RFID", "RFID Tag"),
                            ("SKU", "SKU"),
                            ("UPC", "UPC"),
                            ("EAN", "EAN"),
                            ("MPN", "Manufacturer Part Number"),
                            ("INTERNAL", "Internal Code"),
                            ("LEGACY", "Legacy Code"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("identifier_value", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Identifier",
                "verbose_name_plural": "Item Identifiers",
                "db_table": "item_identifiers",
                "unique_together": {("item", "identifier_type", "identifier_value")},
            },
        ),
        migrations.CreateModel(
            name="ItemPlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "safety_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("lead_time_days", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_records",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_planning_records",
                        to="sales.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Planning",
                "verbose_name_plural": "Item Planning Records",
                "db_table": "item_planning",
                "unique_together": {("item", "warehouse")},
            },
        ),
        migrations.CreateModel(
            name="ItemSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_part_number", models.CharField(blank=True, max_length=100)),
                ("supplier_description", models.CharField(blank=True, max_length=255)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "min_order_qty",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("lead_time_days", models.IntegerField(default=0)),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="1 = Primary, 2 = Secondary, etc."
                    ),
                ),
                ("is_preferred", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_suppliers",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplied_items",
                        to="supplychain.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Supplier",
                "verbose_name_plural": "Item Suppliers",
                "db_table": "item_suppliers",
                "ordering": ["item", "priority"],
                "unique_together": {("item", "supplier")},
            },
        ),
        migrations.CreateModel(
            name="VariantStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "min_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("last_movement_date", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_records",
                        to="inventory.itemvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_stocks",
                        to="sales.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant Stock",
                "verbose_name_plural": "Variant Stocks",
                "db_table": "variant_stocks",
                "unique_together": {("variant", "warehouse")},
            },
        ),
    ]
