# Generated by Django 5.1.15 on 2025-12-16 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_seed_categories"),
        ("sales", "0006_week3_field_data_capture"),
        ("supplychain", "0003_sprint6_fixes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g., size, color, material)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., Size, Color, Material)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this attribute"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
                "db_table": "attributes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("SELECT", "Select (Dropdown)"),
                            ("BOOLEAN", "Yes/No"),
                            ("DATE", "Date"),
                        ],
                        default="TEXT",
                        help_text="How this attribute is used in this category",
                        max_length=20,
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text='Options for SELECT type: ["Option1", "Option2"] or [{"value": "opt1", "label": "Option 1"}]',
                        null=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "is_used_in_name",
                    models.BooleanField(
                        default=False, help_text="Include in auto-generated item name"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_inherited", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Category Attribute",
                "verbose_name_plural": "Category Attributes",
                "db_table": "category_attributes",
                "ordering": ["category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="ItemAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_value", models.CharField(blank=True, max_length=500)),
                (
                    "number_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("date_value", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Item Attribute Value",
                "verbose_name_plural": "Item Attribute Values",
                "db_table": "item_attribute_values",
            },
        ),
        migrations.CreateModel(
            name="ItemVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "standard_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "last_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "legacy_mat_no",
                    models.CharField(
                        blank=True, help_text="Legacy MAT number", max_length=50
                    ),
                ),
                (
                    "erp_item_no",
                    models.CharField(
                        blank=True, help_text="ERP Item number", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item Variant",
                "verbose_name_plural": "Item Variants",
                "db_table": "item_variants",
                "ordering": ["base_item", "variant_case"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (EA, KG, M, etc.)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (Each, Kilogram, Meter)", max_length=50
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("QUANTITY", "Quantity (Count)"),
                            ("LENGTH", "Length"),
                            ("WEIGHT", "Weight/Mass"),
                            ("VOLUME", "Volume"),
                            ("AREA", "Area"),
                            ("TIME", "Time"),
                            ("OTHER", "Other"),
                        ],
                        default="QUANTITY",
                        max_length=20,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Symbol for display (kg, m, L)",
                        max_length=10,
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        help_text="Multiply by this to convert to base unit",
                        max_digits=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "db_table": "units_of_measure",
                "ordering": ["unit_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="VariantCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique case code (e.g., NEW-PUR, USED-RET)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this variant case", max_length=100
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("NEW", "New"), ("USED", "Used")],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "acquisition",
                    models.CharField(
                        choices=[
                            ("PURCHASED", "Purchased"),
                            ("RECLAIMED", "Reclaimed"),
                            ("MANUFACTURED", "Manufactured"),
                            ("CLIENT_PROVIDED", "Client Provided"),
                        ],
                        default="PURCHASED",
                        max_length=20,
                    ),
                ),
                (
                    "reclaim_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RETROFIT", "Retrofit (as New)"),
                            ("E_AND_O", "E&O (Excessive & Obsolete)"),
                            ("GROUND", "Ground (Surface Damage)"),
                            ("STANDARD", "Standard Reclaim"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[("ARDT", "ARDT"), ("CLIENT", "Client")],
                        default="ARDT",
                        max_length=20,
                    ),
                ),
                (
                    "client_code",
                    models.CharField(
                        blank=True,
                        help_text="Client code for CLIENT ownership cases (e.g., LSTK, Halliburton)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of when this case applies"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Variant Case",
                "verbose_name_plural": "Variant Cases",
                "db_table": "variant_cases",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="VariantStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "quantity_available",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("lot_number", models.CharField(blank=True, max_length=50)),
                ("serial_number", models.CharField(blank=True, max_length=50)),
                ("last_movement_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Variant Stock",
                "verbose_name_plural": "Variant Stock",
                "db_table": "variant_stock",
            },
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="code_prefix",
            field=models.CharField(
                blank=True,
                help_text="Prefix for auto-generated item codes (e.g., CUT, MAT, NOZ)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("RAW_MATERIAL", "Raw Material"),
                    ("COMPONENT", "Component"),
                    ("CONSUMABLE", "Consumable"),
                    ("TOOL", "Tool"),
                    ("SPARE_PART", "Spare Part"),
                    ("FINISHED_GOOD", "Finished Good"),
                ],
                default="COMPONENT",
                help_text="Default item type for items in this category",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="name_template",
            field=models.CharField(
                blank=True,
                help_text="Template for auto-name: {size}mm {material} {grade} (uses attribute codes)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="next_sequence",
            field=models.IntegerField(
                default=1, help_text="Next sequence number for code generation"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="has_variants",
            field=models.BooleanField(
                default=False, help_text="Item has condition/source variants"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="item_number",
            field=models.CharField(
                blank=True, help_text="Parallel ERP Item No.", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="mat_number",
            field=models.CharField(
                blank=True, help_text="SAP Legacy MAT No.", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="name_manually_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="requires_expiry_tracking",
            field=models.BooleanField(
                default=False, help_text="Track expiry dates for this item"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="shelf_life_days",
            field=models.IntegerField(
                blank=True,
                help_text="Shelf life in days (for perishable/time-sensitive items)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["mat_number"], name="inventory_i_mat_num_b66add_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["item_number"], name="inventory_i_item_nu_fe1e8e_idx"
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="attribute",
            field=models.ForeignKey(
                help_text="The attribute being configured for this category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_usages",
                to="inventory.attribute",
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_attributes",
                to="inventory.inventorycategory",
            ),
        ),
        migrations.AddField(
            model_name="itemattributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="inventory.categoryattribute",
            ),
        ),
        migrations.AddField(
            model_name="itemattributevalue",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_values",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="base_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_variants",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="base_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Base unit for conversion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_units",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit of measure for NUMBER type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_attributes",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="variant_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item_variants",
                to="inventory.variantcase",
            ),
        ),
        migrations.AddField(
            model_name="variantstock",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_stock_records",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="variantstock",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_records",
                to="inventory.itemvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemattributevalue",
            unique_together={("item", "attribute")},
        ),
        migrations.AlterUniqueTogether(
            name="categoryattribute",
            unique_together={("category", "attribute")},
        ),
        migrations.AlterUniqueTogether(
            name="itemvariant",
            unique_together={("base_item", "variant_case", "customer")},
        ),
        migrations.AlterUniqueTogether(
            name="variantstock",
            unique_together={("variant", "location", "lot_number", "serial_number")},
        ),
    ]
