# Generated by Django 5.1.15 on 2025-12-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_enhanced_category_attributes_variants"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (EA, KG, M, etc.)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (Each, Kilogram, Meter)", max_length=50
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("QUANTITY", "Quantity (Count)"),
                            ("LENGTH", "Length"),
                            ("WEIGHT", "Weight/Mass"),
                            ("VOLUME", "Volume"),
                            ("AREA", "Area"),
                            ("TIME", "Time"),
                            ("OTHER", "Other"),
                        ],
                        default="QUANTITY",
                        max_length=20,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Symbol for display (kg, m, L)",
                        max_length=10,
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        help_text="Multiply by this to convert to base unit",
                        max_digits=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "base_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Base unit for conversion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_units",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "db_table": "units_of_measure",
                "ordering": ["unit_type", "code"],
            },
        ),
    ]
