# Generated by Django 5.1.15 on 2025-12-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_add_client_code_field"),
        ("sales", "0006_week3_field_data_capture"),
        ("supplychain", "0003_sprint6_fixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="abc_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A - High Value"),
                    ("B", "B - Medium Value"),
                    ("C", "C - Low Value"),
                ],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="brand",
            field=models.CharField(blank=True, help_text="Brand name", max_length=100),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="criticality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="lifecycle_state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("OBSOLETE", "Obsolete"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                help_text="Manufacturer (can be different from supplier)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manufactured_items",
                to="supplychain.supplier",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="mpn",
            field=models.CharField(
                blank=True, help_text="Manufacturer Part Number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred: Use UOM FK instead of unit char field",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="is_lot_controlled",
            field=models.BooleanField(
                default=False, help_text="Track by lot/batch (is_lot_tracked)"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="is_serialized",
            field=models.BooleanField(
                default=False, help_text="Track by serial number (is_serial_tracked)"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("STOCK_ITEM", "Stock Item"),
                    ("NON_STOCK", "Non-Stock Item"),
                    ("SERVICE", "Service"),
                    ("ASSET_TEMPLATE", "Asset Template"),
                    ("RAW_MATERIAL", "Raw Material"),
                    ("COMPONENT", "Component"),
                    ("CONSUMABLE", "Consumable"),
                    ("TOOL", "Tool"),
                    ("SPARE_PART", "Spare Part"),
                    ("FINISHED_GOOD", "Finished Good"),
                ],
                default="STOCK_ITEM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="lead_time_days",
            field=models.IntegerField(
                default=0, help_text="DEPRECATED: Use ItemSupplier"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="max_stock",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="DEPRECATED: Use ItemPlanning",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="min_stock",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="DEPRECATED: Use ItemPlanning",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="primary_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use ItemSupplier with is_preferred=True",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_items",
                to="supplychain.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="reorder_point",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="DEPRECATED: Use ItemPlanning",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="reorder_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="DEPRECATED: Use ItemPlanning",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="requires_expiry_tracking",
            field=models.BooleanField(
                default=False, help_text="Track expiry dates (is_expiry_tracked)"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="shelf_life_days",
            field=models.IntegerField(
                blank=True, help_text="Shelf life in days", null=True
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="specifications",
            field=models.JSONField(
                blank=True, help_text="DEPRECATED: Use ItemAttributeValue", null=True
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="supplier_part_number",
            field=models.CharField(
                blank=True, help_text="DEPRECATED: Use ItemSupplier", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="ItemIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("EAN13", "EAN-13 (Unit)"),
                            ("EAN14", "EAN-14 (Case)"),
                            ("UPC", "UPC-A"),
                            ("ITF14", "ITF-14 (Carton)"),
                            ("QR", "QR Code"),
                            ("DATAMATRIX", "Data Matrix"),
                            ("CODE128", "Code 128"),
                            ("CODE39", "Code 39"),
                            ("GS1", "GS1-128"),
                            ("INTERNAL", "Internal Code"),
                            ("SSCC", "SSCC-18 (Pallet)"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The barcode/identifier value", max_length=100
                    ),
                ),
                (
                    "pack_level",
                    models.CharField(
                        choices=[
                            ("UNIT", "Unit/Each"),
                            ("INNER", "Inner Pack"),
                            ("CASE", "Case/Box"),
                            ("CARTON", "Carton"),
                            ("PALLET", "Pallet"),
                        ],
                        default="UNIT",
                        max_length=20,
                    ),
                ),
                (
                    "qty_per_pack",
                    models.IntegerField(
                        default=1, help_text="Units per pack at this level"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary identifier for scanning"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Identifier",
                "verbose_name_plural": "Item Identifiers",
                "db_table": "item_identifiers",
                "ordering": ["item", "pack_level", "identifier_type"],
                "indexes": [
                    models.Index(fields=["value"], name="item_identi_value_e1fa4f_idx")
                ],
                "unique_together": {("item", "identifier_type", "pack_level")},
            },
        ),
        migrations.CreateModel(
            name="ItemPlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "safety_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_items",
                        to="inventory.inventorylocation",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_records",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_planning_records",
                        to="sales.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Planning",
                "verbose_name_plural": "Item Planning Records",
                "db_table": "item_planning",
                "ordering": ["item", "warehouse"],
                "unique_together": {("item", "warehouse")},
            },
        ),
        migrations.CreateModel(
            name="ItemSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_part_number", models.CharField(blank=True, max_length=100)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("price_valid_from", models.DateField(blank=True, null=True)),
                ("price_valid_to", models.DateField(blank=True, null=True)),
                ("lead_time_days", models.IntegerField(default=0)),
                (
                    "min_order_qty",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "order_multiple",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("priority_rank", models.IntegerField(default=1)),
                ("is_preferred", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_records",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_records",
                        to="supplychain.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Supplier",
                "verbose_name_plural": "Item Suppliers",
                "db_table": "item_suppliers",
                "ordering": ["item", "priority_rank"],
                "unique_together": {("item", "supplier")},
            },
        ),
    ]
