# Generated by Django 5.1.15 on 2025-12-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_inventoryitem_requires_expiry_tracking_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g., size, color, material)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., Size, Color, Material)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this attribute"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
                "db_table": "attributes",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="categoryattribute",
            options={
                "ordering": ["category", "display_order"],
                "verbose_name": "Category Attribute",
                "verbose_name_plural": "Category Attributes",
            },
        ),
        migrations.AlterField(
            model_name="categoryattribute",
            name="attribute_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("NUMBER", "Number"),
                    ("SELECT", "Select (Dropdown)"),
                    ("BOOLEAN", "Yes/No"),
                    ("DATE", "Date"),
                ],
                default="TEXT",
                help_text="How this attribute is used in this category",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="categoryattribute",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_attributes",
                to="inventory.inventorycategory",
            ),
        ),
        migrations.AlterField(
            model_name="categoryattribute",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit of measure for NUMBER type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_attributes",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoryattribute",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="attribute",
            field=models.ForeignKey(
                help_text="The attribute being configured for this category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_usages",
                to="inventory.attribute",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoryattribute",
            unique_together={("category", "attribute")},
        ),
        migrations.RemoveField(
            model_name="categoryattribute",
            name="code",
        ),
        migrations.RemoveField(
            model_name="categoryattribute",
            name="name",
        ),
    ]
