# Generated by Django 5.1.15 on 2025-12-19 - Phase 1: Lot Tracking & Ownership

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Phase 1: Enhanced Lot Tracking with Ownership & Quality Gates

    Includes:
    - Phase 0 Refinement: can_own_stock on Party, affects_balance_sheet on OwnershipType
    - Phase 1: tracking_type, costing_method, base_uom on InventoryItem
    - Phase 1: condition, quality_status, owner_party, ownership_type on MaterialLot
    """

    dependencies = [
        ("inventory", "0015_phase0_foundation"),
    ]

    operations = [
        # =====================================================================
        # Phase 0 Refinement: Add can_own_stock to Party
        # =====================================================================
        migrations.AddField(
            model_name="party",
            name="can_own_stock",
            field=models.BooleanField(
                default=True,
                help_text="Can this party own stock? RIG parties typically cannot own stock directly.",
            ),
        ),

        # =====================================================================
        # Phase 0 Refinement: Add affects_balance_sheet to OwnershipType
        # =====================================================================
        migrations.AddField(
            model_name="ownershiptype",
            name="affects_balance_sheet",
            field=models.BooleanField(
                default=False,
                help_text="True if this ownership type should appear on ARDT's balance sheet",
            ),
        ),

        # =====================================================================
        # Phase 1: Add tracking_type, costing_method, base_uom to InventoryItem
        # =====================================================================
        migrations.AddField(
            model_name="inventoryitem",
            name="tracking_type",
            field=models.CharField(
                choices=[
                    ("NONE", "No Tracking (quantity only)"),
                    ("LOT", "Lot/Batch Tracking"),
                    ("SERIAL", "Serial Number Tracking"),
                    ("ASSET", "Asset Tracking (serialized + lifecycle)"),
                ],
                default="NONE",
                help_text="How this item is tracked in inventory",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="costing_method",
            field=models.CharField(
                choices=[
                    ("AVG", "Weighted Average"),
                    ("FIFO", "First In First Out"),
                    ("STD", "Standard Cost"),
                ],
                default="AVG",
                help_text="Inventory costing method",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="base_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Base UOM for ledger - all quantities stored in this unit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_using_as_base",
                to="inventory.unitofmeasure",
            ),
        ),

        # =====================================================================
        # Phase 1: Add condition, quality_status, owner_party, ownership_type to MaterialLot
        # =====================================================================
        migrations.AddField(
            model_name="materiallot",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical condition of the lot (NEW, USED, REFURB, etc.)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="inventory.conditiontype",
            ),
        ),
        migrations.AddField(
            model_name="materiallot",
            name="quality_status",
            field=models.ForeignKey(
                blank=True,
                help_text="QC status - gates what can be done with the lot",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="inventory.qualitystatus",
            ),
        ),
        migrations.AddField(
            model_name="materiallot",
            name="owner_party",
            field=models.ForeignKey(
                blank=True,
                help_text="Who owns this lot (Party - could be ARDT, customer, or vendor)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_lots",
                to="inventory.party",
            ),
        ),
        migrations.AddField(
            model_name="materiallot",
            name="ownership_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Ownership relationship type (OWNED, CLIENT, CONSIGNMENT, etc.)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="inventory.ownershiptype",
            ),
        ),

        # =====================================================================
        # Add indexes for common lookups
        # =====================================================================
        migrations.AddIndex(
            model_name="materiallot",
            index=models.Index(
                fields=["quality_status"], name="material_lo_quality_c1e9a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materiallot",
            index=models.Index(
                fields=["owner_party"], name="material_lo_owner_p_8f3b21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materiallot",
            index=models.Index(
                fields=["ownership_type"], name="material_lo_ownersh_d4a5f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["tracking_type"], name="inventory_i_trackin_a2b1c3_idx"
            ),
        ),
    ]
