# Generated by Django 5.1.15 on 2025-12-19 - Phases 2, 3, 4: Ledger, Documents, Assets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Combined migration for Phases 2, 3, and 4:

    Phase 2: Stock Ledger & Balance
    - StockLedger: Immutable ledger entries (source of truth)
    - StockBalance: Materialized balance view

    Phase 3: Inventory Documents
    - GoodsReceiptNote + GRNLine: Inbound receipts
    - StockIssue + StockIssueLine: Outbound issues
    - StockTransfer + StockTransferLine: Location/ownership transfers
    - StockAdjustment + StockAdjustmentLine: Quantity adjustments

    Phase 4: Asset Tracking
    - Asset: Serialized asset with full lifecycle
    - AssetMovement: Asset movement/status history
    """

    dependencies = [
        ("inventory", "0016_phase1_lot_tracking"),
        ("sales", "0006_week3_field_data_capture"),
        ("supplychain", "0003_sprint6_fixes"),
        ("workorders", "0008_sprint7_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # =====================================================================
        # PHASE 2: STOCK LEDGER & BALANCE
        # =====================================================================

        # StockLedger - Immutable ledger entries
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_number", models.CharField(help_text="Auto-generated unique entry number", max_length=50, unique=True)),
                ("entry_date", models.DateTimeField(auto_now_add=True, help_text="When this ledger entry was created")),
                ("transaction_date", models.DateField(help_text="Business date of the transaction")),
                ("transaction_type", models.CharField(
                    choices=[
                        ("RECEIPT", "Goods Receipt"),
                        ("RETURN_IN", "Customer Return (Inbound)"),
                        ("TRANSFER_IN", "Transfer In"),
                        ("ADJ_IN", "Adjustment (Increase)"),
                        ("ISSUE", "Goods Issue"),
                        ("RETURN_OUT", "Return to Vendor (Outbound)"),
                        ("TRANSFER_OUT", "Transfer Out"),
                        ("ADJ_OUT", "Adjustment (Decrease)"),
                        ("SCRAP", "Scrap/Disposal"),
                        ("CONSUMPTION", "WO Material Consumption"),
                        ("QC_RELEASE", "QC Release"),
                        ("QC_BLOCK", "QC Block"),
                        ("QC_QUARANTINE", "QC Quarantine"),
                        ("OWNER_CHG", "Ownership Change"),
                    ],
                    max_length=20,
                )),
                ("qty_delta", models.DecimalField(decimal_places=3, help_text="Signed quantity change", max_digits=15)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("reference_type", models.CharField(help_text="Source document type", max_length=50)),
                ("reference_id", models.CharField(help_text="Source document ID", max_length=100)),
                ("is_reversal", models.BooleanField(default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.inventoryitem")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.inventorylocation")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.materiallot")),
                ("owner_party", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.party")),
                ("ownership_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.ownershiptype")),
                ("quality_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.qualitystatus")),
                ("condition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.conditiontype")),
                ("uom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.unitofmeasure")),
                ("reverses_entry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reversed_by", to="inventory.stockledger")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Stock Ledger Entry",
                "verbose_name_plural": "Stock Ledger Entries",
                "db_table": "stock_ledger",
                "ordering": ["-entry_date", "-id"],
            },
        ),

        # StockBalance - Materialized balance view
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty_on_hand", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("qty_reserved", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("qty_available", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("avg_unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("last_movement_date", models.DateTimeField(blank=True, null=True)),
                ("last_recalc_date", models.DateTimeField(auto_now=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="inventory.inventoryitem")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="inventory.inventorylocation")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="inventory.materiallot")),
                ("owner_party", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="inventory.party")),
                ("ownership_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="inventory.ownershiptype")),
                ("quality_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="inventory.qualitystatus")),
                ("condition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="inventory.conditiontype")),
            ],
            options={
                "verbose_name": "Stock Balance",
                "verbose_name_plural": "Stock Balances",
                "db_table": "stock_balances",
            },
        ),

        # =====================================================================
        # PHASE 3: INVENTORY DOCUMENTS
        # =====================================================================

        # GoodsReceiptNote
        migrations.CreateModel(
            name="GoodsReceiptNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("grn_number", models.CharField(max_length=50, unique=True)),
                ("receipt_type", models.CharField(
                    choices=[
                        ("PURCHASE", "Purchase Order Receipt"),
                        ("RETURN", "Customer Return"),
                        ("TRANSFER", "Transfer Receipt"),
                        ("OPENING", "Opening Balance"),
                        ("OTHER", "Other Receipt"),
                    ],
                    default="PURCHASE", max_length=20,
                )),
                ("status", models.CharField(
                    choices=[
                        ("DRAFT", "Draft"),
                        ("PENDING_QC", "Pending QC"),
                        ("CONFIRMED", "Confirmed"),
                        ("CANCELLED", "Cancelled"),
                    ],
                    default="DRAFT", max_length=20,
                )),
                ("source_reference", models.CharField(blank=True, max_length=100)),
                ("receipt_date", models.DateField()),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("requires_qc", models.BooleanField(default=True)),
                ("qc_completed", models.BooleanField(default=False)),
                ("qc_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grns", to="sales.warehouse")),
                ("receiving_location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grns_received", to="inventory.inventorylocation")),
                ("supplier", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grns", to="supplychain.supplier")),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grns", to="supplychain.purchaseorder")),
                ("owner_party", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grns_received", to="inventory.party")),
                ("ownership_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grns", to="inventory.ownershiptype")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grns_created", to=settings.AUTH_USER_MODEL)),
                ("confirmed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grns_confirmed", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Goods Receipt Note",
                "verbose_name_plural": "Goods Receipt Notes",
                "db_table": "goods_receipt_notes",
                "ordering": ["-receipt_date", "-grn_number"],
            },
        ),

        # GRNLine
        migrations.CreateModel(
            name="GRNLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.IntegerField()),
                ("qty_expected", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("qty_received", models.DecimalField(decimal_places=3, max_digits=15)),
                ("lot_number_received", models.CharField(blank=True, max_length=50)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("grn", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.goodsreceiptnote")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grn_lines", to="inventory.inventoryitem")),
                ("uom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grn_lines", to="inventory.unitofmeasure")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grn_lines", to="inventory.inventorylocation")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grn_lines", to="inventory.materiallot")),
                ("condition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grn_lines", to="inventory.conditiontype")),
                ("quality_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grn_lines", to="inventory.qualitystatus")),
                ("po_line", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grn_lines", to="supplychain.purchaseorderline")),
            ],
            options={
                "verbose_name": "GRN Line",
                "verbose_name_plural": "GRN Lines",
                "db_table": "grn_lines",
                "ordering": ["grn", "line_number"],
                "unique_together": {("grn", "line_number")},
            },
        ),

        # StockIssue
        migrations.CreateModel(
            name="StockIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issue_number", models.CharField(max_length=50, unique=True)),
                ("issue_type", models.CharField(
                    choices=[
                        ("WO", "Work Order Issue"),
                        ("SALES", "Sales Issue"),
                        ("INTERNAL", "Internal Consumption"),
                        ("SCRAP", "Scrap/Disposal"),
                        ("SAMPLE", "Sample Issue"),
                        ("OTHER", "Other Issue"),
                    ],
                    default="WO", max_length=20,
                )),
                ("status", models.CharField(
                    choices=[
                        ("DRAFT", "Draft"),
                        ("PENDING", "Pending Approval"),
                        ("APPROVED", "Approved"),
                        ("PICKED", "Picked"),
                        ("ISSUED", "Issued"),
                        ("CANCELLED", "Cancelled"),
                    ],
                    default="DRAFT", max_length=20,
                )),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField()),
                ("required_date", models.DateField(blank=True, null=True)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_issues", to="sales.warehouse")),
                ("default_location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_issues", to="inventory.inventorylocation")),
                ("work_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stock_issues", to="workorders.workorder")),
                ("sales_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stock_issues", to="sales.salesorder")),
                ("issue_to_party", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stock_issues_received", to="inventory.party")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_issues_created", to=settings.AUTH_USER_MODEL)),
                ("issued_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stock_issues_issued", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Stock Issue",
                "verbose_name_plural": "Stock Issues",
                "db_table": "stock_issues",
                "ordering": ["-issue_date", "-issue_number"],
            },
        ),

        # StockIssueLine
        migrations.CreateModel(
            name="StockIssueLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.IntegerField()),
                ("qty_requested", models.DecimalField(decimal_places=3, max_digits=15)),
                ("qty_issued", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.stockissue")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issue_lines", to="inventory.inventoryitem")),
                ("uom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issue_lines", to="inventory.unitofmeasure")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issue_lines", to="inventory.inventorylocation")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="issue_lines", to="inventory.materiallot")),
                ("owner_party", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issue_lines", to="inventory.party")),
                ("ownership_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issue_lines", to="inventory.ownershiptype")),
                ("condition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issue_lines", to="inventory.conditiontype")),
                ("quality_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issue_lines", to="inventory.qualitystatus")),
            ],
            options={
                "verbose_name": "Stock Issue Line",
                "verbose_name_plural": "Stock Issue Lines",
                "db_table": "stock_issue_lines",
                "ordering": ["issue", "line_number"],
                "unique_together": {("issue", "line_number")},
            },
        ),

        # StockTransfer
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transfer_number", models.CharField(max_length=50, unique=True)),
                ("transfer_type", models.CharField(
                    choices=[
                        ("LOCATION", "Location Transfer"),
                        ("WAREHOUSE", "Warehouse Transfer"),
                        ("OWNERSHIP", "Ownership Transfer"),
                        ("QC_STATUS", "Quality Status Change"),
                    ],
                    default="LOCATION", max_length=20,
                )),
                ("status", models.CharField(
                    choices=[
                        ("DRAFT", "Draft"),
                        ("PENDING", "Pending Approval"),
                        ("IN_TRANSIT", "In Transit"),
                        ("RECEIVED", "Received"),
                        ("COMPLETED", "Completed"),
                        ("CANCELLED", "Cancelled"),
                    ],
                    default="DRAFT", max_length=20,
                )),
                ("transfer_date", models.DateField()),
                ("shipped_date", models.DateTimeField(blank=True, null=True)),
                ("received_date", models.DateTimeField(blank=True, null=True)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfers_out", to="sales.warehouse")),
                ("to_warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfers_in", to="sales.warehouse")),
                ("from_location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfers_out", to="inventory.inventorylocation")),
                ("to_location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfers_in", to="inventory.inventorylocation")),
                ("from_owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfers_from", to="inventory.party")),
                ("to_owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="transfers_to", to="inventory.party")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfers_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Stock Transfer",
                "verbose_name_plural": "Stock Transfers",
                "db_table": "stock_transfers",
                "ordering": ["-transfer_date", "-transfer_number"],
            },
        ),

        # StockTransferLine
        migrations.CreateModel(
            name="StockTransferLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.IntegerField()),
                ("qty_requested", models.DecimalField(decimal_places=3, max_digits=15)),
                ("qty_shipped", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("qty_received", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("transfer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.stocktransfer")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfer_lines", to="inventory.inventoryitem")),
                ("uom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfer_lines", to="inventory.unitofmeasure")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="transfer_lines", to="inventory.materiallot")),
                ("ownership_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfer_lines", to="inventory.ownershiptype")),
                ("condition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfer_lines", to="inventory.conditiontype")),
                ("from_quality_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfer_lines_from", to="inventory.qualitystatus")),
                ("to_quality_status", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="transfer_lines_to", to="inventory.qualitystatus")),
            ],
            options={
                "verbose_name": "Stock Transfer Line",
                "verbose_name_plural": "Stock Transfer Lines",
                "db_table": "stock_transfer_lines",
                "ordering": ["transfer", "line_number"],
                "unique_together": {("transfer", "line_number")},
            },
        ),

        # StockAdjustment
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adjustment_number", models.CharField(max_length=50, unique=True)),
                ("adjustment_type", models.CharField(
                    choices=[
                        ("CYCLE", "Cycle Count"),
                        ("PHYSICAL", "Physical Inventory"),
                        ("WRITEOFF", "Write Off"),
                        ("OPENING", "Opening Balance"),
                        ("CORRECT", "Correction"),
                        ("OTHER", "Other"),
                    ],
                    default="CORRECT", max_length=20,
                )),
                ("status", models.CharField(
                    choices=[
                        ("DRAFT", "Draft"),
                        ("PENDING", "Pending Approval"),
                        ("APPROVED", "Approved"),
                        ("POSTED", "Posted"),
                        ("CANCELLED", "Cancelled"),
                    ],
                    default="DRAFT", max_length=20,
                )),
                ("adjustment_date", models.DateField()),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("requires_approval", models.BooleanField(default=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_adjustments", to="sales.warehouse")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_adjustments", to="inventory.inventorylocation")),
                ("reason", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustments", to="inventory.adjustmentreason")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustments_created", to=settings.AUTH_USER_MODEL)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="adjustments_approved", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Stock Adjustment",
                "verbose_name_plural": "Stock Adjustments",
                "db_table": "stock_adjustments",
                "ordering": ["-adjustment_date", "-adjustment_number"],
            },
        ),

        # StockAdjustmentLine
        migrations.CreateModel(
            name="StockAdjustmentLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.IntegerField()),
                ("qty_system", models.DecimalField(decimal_places=3, max_digits=15)),
                ("qty_counted", models.DecimalField(decimal_places=3, max_digits=15)),
                ("qty_adjustment", models.DecimalField(decimal_places=3, max_digits=15)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("adjustment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.stockadjustment")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_lines", to="inventory.inventoryitem")),
                ("uom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_lines", to="inventory.unitofmeasure")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_lines", to="inventory.materiallot")),
                ("owner_party", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_lines", to="inventory.party")),
                ("ownership_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_lines", to="inventory.ownershiptype")),
                ("condition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_lines", to="inventory.conditiontype")),
                ("quality_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_lines", to="inventory.qualitystatus")),
            ],
            options={
                "verbose_name": "Stock Adjustment Line",
                "verbose_name_plural": "Stock Adjustment Lines",
                "db_table": "stock_adjustment_lines",
                "ordering": ["adjustment", "line_number"],
                "unique_together": {("adjustment", "line_number")},
            },
        ),

        # =====================================================================
        # PHASE 4: ASSET TRACKING
        # =====================================================================

        # Asset
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("asset_tag", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ("status", models.CharField(
                    choices=[
                        ("ON_ORDER", "On Order"),
                        ("IN_TRANSIT", "In Transit"),
                        ("RECEIVED", "Received"),
                        ("QUARANTINE", "In Quarantine"),
                        ("INSPECTION", "Under Inspection"),
                        ("READY", "Ready for Use"),
                        ("AVAILABLE", "Available"),
                        ("RESERVED", "Reserved"),
                        ("IN_USE", "In Use"),
                        ("DEPLOYED", "Deployed to Field"),
                        ("MAINTENANCE", "Under Maintenance"),
                        ("REPAIR", "Under Repair"),
                        ("REFURBISHMENT", "In Refurbishment"),
                        ("DAMAGED", "Damaged"),
                        ("SCRAP", "Scrapped"),
                        ("SOLD", "Sold"),
                        ("LOST", "Lost"),
                        ("RETIRED", "Retired"),
                    ],
                    default="RECEIVED", max_length=20,
                )),
                ("acquisition_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("current_value", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("salvage_value", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("depreciation_method", models.CharField(blank=True, max_length=20)),
                ("useful_life_months", models.IntegerField(blank=True, null=True)),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                ("in_service_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("next_service_date", models.DateField(blank=True, null=True)),
                ("disposal_date", models.DateField(blank=True, null=True)),
                ("manufacturer_serial", models.CharField(blank=True, max_length=100)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
                ("next_inspection_date", models.DateField(blank=True, null=True)),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("certification_expiry", models.DateField(blank=True, null=True)),
                ("total_run_hours", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total_cycles", models.IntegerField(default=0)),
                ("total_footage", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("specifications", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="inventory.inventoryitem")),
                ("condition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="inventory.conditiontype")),
                ("quality_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="inventory.qualitystatus")),
                ("current_location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="inventory.inventorylocation")),
                ("warehouse", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="sales.warehouse")),
                ("owner_party", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_assets", to="inventory.party")),
                ("ownership_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="inventory.ownershiptype")),
                ("custodian_party", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="custody_assets", to="inventory.party")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="inventory.materiallot")),
                ("grn", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assets_received", to="inventory.goodsreceiptnote")),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="supplychain.purchaseorder")),
                ("supplier", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assets_supplied", to="supplychain.supplier")),
                ("parent_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="child_assets", to="inventory.asset")),
                ("current_work_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deployed_assets", to="workorders.workorder")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "assets",
                "ordering": ["-created_at"],
            },
        ),

        # AssetMovement
        migrations.CreateModel(
            name="AssetMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("movement_number", models.CharField(max_length=50)),
                ("movement_date", models.DateTimeField()),
                ("movement_type", models.CharField(
                    choices=[
                        ("RECEIPT", "Initial Receipt"),
                        ("TRANSFER", "Location Transfer"),
                        ("DEPLOY", "Deploy to Job"),
                        ("RETURN", "Return from Job"),
                        ("STATUS", "Status Change"),
                        ("MAINT_IN", "Sent to Maintenance"),
                        ("MAINT_OUT", "Returned from Maintenance"),
                        ("CONDITION", "Condition Change"),
                        ("OWNER", "Ownership Transfer"),
                        ("DISPOSAL", "Disposed/Scrapped"),
                        ("ADJUST", "Adjustment/Correction"),
                    ],
                    max_length=20,
                )),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("run_hours", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("cycles", models.IntegerField(default=0)),
                ("footage", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="inventory.asset")),
                ("from_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements_from", to="inventory.inventorylocation")),
                ("to_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements_to", to="inventory.inventorylocation")),
                ("from_condition", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements_from", to="inventory.conditiontype")),
                ("to_condition", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements_to", to="inventory.conditiontype")),
                ("from_party", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements_from", to="inventory.party")),
                ("to_party", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements_to", to="inventory.party")),
                ("work_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements", to="workorders.workorder")),
                ("stock_transfer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements", to="inventory.stocktransfer")),
                ("ledger_entry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements", to="inventory.stockledger")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="asset_movements_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Asset Movement",
                "verbose_name_plural": "Asset Movements",
                "db_table": "asset_movements",
                "ordering": ["-movement_date"],
            },
        ),

        # =====================================================================
        # ADD LEDGER LINE REFERENCES TO STOCKLEDGER
        # =====================================================================
        migrations.AddField(
            model_name="stockledger",
            name="grn_line",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.grnline"),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="issue_line",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.stockissueline"),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="transfer_line",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.stocktransferline"),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="adjustment_line",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="inventory.stockadjustmentline"),
        ),

        # =====================================================================
        # CONSTRAINTS AND INDEXES
        # =====================================================================

        # StockLedger constraints and indexes
        migrations.AddConstraint(
            model_name="stockledger",
            constraint=models.UniqueConstraint(fields=["reference_type", "reference_id"], name="unique_ledger_reference"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["item", "location"], name="stock_ledge_item_id_loc_idx"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["item", "owner_party"], name="stock_ledge_item_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["transaction_date"], name="stock_ledge_txn_date_idx"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["transaction_type"], name="stock_ledge_txn_type_idx"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["reference_type", "reference_id"], name="stock_ledge_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["lot"], name="stock_ledge_lot_idx"),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(fields=["entry_number"], name="stock_ledge_entry_num_idx"),
        ),

        # StockBalance constraints and indexes
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(
                condition=models.Q(lot__isnull=False),
                fields=["item", "location", "lot", "owner_party", "ownership_type", "quality_status", "condition"],
                name="unique_stock_balance_with_lot",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(
                condition=models.Q(lot__isnull=True),
                fields=["item", "location", "owner_party", "ownership_type", "quality_status", "condition"],
                name="unique_stock_balance_without_lot",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(fields=["item"], name="stock_bal_item_idx"),
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(fields=["location"], name="stock_bal_loc_idx"),
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(fields=["item", "location"], name="stock_bal_item_loc_idx"),
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(fields=["owner_party"], name="stock_bal_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(fields=["quality_status"], name="stock_bal_qc_idx"),
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(fields=["qty_on_hand"], name="stock_bal_qty_idx"),
        ),

        # Document indexes
        migrations.AddIndex(
            model_name="goodsreceiptnote",
            index=models.Index(fields=["status"], name="grn_status_idx"),
        ),
        migrations.AddIndex(
            model_name="goodsreceiptnote",
            index=models.Index(fields=["receipt_date"], name="grn_date_idx"),
        ),
        migrations.AddIndex(
            model_name="goodsreceiptnote",
            index=models.Index(fields=["supplier"], name="grn_supplier_idx"),
        ),
        migrations.AddIndex(
            model_name="goodsreceiptnote",
            index=models.Index(fields=["grn_number"], name="grn_number_idx"),
        ),
        migrations.AddIndex(
            model_name="stockissue",
            index=models.Index(fields=["status"], name="issue_status_idx"),
        ),
        migrations.AddIndex(
            model_name="stockissue",
            index=models.Index(fields=["issue_date"], name="issue_date_idx"),
        ),
        migrations.AddIndex(
            model_name="stockissue",
            index=models.Index(fields=["issue_number"], name="issue_number_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["status"], name="transfer_status_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["transfer_date"], name="transfer_date_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["transfer_number"], name="transfer_number_idx"),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(fields=["status"], name="adj_status_idx"),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(fields=["adjustment_date"], name="adj_date_idx"),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(fields=["adjustment_number"], name="adj_number_idx"),
        ),

        # Asset indexes
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["serial_number"], name="asset_serial_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["asset_tag"], name="asset_tag_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status"], name="asset_status_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["item"], name="asset_item_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["current_location"], name="asset_location_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["owner_party"], name="asset_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["condition"], name="asset_condition_idx"),
        ),
        migrations.AddIndex(
            model_name="assetmovement",
            index=models.Index(fields=["asset", "movement_date"], name="asset_mvmt_asset_date_idx"),
        ),
        migrations.AddIndex(
            model_name="assetmovement",
            index=models.Index(fields=["movement_type"], name="asset_mvmt_type_idx"),
        ),
        migrations.AddIndex(
            model_name="assetmovement",
            index=models.Index(fields=["movement_number"], name="asset_mvmt_number_idx"),
        ),
    ]
