# Generated by Django 5.1.15 on 2025-12-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_phase5_6_7_8_qc_reservations_bom_cyclecount"),
        ("sales", "0006_week3_field_data_capture"),
        ("supplychain", "0003_sprint6_fixes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemUOMConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="1 from_uom = X to_uom (e.g., 1 ROLL = 100 M)",
                        max_digits=15,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default conversion for this item's packaging unit",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Item UOM Conversion",
                "verbose_name_plural": "Item UOM Conversions",
                "db_table": "item_uom_conversions",
                "ordering": ["item", "from_uom"],
            },
        ),
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_i_trackin_a2b1c3_idx",
        ),
        migrations.RemoveIndex(
            model_name="materiallot",
            name="material_lo_quality_c1e9a2_idx",
        ),
        migrations.RemoveIndex(
            model_name="materiallot",
            name="material_lo_owner_p_8f3b21_idx",
        ),
        migrations.RemoveIndex(
            model_name="materiallot",
            name="material_lo_ownersh_d4a5f1_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_serial__240171_idx",
            old_name="asset_serial_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_asset_t_3d9023_idx",
            old_name="asset_tag_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_status_326766_idx",
            old_name="asset_status_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_item_id_9dc571_idx",
            old_name="asset_item_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_current_57017e_idx",
            old_name="asset_location_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_owner_p_7e9df9_idx",
            old_name="asset_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_conditi_87561e_idx",
            old_name="asset_condition_idx",
        ),
        migrations.RenameIndex(
            model_name="assetmovement",
            new_name="asset_movem_asset_i_5efb1d_idx",
            old_name="asset_mvmt_asset_date_idx",
        ),
        migrations.RenameIndex(
            model_name="assetmovement",
            new_name="asset_movem_movemen_a59465_idx",
            old_name="asset_mvmt_type_idx",
        ),
        migrations.RenameIndex(
            model_name="assetmovement",
            new_name="asset_movem_movemen_c68d05_idx",
            old_name="asset_mvmt_number_idx",
        ),
        migrations.RenameIndex(
            model_name="billofmaterial",
            new_name="bill_of_mat_parent__b00303_idx",
            old_name="bom_parent_idx",
        ),
        migrations.RenameIndex(
            model_name="billofmaterial",
            new_name="bill_of_mat_status_f7d882_idx",
            old_name="bom_status_idx",
        ),
        migrations.RenameIndex(
            model_name="billofmaterial",
            new_name="bill_of_mat_bom_cod_e90210_idx",
            old_name="bom_code_idx",
        ),
        migrations.RenameIndex(
            model_name="bomline",
            new_name="inventory_b_compone_3536e8_idx",
            old_name="bomline_comp_idx",
        ),
        migrations.RenameIndex(
            model_name="cyclecountline",
            new_name="cycle_count_item_id_aa5e9a_idx",
            old_name="ccline_item_idx",
        ),
        migrations.RenameIndex(
            model_name="cyclecountline",
            new_name="cycle_count_count_s_dad342_idx",
            old_name="ccline_status_idx",
        ),
        migrations.RenameIndex(
            model_name="cyclecountplan",
            new_name="cycle_count_status_f579b6_idx",
            old_name="ccplan_status_idx",
        ),
        migrations.RenameIndex(
            model_name="cyclecountplan",
            new_name="cycle_count_warehou_dc8823_idx",
            old_name="ccplan_wh_idx",
        ),
        migrations.RenameIndex(
            model_name="cyclecountsession",
            new_name="cycle_count_status_d51dd3_idx",
            old_name="ccsess_status_idx",
        ),
        migrations.RenameIndex(
            model_name="cyclecountsession",
            new_name="cycle_count_session_3a8c73_idx",
            old_name="ccsess_date_idx",
        ),
        migrations.RenameIndex(
            model_name="cyclecountsession",
            new_name="cycle_count_warehou_870281_idx",
            old_name="ccsess_wh_idx",
        ),
        migrations.RenameIndex(
            model_name="goodsreceiptnote",
            new_name="goods_recei_status_81b329_idx",
            old_name="grn_status_idx",
        ),
        migrations.RenameIndex(
            model_name="goodsreceiptnote",
            new_name="goods_recei_receipt_754f4a_idx",
            old_name="grn_date_idx",
        ),
        migrations.RenameIndex(
            model_name="goodsreceiptnote",
            new_name="goods_recei_supplie_5f367c_idx",
            old_name="grn_supplier_idx",
        ),
        migrations.RenameIndex(
            model_name="goodsreceiptnote",
            new_name="goods_recei_grn_num_ee0ca1_idx",
            old_name="grn_number_idx",
        ),
        migrations.RenameIndex(
            model_name="qualitystatuschange",
            new_name="quality_sta_from_st_5043b0_idx",
            old_name="qsc_status_idx",
        ),
        migrations.RenameIndex(
            model_name="qualitystatuschange",
            new_name="quality_sta_change__755078_idx",
            old_name="qsc_date_idx",
        ),
        migrations.RenameIndex(
            model_name="qualitystatuschange",
            new_name="quality_sta_lot_id_98326e_idx",
            old_name="qsc_lot_idx",
        ),
        migrations.RenameIndex(
            model_name="qualitystatuschange",
            new_name="quality_sta_asset_i_e63f06_idx",
            old_name="qsc_asset_idx",
        ),
        migrations.RenameIndex(
            model_name="stockadjustment",
            new_name="stock_adjus_status_c4358c_idx",
            old_name="adj_status_idx",
        ),
        migrations.RenameIndex(
            model_name="stockadjustment",
            new_name="stock_adjus_adjustm_566336_idx",
            old_name="adj_date_idx",
        ),
        migrations.RenameIndex(
            model_name="stockadjustment",
            new_name="stock_adjus_adjustm_f226f7_idx",
            old_name="adj_number_idx",
        ),
        migrations.RenameIndex(
            model_name="stockbalance",
            new_name="stock_balan_item_id_b1b303_idx",
            old_name="stock_bal_item_idx",
        ),
        migrations.RenameIndex(
            model_name="stockbalance",
            new_name="stock_balan_locatio_271448_idx",
            old_name="stock_bal_loc_idx",
        ),
        migrations.RenameIndex(
            model_name="stockbalance",
            new_name="stock_balan_item_id_600053_idx",
            old_name="stock_bal_item_loc_idx",
        ),
        migrations.RenameIndex(
            model_name="stockbalance",
            new_name="stock_balan_owner_p_4588ea_idx",
            old_name="stock_bal_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="stockbalance",
            new_name="stock_balan_quality_9d1b2e_idx",
            old_name="stock_bal_qc_idx",
        ),
        migrations.RenameIndex(
            model_name="stockbalance",
            new_name="stock_balan_qty_on__77ba29_idx",
            old_name="stock_bal_qty_idx",
        ),
        migrations.RenameIndex(
            model_name="stockissue",
            new_name="stock_issue_status_8a1e4c_idx",
            old_name="issue_status_idx",
        ),
        migrations.RenameIndex(
            model_name="stockissue",
            new_name="stock_issue_issue_d_46e911_idx",
            old_name="issue_date_idx",
        ),
        migrations.RenameIndex(
            model_name="stockissue",
            new_name="stock_issue_issue_n_d9c3b2_idx",
            old_name="issue_number_idx",
        ),
        migrations.RenameIndex(
            model_name="stockledger",
            new_name="stock_ledge_item_id_c5ba0e_idx",
            old_name="stock_ledge_item_id_loc_idx",
        ),
        migrations.RenameIndex(
            model_name="stockledger",
            new_name="stock_ledge_item_id_dc50f8_idx",
            old_name="stock_ledge_item_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="stockledger",
            new_name="stock_ledge_transac_7200bc_idx",
            old_name="stock_ledge_txn_date_idx",
        ),
        migrations.RenameIndex(
            model_name="stockledger",
            new_name="stock_ledge_transac_5bd022_idx",
            old_name="stock_ledge_txn_type_idx",
        ),
        migrations.RenameIndex(
            model_name="stockledger",
            new_name="stock_ledge_referen_f43b64_idx",
            old_name="stock_ledge_ref_idx",
        ),
        migrations.RenameIndex(
            model_name="stockledger",
            new_name="stock_ledge_lot_id_c8a8da_idx",
            old_name="stock_ledge_lot_idx",
        ),
        migrations.RenameIndex(
            model_name="stockledger",
            new_name="stock_ledge_entry_n_631a35_idx",
            old_name="stock_ledge_entry_num_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="stock_reser_status_be06ad_idx",
            old_name="res_status_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="stock_reser_item_id_991bc6_idx",
            old_name="res_item_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="stock_reser_work_or_4ad1a1_idx",
            old_name="res_wo_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="stock_reser_require_f220ff_idx",
            old_name="res_req_date_idx",
        ),
        migrations.RenameIndex(
            model_name="stocktransfer",
            new_name="stock_trans_status_332e43_idx",
            old_name="transfer_status_idx",
        ),
        migrations.RenameIndex(
            model_name="stocktransfer",
            new_name="stock_trans_transfe_204c6a_idx",
            old_name="transfer_date_idx",
        ),
        migrations.RenameIndex(
            model_name="stocktransfer",
            new_name="stock_trans_transfe_2376ec_idx",
            old_name="transfer_number_idx",
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="is_packaging",
            field=models.BooleanField(
                default=False,
                help_text="Is this a packaging unit with variable conversion per item? (ROLL, CARTON, DRUM)",
            ),
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="is_si_base",
            field=models.BooleanField(
                default=False,
                help_text="Is this an SI standard base unit? (M, KG, L, EA)",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_tag",
            field=models.CharField(
                blank=True,
                help_text="Internal asset tag (optional)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="current_location",
            field=models.ForeignKey(
                help_text="Current physical location",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="custodian_party",
            field=models.ForeignKey(
                blank=True,
                help_text="Who currently has custody (if different from owner)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="custody_assets",
                to="inventory.party",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="depreciation_method",
            field=models.CharField(
                blank=True,
                help_text="SL=Straight Line, DD=Declining Balance",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="item",
            field=models.ForeignKey(
                help_text="Item template defining this asset type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Source lot (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="inventory.materiallot",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="manufacturer_serial",
            field=models.CharField(
                blank=True,
                help_text="Manufacturer's serial number (if different)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="owner_party",
            field=models.ForeignKey(
                help_text="Who owns this asset",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_assets",
                to="inventory.party",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="parent_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent asset if this is a component",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_assets",
                to="inventory.asset",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="serial_number",
            field=models.CharField(
                help_text="Unique serial number", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="specifications",
            field=models.JSONField(
                blank=True, help_text="Asset-specific specifications", null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="total_cycles",
            field=models.IntegerField(default=0, help_text="Total operational cycles"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="total_footage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total footage drilled (for bits)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="total_run_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total operational hours",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="assetmovement",
            name="run_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Run hours at this movement",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterial",
            name="base_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                help_text="Quantity produced by this BOM",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterial",
            name="bom_code",
            field=models.CharField(
                help_text="Unique BOM identifier", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterial",
            name="default_for_wo_type",
            field=models.CharField(
                blank=True,
                help_text="Default BOM for this work order type",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterial",
            name="material_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total material cost (sum of components)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterial",
            name="parent_item",
            field=models.ForeignKey(
                help_text="The item being assembled/built",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boms_as_parent",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterial",
            name="version",
            field=models.CharField(
                default="1.0", help_text="BOM version", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="component_item",
            field=models.ForeignKey(
                help_text="Component/material required",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bom_usages",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="extended_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="quantity_per * unit_cost * (1 + scrap_percent)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="is_optional",
            field=models.BooleanField(default=False, help_text="Optional component"),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="operation_sequence",
            field=models.IntegerField(
                blank=True, help_text="Operation where component is consumed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="quantity_per",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Quantity per base_quantity of parent",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="reference_designator",
            field=models.CharField(
                blank=True, help_text="Position/reference on assembly", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="scrap_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Expected scrap percentage",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="substitute_group",
            field=models.CharField(
                blank=True, help_text="Group code for substitute items", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountline",
            name="qty_counted",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="First count quantity",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountline",
            name="qty_final",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Final accepted quantity",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountline",
            name="qty_recounted",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Recount quantity (if variance)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountline",
            name="qty_system",
            field=models.DecimalField(
                decimal_places=3,
                help_text="System quantity at time of count",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountline",
            name="qty_variance",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Variance (final - system)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountplan",
            name="auto_adjust_within_tolerance",
            field=models.BooleanField(
                default=False,
                help_text="Automatically create adjustments within tolerance",
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountplan",
            name="count_frequency_a",
            field=models.IntegerField(
                default=30, help_text="Days between counts for A items"
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountplan",
            name="count_frequency_b",
            field=models.IntegerField(
                default=60, help_text="Days between counts for B items"
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountplan",
            name="count_frequency_c",
            field=models.IntegerField(
                default=90, help_text="Days between counts for C items"
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountplan",
            name="tolerance_qty_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Acceptable variance percent",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="cyclecountplan",
            name="tolerance_value",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Acceptable variance value",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="grn_number",
            field=models.CharField(
                help_text="Auto-generated GRN number (e.g., GRN-2024-0001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="owner_party",
            field=models.ForeignKey(
                help_text="Who will own the received goods",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns_received",
                to="inventory.party",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="ownership_type",
            field=models.ForeignKey(
                help_text="Ownership type (OWNED, CONSIGNMENT, CLIENT, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="inventory.ownershiptype",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="posted_date",
            field=models.DateTimeField(
                blank=True, help_text="When GRN was posted to ledger", null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Source PO for purchase receipts",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="supplychain.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="receipt_date",
            field=models.DateField(help_text="Date goods received"),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="receiving_location",
            field=models.ForeignKey(
                help_text="Default receiving location (can be overridden per line)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns_received",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="requires_qc",
            field=models.BooleanField(
                default=True, help_text="Does this receipt require QC inspection?"
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="source_reference",
            field=models.CharField(
                blank=True,
                help_text="External reference (e.g., vendor delivery note number)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="warehouse",
            field=models.ForeignKey(
                help_text="Receiving warehouse",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="sales.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="grnline",
            name="condition",
            field=models.ForeignKey(
                help_text="Condition of goods at receipt",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_lines",
                to="inventory.conditiontype",
            ),
        ),
        migrations.AlterField(
            model_name="grnline",
            name="is_posted",
            field=models.BooleanField(
                default=False, help_text="Has this line been posted to ledger?"
            ),
        ),
        migrations.AlterField(
            model_name="grnline",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Override receiving location (if different from GRN header)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_lines",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AlterField(
            model_name="grnline",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Lot for lot-tracked items",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_lines",
                to="inventory.materiallot",
            ),
        ),
        migrations.AlterField(
            model_name="grnline",
            name="lot_number_received",
            field=models.CharField(
                blank=True,
                help_text="Lot number from supplier (if creating new lot)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="grnline",
            name="qty_expected",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Expected quantity from PO",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="grnline",
            name="qty_received",
            field=models.DecimalField(
                decimal_places=3, help_text="Actual quantity received", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="grnline",
            name="quality_status",
            field=models.ForeignKey(
                help_text="Initial quality status (typically QUARANTINE)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_lines",
                to="inventory.qualitystatus",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="costing_method",
            field=models.CharField(
                choices=[
                    ("AVG", "Weighted Average"),
                    ("FIFO", "First In First Out"),
                    ("STD", "Standard Cost"),
                ],
                default="AVG",
                help_text="Costing method: AVG (default), FIFO, or STD",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="tracking_type",
            field=models.CharField(
                choices=[
                    ("NONE", "No Tracking (quantity only)"),
                    ("LOT", "Lot/Batch Tracking"),
                    ("SERIAL", "Serial Number Tracking"),
                    ("ASSET", "Asset Tracking (serialized + lifecycle)"),
                ],
                default="NONE",
                help_text="How this item is tracked: NONE, LOT, SERIAL, or ASSET",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="qualitystatuschange",
            name="from_status",
            field=models.ForeignKey(
                help_text="Previous quality status",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes_from",
                to="inventory.qualitystatus",
            ),
        ),
        migrations.AlterField(
            model_name="qualitystatuschange",
            name="qty_affected",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Quantity affected (if partial change)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="qualitystatuschange",
            name="reason",
            field=models.TextField(help_text="Reason for status change"),
        ),
        migrations.AlterField(
            model_name="qualitystatuschange",
            name="to_status",
            field=models.ForeignKey(
                help_text="New quality status",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes_to",
                to="inventory.qualitystatus",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustmentline",
            name="qty_adjustment",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Difference (counted - system)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustmentline",
            name="qty_counted",
            field=models.DecimalField(
                decimal_places=3, help_text="Actual counted quantity", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustmentline",
            name="qty_system",
            field=models.DecimalField(
                decimal_places=3,
                help_text="System quantity before adjustment",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="avg_unit_cost",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Average unit cost (total_cost / qty_on_hand)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="last_movement_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Last ledger entry date affecting this balance",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="last_recalc_date",
            field=models.DateTimeField(
                auto_now=True, help_text="When balance was last recalculated"
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for non-lot-tracked items",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_balances",
                to="inventory.materiallot",
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="qty_available",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Available = on_hand - reserved (denormalized for speed)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="qty_on_hand",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Current quantity on hand",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="qty_reserved",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Quantity reserved/allocated",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockbalance",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total value of stock at this balance",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockissue",
            name="default_location",
            field=models.ForeignKey(
                help_text="Default issue location",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_issues",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AlterField(
            model_name="stockissue",
            name="issue_number",
            field=models.CharField(
                help_text="Auto-generated issue number (e.g., ISS-2024-0001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockissue",
            name="issue_to_party",
            field=models.ForeignKey(
                blank=True,
                help_text="Party receiving the goods (e.g., rig)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_issues_received",
                to="inventory.party",
            ),
        ),
        migrations.AlterField(
            model_name="stockissue",
            name="reference",
            field=models.CharField(
                blank=True, help_text="External reference", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="stockissueline",
            name="qty_issued",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Actual quantity issued",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockissueline",
            name="qty_requested",
            field=models.DecimalField(
                decimal_places=3, help_text="Quantity requested", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="condition",
            field=models.ForeignKey(
                help_text="Physical condition at time of transaction",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.conditiontype",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="entry_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this ledger entry was created (immutable)",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="entry_number",
            field=models.CharField(
                help_text="Auto-generated unique entry number (e.g., SL-2024-000001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="is_reversal",
            field=models.BooleanField(
                default=False, help_text="Is this entry a reversal of another entry?"
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="item",
            field=models.ForeignKey(
                help_text="The inventory item affected",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="location",
            field=models.ForeignKey(
                help_text="Location affected by this entry",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Lot reference (required if item.tracking_type in [LOT, SERIAL, ASSET])",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.materiallot",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="owner_party",
            field=models.ForeignKey(
                help_text="Who owns this stock",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.party",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="ownership_type",
            field=models.ForeignKey(
                help_text="Type of ownership (OWNED, CLIENT, CONSIGNMENT, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.ownershiptype",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="qty_delta",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Signed quantity change (+ve = increase, -ve = decrease)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="quality_status",
            field=models.ForeignKey(
                help_text="Quality status at time of transaction",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.qualitystatus",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="reference_id",
            field=models.CharField(
                help_text="Source document ID (e.g., 'GRN-2024-0001-LINE-1')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="reference_type",
            field=models.CharField(
                help_text="Source document type (e.g., 'GRN', 'ISSUE', 'TRANSFER', 'ADJUSTMENT')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="reversed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this entry was reversed (if reversed)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="reverses_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="The entry this reverses (if is_reversal=True)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_by",
                to="inventory.stockledger",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total cost (qty_delta * unit_cost)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Unit cost at time of transaction",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="uom",
            field=models.ForeignKey(
                help_text="Unit of measure (should match item.base_uom)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Reservation expires if not fulfilled by this date",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific location (if location-specific reservation)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific lot (if lot-specific reservation)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="inventory.materiallot",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="priority",
            field=models.IntegerField(default=5, help_text="1=Highest, 10=Lowest"),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="qty_issued",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Quantity already issued against this reservation",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="qty_reserved",
            field=models.DecimalField(
                decimal_places=3, help_text="Quantity reserved", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="stock_balance",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific stock balance (fully dimensioned reservation)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="inventory.stockbalance",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="from_owner",
            field=models.ForeignKey(
                help_text="Original owner",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_from",
                to="inventory.party",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="to_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="New owner (if ownership transfer)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_to",
                to="inventory.party",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="transfer_number",
            field=models.CharField(
                help_text="Auto-generated transfer number", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferline",
            name="to_quality_status",
            field=models.ForeignKey(
                blank=True,
                help_text="New quality status (if changing)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfer_lines_to",
                to="inventory.qualitystatus",
            ),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="base_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Base unit for conversion (for non-packaging units)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_units",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="conversion_factor",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="Multiply by this to convert to base unit (for non-packaging units)",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="itemuomconversion",
            name="from_uom",
            field=models.ForeignKey(
                help_text="Packaging/alternate unit (ROLL, CARTON, DRUM)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item_conversions_from",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="itemuomconversion",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uom_conversions",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="itemuomconversion",
            name="to_uom",
            field=models.ForeignKey(
                help_text="Base unit to convert to (M, KG, L, EA)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item_conversions_to",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemuomconversion",
            unique_together={("item", "from_uom", "to_uom")},
        ),
    ]
