# Generated by Django 5.1.15 on 2025-12-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_add_conditional_rules_to_category_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycategory",
            name="name_template_config",
            field=models.JSONField(
                blank=True,
                help_text='\n        Structured name template with conditional logic. Format:\n        {\n            "parts": [\n                {"type": "attr", "code": "material"},\n                {"type": "text", "value": " Cutter "},\n                {"type": "conditional", "if": {"attr": "grade", "op": "not_empty"}, "then": {"type": "attr", "code": "grade"}}\n            ]\n        }\n        ',
                null=True,
            ),
        ),
    ]
