# Generated by Django 5.1.15 on 2025-12-24 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        ("inventory", "0024_add_item_relationships_and_packaging"),
        ("supplychain", "0003_sprint6_fixes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="has_quantity_variance",
            field=models.BooleanField(
                default=False, help_text="True if any line exceeds tolerance"
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns_posted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="qc_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="qc_completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns_qc_completed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="qc_inspection",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to QC inspection record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns",
                to="compliance.qualitycontrol",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="qc_status",
            field=models.CharField(
                choices=[
                    ("NOT_REQUIRED", "QC Not Required"),
                    ("PENDING", "Pending Inspection"),
                    ("IN_PROGRESS", "Inspection In Progress"),
                    ("PASSED", "QC Passed"),
                    ("FAILED", "QC Failed"),
                    ("PARTIAL", "Partially Passed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="variance_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="variance_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="variance_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns_variance_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor for purchase receipts (preferred over supplier)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="supplychain.vendor",
            ),
        ),
        migrations.AddField(
            model_name="grnline",
            name="line_qc_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("PARTIAL", "Partial Pass"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="grnline",
            name="qc_defects",
            field=models.TextField(
                blank=True, help_text="Description of defects found"
            ),
        ),
        migrations.AddField(
            model_name="grnline",
            name="qc_notes",
            field=models.TextField(blank=True, help_text="QC inspection notes"),
        ),
        migrations.AddField(
            model_name="grnline",
            name="qty_accepted",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Quantity accepted after QC",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="grnline",
            name="qty_rejected",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Quantity rejected during QC",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="grnline",
            name="variance_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Variance from expected quantity (%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="grnline",
            name="variance_type",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("SHORT", "Under Receipt"),
                    ("OVER", "Over Receipt"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ReceiptTolerance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System Default"),
                            ("CATEGORY", "Category"),
                            ("ITEM", "Specific Item"),
                            ("VENDOR", "Vendor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "over_receipt_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Maximum over-receipt allowed (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "under_receipt_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Maximum under-receipt allowed without approval (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "require_qc",
                    models.BooleanField(
                        default=True,
                        help_text="Require QC inspection for items with this tolerance",
                    ),
                ),
                (
                    "auto_close_on_tolerance",
                    models.BooleanField(
                        default=True, help_text="Auto-close PO line if within tolerance"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_tolerances",
                        to="inventory.inventorycategory",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_tolerances",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_tolerances",
                        to="supplychain.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt Tolerance",
                "verbose_name_plural": "Receipt Tolerances",
                "db_table": "receipt_tolerances",
            },
        ),
    ]
