# Generated by Django 5.1.15 on 2025-12-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_allow_blank_variant_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemvariant",
            name="account",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LSTK", "LSTK"),
                    ("CORE_HEADS", "Core Heads"),
                    ("REGIONAL", "Regional"),
                ],
                help_text="Account type for CLIENT ownership variants",
                max_length=20,
            ),
        ),
    ]
