# Generated by Django 5.1.15 on 2026-01-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_add_account_to_itemvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryattribute",
            name="allow_negative",
            field=models.BooleanField(
                default=True, help_text="For NUMBER: Allow negative values?"
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="decimal_places",
            field=models.PositiveSmallIntegerField(
                default=2, help_text="For DECIMAL: Number of decimal places (0-10)"
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="field_help_text",
            field=models.TextField(
                blank=True, help_text="Help text/description shown below the field"
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="is_multiline",
            field=models.BooleanField(
                default=False,
                help_text="For TEXT: Allow multiple lines (textarea vs input)",
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="max_length",
            field=models.PositiveIntegerField(
                blank=True, help_text="For TEXT: Maximum character length", null=True
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="number_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer (whole numbers)"),
                    ("DECIMAL", "Decimal (with decimals)"),
                ],
                default="DECIMAL",
                help_text="For NUMBER: Integer (whole numbers) or Decimal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="placeholder",
            field=models.CharField(
                blank=True,
                help_text="Placeholder/hint text shown in input field",
                max_length=200,
            ),
        ),
    ]
