# Generated by Django 5.1.15 on 2026-01-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_landingcosttype_grnline_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="shape_image_base64",
            field=models.TextField(
                blank=True, help_text="Cutter shape image as base64 data URI", null=True
            ),
        ),
    ]
