# Generated by Django 5.2.8 on 2025-12-05 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentCalibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calibration_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "performed_by",
                    models.CharField(
                        help_text="Calibration service provider", max_length=200
                    ),
                ),
                ("cert_number", models.CharField(blank=True, max_length=100)),
                ("passed", models.BooleanField(default=True)),
                ("results_notes", models.TextField(blank=True)),
                ("standard_used", models.CharField(blank=True, max_length=200)),
                ("reference_equipment", models.CharField(blank=True, max_length=200)),
                (
                    "certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="calibration_certs/"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_calibrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibrations",
                        to="maintenance.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Calibration",
                "verbose_name_plural": "Equipment Calibrations",
                "db_table": "equipment_calibrations",
                "ordering": ["-calibration_date"],
                "indexes": [
                    models.Index(
                        fields=["equipment", "due_date"],
                        name="equipment_c_equipme_c1f88a_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="equipment_c_due_dat_f1ea7a_idx"
                    ),
                ],
            },
        ),
    ]
