# Generated by Django 5.2.8 on 2025-12-06 04:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("days_per_year", models.IntegerField(default=0)),
                ("is_paid", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
                "db_table": "leave_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LEAVE", "On Leave"),
                            ("HOLIDAY", "Holiday"),
                            ("HALF_DAY", "Half Day"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("first_in", models.TimeField(blank=True, null=True)),
                ("last_out", models.TimeField(blank=True, null=True)),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance",
                "ordering": ["-date", "user"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendancePunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "punch_type",
                    models.CharField(
                        choices=[("IN", "Clock In"), ("OUT", "Clock Out")],
                        max_length=10,
                    ),
                ),
                ("punch_time", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punches",
                        to="hr.attendance",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_punches",
                "ordering": ["attendance", "punch_time"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique employee number (auto-generated: EMP-####)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "badge_number",
                    models.CharField(
                        blank=True, help_text="Physical badge/ID number", max_length=50
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="National ID / SSN (encrypted in production)",
                        max_length=50,
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True, help_text="Passport number", max_length=50
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, help_text="Nationality/Citizenship", max_length=100
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Marital status",
                        max_length=20,
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True, help_text="Personal email address", max_length=254
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, help_text="Mobile phone number", max_length=50
                    ),
                ),
                (
                    "home_phone",
                    models.CharField(
                        blank=True, help_text="Home phone number", max_length=50
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, help_text="Home address line 1", max_length=500
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, help_text="Home address line 2", max_length=500
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=100),
                ),
                (
                    "state_province",
                    models.CharField(
                        blank=True, help_text="State or province", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal/ZIP code", max_length=20
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Saudi Arabia", help_text="Country", max_length=100
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-Time"),
                            ("PART_TIME", "Part-Time"),
                            ("CONTRACT", "Contract"),
                            ("TEMPORARY", "Temporary"),
                            ("INTERN", "Intern"),
                            ("SEASONAL", "Seasonal"),
                        ],
                        db_index=True,
                        default="FULL_TIME",
                        help_text="Type of employment",
                        max_length=20,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("TERMINATED", "Terminated"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Current employment status",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField(help_text="Date of hire")),
                (
                    "probation_end_date",
                    models.DateField(
                        blank=True, help_text="End of probation period", null=True
                    ),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of termination (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(blank=True, help_text="Reason for termination"),
                ),
                (
                    "department",
                    models.CharField(
                        db_index=True, help_text="Department", max_length=100
                    ),
                ),
                ("job_title", models.CharField(help_text="Job title", max_length=200)),
                (
                    "job_description",
                    models.TextField(
                        blank=True, help_text="Job description and responsibilities"
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        blank=True,
                        help_text="Primary work location/office",
                        max_length=200,
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("SALARIED", "Salaried"),
                            ("COMMISSION", "Commission"),
                            ("CONTRACT", "Contract/Fixed"),
                        ],
                        default="HOURLY",
                        help_text="How employee is paid",
                        max_length=20,
                    ),
                ),
                (
                    "pay_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hourly rate or annual salary",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="SAR",
                        help_text="Currency for pay rate (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "pay_grade",
                    models.CharField(
                        blank=True, help_text="Pay grade or band", max_length=50
                    ),
                ),
                (
                    "standard_hours_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40.00"),
                        help_text="Standard hours per week",
                        max_digits=5,
                    ),
                ),
                (
                    "work_shift",
                    models.CharField(
                        blank=True,
                        help_text="Standard work shift (e.g., 'Day', 'Night', '8am-5pm')",
                        max_length=50,
                    ),
                ),
                (
                    "annual_leave_days",
                    models.IntegerField(
                        default=21, help_text="Annual leave entitlement (days per year)"
                    ),
                ),
                (
                    "sick_leave_days",
                    models.IntegerField(
                        default=10, help_text="Sick leave entitlement (days per year)"
                    ),
                ),
                (
                    "benefits_enrolled",
                    models.TextField(
                        blank=True,
                        help_text="Benefits enrolled in (health insurance, pension, etc.)",
                    ),
                ),
                (
                    "last_review_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last performance review",
                        null=True,
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, help_text="Date of next scheduled review", null=True
                    ),
                ),
                (
                    "performance_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OUTSTANDING", "Outstanding"),
                            ("EXCEEDS", "Exceeds Expectations"),
                            ("MEETS", "Meets Expectations"),
                            ("NEEDS_IMPROVEMENT", "Needs Improvement"),
                            ("UNSATISFACTORY", "Unsatisfactory"),
                        ],
                        help_text="Most recent performance rating",
                        max_length=20,
                    ),
                ),
                (
                    "background_check_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether background check was completed",
                    ),
                ),
                (
                    "background_check_date",
                    models.DateField(
                        blank=True, help_text="Date of background check", null=True
                    ),
                ),
                (
                    "work_permit_number",
                    models.CharField(
                        blank=True,
                        help_text="Work permit/visa number (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "work_permit_expiry",
                    models.DateField(
                        blank=True, help_text="Work permit expiry date", null=True
                    ),
                ),
                (
                    "is_field_technician",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Is this employee a field service technician?",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about employee"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When employee record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When employee record was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this employee record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct manager/supervisor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="hr.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Related Django User account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
                "ordering": ["employee_number"],
                "permissions": [
                    (
                        "can_view_employee_compensation",
                        "Can view employee compensation",
                    ),
                    ("can_manage_employee_records", "Can manage employee records"),
                    ("can_terminate_employees", "Can terminate employees"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Contact's full name", max_length=200),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("SPOUSE", "Spouse"),
                            ("PARENT", "Parent"),
                            ("CHILD", "Child"),
                            ("SIBLING", "Sibling"),
                            ("FRIEND", "Friend"),
                            ("OTHER_FAMILY", "Other Family Member"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Relationship to employee",
                        max_length=20,
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(help_text="Primary phone number", max_length=50),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True, help_text="Alternate phone number", max_length=50
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email address", max_length=254
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Full address")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary emergency contact?",
                    ),
                ),
                (
                    "priority_order",
                    models.IntegerField(
                        default=1, help_text="Order to contact (1 = first)"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When contact was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When contact was last updated"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee this contact belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "emergency_contacts",
                "ordering": ["employee", "priority_order"],
            },
        ),
        migrations.CreateModel(
            name="DisciplinaryAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_number",
                    models.CharField(
                        help_text="Auto-generated: DA-YYYY-####",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("VERBAL_WARNING", "Verbal Warning"),
                            ("WRITTEN_WARNING", "Written Warning"),
                            ("FINAL_WARNING", "Final Warning"),
                            ("SUSPENSION", "Suspension"),
                            ("DEMOTION", "Demotion"),
                            ("TERMINATION", "Termination"),
                        ],
                        help_text="Type of disciplinary action",
                        max_length=25,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MODERATE", "Moderate"),
                            ("SERIOUS", "Serious"),
                            ("SEVERE", "Severe"),
                        ],
                        default="MINOR",
                        help_text="Severity level",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("ISSUED", "Issued"),
                            ("APPEALED", "Appealed"),
                            ("RESOLVED", "Resolved"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        help_text="Action status",
                        max_length=20,
                    ),
                ),
                ("incident_date", models.DateField(help_text="Date of incident")),
                (
                    "incident_description",
                    models.TextField(help_text="Description of incident"),
                ),
                (
                    "policy_violated",
                    models.TextField(
                        blank=True, help_text="Policies or rules violated"
                    ),
                ),
                (
                    "witnesses",
                    models.TextField(blank=True, help_text="Witnesses to incident"),
                ),
                (
                    "action_taken",
                    models.TextField(help_text="Description of action taken"),
                ),
                (
                    "consequences",
                    models.TextField(blank=True, help_text="Consequences of action"),
                ),
                (
                    "corrective_action_required",
                    models.TextField(
                        blank=True, help_text="Required corrective actions"
                    ),
                ),
                (
                    "corrective_action_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Deadline for corrective action",
                        null=True,
                    ),
                ),
                (
                    "appeal_filed",
                    models.BooleanField(
                        default=False, help_text="Has appeal been filed?"
                    ),
                ),
                (
                    "appeal_date",
                    models.DateField(blank=True, help_text="Date of appeal", null=True),
                ),
                (
                    "appeal_outcome",
                    models.TextField(blank=True, help_text="Outcome of appeal"),
                ),
                (
                    "issued_date",
                    models.DateField(
                        blank=True, help_text="Date action was issued", null=True
                    ),
                ),
                (
                    "acknowledged_by_employee",
                    models.BooleanField(
                        default=False, help_text="Has employee acknowledged?"
                    ),
                ),
                (
                    "acknowledged_date",
                    models.DateField(
                        blank=True, help_text="Date employee acknowledged", null=True
                    ),
                ),
                (
                    "employee_comments",
                    models.TextField(blank=True, help_text="Employee's comments"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Date action expires", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When action was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When action was last updated"
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="Manager who issued action",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_disciplinary_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee receiving action",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disciplinary_actions",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "disciplinary_actions",
                "ordering": ["-incident_date"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(help_text="Name of bank", max_length=200),
                ),
                (
                    "bank_branch",
                    models.CharField(
                        blank=True, help_text="Bank branch", max_length=200
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True, help_text="Bank/SWIFT code", max_length=50
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "Checking Account"),
                            ("SAVINGS", "Savings Account"),
                            ("SALARY", "Salary Account"),
                        ],
                        help_text="Type of account",
                        max_length=20,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Bank account number (should be encrypted in production)",
                        max_length=100,
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(help_text="Name on the account", max_length=200),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        help_text="International Bank Account Number",
                        max_length=50,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary account for salary payments?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this account active?"
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Has this account been verified?"
                    ),
                ),
                (
                    "verified_date",
                    models.DateField(
                        blank=True, help_text="Date account was verified", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When account was added"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When account was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who added this account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee this account belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_bank_accounts",
                "ordering": ["employee", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        help_text="Auto-generated: DOC-YYYY-######",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Employment Contract"),
                            ("ID_DOCUMENT", "ID Document (Passport, National ID)"),
                            ("CERTIFICATE", "Certificate/Diploma"),
                            ("MEDICAL", "Medical Certificate"),
                            ("BACKGROUND_CHECK", "Background Check"),
                            ("PERFORMANCE_REVIEW", "Performance Review"),
                            ("DISCIPLINARY", "Disciplinary Action"),
                            ("TERMINATION", "Termination Letter"),
                            ("OFFER_LETTER", "Offer Letter"),
                            ("RESIGNATION", "Resignation Letter"),
                            ("REFERENCE", "Reference Letter"),
                            ("TAX_FORM", "Tax Form"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of document",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(help_text="Document title", max_length=500)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Document description"),
                ),
                (
                    "file_path",
                    models.CharField(help_text="Path to document file", max_length=500),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=500),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("file_type", models.CharField(help_text="MIME type", max_length=50)),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, help_text="Date document was issued", null=True
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Date document expires", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_SIGNATURE", "Pending Signature"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        help_text="Document status",
                        max_length=20,
                    ),
                ),
                (
                    "requires_employee_signature",
                    models.BooleanField(
                        default=False,
                        help_text="Does this document require employee signature?",
                    ),
                ),
                (
                    "employee_signed_date",
                    models.DateField(
                        blank=True, help_text="Date employee signed", null=True
                    ),
                ),
                (
                    "requires_hr_signature",
                    models.BooleanField(
                        default=False,
                        help_text="Does this document require HR signature?",
                    ),
                ),
                (
                    "hr_signed_date",
                    models.DateField(blank=True, help_text="Date HR signed", null=True),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False, help_text="Is this a confidential document?"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When document was uploaded"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When document was last updated"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
                (
                    "hr_signed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="HR representative who signed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_employee_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_employee_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        help_text="Auto-generated: LEAVE-YYYY-####",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual Leave"),
                            ("SICK", "Sick Leave"),
                            ("EMERGENCY", "Emergency Leave"),
                            ("MATERNITY", "Maternity Leave"),
                            ("PATERNITY", "Paternity Leave"),
                            ("BEREAVEMENT", "Bereavement Leave"),
                            ("UNPAID", "Unpaid Leave"),
                            ("COMPENSATORY", "Compensatory Leave"),
                            ("STUDY", "Study Leave"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of leave",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, help_text="Leave start date"),
                ),
                ("end_date", models.DateField(help_text="Leave end date")),
                (
                    "is_half_day",
                    models.BooleanField(
                        default=False, help_text="Is this a half-day leave?"
                    ),
                ),
                (
                    "total_days",
                    models.DecimalField(
                        decimal_places=2, help_text="Total leave days", max_digits=5
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for leave")),
                (
                    "supporting_document",
                    models.CharField(
                        blank=True,
                        help_text="Path to supporting document",
                        max_length=500,
                    ),
                ),
                (
                    "medical_certificate_required",
                    models.BooleanField(
                        default=False, help_text="Is medical certificate required?"
                    ),
                ),
                (
                    "submitted_date",
                    models.DateField(blank=True, help_text="Date submitted", null=True),
                ),
                (
                    "approved_date",
                    models.DateField(blank=True, help_text="Date approved", null=True),
                ),
                (
                    "approval_comments",
                    models.TextField(blank=True, help_text="Approval comments"),
                ),
                (
                    "rejected_date",
                    models.DateField(blank=True, help_text="Date rejected", null=True),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection"),
                ),
                (
                    "cancelled_date",
                    models.DateField(blank=True, help_text="Date cancelled", null=True),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When request was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When request was last updated"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_employee_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee requesting leave",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_leave_requests",
                        to="hr.employee",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who rejected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_employee_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_leave_requests",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_overtime",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "overtime_requests",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_number",
                    models.CharField(
                        help_text="Auto-generated: PAY-YYYY-##",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Bi-Weekly"),
                            ("SEMIMONTHLY", "Semi-Monthly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="MONTHLY",
                        help_text="Type of payroll period",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PROCESSING", "Processing"),
                            ("CLOSED", "Closed"),
                            ("PAID", "Paid"),
                        ],
                        default="OPEN",
                        help_text="Period status",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Period start date")),
                ("end_date", models.DateField(help_text="Period end date")),
                ("pay_date", models.DateField(help_text="Pay date")),
                (
                    "total_employees",
                    models.IntegerField(
                        default=0, help_text="Total employees in period"
                    ),
                ),
                (
                    "total_gross_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total gross pay",
                        max_digits=15,
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total deductions",
                        max_digits=15,
                    ),
                ),
                (
                    "total_net_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total net pay",
                        max_digits=15,
                    ),
                ),
                (
                    "processed_date",
                    models.DateTimeField(
                        blank=True, help_text="When payroll was processed", null=True
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="When payroll was approved", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When period was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When period was last updated"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approved payroll",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payroll_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Who created period",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who processed payroll",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payroll_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_periods",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_number",
                    models.CharField(
                        help_text="Auto-generated: REV-YYYY-####",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual Review"),
                            ("PROBATION", "Probation Review"),
                            ("MID_YEAR", "Mid-Year Review"),
                            ("PROJECT", "Project Review"),
                            ("PROMOTION", "Promotion Review"),
                        ],
                        help_text="Type of review",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_EMPLOYEE", "Pending Employee Input"),
                            ("PENDING_MANAGER", "Pending Manager Review"),
                            ("PENDING_HR", "Pending HR Approval"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Review status",
                        max_length=25,
                    ),
                ),
                (
                    "review_period_start",
                    models.DateField(help_text="Start of review period"),
                ),
                (
                    "review_period_end",
                    models.DateField(help_text="End of review period"),
                ),
                ("review_date", models.DateField(help_text="Date of review meeting")),
                (
                    "overall_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OUTSTANDING", "Outstanding (5)"),
                            ("EXCEEDS", "Exceeds Expectations (4)"),
                            ("MEETS", "Meets Expectations (3)"),
                            ("NEEDS_IMPROVEMENT", "Needs Improvement (2)"),
                            ("UNSATISFACTORY", "Unsatisfactory (1)"),
                        ],
                        help_text="Overall performance rating",
                        max_length=20,
                    ),
                ),
                (
                    "technical_skills_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                (
                    "communication_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                (
                    "teamwork_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                (
                    "leadership_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                (
                    "initiative_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                (
                    "quality_of_work_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                (
                    "strengths",
                    models.TextField(blank=True, help_text="Employee strengths"),
                ),
                (
                    "areas_for_improvement",
                    models.TextField(blank=True, help_text="Areas for improvement"),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True, help_text="Key achievements during period"
                    ),
                ),
                (
                    "challenges",
                    models.TextField(blank=True, help_text="Challenges faced"),
                ),
                (
                    "employee_self_assessment",
                    models.TextField(
                        blank=True, help_text="Employee's self-assessment"
                    ),
                ),
                (
                    "employee_comments",
                    models.TextField(
                        blank=True, help_text="Employee's comments on review"
                    ),
                ),
                (
                    "employee_acknowledged",
                    models.BooleanField(
                        default=False, help_text="Has employee acknowledged review?"
                    ),
                ),
                (
                    "employee_acknowledged_date",
                    models.DateField(
                        blank=True, help_text="Date employee acknowledged", null=True
                    ),
                ),
                (
                    "development_plan",
                    models.TextField(
                        blank=True, help_text="Career development and improvement plan"
                    ),
                ),
                (
                    "training_recommended",
                    models.TextField(blank=True, help_text="Recommended training"),
                ),
                (
                    "goals_met_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of goals achieved",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "promotion_recommended",
                    models.BooleanField(
                        default=False, help_text="Is promotion recommended?"
                    ),
                ),
                (
                    "salary_increase_recommended",
                    models.BooleanField(
                        default=False, help_text="Is salary increase recommended?"
                    ),
                ),
                (
                    "salary_increase_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Recommended salary increase %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "hr_approved_date",
                    models.DateField(
                        blank=True, help_text="Date HR approved", null=True
                    ),
                ),
                ("hr_comments", models.TextField(blank=True, help_text="HR comments")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When review was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When review was last updated"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee being reviewed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performance_reviews",
                        to="hr.employee",
                    ),
                ),
                (
                    "hr_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="HR approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_performance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="Manager conducting review",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conducted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "performance_reviews",
                "ordering": ["-review_date"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_number",
                    models.CharField(
                        help_text="Auto-generated: GOAL-YYYY-####",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Goal title", max_length=300)),
                (
                    "description",
                    models.TextField(help_text="Detailed goal description"),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal Goal"),
                            ("TEAM", "Team Goal"),
                            ("DEPARTMENTAL", "Departmental Goal"),
                            ("COMPANY", "Company Goal"),
                        ],
                        default="PERSONAL",
                        help_text="Type of goal",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PERFORMANCE", "Performance"),
                            ("DEVELOPMENT", "Development"),
                            ("BEHAVIORAL", "Behavioral"),
                            ("PROJECT", "Project"),
                            ("TECHNICAL", "Technical"),
                        ],
                        default="PERFORMANCE",
                        help_text="Goal category",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="NOT_STARTED",
                        help_text="Current status",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Goal start date")),
                ("target_date", models.DateField(help_text="Target completion date")),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, help_text="Actual completion date", null=True
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "measurement_criteria",
                    models.TextField(
                        blank=True, help_text="How success will be measured"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When goal was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When goal was last updated"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who assigned goal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee this goal belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="hr.employee",
                    ),
                ),
                (
                    "related_performance_review",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related performance review",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="hr.performancereview",
                    ),
                ),
            ],
            options={
                "db_table": "employee_goals",
                "ordering": ["-target_date"],
            },
        ),
        migrations.CreateModel(
            name="ShiftSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("DAY", "Day Shift"),
                            ("EVENING", "Evening Shift"),
                            ("NIGHT", "Night Shift"),
                            ("ROTATING", "Rotating Shift"),
                            ("ON_CALL", "On-Call"),
                            ("SPLIT", "Split Shift"),
                        ],
                        help_text="Type of shift",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="SCHEDULED",
                        help_text="Shift status",
                        max_length=20,
                    ),
                ),
                (
                    "shift_date",
                    models.DateField(db_index=True, help_text="Date of shift"),
                ),
                ("start_time", models.TimeField(help_text="Scheduled start time")),
                ("end_time", models.TimeField(help_text="Scheduled end time")),
                (
                    "break_duration_minutes",
                    models.IntegerField(
                        default=0, help_text="Total break time in minutes"
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        blank=True, help_text="Work location", max_length=200
                    ),
                ),
                (
                    "actual_start_time",
                    models.TimeField(
                        blank=True, help_text="Actual start time", null=True
                    ),
                ),
                (
                    "actual_end_time",
                    models.TimeField(
                        blank=True, help_text="Actual end time", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When shift was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When shift was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created shift",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee assigned to shift",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_schedules",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "shift_schedules",
                "ordering": ["-shift_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="SkillMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(help_text="Name of skill", max_length=200),
                ),
                (
                    "skill_category",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical"),
                            ("SOFT", "Soft Skills"),
                            ("LEADERSHIP", "Leadership"),
                            ("INDUSTRY", "Industry-Specific"),
                            ("LANGUAGE", "Language"),
                            ("SAFETY", "Safety"),
                            ("OTHER", "Other"),
                        ],
                        default="TECHNICAL",
                        help_text="Skill category",
                        max_length=20,
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="BEGINNER",
                        help_text="Current proficiency level",
                        max_length=20,
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Years of experience with this skill",
                        max_digits=4,
                    ),
                ),
                (
                    "last_used_date",
                    models.DateField(
                        blank=True, help_text="When skill was last used", null=True
                    ),
                ),
                (
                    "certified",
                    models.BooleanField(default=False, help_text="Is skill certified?"),
                ),
                (
                    "certification_details",
                    models.TextField(blank=True, help_text="Certification details"),
                ),
                (
                    "certification_expiry",
                    models.DateField(
                        blank=True, help_text="Certification expiry date", null=True
                    ),
                ),
                (
                    "verified_date",
                    models.DateField(
                        blank=True, help_text="Date skill was verified", null=True
                    ),
                ),
                (
                    "required_for_position",
                    models.BooleanField(
                        default=False,
                        help_text="Is this skill required for employee's position?",
                    ),
                ),
                (
                    "training_recommended",
                    models.BooleanField(
                        default=False,
                        help_text="Is training recommended for this skill?",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When skill was added"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When skill was last updated"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee this skill belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="hr.employee",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who verified this skill",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_skills",
                "ordering": ["employee", "skill_name"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(
                        help_text="Auto-generated: TIME-YYYY-######",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Work"),
                            ("OVERTIME", "Overtime"),
                            ("HOLIDAY", "Holiday Work"),
                            ("SICK", "Sick Leave"),
                            ("VACATION", "Vacation"),
                            ("TRAINING", "Training"),
                            ("OTHER", "Other"),
                        ],
                        default="REGULAR",
                        help_text="Type of time entry",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        help_text="Entry status",
                        max_length=20,
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(db_index=True, help_text="Date of entry"),
                ),
                (
                    "clock_in_time",
                    models.TimeField(blank=True, help_text="Clock in time", null=True),
                ),
                (
                    "clock_out_time",
                    models.TimeField(blank=True, help_text="Clock out time", null=True),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total hours worked",
                        max_digits=5,
                    ),
                ),
                (
                    "break_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Break hours",
                        max_digits=5,
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overtime hours",
                        max_digits=5,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Work location", max_length=200
                    ),
                ),
                (
                    "gps_coordinates",
                    models.CharField(
                        blank=True,
                        help_text="GPS coordinates (lat,long)",
                        max_length=100,
                    ),
                ),
                (
                    "work_description",
                    models.TextField(
                        blank=True, help_text="Description of work performed"
                    ),
                ),
                (
                    "submitted_date",
                    models.DateField(
                        blank=True, help_text="Date submitted for approval", null=True
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(blank=True, help_text="Date approved", null=True),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When entry was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When entry was last updated"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_time_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee this entry belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "time_entries",
                "ordering": ["-entry_date"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_number"], name="employees_employe_68f2c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employment_status", "employment_type"],
                name="employees_employm_061e2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department"], name="employees_departm_ef7a1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["hire_date"], name="employees_hire_da_c03eea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["employee", "is_primary"], name="emergency_c_employe_b5b626_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryaction",
            index=models.Index(
                fields=["employee", "-incident_date"],
                name="disciplinar_employe_a5509a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryaction",
            index=models.Index(fields=["status"], name="disciplinar_status_91ba35_idx"),
        ),
        migrations.AddIndex(
            model_name="disciplinaryaction",
            index=models.Index(
                fields=["action_type"], name="disciplinar_action__8889fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["employee", "is_primary"], name="employee_ba_employe_c8438f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(
                fields=["employee", "document_type"],
                name="employee_do_employe_011309_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(fields=["status"], name="employee_do_status_9abfec_idx"),
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(
                fields=["expiry_date"], name="employee_do_expiry__fa0ced_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "-start_date"],
                name="employee_le_employe_35042b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["status"], name="employee_le_status_cc0d22_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="employee_le_start_d_806e51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="overtimerequest",
            index=models.Index(
                fields=["user", "status"], name="overtime_re_user_id_03e442_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="overtimerequest",
            index=models.Index(fields=["date"], name="overtime_re_date_8c6604_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(fields=["status"], name="payroll_per_status_1a807a_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="payroll_per_start_d_26e3d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["pay_date"], name="payroll_per_pay_dat_a3442c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(
                fields=["employee", "-review_date"],
                name="performance_employe_628c01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(fields=["status"], name="performance_status_a9694d_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["employee", "status"], name="employee_go_employe_0e5193_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["target_date"], name="employee_go_target__f80198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftschedule",
            index=models.Index(
                fields=["employee", "shift_date"], name="shift_sched_employe_bc6412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftschedule",
            index=models.Index(
                fields=["shift_date", "status"], name="shift_sched_shift_d_e01891_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillmatrix",
            index=models.Index(
                fields=["employee", "skill_category"],
                name="employee_sk_employe_580053_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skillmatrix",
            index=models.Index(
                fields=["proficiency_level"], name="employee_sk_profici_94f87b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillmatrix",
            unique_together={("employee", "skill_name")},
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["employee", "-entry_date"],
                name="time_entrie_employe_38705b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["status"], name="time_entrie_status_22f49a_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["entry_date"], name="time_entrie_entry_d_ecf93c_idx"
            ),
        ),
    ]
