# Generated by Django 5.1.15 on 2026-03-27 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_add_field_work_integration"),
        ("organization", "0002_alter_systemsetting_updated_by"),
        ("workorders", "0067_router_step_eval_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessCompetencyMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("NONE", "Not Authorized"),
                            ("TRAINEE", "Trainee (supervised only)"),
                            ("CERTIFIED", "Certified (independent)"),
                            ("TRAINER", "Trainer (can certify others)"),
                        ],
                        db_index=True,
                        default="NONE",
                        help_text="Authorization level for this process",
                        max_length=10,
                    ),
                ),
                (
                    "certified_date",
                    models.DateField(
                        blank=True,
                        help_text="Date employee was certified for this process",
                        null=True,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Certification expiry date (leave blank = no expiry)",
                        null=True,
                    ),
                ),
                (
                    "certificate_reference",
                    models.CharField(
                        blank=True,
                        help_text="Training record or certificate reference number",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes (limitations, conditions, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Process Competency",
                "verbose_name_plural": "Process Competency Matrix",
                "db_table": "process_competency_matrix",
                "ordering": [
                    "employee",
                    "master_process__category",
                    "master_process__sort_order",
                ],
            },
        ),
        migrations.RenameIndex(
            model_name="employee",
            new_name="employees_departm_24ab5f_idx",
            old_name="employees_departm_ef7a1f_idx",
        ),
        migrations.AddField(
            model_name="employee",
            name="department_legacy",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legacy free-text department name (kept for data migration)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                help_text="Formal position — drives competency matrix and permissions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="organization.position",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department (FK to organization.Department)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="organization.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="Job title display name (legacy — use position FK for logic)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="processcompetencymatrix",
            name="certified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor/trainer who certified this employee",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certifications_issued",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="processcompetencymatrix",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competencies_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="processcompetencymatrix",
            name="employee",
            field=models.ForeignKey(
                help_text="Employee this competency belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competencies",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="processcompetencymatrix",
            name="master_process",
            field=models.ForeignKey(
                help_text="The production process this competency covers",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competency_records",
                to="workorders.masterprocess",
            ),
        ),
        migrations.AddIndex(
            model_name="processcompetencymatrix",
            index=models.Index(
                fields=["employee", "level"], name="process_com_employe_9930a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processcompetencymatrix",
            index=models.Index(
                fields=["master_process", "level"],
                name="process_com_master__9c0399_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processcompetencymatrix",
            index=models.Index(
                fields=["expiry_date"], name="process_com_expiry__72b367_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="processcompetencymatrix",
            unique_together={("employee", "master_process")},
        ),
    ]
