# Generated by Django 5.1.15 on 2026-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_add_position_fk_competency_matrix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ON_LEAVE", "On Leave"),
                    ("SUSPENDED", "Suspended"),
                    ("RESIGNED", "Resigned"),
                    ("TERMINATED", "Terminated"),
                    ("RETIRED", "Retired"),
                ],
                db_index=True,
                default="ACTIVE",
                help_text="Current employment status",
                max_length=20,
            ),
        ),
    ]
