# Generated by Django 5.2.8 on 2025-12-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_sprint8_hr_workforce"),
        ("sales", "0006_week3_field_data_capture"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftschedule",
            name="site_visit",
            field=models.ForeignKey(
                blank=True,
                help_text="Related site visit if field work",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_schedules",
                to="sales.sitevisit",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="site_visit",
            field=models.ForeignKey(
                blank=True,
                help_text="Related site visit for field work",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="sales.sitevisit",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Related work order for labor tracking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="workorders.workorder",
            ),
        ),
    ]
