# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("execution", "0002_initial"),
        ("forms_engine", "0001_initial"),
        ("procedures", "0001_initial"),
        ("quality", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointresult",
            name="ncr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkpoint_results",
                to="quality.ncr",
            ),
        ),
        migrations.AddField(
            model_name="formfieldvalue",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="forms_engine.formfield"
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="form_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="forms_engine.formtemplate",
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="submitted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formfieldvalue",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_values",
                to="execution.formsubmission",
            ),
        ),
        migrations.AddField(
            model_name="procedureexecution",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="procedureexecution",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_executions",
                to="procedures.procedurestep",
            ),
        ),
        migrations.AddField(
            model_name="procedureexecution",
            name="procedure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="procedures.procedure",
            ),
        ),
        migrations.AddField(
            model_name="procedureexecution",
            name="started_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="started_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
