# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("execution", "0003_initial"),
        ("procedures", "0001_initial"),
        ("workorders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="procedureexecution",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedure_executions",
                to="workorders.workorder",
            ),
        ),
        migrations.AddField(
            model_name="stepexecution",
            name="executed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executed_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stepexecution",
            name="execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_executions",
                to="execution.procedureexecution",
            ),
        ),
        migrations.AddField(
            model_name="stepexecution",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="step_executions",
                to="procedures.procedurestep",
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="step_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_submissions",
                to="execution.stepexecution",
            ),
        ),
        migrations.AddField(
            model_name="checkpointresult",
            name="step_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint_results",
                to="execution.stepexecution",
            ),
        ),
        migrations.AddField(
            model_name="branchevaluation",
            name="step_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_evaluations",
                to="execution.stepexecution",
            ),
        ),
        migrations.AddIndex(
            model_name="formfieldvalue",
            index=models.Index(
                fields=["submission", "field"], name="form_field__submiss_53f965_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedureexecution",
            index=models.Index(
                fields=["work_order", "status"], name="procedure_e_work_or_20ae2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedureexecution",
            index=models.Index(
                fields=["procedure", "status"], name="procedure_e_procedu_1e3fc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedureexecution",
            index=models.Index(
                fields=["status", "started_at"], name="procedure_e_status_f3bbb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkpointresult",
            index=models.Index(
                fields=["step_execution", "checkpoint"],
                name="checkpoint__step_ex_261ca5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkpointresult",
            index=models.Index(fields=["result"], name="checkpoint__result_443b09_idx"),
        ),
        migrations.AddIndex(
            model_name="branchevaluation",
            index=models.Index(
                fields=["step_execution", "branch"],
                name="branch_eval_step_ex_dd1042_idx",
            ),
        ),
    ]
