# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ncr_number", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField()),
                ("detection_stage", models.CharField(blank=True, max_length=100)),
                ("root_cause", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Under Investigation"),
                            ("PENDING_DISPOSITION", "Pending Disposition"),
                            ("IN_REWORK", "In Rework"),
                            ("PENDING_VERIFICATION", "Pending Verification"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USE_AS_IS", "Use As Is"),
                            ("REWORK", "Rework"),
                            ("REPAIR", "Repair"),
                            ("SCRAP", "Scrap"),
                            ("RETURN_SUPPLIER", "Return to Supplier"),
                            ("DEVIATE", "Deviation/Concession"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("disposition_date", models.DateField(blank=True, null=True)),
                ("disposition_notes", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closure_notes", models.TextField(blank=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NCR",
                "verbose_name_plural": "NCRs",
                "db_table": "ncrs",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="NCRPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="ncr_photos/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "NCR Photo",
                "verbose_name_plural": "NCR Photos",
                "db_table": "ncr_photos",
                "ordering": ["ncr", "-taken_at"],
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_number", models.CharField(max_length=30, unique=True)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("INCOMING", "Incoming Inspection"),
                            ("IN_PROCESS", "In-Process Inspection"),
                            ("FINAL", "Final Inspection"),
                            ("CUSTOMER", "Customer Inspection"),
                            ("THIRD_PARTY", "Third Party Inspection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("CONDITIONAL", "Conditional Pass"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("inspected_at", models.DateTimeField(blank=True, null=True)),
                ("findings", models.TextField(blank=True)),
                ("pass_count", models.IntegerField(default=0)),
                ("fail_count", models.IntegerField(default=0)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection",
                "verbose_name_plural": "Inspections",
                "db_table": "inspections",
                "ordering": ["-scheduled_date"],
            },
        ),
    ]
