# Generated by Django 5.1.15 on 2026-04-03 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0003_alter_inspection_procedure_and_more"),
        ("workorders", "0072_add_reordered_skip_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "source_step",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Die Check (Receiving)", "PDC Evaluation"',
                        max_length=100,
                    ),
                ),
                ("router_step_number", models.IntegerField(blank=True, null=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Auto-generated summary from the process page"
                    ),
                ),
                ("additional_remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open — Pending Review"),
                            ("ACCEPTED", "Accepted — No Action Needed"),
                            ("NCR_CREATED", "NCR Created"),
                            ("REWORK", "Rework Required"),
                            ("TECH_INFORMED", "Technical Team Informed"),
                            ("CUSTOMER_INFORMED", "Customer Informed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=25,
                    ),
                ),
                ("decision_notes", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill_bit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_issues",
                        to="workorders.drillbit",
                    ),
                ),
                (
                    "ncr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_issues",
                        to="quality.ncr",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_quality_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_issues",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "quality_issues",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["work_order", "status"],
                        name="quality_iss_work_or_5faca5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="quality_iss_status_ac36d3_idx"
                    ),
                ],
            },
        ),
    ]
