# Generated by Django 5.1.15 on 2026-04-03 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0004_add_quality_issue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualityissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open — Pending Review"),
                    ("IN_REVIEW", "In Review"),
                    ("ACCEPTED", "Accepted — No Action Needed"),
                    ("NCR_CREATED", "NCR Created"),
                    ("REWORK", "Rework Required"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="QualityIssueAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ACCEPT", "Accepted — No Action Needed"),
                            ("CREATE_NCR", "Create NCR"),
                            ("CREATE_NCR_CAPA", "Create NCR with CAPA"),
                            ("REWORK", "Rework Required"),
                            ("INFORM_TECHNICAL", "Inform Technical Team"),
                            ("INFORM_CUSTOMER", "Inform Customer"),
                            ("TECHNICAL_ACCEPT", "Technical: Accept As-Is"),
                            ("TECHNICAL_REWORK", "Technical: Rework Needed"),
                            ("CLOSE", "Close Issue"),
                            ("NOTE", "Add Note"),
                        ],
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="quality.qualityissue",
                    ),
                ),
                (
                    "ncr",
                    models.ForeignKey(
                        blank=True,
                        help_text="NCR created by this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quality.ncr",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_issue_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quality_issue_actions",
                "ordering": ["performed_at"],
            },
        ),
    ]
