# Generated by Django 5.1.15 on 2026-04-03 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0005_add_quality_issue_action"),
        ("workorders", "0072_add_reordered_skip_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualityissue",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_issues",
                to="workorders.workorder",
            ),
        ),
    ]
