# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("execution", "0004_initial"),
        ("inventory", "0003_initial"),
        ("procedures", "0001_initial"),
        ("quality", "0001_initial"),
        ("workorders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="drill_bit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspections",
                to="workorders.drillbit",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="inspected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_inspections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="procedure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="procedures.procedure",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="procedure_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="execution.procedureexecution",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspections",
                to="workorders.workorder",
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_ncrs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_ncrs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="detected_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detected_ncrs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="disposition_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispositioned_ncrs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="drill_bit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ncrs",
                to="workorders.drillbit",
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="inspection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ncrs",
                to="quality.inspection",
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ncrs",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="investigated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigated_ncrs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="rework_work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_ncrs",
                to="workorders.workorder",
            ),
        ),
        migrations.AddField(
            model_name="ncr",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ncrs",
                to="workorders.workorder",
            ),
        ),
        migrations.AddField(
            model_name="ncrphoto",
            name="ncr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="quality.ncr",
            ),
        ),
        migrations.AddField(
            model_name="ncrphoto",
            name="taken_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["inspection_number"], name="insp_number_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["status"], name="insp_status_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["work_order", "status"], name="insp_wo_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ncr",
            index=models.Index(fields=["ncr_number"], name="ncr_number_idx"),
        ),
        migrations.AddIndex(
            model_name="ncr",
            index=models.Index(fields=["status"], name="ncr_status_idx"),
        ),
        migrations.AddIndex(
            model_name="ncr",
            index=models.Index(fields=["severity"], name="ncr_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="ncr",
            index=models.Index(
                fields=["work_order", "status"], name="ncr_wo_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ncrphoto",
            index=models.Index(fields=["ncr"], name="ncr_photos_ncr_id_023da7_idx"),
        ),
    ]
