# Generated by Django 5.2.8 on 2025-12-05 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0005_alter_branchevaluation_branch_and_more"),
        ("procedures", "0002_alter_procedurestep_responsible_role_and_more"),
        ("quality", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="procedure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspections",
                to="procedures.procedure",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="procedure_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspections",
                to="execution.procedureexecution",
            ),
        ),
        migrations.AlterField(
            model_name="ncrphoto",
            name="taken_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ncr_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
