# Generated by Django 5.2.8 on 2025-12-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DRSSRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drss_number",
                    models.CharField(
                        help_text="ARAMCO DRSS Number", max_length=50, unique=True
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, help_text="Additional ARAMCO ref", max_length=100
                    ),
                ),
                ("requested_date", models.DateField(help_text="Date request was made")),
                ("required_date", models.DateField(help_text="Date bits are needed")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("EVALUATING", "Evaluating"),
                            ("CONFIRMED", "Confirmed"),
                            ("PARTIAL", "Partially Fulfilled"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("customer_notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DRSS Request",
                "verbose_name_plural": "DRSS Requests",
                "db_table": "drss_requests",
                "ordering": ["-requested_date", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="DRSSRequestLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField()),
                ("bit_type", models.CharField(help_text="FC/RC", max_length=20)),
                (
                    "bit_size",
                    models.DecimalField(
                        decimal_places=3, help_text="Size in inches", max_digits=6
                    ),
                ),
                (
                    "design_code",
                    models.CharField(
                        blank=True, help_text="Requested design", max_length=50
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("iadc_code", models.CharField(blank=True, max_length=20)),
                ("formation", models.CharField(blank=True, max_length=100)),
                (
                    "depth_from",
                    models.IntegerField(blank=True, help_text="Feet", null=True),
                ),
                (
                    "depth_to",
                    models.IntegerField(blank=True, help_text="Feet", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Evaluation"),
                            ("EVALUATING", "Under Evaluation"),
                            ("CONFIRMED", "Confirmed"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "fulfillment_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STOCK", "From Stock"),
                            ("TRANSFER", "Transfer from Location"),
                            ("BUILD_NEW", "Build New"),
                            ("RETROFIT", "Retrofit Existing"),
                            ("REWORK", "Rework/Repair"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("fulfillment_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DRSS Request Line",
                "verbose_name_plural": "DRSS Request Lines",
                "db_table": "drss_request_lines",
                "ordering": ["drss_request", "line_number"],
            },
        ),
    ]
