# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drss", "0001_initial"),
        ("sales", "0001_initial"),
        ("technology", "0001_initial"),
        ("workorders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="drssrequest",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drss_requests",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="drssrequest",
            name="evaluated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluated_drss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="drssrequest",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_drss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="drssrequest",
            name="rig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drss_requests",
                to="sales.rig",
            ),
        ),
        migrations.AddField(
            model_name="drssrequest",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drss_requests",
                to="sales.well",
            ),
        ),
        migrations.AddField(
            model_name="drssrequestline",
            name="design",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drss_lines",
                to="technology.design",
            ),
        ),
        migrations.AddField(
            model_name="drssrequestline",
            name="drss_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="drss.drssrequest",
            ),
        ),
        migrations.AddField(
            model_name="drssrequestline",
            name="sales_order_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drss_lines",
                to="sales.salesorderline",
            ),
        ),
        migrations.AddField(
            model_name="drssrequestline",
            name="source_bit",
            field=models.ForeignKey(
                blank=True,
                help_text="Existing bit for STOCK/TRANSFER/REWORK",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drss_source_lines",
                to="workorders.drillbit",
            ),
        ),
        migrations.AddField(
            model_name="drssrequestline",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drss_lines",
                to="workorders.workorder",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="drssrequestline",
            unique_together={("drss_request", "line_number")},
        ),
    ]
