# Generated by Django 5.1.15 on 2026-02-07 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ERPRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_number",
                    models.CharField(
                        help_text="Route ID in ERP (e.g., ROUTE-0091)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Route name (e.g., FC-R AB With Port Standard)",
                        max_length=200,
                    ),
                ),
                (
                    "item_group",
                    models.CharField(
                        blank=True,
                        help_text="Item group in ERP (e.g., RPR-FC-AR)",
                        max_length=50,
                    ),
                ),
                (
                    "bit_type",
                    models.CharField(
                        choices=[("FC", "Fixed Cutter"), ("RC", "Roller Cone")],
                        default="FC",
                        max_length=5,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("L3", "Level 3"),
                            ("L4", "Level 4"),
                            ("L5", "Level 5"),
                            ("L6", "Level 6"),
                            ("REPAIR", "Repair"),
                            ("RERUN", "Re-Run"),
                            ("INSPECTION", "Inspection Only"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "size_class",
                    models.CharField(
                        blank=True,
                        choices=[("AB", 'AB (< 12")'), ("JUMBO", 'Jumbo (>= 12")')],
                        max_length=10,
                    ),
                ),
                (
                    "has_port",
                    models.BooleanField(
                        blank=True,
                        help_text="True=With Port, False=No Port, Null=N/A",
                        null=True,
                    ),
                ),
                (
                    "has_usr",
                    models.BooleanField(
                        default=False, help_text="Upper Section Replacement"
                    ),
                ),
                (
                    "has_hardfacing",
                    models.BooleanField(
                        default=False, help_text="Hardfacing/Matrix Repair"
                    ),
                ),
                (
                    "has_crush_shear",
                    models.BooleanField(default=False, help_text="Crush & Shear"),
                ),
                (
                    "has_retro",
                    models.BooleanField(default=False, help_text="Retrofit (L6 only)"),
                ),
                (
                    "has_grinding",
                    models.BooleanField(default=False, help_text="Grinding step"),
                ),
                (
                    "is_sealed",
                    models.BooleanField(
                        blank=True, help_text="RC: Sealed/NonSealed", null=True
                    ),
                ),
                (
                    "has_cc",
                    models.BooleanField(
                        blank=True, help_text="RC: With/Without CC", null=True
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approved_by", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ERP Route",
                "verbose_name_plural": "ERP Routes",
                "db_table": "erp_automation_routes",
                "ordering": ["route_number"],
            },
        ),
        migrations.CreateModel(
            name="ERPJobData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_order_number",
                    models.CharField(help_text="ARDT Work Order Number", max_length=50),
                ),
                (
                    "serial_number",
                    models.CharField(help_text="Bit serial number", max_length=50),
                ),
                (
                    "size_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw size from Excel (e.g., '3 3/4\"' or 6.125)",
                        max_length=30,
                    ),
                ),
                (
                    "size_inches",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Parsed numeric size in inches",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "smi_type",
                    models.CharField(
                        blank=True,
                        help_text="HDBS/SMI Type (e.g., GT53s, HD54)",
                        max_length=50,
                    ),
                ),
                (
                    "l5_mat_full",
                    models.CharField(
                        blank=True,
                        help_text="Full LV5 Mat # with suffix (e.g., 1224750M)",
                        max_length=50,
                    ),
                ),
                ("date_received", models.DateField(blank=True, null=True)),
                (
                    "account",
                    models.CharField(
                        help_text="Account/FROM (e.g., LSTK, ARAMCO)", max_length=50
                    ),
                ),
                ("contract_number", models.CharField(blank=True, max_length=50)),
                ("vendor_number", models.CharField(blank=True, max_length=50)),
                (
                    "l3_l4_mat",
                    models.CharField(
                        blank=True, help_text="LV3/LV4 Mat #", max_length=50
                    ),
                ),
                ("evaluated_by", models.CharField(blank=True, max_length=100)),
                ("reviewed_by", models.CharField(blank=True, max_length=100)),
                (
                    "cutter_bom_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cutter BOM with variant breakdown",
                    ),
                ),
                (
                    "modified_cutters_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Modified cutters (cutter swaps)",
                    ),
                ),
                (
                    "l5_mat_original",
                    models.CharField(
                        blank=True,
                        help_text="Original L5 MAT (digits only, M stripped)",
                        max_length=50,
                    ),
                ),
                (
                    "body_material",
                    models.CharField(
                        blank=True,
                        choices=[("SB", "Steel Body"), ("MB", "Matrix Body")],
                        help_text="SB if type starts/ends with 's', else MB",
                        max_length=5,
                    ),
                ),
                (
                    "item_group",
                    models.CharField(
                        blank=True,
                        help_text="ERP Item Group (e.g., RPR-FC-LST)",
                        max_length=30,
                    ),
                ),
                (
                    "size_class",
                    models.CharField(
                        blank=True,
                        help_text='AB (<12") or JUMBO (>=12")',
                        max_length=10,
                    ),
                ),
                (
                    "has_port",
                    models.BooleanField(default=False, help_text='True if size < 4"'),
                ),
                (
                    "has_usr",
                    models.BooleanField(
                        default=False, help_text="Upper Section Replacement (Data E31)"
                    ),
                ),
                (
                    "has_hardfacing",
                    models.BooleanField(
                        default=False,
                        help_text="Hardfacing/Matrix Repair (Eval D36 or Eval-LSTK R34/U34/X34)",
                    ),
                ),
                (
                    "has_crush_shear",
                    models.BooleanField(
                        default=False,
                        help_text="Crush & Shear (type starts/ends with CS)",
                    ),
                ),
                (
                    "is_rerun",
                    models.BooleanField(
                        default=False, help_text="Re-run job (Data L2=1 or L3=1)"
                    ),
                ),
                (
                    "is_inspection_only",
                    models.BooleanField(
                        default=False,
                        help_text="Initial Bit Inspection only (Data L4=1)",
                    ),
                ),
                (
                    "is_scrap",
                    models.BooleanField(default=False, help_text="Scrap (Data L5=1)"),
                ),
                (
                    "route_override",
                    models.BooleanField(
                        default=False,
                        help_text="True if user manually changed the route",
                    ),
                ),
                (
                    "item_number",
                    models.CharField(
                        blank=True,
                        help_text="Generated or ERP-assigned item number",
                        max_length=50,
                    ),
                ),
                (
                    "production_order_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("transfer_order_number", models.CharField(blank=True, max_length=50)),
                (
                    "source_file",
                    models.CharField(
                        blank=True, help_text="Original Excel filename", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready for ERP"),
                            ("SENT", "Sent to ERP"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erp_job_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-selected or manually overridden route",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_data",
                        to="erp_automation.erproute",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP Job Data",
                "verbose_name_plural": "ERP Job Data",
                "db_table": "erp_automation_job_data",
                "ordering": ["-created_at"],
            },
        ),
    ]
