# Generated by Django 5.1.15 on 2026-02-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0002_erproute_erpjobdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="job_data",
            field=models.ForeignKey(
                blank=True,
                help_text="ERPJobData record this execution was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="erp_automation.erpjobdata",
            ),
        ),
    ]
