# Generated by Django 5.1.15 on 2026-02-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0003_add_job_data_fk_to_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordedaction",
            name="locator_strategies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Generated locator strategies [{strategy_type, value, priority}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="recordingsession",
            name="job_data",
            field=models.ForeignKey(
                blank=True,
                help_text="Job data used during recording for copy-paste values",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recording_sessions",
                to="erp_automation.erpjobdata",
            ),
        ),
        migrations.AddField(
            model_name="recordingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("recording", "Recording"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="recording",
                help_text="Current session status",
                max_length=20,
            ),
        ),
    ]
