# Generated by Django 5.1.15 on 2026-02-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0004_recording_status_and_locator_strategies"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordedaction",
            name="element_role",
            field=models.CharField(
                blank=True,
                help_text="ARIA role (e.g., option, menuitem, checkbox, listbox)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="recordedaction",
            name="element_type",
            field=models.CharField(
                blank=True,
                help_text="HTML type attribute (e.g., text, checkbox, radio)",
                max_length=50,
            ),
        ),
    ]
