# Generated by Django 5.1.15 on 2026-02-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0006_add_workflow_chain_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowchainlink",
            name="precondition_selector",
            field=models.TextField(
                blank=True,
                default="",
                help_text="CSS selector, XPath, or text to search for on the page",
            ),
        ),
        migrations.AddField(
            model_name="workflowchainlink",
            name="precondition_timeout_ms",
            field=models.IntegerField(
                default=5000,
                help_text="How long to wait for the precondition check (ms)",
            ),
        ),
        migrations.AddField(
            model_name="workflowchainlink",
            name="precondition_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No check"),
                    ("element_exists", "Element exists (CSS/XPath)"),
                    ("text_contains", "Page contains text"),
                    ("element_count_gt", "Element count > value"),
                ],
                default="",
                help_text="Type of page check before running this link",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="workflowchainlink",
            name="precondition_value",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Expected value (for count checks) or search text",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="workflowchainlink",
            name="skip_if_found",
            field=models.BooleanField(
                default=True,
                help_text="True = skip this link if precondition IS met. False = skip if NOT met.",
            ),
        ),
    ]
