# Generated by Django 5.1.15 on 2026-02-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0007_add_precondition_to_chainlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordedaction",
            name="element_data_testid",
            field=models.CharField(
                blank=True, help_text="data-testid attribute", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="recordedaction",
            name="element_dyn_control_name",
            field=models.CharField(
                blank=True,
                help_text="D365 data-dyn-controlname from ancestor element",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="interaction_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Auto-detect"),
                    ("standard_input", "Standard Input"),
                    ("combobox", "Combobox (Alt+Down)"),
                    ("lookup_button", "Lookup Button (double-click)"),
                    ("custom_dropdown", "Custom Dropdown"),
                    ("segmented_entry", "Segmented Entry"),
                    ("checkbox_toggle", "Checkbox Toggle"),
                    ("dialog_button", "Dialog Button"),
                    ("nav_button", "Navigation Button"),
                    ("tab_header", "Tab Header"),
                ],
                default="auto",
                help_text="D365 element interaction mode (auto-detect, combobox, lookup button, etc.)",
                max_length=30,
            ),
        ),
    ]
