# Generated by Django 5.1.15 on 2026-02-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0008_add_interaction_mode_and_dyn_control_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="check_for_errors",
            field=models.BooleanField(
                default=False, help_text="After this step, check for D365 error dialogs"
            ),
        ),
    ]
