# Generated by Django 5.1.15 on 2026-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0013_remove_workflowstep_repeat_data_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="repeat_data_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Key in row_data containing the list to iterate (e.g., 'BOM_LINES'). Only needed on the first step of the group.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="repeat_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Loop group name (e.g., 'bom_lines'). Consecutive steps with the same group repeat together.",
                max_length=50,
            ),
        ),
    ]
