# Generated by Django 5.1.15 on 2026-02-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0014_workflowstep_repeat_data_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordedaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("click", "Click"),
                    ("fill", "Fill/Type"),
                    ("select", "Select Option"),
                    ("check", "Check/Uncheck"),
                    ("hover", "Hover"),
                    ("scroll", "Scroll Into View"),
                    ("wait", "Wait for Element"),
                    ("wait_time", "Wait (Time)"),
                    ("press_key", "Press Key"),
                    ("screenshot", "Take Screenshot"),
                    ("assert_text", "Assert Text"),
                    ("assert_visible", "Assert Visible"),
                    ("conditional", "Conditional Branch"),
                    ("read_value", "Read Value"),
                    ("goto_url", "Navigate to URL"),
                    ("select_grid_row", "Select Grid Row"),
                    ("type_text", "Type Text (keyboard)"),
                    ("navigate", "Navigate (SPA)"),
                    ("click_dynamic_locator", "Click Dynamic Locator"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("click", "Click"),
                    ("fill", "Fill/Type"),
                    ("select", "Select Option"),
                    ("check", "Check/Uncheck"),
                    ("hover", "Hover"),
                    ("scroll", "Scroll Into View"),
                    ("wait", "Wait for Element"),
                    ("wait_time", "Wait (Time)"),
                    ("press_key", "Press Key"),
                    ("screenshot", "Take Screenshot"),
                    ("assert_text", "Assert Text"),
                    ("assert_visible", "Assert Visible"),
                    ("conditional", "Conditional Branch"),
                    ("read_value", "Read Value"),
                    ("goto_url", "Navigate to URL"),
                    ("select_grid_row", "Select Grid Row"),
                    ("type_text", "Type Text (keyboard)"),
                    ("navigate", "Navigate (SPA)"),
                    ("click_dynamic_locator", "Click Dynamic Locator"),
                ],
                default="click",
                max_length=30,
            ),
        ),
    ]
