# Generated by Django 5.1.15 on 2026-02-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0016_add_right_click_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="erpjobdata",
            name="movement_journal_number",
            field=models.CharField(
                blank=True,
                help_text="Movement Journal number captured from D365",
                max_length=50,
            ),
        ),
    ]
