# Generated by Django 5.1.15 on 2026-03-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0017_add_movement_journal_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="erpjobdata",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Repair price from quotation sheet",
                max_digits=12,
                null=True,
            ),
        ),
    ]
