# Generated by Django 5.1.15 on 2026-03-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0018_add_price_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="skip_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Skip group name. When a COE step with this group fails, all subsequent steps with the same group are skipped.",
                max_length=50,
            ),
        ),
    ]
