# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "dispatch_items",
                "ordering": ["dispatch", "id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved"),
                            ("ISSUED", "Issued"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="RESERVED",
                        max_length=20,
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inventory_reservations",
                "ordering": ["-reserved_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("plate_number", models.CharField(max_length=20)),
                ("make", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, max_length=50)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("capacity", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicles",
            },
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatch_number", models.CharField(max_length=30, unique=True)),
                ("driver_name", models.CharField(blank=True, max_length=100)),
                ("planned_date", models.DateField()),
                ("actual_departure", models.DateTimeField(blank=True, null=True)),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("LOADING", "Loading"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch",
                "verbose_name_plural": "Dispatches",
                "db_table": "dispatches",
                "ordering": ["-planned_date", "dispatch_number"],
            },
        ),
    ]
