# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dispatch", "0001_initial"),
        ("inventory", "0002_initial"),
        ("sales", "0001_initial"),
        ("workorders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatches",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="rig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.rig",
            ),
        ),
        migrations.AddField(
            model_name="dispatchitem",
            name="dispatch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="dispatch.dispatch",
            ),
        ),
        migrations.AddField(
            model_name="dispatchitem",
            name="drill_bit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workorders.drillbit",
            ),
        ),
        migrations.AddField(
            model_name="dispatchitem",
            name="sales_order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sales.salesorderline"
            ),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="reserved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workorders.workorder"
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dispatch.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["status", "vehicle"], name="dispatches_status_5225a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["planned_date"], name="dispatches_planned_6b6750_idx"
            ),
        ),
    ]
