# Generated by Django 5.2.8 on 2025-12-05 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0002_initial"),
        ("inventory", "0005_materialconsumption_operation_execution_and_more"),
        ("sales", "0002_initial"),
        (
            "workorders",
            "0003_alter_bitevaluation_rig_alter_bitevaluation_well_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_dispatches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatch_destinations",
                to="sales.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="rig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatches",
                to="sales.rig",
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatches",
                to="dispatch.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchitem",
            name="drill_bit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatch_items",
                to="workorders.drillbit",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchitem",
            name="sales_order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatch_items",
                to="sales.salesorderline",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryreservation",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryreservation",
            name="reserved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryreservation",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_reservations",
                to="workorders.workorder",
            ),
        ),
    ]
