# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("html_input_type", models.CharField(default="text", max_length=30)),
                (
                    "has_options",
                    models.BooleanField(
                        default=False, help_text="Requires dropdown options"
                    ),
                ),
                ("has_validation", models.BooleanField(default=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Field Type",
                "verbose_name_plural": "Field Types",
                "db_table": "field_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FormSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("sequence", models.IntegerField(default=0)),
                ("is_collapsible", models.BooleanField(default=False)),
                ("is_collapsed_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Form Section",
                "verbose_name_plural": "Form Sections",
                "db_table": "form_sections",
                "ordering": ["template", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Internal field name", max_length=100),
                ),
                ("label", models.CharField(help_text="Display label", max_length=200)),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                ("help_text", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                ("min_length", models.IntegerField(blank=True, null=True)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("regex_pattern", models.CharField(blank=True, max_length=500)),
                ("validation_message", models.CharField(blank=True, max_length=500)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text='[{"value": "A", "label": "Option A"}, ...]',
                        null=True,
                    ),
                ),
                ("default_value", models.CharField(blank=True, max_length=500)),
                ("sequence", models.IntegerField(default=0)),
                (
                    "width",
                    models.CharField(
                        default="full",
                        help_text="full, half, third, quarter",
                        max_length=20,
                    ),
                ),
                ("is_readonly", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("depends_on_value", models.CharField(blank=True, max_length=200)),
                (
                    "depends_on_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_fields",
                        to="forms_engine.formfield",
                    ),
                ),
                (
                    "field_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forms_engine.fieldtype",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms_engine.formsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Field",
                "verbose_name_plural": "Form Fields",
                "db_table": "form_fields",
                "ordering": ["section", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("OBSOLETE", "Obsolete"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_form_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Template",
                "verbose_name_plural": "Form Templates",
                "db_table": "form_templates",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="formsection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="forms_engine.formtemplate",
            ),
        ),
        migrations.CreateModel(
            name="FormTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "snapshot",
                    models.JSONField(help_text="Full template JSON at this version"),
                ),
                ("change_summary", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="forms_engine.formtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Template Version",
                "verbose_name_plural": "Form Template Versions",
                "db_table": "form_template_versions",
                "ordering": ["template", "-version_number"],
                "unique_together": {("template", "version_number")},
            },
        ),
    ]
