# Generated by Django 5.2.8 on 2025-12-05 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="form_fields",
                to="forms_engine.fieldtype",
            ),
        ),
        migrations.AlterField(
            model_name="formtemplateversion",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_template_version_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
