# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("EXCEL", "Excel (.xlsx)"),
                            ("CSV", "CSV (.csv)"),
                            ("PDF", "PDF (.pdf)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("filters_applied", models.JSONField(blank=True, default=dict)),
                ("record_count", models.IntegerField(default=0)),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Export Log",
                "verbose_name_plural": "Report Export Logs",
                "db_table": "report_export_logs",
                "ordering": ["-exported_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("WORK_ORDER", "Work Order Report"),
                            ("INVENTORY", "Inventory Report"),
                            ("QUALITY", "Quality Report"),
                            ("MAINTENANCE", "Maintenance Report"),
                            ("SUPPLY_CHAIN", "Supply Chain Report"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Share with all users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Report",
                "verbose_name_plural": "Saved Reports",
                "db_table": "saved_reports",
                "ordering": ["-updated_at"],
            },
        ),
    ]
