# Generated by Django 5.2.8 on 2025-12-05 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_rolepermission_permission_and_more"),
        ("inventory", "0005_materialconsumption_operation_execution_and_more"),
        ("maintenance", "0003_alter_equipment_department"),
        ("procedures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedurestep",
            name="responsible_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_steps",
                to="accounts.role",
            ),
        ),
        migrations.AlterField(
            model_name="procedurestep",
            name="step_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedure_steps",
                to="procedures.steptype",
            ),
        ),
        migrations.AlterField(
            model_name="procedureversion",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedure_version_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stepbranch",
            name="then_notify_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_notifications",
                to="accounts.role",
            ),
        ),
        migrations.AlterField(
            model_name="stepcheckpoint",
            name="check_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkpoints",
                to="procedures.checkpointtype",
            ),
        ),
        migrations.AlterField(
            model_name="stepcheckpoint",
            name="failure_notify_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="failure_notification_checkpoints",
                to="accounts.role",
            ),
        ),
        migrations.AlterField(
            model_name="stepinput",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_inputs",
                to="maintenance.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="stepinput",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_inputs",
                to="inventory.inventoryitem",
            ),
        ),
    ]
