# Generated by Django 5.2.8 on 2025-12-05 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_number", models.CharField(max_length=50, unique=True)),
                (
                    "initial_quantity",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("received_date", models.DateField()),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("purchase_order", models.CharField(blank=True, max_length=50)),
                ("vendor_lot_number", models.CharField(blank=True, max_length=50)),
                ("cert_number", models.CharField(blank=True, max_length=100)),
                (
                    "certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="lot_certificates/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("IN_USE", "In Use"),
                            ("CONSUMED", "Consumed"),
                            ("EXPIRED", "Expired"),
                            ("QUARANTINED", "Quarantined"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Material Lot",
                "verbose_name_plural": "Material Lots",
                "db_table": "material_lots",
                "ordering": ["-received_date", "lot_number"],
            },
        ),
        migrations.CreateModel(
            name="MaterialConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_consumed",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "consumed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_consumptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Consumption",
                "verbose_name_plural": "Material Consumptions",
                "db_table": "material_consumptions",
                "ordering": ["-consumed_at"],
            },
        ),
    ]
