# Generated by Django 5.2.8 on 2025-12-05 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_materiallot_materialconsumption"),
        ("supplychain", "0001_initial"),
        ("workorders", "0002_workordercost_drillbit_accounting_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="materialconsumption",
            name="operation_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_consumptions",
                to="workorders.operationexecution",
            ),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_consumptions",
                to="workorders.workorder",
            ),
        ),
        migrations.AddField(
            model_name="materiallot",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_lots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materiallot",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="materiallot",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lots",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="materiallot",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_lots",
                to="supplychain.supplier",
            ),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumptions",
                to="inventory.materiallot",
            ),
        ),
        migrations.AddIndex(
            model_name="materiallot",
            index=models.Index(fields=["status"], name="material_lo_status_65d38e_idx"),
        ),
        migrations.AddIndex(
            model_name="materiallot",
            index=models.Index(
                fields=["expiry_date"], name="material_lo_expiry__ee4d80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materiallot",
            index=models.Index(
                fields=["inventory_item", "status"],
                name="material_lo_invento_c2eb7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(
                fields=["work_order"], name="material_co_work_or_db5825_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialconsumption",
            index=models.Index(fields=["lot"], name="material_co_lot_id_381a6e_idx"),
        ),
    ]
