# Generated by Django 5.1

from django.db import migrations


def create_categories(apps, schema_editor):
    """Seed inventory categories for drill bit manufacturing."""
    InventoryCategory = apps.get_model("inventory", "InventoryCategory")

    # Parent categories
    parent_categories = [
        {"code": "CUTTERS", "name": "Cutters", "description": "PDC cutters and diamond elements"},
        {"code": "MATRIX", "name": "Matrix Materials", "description": "Tungsten carbide and matrix powders"},
        {"code": "BODIES", "name": "Bit Bodies", "description": "Steel and matrix bit bodies"},
        {"code": "STEEL", "name": "Steel Components", "description": "Steel pins, blades, and structural parts"},
        {"code": "NOZZLES", "name": "Nozzles", "description": "Flow control nozzles and jets"},
        {"code": "CONSUMABLES", "name": "Consumables", "description": "Brazing alloys, flux, abrasives"},
        {"code": "TOOLS", "name": "Tools & Equipment", "description": "Manufacturing tools and fixtures"},
        {"code": "SPARE", "name": "Spare Parts", "description": "Machine spare parts and replacements"},
        {"code": "PACKAGING", "name": "Packaging", "description": "Boxes, containers, thread protectors"},
        {"code": "SAFETY", "name": "Safety Equipment", "description": "PPE and safety supplies"},
    ]

    parent_objs = {}
    for cat in parent_categories:
        obj, _ = InventoryCategory.objects.get_or_create(
            code=cat["code"],
            defaults={
                "name": cat["name"],
                "description": cat["description"],
                "is_active": True,
                "parent": None,
            },
        )
        parent_objs[cat["code"]] = obj

    # Child categories
    child_categories = [
        # Cutters
        {"code": "CUT-PDC", "name": "PDC Cutters", "parent": "CUTTERS", "description": "Polycrystalline diamond compact cutters"},
        {"code": "CUT-TSP", "name": "TSP Cutters", "parent": "CUTTERS", "description": "Thermally stable polycrystalline cutters"},
        {"code": "CUT-NAT", "name": "Natural Diamond", "parent": "CUTTERS", "description": "Natural diamond elements"},
        {"code": "CUT-IMP", "name": "Impregnated Diamond", "parent": "CUTTERS", "description": "Impregnated diamond segments"},
        # Matrix Materials
        {"code": "MAT-TC", "name": "Tungsten Carbide", "parent": "MATRIX", "description": "Tungsten carbide powders"},
        {"code": "MAT-NI", "name": "Nickel Powders", "parent": "MATRIX", "description": "Nickel and nickel alloy powders"},
        {"code": "MAT-CU", "name": "Copper Powders", "parent": "MATRIX", "description": "Copper and bronze powders"},
        {"code": "MAT-BIND", "name": "Binders", "parent": "MATRIX", "description": "Matrix binder materials"},
        # Bodies
        {"code": "BOD-BLANK", "name": "Steel Blanks", "parent": "BODIES", "description": "Steel body blanks for machining"},
        {"code": "BOD-MOLD", "name": "Matrix Molds", "parent": "BODIES", "description": "Graphite molds for matrix infiltration"},
        {"code": "BOD-CAST", "name": "Cast Bodies", "parent": "BODIES", "description": "Pre-cast matrix bodies"},
        # Steel Components
        {"code": "STL-PIN", "name": "Pins & Studs", "parent": "STEEL", "description": "Cutter retention pins and studs"},
        {"code": "STL-BLADE", "name": "Blades", "parent": "STEEL", "description": "Steel blade inserts"},
        {"code": "STL-RING", "name": "Rings & Collars", "parent": "STEEL", "description": "Retention rings and collars"},
        # Nozzles
        {"code": "NOZ-STD", "name": "Standard Nozzles", "parent": "NOZZLES", "description": "Standard flow nozzles"},
        {"code": "NOZ-TC", "name": "TC Nozzles", "parent": "NOZZLES", "description": "Tungsten carbide nozzles"},
        {"code": "NOZ-PLUG", "name": "Nozzle Plugs", "parent": "NOZZLES", "description": "Nozzle blanking plugs"},
        # Consumables
        {"code": "CON-BRAZE", "name": "Brazing Alloys", "parent": "CONSUMABLES", "description": "Brazing materials and alloys"},
        {"code": "CON-FLUX", "name": "Flux", "parent": "CONSUMABLES", "description": "Brazing and welding flux"},
        {"code": "CON-ABRAS", "name": "Abrasives", "parent": "CONSUMABLES", "description": "Grinding and polishing abrasives"},
        {"code": "CON-COAT", "name": "Coatings", "parent": "CONSUMABLES", "description": "Surface coatings and paints"},
        {"code": "CON-CHEM", "name": "Chemicals", "parent": "CONSUMABLES", "description": "Cleaning and treatment chemicals"},
        # Tools
        {"code": "TL-CUT", "name": "Cutting Tools", "parent": "TOOLS", "description": "Machining cutting tools"},
        {"code": "TL-GRIND", "name": "Grinding Tools", "parent": "TOOLS", "description": "Grinding wheels and tools"},
        {"code": "TL-MEAS", "name": "Measuring Tools", "parent": "TOOLS", "description": "Gauges and measuring instruments"},
        {"code": "TL-FIX", "name": "Fixtures", "parent": "TOOLS", "description": "Work holding fixtures"},
        # Spare Parts
        {"code": "SP-CNC", "name": "CNC Spares", "parent": "SPARE", "description": "CNC machine spare parts"},
        {"code": "SP-FURN", "name": "Furnace Spares", "parent": "SPARE", "description": "Furnace and oven spare parts"},
        {"code": "SP-PUMP", "name": "Pump Spares", "parent": "SPARE", "description": "Pump and hydraulic spares"},
        # Packaging
        {"code": "PKG-BOX", "name": "Boxes", "parent": "PACKAGING", "description": "Shipping and storage boxes"},
        {"code": "PKG-PROT", "name": "Thread Protectors", "parent": "PACKAGING", "description": "API thread protectors"},
        {"code": "PKG-WRAP", "name": "Wrapping", "parent": "PACKAGING", "description": "Protective wrapping materials"},
    ]

    for cat in child_categories:
        parent = parent_objs.get(cat["parent"])
        InventoryCategory.objects.get_or_create(
            code=cat["code"],
            defaults={
                "name": cat["name"],
                "description": cat["description"],
                "is_active": True,
                "parent": parent,
            },
        )


def reverse_categories(apps, schema_editor):
    """Remove seeded categories (optional - keeps data on reverse)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_materialconsumption_operation_execution_and_more"),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_categories),
    ]
