# Generated by Django 5.1.15 on 2025-12-16 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_seed_categories"),
        ("sales", "0006_week3_field_data_capture"),
        ("supplychain", "0003_sprint6_fixes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Attribute code for templates (e.g., size, material)",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("SELECT", "Select (Dropdown)"),
                            ("BOOLEAN", "Yes/No"),
                            ("DATE", "Date"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measure (mm, kg, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text='Options for SELECT type: ["Option1", "Option2"] or [{"value": "opt1", "label": "Option 1"}]',
                        null=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "is_used_in_name",
                    models.BooleanField(
                        default=False, help_text="Include in auto-generated item name"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_inherited", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Category Attribute",
                "verbose_name_plural": "Category Attributes",
                "db_table": "category_attributes",
                "ordering": ["category", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ItemAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_value", models.CharField(blank=True, max_length=500)),
                (
                    "number_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("date_value", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Item Attribute Value",
                "verbose_name_plural": "Item Attribute Values",
                "db_table": "item_attribute_values",
            },
        ),
        migrations.CreateModel(
            name="ItemVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("RECLAIMED", "Reclaimed"),
                            ("USED", "Used"),
                            ("REFURBISHED", "Refurbished"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("PURCHASED", "Purchased New"),
                            ("RETROFIT", "Retrofit (New Reclaimed)"),
                            ("E_AND_O", "E&O (Excessive & Obsolete)"),
                            ("ARDT_RECLAIMED", "ARDT Reclaimed Used"),
                            ("LSTK_RECLAIMED", "LSTK (Halliburton) Reclaimed"),
                            ("CLIENT_SPECIFIC", "Client Specific"),
                        ],
                        default="PURCHASED",
                        max_length=20,
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "last_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "valuation_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Percentage of base item cost for valuation",
                        max_digits=5,
                    ),
                ),
                (
                    "source_bit_serial",
                    models.CharField(
                        blank=True,
                        help_text="Serial number of source bit (for reclaimed items)",
                        max_length=100,
                    ),
                ),
                (
                    "source_work_order",
                    models.CharField(
                        blank=True,
                        help_text="Work order that produced this reclaimed item",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item Variant",
                "verbose_name_plural": "Item Variants",
                "db_table": "item_variants",
                "ordering": ["base_item", "condition", "source_type"],
            },
        ),
        migrations.CreateModel(
            name="VariantStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "quantity_available",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("lot_number", models.CharField(blank=True, max_length=50)),
                ("serial_number", models.CharField(blank=True, max_length=50)),
                ("last_movement_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Variant Stock",
                "verbose_name_plural": "Variant Stock",
                "db_table": "variant_stock",
            },
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="code_prefix",
            field=models.CharField(
                blank=True,
                help_text="Prefix for auto-generated item codes (e.g., CUT, MAT, NOZ)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("RAW_MATERIAL", "Raw Material"),
                    ("COMPONENT", "Component"),
                    ("CONSUMABLE", "Consumable"),
                    ("TOOL", "Tool"),
                    ("SPARE_PART", "Spare Part"),
                    ("FINISHED_GOOD", "Finished Good"),
                ],
                default="COMPONENT",
                help_text="Default item type for items in this category",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="name_template",
            field=models.CharField(
                blank=True,
                help_text="Template for auto-name: {size}mm {material} {grade} (uses attribute codes)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="next_sequence",
            field=models.IntegerField(
                default=1, help_text="Next sequence number for code generation"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="has_variants",
            field=models.BooleanField(
                default=False, help_text="Item has condition/source variants"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="item_number",
            field=models.CharField(
                blank=True, help_text="Parallel ERP Item No.", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="mat_number",
            field=models.CharField(
                blank=True, help_text="SAP Legacy MAT No.", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="name_manually_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["mat_number"], name="inventory_i_mat_num_b66add_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["item_number"], name="inventory_i_item_nu_fe1e8e_idx"
            ),
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="inventory.inventorycategory",
            ),
        ),
        migrations.AddField(
            model_name="itemattributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="inventory.categoryattribute",
            ),
        ),
        migrations.AddField(
            model_name="itemattributevalue",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_values",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="base_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_variants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_variants",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="variantstock",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_stock_records",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="variantstock",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_records",
                to="inventory.itemvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoryattribute",
            unique_together={("category", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="itemattributevalue",
            unique_together={("item", "attribute")},
        ),
        migrations.AddIndex(
            model_name="itemvariant",
            index=models.Index(
                fields=["condition"], name="item_varian_conditi_21bd97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemvariant",
            index=models.Index(
                fields=["source_type"], name="item_varian_source__2b4f4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemvariant",
            index=models.Index(
                fields=["base_item", "condition"], name="item_varian_base_it_a2b31f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variantstock",
            unique_together={("variant", "location", "lot_number", "serial_number")},
        ),
    ]
