# Generated by Django 5.1.15 on 2025-12-16 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_add_unit_of_measure"),
        ("sales", "0006_week3_field_data_capture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemvariant",
            options={
                "ordering": ["base_item", "ownership", "condition", "acquisition"],
                "verbose_name": "Item Variant",
                "verbose_name_plural": "Item Variants",
            },
        ),
        migrations.RemoveIndex(
            model_name="itemvariant",
            name="item_varian_source__2b4f4f_idx",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="source_type",
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="acquisition",
            field=models.CharField(
                choices=[
                    ("PURCHASED", "Purchased"),
                    ("RECLAIMED", "Reclaimed"),
                    ("CLIENT_PROVIDED", "Client Provided"),
                ],
                default="PURCHASED",
                help_text="How the item was obtained",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="erp_item_no",
            field=models.CharField(
                blank=True, help_text="ERP Item number reference", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="legacy_mat_no",
            field=models.CharField(
                blank=True, help_text="Legacy MAT number from old system", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="ownership",
            field=models.CharField(
                choices=[("ARDT", "ARDT"), ("CLIENT", "Client")],
                default="ARDT",
                help_text="Who owns this variant",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="reclaim_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RETROFIT", "Retrofit (as New)"),
                    ("E_AND_O", "E&O (Excessive & Obsolete)"),
                    ("GROUND", "Ground (Surface Damage)"),
                    ("STANDARD", "Standard Reclaim"),
                ],
                help_text="Category for reclaimed items (determines financial treatment)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itemvariant",
            name="condition",
            field=models.CharField(
                choices=[("NEW", "New"), ("USED", "Used")],
                default="NEW",
                help_text="Physical state: New or Used",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itemvariant",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer (required when ownership is CLIENT)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_variants",
                to="sales.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="itemvariant",
            index=models.Index(
                fields=["acquisition"], name="item_varian_acquisi_9759e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemvariant",
            index=models.Index(
                fields=["ownership"], name="item_varian_ownersh_c439e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemvariant",
            index=models.Index(
                fields=["legacy_mat_no"], name="item_varian_legacy__97127d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemvariant",
            index=models.Index(
                fields=["erp_item_no"], name="item_varian_erp_ite_41b4ac_idx"
            ),
        ),
    ]
