# Generated by Django 5.1.15 on 2025-12-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_normalize_item_variant_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="requires_expiry_tracking",
            field=models.BooleanField(
                default=False, help_text="Track expiry dates for this item"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="shelf_life_days",
            field=models.IntegerField(
                blank=True,
                help_text="Shelf life in days (for perishable/time-sensitive items)",
                null=True,
            ),
        ),
    ]
