# Generated by Django 5.1.15 on 2025-12-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_attribute_alter_categoryattribute_options_and_more"),
        ("sales", "0006_week3_field_data_capture"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique case code (e.g., NEW-PUR, USED-RET)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this variant case", max_length=100
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("NEW", "New"), ("USED", "Used")],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "acquisition",
                    models.CharField(
                        choices=[
                            ("PURCHASED", "Purchased"),
                            ("RECLAIMED", "Reclaimed"),
                            ("MANUFACTURED", "Manufactured"),
                            ("CLIENT_PROVIDED", "Client Provided"),
                        ],
                        default="PURCHASED",
                        max_length=20,
                    ),
                ),
                (
                    "reclaim_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RETROFIT", "Retrofit (as New)"),
                            ("E_AND_O", "E&O (Excessive & Obsolete)"),
                            ("GROUND", "Ground (Surface Damage)"),
                            ("STANDARD", "Standard Reclaim"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[("ARDT", "ARDT"), ("CLIENT", "Client")],
                        default="ARDT",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of when this case applies"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Variant Case",
                "verbose_name_plural": "Variant Cases",
                "db_table": "variant_cases",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.AlterModelOptions(
            name="itemvariant",
            options={
                "ordering": ["base_item", "variant_case"],
                "verbose_name": "Item Variant",
                "verbose_name_plural": "Item Variants",
            },
        ),
        migrations.RemoveIndex(
            model_name="itemvariant",
            name="item_varian_conditi_21bd97_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemvariant",
            name="item_varian_base_it_a2b31f_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemvariant",
            name="item_varian_acquisi_9759e4_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemvariant",
            name="item_varian_ownersh_c439e4_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemvariant",
            name="item_varian_legacy__97127d_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemvariant",
            name="item_varian_erp_ite_41b4ac_idx",
        ),
        migrations.AlterField(
            model_name="itemvariant",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="itemvariant",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_variants",
                to="sales.customer",
            ),
        ),
        migrations.AlterField(
            model_name="itemvariant",
            name="erp_item_no",
            field=models.CharField(
                blank=True, help_text="ERP Item number", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="itemvariant",
            name="legacy_mat_no",
            field=models.CharField(
                blank=True, help_text="Legacy MAT number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="variant_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item_variants",
                to="inventory.variantcase",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemvariant",
            unique_together={("base_item", "variant_case", "customer")},
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="acquisition",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="name",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="ownership",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="reclaim_category",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="source_bit_serial",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="source_work_order",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="valuation_percentage",
        ),
    ]
