# Generated by Django 5.1.15 on 2025-12-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_merge_20251216_2126"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemBitSpec",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bit_spec",
                        serialize=False,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "bit_type",
                    models.CharField(
                        choices=[
                            ("PDC", "PDC (Fixed Cutter)"),
                            ("RC", "Roller Cone"),
                            ("HYBRID", "Hybrid"),
                            ("DIAMOND", "Diamond Impregnated"),
                        ],
                        default="PDC",
                        max_length=20,
                    ),
                ),
                (
                    "iadc_code",
                    models.CharField(
                        blank=True, help_text="IADC classification code", max_length=10
                    ),
                ),
                (
                    "bit_size",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Bit diameter in inches",
                        max_digits=6,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        blank=True, help_text="e.g., API REG, IF", max_length=50
                    ),
                ),
                (
                    "connection_size",
                    models.CharField(
                        blank=True, help_text="e.g., 4-1/2 IF", max_length=20
                    ),
                ),
                ("blade_count", models.IntegerField(blank=True, null=True)),
                ("cutter_count", models.IntegerField(blank=True, null=True)),
                (
                    "cutter_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Primary cutter size mm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("nozzle_count", models.IntegerField(blank=True, null=True)),
                (
                    "tfa_range_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Min TFA sq.in",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "tfa_range_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Max TFA sq.in",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "weight_on_bit_min",
                    models.IntegerField(
                        blank=True, help_text="Min WOB (klbs)", null=True
                    ),
                ),
                (
                    "weight_on_bit_max",
                    models.IntegerField(
                        blank=True, help_text="Max WOB (klbs)", null=True
                    ),
                ),
                ("rpm_min", models.IntegerField(blank=True, null=True)),
                ("rpm_max", models.IntegerField(blank=True, null=True)),
                (
                    "formation_hardness",
                    models.CharField(
                        blank=True,
                        help_text="Soft/Medium/Hard/Very Hard",
                        max_length=50,
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Curve Drilling, Vertical",
                        max_length=100,
                    ),
                ),
                ("gauge_protection", models.CharField(blank=True, max_length=50)),
                (
                    "body_material",
                    models.CharField(
                        blank=True, help_text="Steel/Matrix", max_length=50
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bit Specification",
                "verbose_name_plural": "Bit Specifications",
                "db_table": "item_bit_specs",
            },
        ),
        migrations.CreateModel(
            name="ItemCutterSpec",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cutter_spec",
                        serialize=False,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "cutter_size",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cutter diameter in mm",
                        max_digits=6,
                    ),
                ),
                (
                    "thickness",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Cutter thickness in mm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "diamond_table_thickness",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Diamond table thickness in mm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("PREMIUM", "Premium"),
                            ("STANDARD", "Standard"),
                            ("ECONOMY", "Economy"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "substrate_material",
                    models.CharField(
                        blank=True, help_text="e.g., Tungsten Carbide", max_length=50
                    ),
                ),
                (
                    "chamfer_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No Chamfer"),
                            ("SINGLE", "Single Chamfer"),
                            ("DOUBLE", "Double Chamfer"),
                            ("MULTI", "Multi-Chamfer"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "chamfer_angle",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "chamfer_size",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "braze_temp_min",
                    models.IntegerField(
                        blank=True, help_text="Min braze temp °C", null=True
                    ),
                ),
                (
                    "braze_temp_max",
                    models.IntegerField(
                        blank=True, help_text="Max braze temp °C", null=True
                    ),
                ),
                ("impact_resistance", models.CharField(blank=True, max_length=20)),
                ("abrasion_resistance", models.CharField(blank=True, max_length=20)),
                (
                    "thermal_stability_temp",
                    models.IntegerField(
                        blank=True, help_text="Max thermal stability °C", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cutter Specification",
                "verbose_name_plural": "Cutter Specifications",
                "db_table": "item_cutter_specs",
            },
        ),
        migrations.AlterField(
            model_name="inventorystock",
            name="quantity_on_hand",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Cached - recalculate from ledger",
                max_digits=15,
            ),
        ),
    ]
