# Generated by Django 5.1.15 on 2025-12-19 - Phases 5-8: QC Gates, Reservations, BOM, Cycle Count

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Combined migration for Phases 5, 6, 7, and 8:

    Phase 5: QC Gates
    - QualityStatusChange: Tracks all QC status transitions

    Phase 6: Stock Reservations
    - StockReservation: Allocates stock to demand sources

    Phase 7: Bill of Materials
    - BillOfMaterial: Component structure for assemblies
    - BOMLine: Individual components in a BOM

    Phase 8: Cycle Count & Physical Inventory
    - CycleCountPlan: Counting strategy and schedule
    - CycleCountSession: Individual counting session
    - CycleCountLine: Items to count in a session
    """

    dependencies = [
        ("inventory", "0017_phase2_3_4_ledger_docs_assets"),
        ("sales", "0006_week3_field_data_capture"),
        ("workorders", "0006_bittype_phase2_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # =====================================================================
        # PHASE 5: QC GATES
        # =====================================================================
        migrations.CreateModel(
            name="QualityStatusChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("change_number", models.CharField(max_length=50, unique=True)),
                ("change_date", models.DateTimeField(auto_now_add=True)),
                ("change_type", models.CharField(
                    choices=[
                        ("RECEIPT", "Initial Receipt"),
                        ("INSPECTION", "Inspection Result"),
                        ("REWORK", "After Rework"),
                        ("RETEST", "Re-test/Re-inspection"),
                        ("RELEASE", "Manual Release"),
                        ("BLOCK", "Manual Block"),
                        ("EXPIRY", "Expired/Time-based"),
                        ("CORRECTION", "Data Correction"),
                    ],
                    max_length=20,
                )),
                ("qty_affected", models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ("inspection_date", models.DateTimeField(blank=True, null=True)),
                ("inspection_notes", models.TextField(blank=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("from_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="changes_from", to="inventory.qualitystatus")),
                ("to_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="changes_to", to="inventory.qualitystatus")),
                ("stock_balance", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="qc_changes", to="inventory.stockbalance")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="qc_changes", to="inventory.materiallot")),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="qc_changes", to="inventory.asset")),
                ("inspector", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="inspections_performed", to=settings.AUTH_USER_MODEL)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="qc_approvals", to=settings.AUTH_USER_MODEL)),
                ("grn", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="qc_changes", to="inventory.goodsreceiptnote")),
                ("work_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="qc_changes", to="workorders.workorder")),
                ("ledger_entry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="qc_changes", to="inventory.stockledger")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="qc_changes_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Quality Status Change",
                "verbose_name_plural": "Quality Status Changes",
                "db_table": "quality_status_changes",
                "ordering": ["-change_date"],
            },
        ),

        # =====================================================================
        # PHASE 6: STOCK RESERVATIONS
        # =====================================================================
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reservation_number", models.CharField(max_length=50, unique=True)),
                ("reservation_type", models.CharField(
                    choices=[
                        ("WO", "Work Order"),
                        ("SO", "Sales Order"),
                        ("TRANSFER", "Transfer Request"),
                        ("HOLD", "Customer Hold"),
                        ("PROJECT", "Project Allocation"),
                        ("OTHER", "Other"),
                    ],
                    max_length=20,
                )),
                ("status", models.CharField(
                    choices=[
                        ("PENDING", "Pending"),
                        ("CONFIRMED", "Confirmed"),
                        ("PARTIAL", "Partially Issued"),
                        ("ISSUED", "Fully Issued"),
                        ("CANCELLED", "Cancelled"),
                        ("EXPIRED", "Expired"),
                    ],
                    default="PENDING",
                    max_length=20,
                )),
                ("qty_reserved", models.DecimalField(decimal_places=3, max_digits=15)),
                ("qty_issued", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("required_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("priority", models.IntegerField(default=5)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reservation_date", models.DateTimeField(auto_now_add=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="inventory.inventoryitem")),
                ("uom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="inventory.unitofmeasure")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="inventory.inventorylocation")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="inventory.materiallot")),
                ("stock_balance", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="inventory.stockbalance")),
                ("reserved_for_party", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reservations_for", to="inventory.party")),
                ("work_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="workorders.workorder")),
                ("sales_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="sales.salesorder")),
                ("transfer_request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="inventory.stocktransfer")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reservations_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Stock Reservation",
                "verbose_name_plural": "Stock Reservations",
                "db_table": "stock_reservations",
                "ordering": ["priority", "required_date", "-reservation_date"],
            },
        ),

        # =====================================================================
        # PHASE 7: BILL OF MATERIALS
        # =====================================================================
        migrations.CreateModel(
            name="BillOfMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bom_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("bom_type", models.CharField(
                    choices=[
                        ("STD", "Standard BOM"),
                        ("PHANTOM", "Phantom/Sub-assembly"),
                        ("TEMPLATE", "Template (for estimation)"),
                        ("REPAIR", "Repair BOM"),
                    ],
                    default="STD",
                    max_length=20,
                )),
                ("status", models.CharField(
                    choices=[
                        ("DRAFT", "Draft"),
                        ("ACTIVE", "Active"),
                        ("INACTIVE", "Inactive"),
                        ("OBSOLETE", "Obsolete"),
                    ],
                    default="DRAFT",
                    max_length=20,
                )),
                ("base_quantity", models.DecimalField(decimal_places=3, default=1, max_digits=15)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("material_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("labor_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("overhead_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("default_for_wo_type", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parent_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="boms_as_parent", to="inventory.inventoryitem")),
                ("uom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="boms", to="inventory.unitofmeasure")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="boms_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Bill of Material",
                "verbose_name_plural": "Bills of Material",
                "db_table": "bill_of_materials",
                "ordering": ["parent_item", "version"],
            },
        ),
        migrations.CreateModel(
            name="BOMLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.IntegerField()),
                ("component_type", models.CharField(
                    choices=[
                        ("MATERIAL", "Material"),
                        ("CONSUMABLE", "Consumable"),
                        ("TOOL", "Tool (non-consumed)"),
                        ("SUBASM", "Sub-assembly"),
                    ],
                    default="MATERIAL",
                    max_length=20,
                )),
                ("quantity_per", models.DecimalField(decimal_places=6, max_digits=15)),
                ("scrap_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("extended_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("is_optional", models.BooleanField(default=False)),
                ("substitute_group", models.CharField(blank=True, max_length=20)),
                ("reference_designator", models.CharField(blank=True, max_length=50)),
                ("operation_sequence", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("bom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.billofmaterial")),
                ("component_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bom_usages", to="inventory.inventoryitem")),
                ("uom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bom_lines", to="inventory.unitofmeasure")),
            ],
            options={
                "verbose_name": "BOM Line",
                "verbose_name_plural": "BOM Lines",
                "db_table": "inventory_bom_lines",
                "ordering": ["bom", "line_number"],
                "unique_together": {("bom", "line_number")},
            },
        ),

        # =====================================================================
        # PHASE 8: CYCLE COUNT
        # =====================================================================
        migrations.CreateModel(
            name="CycleCountPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("plan_type", models.CharField(
                    choices=[
                        ("ABC", "ABC Classification"),
                        ("LOCATION", "Location Based"),
                        ("RANDOM", "Random Selection"),
                        ("FULL", "Full Physical Inventory"),
                        ("CUSTOM", "Custom Selection"),
                    ],
                    default="ABC",
                    max_length=20,
                )),
                ("status", models.CharField(
                    choices=[
                        ("DRAFT", "Draft"),
                        ("ACTIVE", "Active"),
                        ("PAUSED", "Paused"),
                        ("COMPLETED", "Completed"),
                        ("CANCELLED", "Cancelled"),
                    ],
                    default="DRAFT",
                    max_length=20,
                )),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("count_frequency_a", models.IntegerField(default=30)),
                ("count_frequency_b", models.IntegerField(default=60)),
                ("count_frequency_c", models.IntegerField(default=90)),
                ("tolerance_qty_percent", models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ("tolerance_value", models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ("auto_adjust_within_tolerance", models.BooleanField(default=False)),
                ("require_approval_outside_tolerance", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_plans", to="sales.warehouse")),
                ("include_locations", models.ManyToManyField(blank=True, related_name="cycle_count_plans", to="inventory.inventorylocation")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_plans_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Cycle Count Plan",
                "verbose_name_plural": "Cycle Count Plans",
                "db_table": "cycle_count_plans",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CycleCountSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_number", models.CharField(max_length=50, unique=True)),
                ("session_date", models.DateField()),
                ("status", models.CharField(
                    choices=[
                        ("PENDING", "Pending"),
                        ("IN_PROGRESS", "In Progress"),
                        ("COUNTING", "Counting"),
                        ("REVIEW", "Under Review"),
                        ("APPROVED", "Approved"),
                        ("POSTED", "Posted to Adjustments"),
                        ("CANCELLED", "Cancelled"),
                    ],
                    default="PENDING",
                    max_length=20,
                )),
                ("count_started_at", models.DateTimeField(blank=True, null=True)),
                ("count_completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_items", models.IntegerField(default=0)),
                ("items_counted", models.IntegerField(default=0)),
                ("items_matched", models.IntegerField(default=0)),
                ("items_variance", models.IntegerField(default=0)),
                ("total_variance_value", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sessions", to="inventory.cyclecountplan")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_sessions", to="sales.warehouse")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_sessions", to="inventory.inventorylocation")),
                ("counter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cycle_counts_performed", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cycle_counts_reviewed", to=settings.AUTH_USER_MODEL)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cycle_counts_approved", to=settings.AUTH_USER_MODEL)),
                ("adjustment", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_session", to="inventory.stockadjustment")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_sessions_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Cycle Count Session",
                "verbose_name_plural": "Cycle Count Sessions",
                "db_table": "cycle_count_sessions",
                "ordering": ["-session_date", "-session_number"],
            },
        ),
        migrations.CreateModel(
            name="CycleCountLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.IntegerField()),
                ("qty_system", models.DecimalField(decimal_places=3, max_digits=15)),
                ("qty_counted", models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ("qty_recounted", models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ("qty_final", models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ("qty_variance", models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("variance_value", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("count_status", models.CharField(
                    choices=[
                        ("PENDING", "Pending Count"),
                        ("COUNTED", "Counted"),
                        ("RECOUNTED", "Recounted"),
                        ("VERIFIED", "Verified"),
                        ("VARIANCE", "Variance Found"),
                        ("MATCHED", "Matched"),
                    ],
                    default="PENDING",
                    max_length=20,
                )),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
                ("requires_recount", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.cyclecountsession")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_lines", to="inventory.inventoryitem")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_lines", to="inventory.inventorylocation")),
                ("lot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_lines", to="inventory.materiallot")),
                ("uom", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_lines", to="inventory.unitofmeasure")),
                ("owner_party", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_lines", to="inventory.party")),
                ("ownership_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_lines", to="inventory.ownershiptype")),
                ("condition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_lines", to="inventory.conditiontype")),
                ("quality_status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cycle_count_lines", to="inventory.qualitystatus")),
                ("counted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="items_counted", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Cycle Count Line",
                "verbose_name_plural": "Cycle Count Lines",
                "db_table": "cycle_count_lines",
                "ordering": ["session", "line_number"],
                "unique_together": {("session", "line_number")},
            },
        ),

        # =====================================================================
        # INDEXES
        # =====================================================================
        migrations.AddIndex(
            model_name="qualitystatuschange",
            index=models.Index(fields=["from_status", "to_status"], name="qsc_status_idx"),
        ),
        migrations.AddIndex(
            model_name="qualitystatuschange",
            index=models.Index(fields=["change_date"], name="qsc_date_idx"),
        ),
        migrations.AddIndex(
            model_name="qualitystatuschange",
            index=models.Index(fields=["lot"], name="qsc_lot_idx"),
        ),
        migrations.AddIndex(
            model_name="qualitystatuschange",
            index=models.Index(fields=["asset"], name="qsc_asset_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["status"], name="res_status_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["item"], name="res_item_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["work_order"], name="res_wo_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["required_date"], name="res_req_date_idx"),
        ),
        migrations.AddIndex(
            model_name="billofmaterial",
            index=models.Index(fields=["parent_item"], name="bom_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="billofmaterial",
            index=models.Index(fields=["status"], name="bom_status_idx"),
        ),
        migrations.AddIndex(
            model_name="billofmaterial",
            index=models.Index(fields=["bom_code"], name="bom_code_idx"),
        ),
        migrations.AddIndex(
            model_name="bomline",
            index=models.Index(fields=["component_item"], name="bomline_comp_idx"),
        ),
        migrations.AddIndex(
            model_name="cyclecountplan",
            index=models.Index(fields=["status"], name="ccplan_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cyclecountplan",
            index=models.Index(fields=["warehouse"], name="ccplan_wh_idx"),
        ),
        migrations.AddIndex(
            model_name="cyclecountsession",
            index=models.Index(fields=["status"], name="ccsess_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cyclecountsession",
            index=models.Index(fields=["session_date"], name="ccsess_date_idx"),
        ),
        migrations.AddIndex(
            model_name="cyclecountsession",
            index=models.Index(fields=["warehouse"], name="ccsess_wh_idx"),
        ),
        migrations.AddIndex(
            model_name="cyclecountline",
            index=models.Index(fields=["item"], name="ccline_item_idx"),
        ),
        migrations.AddIndex(
            model_name="cyclecountline",
            index=models.Index(fields=["count_status"], name="ccline_status_idx"),
        ),
    ]
