# Generated by Django 5.1.15 on 2025-12-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_add_uom_conversion_system"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={
                "ordering": ["classification", "name"],
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="classification",
            field=models.CharField(
                choices=[
                    ("PHYS", "Physical Dimensions"),
                    ("TECH", "Technical Specifications"),
                    ("CONN", "Connection & Thread"),
                    ("MATL", "Material & Composition"),
                    ("IADC", "IADC & Drilling Specifications"),
                    ("OPER", "Operational Parameters"),
                    ("IDEN", "Identification & Commercial"),
                    ("QUAL", "Quality & Compliance"),
                    ("STOR", "Storage & Logistics"),
                    ("SAFE", "Safety & PPE"),
                    ("TOOL", "Tools & Equipment"),
                    ("CONS", "Consumables"),
                    ("ELEC", "Electrical Components"),
                    ("FAST", "Fasteners"),
                    ("GEN", "General Attributes"),
                ],
                default="GEN",
                help_text="Attribute classification category",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("decimal", "Decimal"),
                    ("boolean", "Yes/No"),
                    ("date", "Date"),
                    ("select", "Select (Dropdown)"),
                    ("enum", "Enum"),
                ],
                default="text",
                help_text="Suggested data type for this attribute",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Usage notes or guidance for this attribute"
            ),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("QUANTITY", "Quantity (Count)"),
                    ("LENGTH", "Length"),
                    ("WEIGHT", "Weight/Mass"),
                    ("VOLUME", "Volume"),
                    ("AREA", "Area"),
                    ("TIME", "Time"),
                    ("PRESSURE", "Pressure"),
                    ("TEMPERATURE", "Temperature"),
                    ("ROTATIONAL_SPEED", "Rotational Speed"),
                    ("TORQUE", "Torque"),
                    ("POWER", "Power"),
                    ("FORCE", "Force"),
                    ("ENERGY", "Energy"),
                    ("VOLTAGE", "Voltage"),
                    ("CURRENT", "Current"),
                    ("RESISTANCE", "Resistance"),
                    ("FREQUENCY", "Frequency"),
                    ("FLOW_RATE", "Flow Rate"),
                    ("SPEED", "Speed"),
                    ("HARDNESS", "Hardness"),
                    ("STRESS", "Stress/Strength"),
                    ("DENSITY", "Density"),
                    ("VISCOSITY", "Viscosity"),
                    ("RATIO", "Ratio/Percentage"),
                    ("CONCENTRATION", "Concentration"),
                    ("ANGLE", "Angle"),
                    ("THREAD_SPEC", "Thread Specification"),
                    ("WIRE_SPEC", "Wire Specification"),
                    ("SURFACE_FINISH", "Surface Finish"),
                    ("ABRASIVE_SPEC", "Abrasive Specification"),
                    ("PARTICLE_SIZE", "Particle Size"),
                    ("CHEMICAL", "Chemical Property"),
                    ("SOUND", "Sound/Noise"),
                    ("ILLUMINATION", "Illumination"),
                    ("LUMINOUS_FLUX", "Luminous Flux"),
                    ("PACKAGING", "Packaging"),
                    ("OTHER", "Other"),
                ],
                default="QUANTITY",
                max_length=20,
            ),
        ),
    ]
