# Generated by Django 5.1.15 on 2025-12-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_add_attribute_classification_and_expand_unit_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryattribute",
            name="default_value",
            field=models.CharField(
                blank=True,
                help_text="Default value when creating new items",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="categoryattribute",
            name="attribute_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("NUMBER", "Number"),
                    ("BOOLEAN", "Yes/No"),
                    ("DATE", "Date"),
                ],
                default="TEXT",
                help_text="How this attribute is used in this category",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="categoryattribute",
            name="options",
            field=models.JSONField(
                blank=True,
                help_text='Dropdown options: ["Option1", "Option2"]. TEXT with options = dropdown. NUMBER with options = common values.',
                null=True,
            ),
        ),
    ]
