# Generated by Django 5.1.15 on 2025-12-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_add_default_value_to_category_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryattribute",
            name="conditional_rules",
            field=models.JSONField(
                blank=True,
                help_text='\n        Rules to auto-set value based on other attributes. Format:\n        {\n            "rules": [\n                {\n                    "conditions": [\n                        {"attr": "cutter_shape", "op": "in", "value": ["Machete", "Chisel"]},\n                        {"attr": "size", "op": "gt", "value": 16}\n                    ],\n                    "logic": "AND",\n                    "result": "0",\n                    "message": "Non-rotatable due to Machete/Chisel shape"\n                }\n            ],\n            "locked": true\n        }\n        Operators: eq, ne, in, nin, contains, gt, gte, lt, lte, empty, not_empty\n        ',
                null=True,
            ),
        ),
    ]
