# Generated by Django 5.1.15 on 2025-12-24 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_add_name_template_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="estimated_consumption_per_day",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Estimated daily consumption rate for forecasting",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="floor_location",
            field=models.CharField(
                blank=True,
                help_text="Current location on production floor (e.g., Machine A, Workstation 5)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="floor_reorder_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="When floor stock drops below this, trigger replenishment",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="issued_to_floor",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Quantity currently issued to production floor",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="purchase_to_release_factor",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="1 purchase UOM = X release UOM (e.g., 1 CARTON = 100 EA)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="purchase_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit for purchasing (e.g., CARTON, BOX)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_purchase_uom",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="release_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit for issuing/releasing (e.g., EACH, PC)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_release_uom",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.CreateModel(
            name="ItemRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EQUAL", "Equal/Interchangeable"),
                            ("OBSOLETE", "Obsolete (use alternative)"),
                            ("UNAVAILABLE", "Temporarily Unavailable"),
                            ("BLOCKED", "Blocked (use alternative)"),
                            ("USE_UNTIL_CONSUME", "Use Until Consumed"),
                        ],
                        default="EQUAL",
                        help_text="Relationship type/status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the relationship"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_item_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_to",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "to_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_from",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Relationship",
                "verbose_name_plural": "Item Relationships",
                "db_table": "item_relationships",
                "ordering": ["from_item", "status"],
                "unique_together": {("from_item", "to_item")},
            },
        ),
    ]
