# Generated by Django 5.1.15 on 2025-12-24 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_grn_enhancements"),
        ("supplychain", "0003_sprint6_fixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="invoice_match",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the three-way match record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns_matched",
                to="supplychain.invoicematch",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="invoice_match_status",
            field=models.CharField(
                choices=[
                    ("NOT_APPLICABLE", "Not Applicable"),
                    ("PENDING", "Pending Match"),
                    ("MATCHED", "Matched"),
                    ("EXCEPTION", "Exception"),
                    ("RESOLVED", "Exception Resolved"),
                ],
                default="NOT_APPLICABLE",
                help_text="Status of three-way match (PO-GRN-Invoice)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="vendor_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked vendor invoice for three-way matching",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns",
                to="supplychain.vendorinvoice",
            ),
        ),
    ]
