# Generated by Django 5.1.15 on 2025-12-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_grn_three_way_matching"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemvariant",
            name="code",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
