# Generated by Django 5.1.15 on 2026-01-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_add_category_attribute_config_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="block_reason",
            field=models.CharField(
                blank=True, help_text="Reason for blocking", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="blocked_for_counting",
            field=models.BooleanField(
                default=False, help_text="Block from inventory counts"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="blocked_for_issue",
            field=models.BooleanField(
                default=False, help_text="Block from stock issues/sales"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="blocked_for_production",
            field=models.BooleanField(
                default=False, help_text="Block from BOM/manufacturing"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="blocked_for_receipt",
            field=models.BooleanField(
                default=False, help_text="Block from receiving/purchase"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="is_blocked",
            field=models.BooleanField(
                default=False, help_text="Master block - prevents all transactions"
            ),
        ),
    ]
