# Generated by Django 5.1.15 on 2026-01-18 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_add_blocking_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingCostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_allocation",
                    models.CharField(
                        choices=[
                            ("VALUE", "Proportional to Value"),
                            ("QTY", "Proportional to Quantity"),
                            ("WEIGHT", "Proportional to Weight"),
                            ("FIXED", "Fixed per Unit"),
                        ],
                        default="VALUE",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Landing Cost Type",
                "verbose_name_plural": "Landing Cost Types",
                "db_table": "landing_cost_types",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="grnline",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Item variant (for variant-level stock tracking)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_lines",
                to="inventory.itemvariant",
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="default_conversion_factor",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Default qty per package (Buy→Issue conversion)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="default_currency",
            field=models.CharField(
                choices=[("SAR", "SAR (Saudi Riyal)"), ("USD", "USD (US Dollar)")],
                default="SAR",
                help_text="Default currency for items in this category",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="default_min_stock",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Default minimum stock level for items in this category",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="default_purchase_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Default 'Buy As' unit for items in this category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_purchase_defaults",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="default_release_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Default 'Issue As' unit for items in this category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_release_defaults",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="default_reorder_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Default reorder quantity for items in this category",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="notes",
            field=models.TextField(
                blank=True, help_text="General notes or remarks about this item"
            ),
        ),
        migrations.AddField(
            model_name="stockadjustmentline",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Item variant (for variant-level stock tracking)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustment_lines",
                to="inventory.itemvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockissueline",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Item variant (for variant-level stock tracking)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issue_lines",
                to="inventory.itemvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Item variant (if tracking at variant level, e.g., NEW vs USED cutters)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="inventory.itemvariant",
            ),
        ),
        migrations.AddField(
            model_name="stocktransferline",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Item variant (for variant-level stock tracking)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfer_lines",
                to="inventory.itemvariant",
            ),
        ),
        migrations.CreateModel(
            name="LandingCostRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "allocation_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VALUE", "Proportional to Value"),
                            ("QTY", "Proportional to Quantity"),
                            ("WEIGHT", "Proportional to Weight"),
                            ("FIXED", "Fixed per Unit"),
                        ],
                        help_text="Override cost type default",
                        max_length=10,
                    ),
                ),
                ("is_allocated", models.BooleanField(default=False)),
                ("allocated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landing_costs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_costs",
                        to="inventory.goodsreceiptnote",
                    ),
                ),
                (
                    "cost_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_records",
                        to="inventory.landingcosttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Cost Record",
                "verbose_name_plural": "Landing Cost Records",
                "db_table": "landing_cost_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "price_list_type",
                    models.CharField(
                        choices=[
                            ("LSTK", "Lump Sum Turn Key (Fixed Tiers)"),
                            ("COST_PLUS", "Cost Plus Markup"),
                            ("MATRIX", "Matrix Pricing (Size × Quality)"),
                            ("CUSTOM", "Custom Formula"),
                        ],
                        default="LSTK",
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Markup percentage (e.g., 30 for 30%)",
                        max_digits=5,
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Categories this price list applies to (blank = all)",
                        related_name="price_lists",
                        to="inventory.inventorycategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_lists_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer this price list applies to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_lists",
                        to="inventory.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price List",
                "verbose_name_plural": "Price Lists",
                "db_table": "price_lists",
                "ordering": ["priority", "code"],
            },
        ),
        migrations.CreateModel(
            name="PriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Small Cutters', '8-10mm Tier'", max_length=100
                    ),
                ),
                (
                    "size_from",
                    models.PositiveIntegerField(help_text="Minimum size (mm)"),
                ),
                ("size_to", models.PositiveIntegerField(help_text="Maximum size (mm)")),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "min_qty",
                    models.DecimalField(decimal_places=3, default=1, max_digits=15),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="inventory.pricelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Tier",
                "verbose_name_plural": "Price Tiers",
                "db_table": "price_tiers",
                "ordering": ["price_list", "display_order", "size_from"],
            },
        ),
        migrations.CreateModel(
            name="LandingCostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "per_unit_amount",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                (
                    "grn_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_cost_allocations",
                        to="inventory.grnline",
                    ),
                ),
                (
                    "landing_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="inventory.landingcostrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Cost Allocation",
                "verbose_name_plural": "Landing Cost Allocations",
                "db_table": "landing_cost_allocations",
                "unique_together": {("landing_cost", "grn_line")},
            },
        ),
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("price_source", models.CharField(blank=True, max_length=200)),
                (
                    "landed_cost_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Additional per-unit cost from landing costs",
                        max_digits=15,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("is_manual_override", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="inventory.itemvariant",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_prices",
                        to="inventory.pricelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Price",
                "verbose_name_plural": "Item Prices",
                "db_table": "item_prices",
                "ordering": ["item", "price_list", "-effective_from"],
                "unique_together": {
                    ("item", "variant", "price_list", "effective_from")
                },
            },
        ),
        migrations.CreateModel(
            name="PriceMatrixRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size_code",
                    models.CharField(
                        help_text="Size identifier (e.g., '16', '13', '10')",
                        max_length=20,
                    ),
                ),
                (
                    "quality_level",
                    models.CharField(
                        help_text="Quality level (e.g., 'NEW', 'USED', 'REFURB', 'PREMIUM')",
                        max_length=20,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=15)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_rules",
                        to="inventory.pricelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Matrix Rule",
                "verbose_name_plural": "Price Matrix Rules",
                "db_table": "price_matrix_rules",
                "ordering": ["price_list", "size_code", "quality_level"],
                "unique_together": {("price_list", "size_code", "quality_level")},
            },
        ),
    ]
