# Generated by Django 5.1.15 on 2026-02-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_remove_deprecated_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialconsumption",
            name="operation_execution",
        ),
    ]
