# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("forms_engine", "0001_initial"),
        ("inventory", "0001_initial"),
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckpointType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "input_type",
                    models.CharField(
                        help_text="OK_NOK, PASS_FAIL, YES_NO, MEASURE, SELECT, TEXT, NUMBER",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkpoint Type",
                "verbose_name_plural": "Checkpoint Types",
                "db_table": "checkpoint_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StepType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class/name", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Display color", max_length=20
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Type",
                "verbose_name_plural": "Step Types",
                "db_table": "step_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., SA-PP-104", max_length=30, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("revision", models.CharField(blank=True, max_length=10)),
                ("revision_date", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Production"),
                            ("QUALITY", "Quality"),
                            ("SAFETY", "Safety"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SUPPLY_CHAIN", "Supply Chain"),
                            ("GENERAL", "General"),
                        ],
                        default="PRODUCTION",
                        max_length=20,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("FC", "Fixed Cutter (FC)"),
                            ("RC", "Roller Cone (RC)"),
                            ("BOTH", "Both FC & RC"),
                            ("ALL", "All Types"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.TextField(blank=True, help_text="Scope and applicability"),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, help_text="Purpose and objectives"),
                ),
                (
                    "safety_notes",
                    models.TextField(blank=True, help_text="Safety precautions"),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("OBSOLETE", "Obsolete"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_procedures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_procedures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_procedures",
                        to="accounts.role",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_procedures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure",
                "verbose_name_plural": "Procedures",
                "db_table": "procedures",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_number",
                    models.IntegerField(help_text="10, 20, 30... allows inserting"),
                ),
                ("step_code", models.CharField(blank=True, max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "reference_procedure_code",
                    models.CharField(
                        blank=True, help_text="Sub-procedure link", max_length=30
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("is_parallel", models.BooleanField(default=False)),
                ("is_conditional", models.BooleanField(default=False)),
                (
                    "can_skip",
                    models.BooleanField(
                        default=False, help_text="Allow skipping with reason"
                    ),
                ),
                (
                    "can_go_back",
                    models.BooleanField(
                        default=True, help_text="Allow returning to previous"
                    ),
                ),
                (
                    "dependency_condition",
                    models.JSONField(
                        blank=True,
                        help_text='Condition: {"field": "result", "operator": "equals", "value": "PASS"}',
                        null=True,
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        blank=True, help_text="Max time allowed", null=True
                    ),
                ),
                ("requires_qr_scan", models.BooleanField(default=False)),
                ("requires_photo", models.BooleanField(default=False)),
                ("requires_signature", models.BooleanField(default=False)),
                (
                    "requires_form",
                    models.BooleanField(default=False, help_text="Has attached form"),
                ),
                (
                    "expected_output",
                    models.JSONField(
                        blank=True,
                        help_text='Expected outcomes: {"torque_min": 40, "torque_max": 50}',
                        null=True,
                    ),
                ),
                ("validation_rules", models.JSONField(blank=True, null=True)),
                ("sequence", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "depends_on_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="Must complete this step first",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_steps",
                        to="procedures.procedurestep",
                    ),
                ),
                (
                    "form_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedure_steps",
                        to="forms_engine.formtemplate",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="procedures.procedure",
                    ),
                ),
                (
                    "responsible_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
                (
                    "step_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procedures.steptype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Step",
                "verbose_name_plural": "Procedure Steps",
                "db_table": "procedure_steps",
                "ordering": ["procedure", "step_number"],
            },
        ),
        migrations.CreateModel(
            name="StepBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(default=0)),
                (
                    "condition_description",
                    models.CharField(help_text="Human readable", max_length=200),
                ),
                (
                    "condition_field",
                    models.CharField(help_text="Field to evaluate", max_length=100),
                ),
                (
                    "condition_operator",
                    models.CharField(
                        help_text="=, !=, >, <, IN, CONTAINS, IS_NULL", max_length=20
                    ),
                ),
                ("condition_value", models.CharField(blank=True, max_length=200)),
                (
                    "then_action",
                    models.CharField(
                        choices=[
                            ("GOTO_STEP", "Go to Step"),
                            ("SKIP_STEP", "Skip Step"),
                            ("STOP", "Stop Procedure"),
                            ("NCR", "Create NCR"),
                            ("NOTIFY", "Notify"),
                            ("COMPLETE", "Complete Procedure"),
                        ],
                        max_length=30,
                    ),
                ),
                ("then_message", models.TextField(blank=True)),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="ELSE branch"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="procedures.procedurestep",
                    ),
                ),
                (
                    "then_notify_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
                (
                    "then_target_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_branches",
                        to="procedures.procedurestep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Branch",
                "verbose_name_plural": "Step Branches",
                "db_table": "step_branches",
                "ordering": ["step", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="StepCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(default=0)),
                ("checkpoint_code", models.CharField(blank=True, max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("expected_value", models.CharField(blank=True, max_length=100)),
                (
                    "tolerance_min",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "tolerance_max",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="mm, inch, PSI", max_length=20
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, help_text="For dropdown options", null=True
                    ),
                ),
                ("is_critical", models.BooleanField(default=False)),
                (
                    "failure_action",
                    models.CharField(
                        choices=[
                            ("STOP", "Stop Procedure"),
                            ("NCR", "Create NCR"),
                            ("NOTIFY", "Notify Only"),
                            ("REWORK", "Send to Rework"),
                            ("CONTINUE", "Continue Anyway"),
                        ],
                        default="NOTIFY",
                        max_length=30,
                    ),
                ),
                ("help_text", models.TextField(blank=True)),
                ("photo_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "check_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procedures.checkpointtype",
                    ),
                ),
                (
                    "failure_notify_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="procedures.procedurestep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Checkpoint",
                "verbose_name_plural": "Step Checkpoints",
                "db_table": "step_checkpoints",
                "ordering": ["step", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="StepInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material"),
                            ("TOOL", "Tool"),
                            ("EQUIPMENT", "Equipment"),
                            ("DOCUMENT", "Document"),
                            ("PPE", "PPE"),
                            ("FORM", "Form"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "is_consumed",
                    models.BooleanField(
                        default=False, help_text="Material consumed during step"
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintenance.equipment",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="procedures.procedurestep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Input",
                "verbose_name_plural": "Step Inputs",
                "db_table": "step_inputs",
                "ordering": ["step", "input_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="StepOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("DOCUMENT", "Document"),
                            ("MEASUREMENT", "Measurement"),
                            ("PHOTO", "Photo"),
                            ("APPROVAL", "Approval"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="procedures.procedurestep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Output",
                "verbose_name_plural": "Step Outputs",
                "db_table": "step_outputs",
                "ordering": ["step", "output_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "snapshot",
                    models.JSONField(help_text="Full procedure JSON at this version"),
                ),
                ("change_summary", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="procedures.procedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Version",
                "verbose_name_plural": "Procedure Versions",
                "db_table": "procedure_versions",
                "ordering": ["procedure", "-version_number"],
                "unique_together": {("procedure", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="procedurestep",
            index=models.Index(
                fields=["procedure"], name="procedure_s_procedu_5bb0fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedurestep",
            index=models.Index(
                fields=["depends_on_step"], name="procedure_s_depends_2cd089_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="procedurestep",
            unique_together={("procedure", "step_number")},
        ),
    ]
