# Generated by Django 5.1.15 on 2025-12-21 06:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        help_text="Account type (e.g., 'RC-LSTK')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        default="RPR-",
                        help_text="Prefix for item numbers",
                        max_length=50,
                    ),
                ),
                (
                    "current_number",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "padding",
                    models.IntegerField(default=4, help_text="Zero-padding length"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "erp_automation_item_counters",
            },
        ),
        migrations.CreateModel(
            name="Locator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this locator (e.g., 'product_number_field')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of what this element is",
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        default="dynamics365",
                        help_text="Target application (e.g., dynamics365, sap)",
                        max_length=100,
                    ),
                ),
                (
                    "page_context",
                    models.CharField(
                        blank=True,
                        help_text="Page or form where this locator is valid",
                        max_length=200,
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Screenshot of the element for reference",
                        null=True,
                        upload_to="erp_automation/locator_screenshots/",
                    ),
                ),
                (
                    "is_dynamic",
                    models.BooleanField(
                        default=False,
                        help_text="Element has dynamic IDs that change between sessions",
                    ),
                ),
                (
                    "requires_scroll",
                    models.BooleanField(
                        default=False,
                        help_text="Element may need scrolling to become visible",
                    ),
                ),
                (
                    "requires_wait",
                    models.BooleanField(
                        default=True,
                        help_text="Wait for element to be visible before interacting",
                    ),
                ),
                (
                    "default_timeout",
                    models.IntegerField(
                        default=30000,
                        help_text="Default timeout in milliseconds",
                        validators=[django.core.validators.MinValueValidator(1000)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_locators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Locator",
                "verbose_name_plural": "Locators",
                "db_table": "erp_automation_locators",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LocatorStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("data-testid", "Data Test ID"),
                            ("aria-label", "ARIA Label"),
                            ("name", "Name Attribute"),
                            ("id", "ID Attribute"),
                            ("css", "CSS Selector"),
                            ("xpath", "XPath"),
                            ("text", "Text Content"),
                            ("text-nearby", "Text Nearby Element"),
                            ("role", "ARIA Role"),
                        ],
                        help_text="Type of locator strategy",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="The locator value (XPath, CSS, text, etc.)"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=10,
                        help_text="Lower number = higher priority (tried first)",
                    ),
                ),
                (
                    "offset_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("above", "Above"),
                            ("below", "Below"),
                            ("left", "Left"),
                            ("right", "Right"),
                        ],
                        help_text="Direction from label text to input (for text-nearby)",
                        max_length=20,
                    ),
                ),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "locator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="erp_automation.locator",
                    ),
                ),
            ],
            options={
                "db_table": "erp_automation_locator_strategies",
                "ordering": ["locator", "priority"],
                "unique_together": {("locator", "strategy_type", "value")},
            },
        ),
        migrations.CreateModel(
            name="RecordingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "target_url",
                    models.URLField(help_text="URL where recording started"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "erp_automation_recording_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RecordedAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("fill", "Fill/Type"),
                            ("select", "Select Option"),
                            ("check", "Check/Uncheck"),
                            ("hover", "Hover"),
                            ("scroll", "Scroll Into View"),
                            ("wait", "Wait for Element"),
                            ("wait_time", "Wait (Time)"),
                            ("press_key", "Press Key"),
                            ("screenshot", "Take Screenshot"),
                            ("assert_text", "Assert Text"),
                            ("assert_visible", "Assert Visible"),
                            ("conditional", "Conditional Branch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("element_tag", models.CharField(blank=True, max_length=50)),
                ("element_id", models.CharField(blank=True, max_length=200)),
                ("element_name", models.CharField(blank=True, max_length=200)),
                ("element_class", models.TextField(blank=True)),
                ("element_xpath", models.TextField(blank=True)),
                ("element_css", models.TextField(blank=True)),
                ("element_text", models.TextField(blank=True)),
                ("element_aria_label", models.CharField(blank=True, max_length=200)),
                ("element_placeholder", models.CharField(blank=True, max_length=200)),
                (
                    "element_rect",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bounding box {x, y, width, height}",
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="erp_automation/recordings/"
                    ),
                ),
                ("page_url", models.URLField(blank=True)),
                ("page_title", models.CharField(blank=True, max_length=200)),
                ("input_value", models.TextField(blank=True)),
                ("key_pressed", models.CharField(blank=True, max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="erp_automation.recordingsession",
                    ),
                ),
            ],
            options={
                "db_table": "erp_automation_recorded_actions",
                "ordering": ["session", "order"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Workflow name (e.g., 'Create Released Product')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this workflow does"),
                ),
                (
                    "target_url",
                    models.URLField(
                        blank=True, help_text="Default starting URL for this workflow"
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        default="dynamics365",
                        help_text="Target application",
                        max_length=100,
                    ),
                ),
                (
                    "valid_sheets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Excel sheet names this workflow can process",
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Required data fields for this workflow",
                    ),
                ),
                (
                    "condition_field",
                    models.CharField(
                        blank=True,
                        help_text="Field name used for conditional branching (e.g., 'FROM' or 'account_type')",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "erp_automation_workflows",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="recordingsession",
            name="generated_workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recording_sessions",
                to="erp_automation.workflow",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("excel_file_path", models.CharField(blank=True, max_length=500)),
                ("sheet_name", models.CharField(blank=True, max_length=100)),
                (
                    "row_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The Excel row data being processed",
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="erp_automation.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "erp_automation_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(help_text="Execution order (lower = first)"),
                ),
                (
                    "name",
                    models.CharField(help_text="Step name for logging", max_length=100),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("fill", "Fill/Type"),
                            ("select", "Select Option"),
                            ("check", "Check/Uncheck"),
                            ("hover", "Hover"),
                            ("scroll", "Scroll Into View"),
                            ("wait", "Wait for Element"),
                            ("wait_time", "Wait (Time)"),
                            ("press_key", "Press Key"),
                            ("screenshot", "Take Screenshot"),
                            ("assert_text", "Assert Text"),
                            ("assert_visible", "Assert Visible"),
                            ("conditional", "Conditional Branch"),
                        ],
                        default="click",
                        max_length=20,
                    ),
                ),
                (
                    "value_static",
                    models.TextField(blank=True, help_text="Static value to enter"),
                ),
                (
                    "value_field",
                    models.CharField(
                        blank=True,
                        help_text="Excel column name to get value from (e.g., 'SERIAL NO')",
                        max_length=100,
                    ),
                ),
                (
                    "value_template",
                    models.CharField(
                        blank=True,
                        help_text="Template with placeholders (e.g., 'RPR-{{FROM}}-{{ID}}')",
                        max_length=200,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        blank=True,
                        help_text="Only execute if workflow condition matches this value",
                        max_length=100,
                    ),
                ),
                (
                    "clear_before_fill",
                    models.BooleanField(
                        default=False, help_text="Clear field before filling"
                    ),
                ),
                (
                    "press_key_after",
                    models.CharField(
                        blank=True,
                        help_text="Key to press after action (e.g., 'Tab', 'Enter')",
                        max_length=50,
                    ),
                ),
                (
                    "wait_after",
                    models.IntegerField(
                        default=500, help_text="Milliseconds to wait after this step"
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        default=30000, help_text="Step timeout in milliseconds"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3, help_text="Number of retry attempts on failure"
                    ),
                ),
                (
                    "continue_on_error",
                    models.BooleanField(
                        default=False,
                        help_text="Continue workflow even if this step fails",
                    ),
                ),
                (
                    "save_result_as",
                    models.CharField(
                        blank=True,
                        help_text="Save step result to context with this key",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "error_handler_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="Step to execute if this step fails",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp_automation.workflowstep",
                    ),
                ),
                (
                    "locator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Element to interact with",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erp_automation.locator",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="erp_automation.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "erp_automation_workflow_steps",
                "ordering": ["workflow", "order"],
                "unique_together": {("workflow", "order")},
            },
        ),
        migrations.CreateModel(
            name="StepExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="erp_automation/step_screenshots/",
                    ),
                ),
                (
                    "locator_strategy_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp_automation.locatorstrategy",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="erp_automation.workflowexecution",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_automation.workflowstep",
                    ),
                ),
            ],
            options={
                "db_table": "erp_automation_step_executions",
                "ordering": ["execution", "step__order"],
            },
        ),
        migrations.CreateModel(
            name="FieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excel_column",
                    models.CharField(help_text="Column name in Excel", max_length=100),
                ),
                (
                    "erp_field",
                    models.CharField(help_text="Field name in ERP", max_length=100),
                ),
                (
                    "transform_function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("uppercase", "Uppercase"),
                            ("lowercase", "Lowercase"),
                            ("trim", "Trim Whitespace"),
                            ("date_format", "Format Date"),
                            ("number_format", "Format Number"),
                        ],
                        help_text="Optional transformation to apply",
                        max_length=100,
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True,
                        help_text="Default value if Excel cell is empty",
                        max_length=200,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "locator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Locator for the ERP field",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp_automation.locator",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="erp_automation.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "erp_automation_field_mappings",
                "unique_together": {("workflow", "excel_column")},
            },
        ),
    ]
