# Generated by Django 5.1.15 on 2026-02-08 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0005_add_element_role_type_to_recorded_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChainExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "row_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Initial row_data from job_data.get_row_data()",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Accumulated context vars from all completed links",
                    ),
                ),
                ("total_links", models.IntegerField(default=0)),
                ("completed_links", models.IntegerField(default=0)),
                (
                    "current_link_order",
                    models.IntegerField(
                        blank=True,
                        help_text="Order of the currently executing link",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_data",
                    models.ForeignKey(
                        blank=True,
                        help_text="Job data record being processed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chain_executions",
                        to="erp_automation.erpjobdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chain Execution",
                "verbose_name_plural": "Chain Executions",
                "db_table": "erp_automation_chain_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="chain_execution",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent chain execution (if running as part of a chain)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_executions",
                to="erp_automation.chainexecution",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Chain name (e.g., 'Full LSTK ERP Processing')",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this chain of workflows does"
                    ),
                ),
                (
                    "condition_field",
                    models.CharField(
                        blank=True,
                        help_text="Field used for conditional branching (e.g., 'FROM')",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "stop_on_failure",
                    models.BooleanField(
                        default=True, help_text="Stop chain if a sub-workflow fails"
                    ),
                ),
                (
                    "keep_browser_open",
                    models.BooleanField(
                        default=True,
                        help_text="Keep browser open between sub-workflows (faster, preserves login)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_chains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Chain",
                "verbose_name_plural": "Workflow Chains",
                "db_table": "erp_automation_workflow_chains",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="chainexecution",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="erp_automation.workflowchain",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowChainLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Execution order within the chain (lower = first)"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional label (defaults to workflow name)",
                        max_length=150,
                    ),
                ),
                (
                    "wait_before_ms",
                    models.IntegerField(
                        default=2000,
                        help_text="Milliseconds to wait before starting this link",
                    ),
                ),
                (
                    "navigate_url",
                    models.URLField(
                        blank=True,
                        help_text="Override workflow's target_url (navigate here before running)",
                    ),
                ),
                (
                    "context_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Map context vars to row_data keys. Example: {"ITEM_NO": "created_item_number"}',
                    ),
                ),
                (
                    "condition_field",
                    models.CharField(
                        blank=True,
                        help_text="Field to check for skipping this link",
                        max_length=100,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        blank=True,
                        help_text="Only execute if condition_field matches this value",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="erp_automation.workflowchain",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="The workflow to execute at this position",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chain_links",
                        to="erp_automation.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chain Link",
                "verbose_name_plural": "Chain Links",
                "db_table": "erp_automation_chain_links",
                "ordering": ["chain", "order"],
                "unique_together": {("chain", "order")},
            },
        ),
    ]
