# Generated by Django 5.1.15 on 2026-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0009_add_check_for_errors_to_workflowstep"),
    ]

    operations = [
        migrations.CreateModel(
            name="ERPEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField(max_length=500)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default environment pre-selected on credentials page",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ERP Environment",
                "verbose_name_plural": "ERP Environments",
                "db_table": "erp_automation_environments",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="recordedaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("click", "Click"),
                    ("fill", "Fill/Type"),
                    ("select", "Select Option"),
                    ("check", "Check/Uncheck"),
                    ("hover", "Hover"),
                    ("scroll", "Scroll Into View"),
                    ("wait", "Wait for Element"),
                    ("wait_time", "Wait (Time)"),
                    ("press_key", "Press Key"),
                    ("screenshot", "Take Screenshot"),
                    ("assert_text", "Assert Text"),
                    ("assert_visible", "Assert Visible"),
                    ("conditional", "Conditional Branch"),
                    ("read_value", "Read Value"),
                    ("goto_url", "Navigate to URL"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("click", "Click"),
                    ("fill", "Fill/Type"),
                    ("select", "Select Option"),
                    ("check", "Check/Uncheck"),
                    ("hover", "Hover"),
                    ("scroll", "Scroll Into View"),
                    ("wait", "Wait for Element"),
                    ("wait_time", "Wait (Time)"),
                    ("press_key", "Press Key"),
                    ("screenshot", "Take Screenshot"),
                    ("assert_text", "Assert Text"),
                    ("assert_visible", "Assert Visible"),
                    ("conditional", "Conditional Branch"),
                    ("read_value", "Read Value"),
                    ("goto_url", "Navigate to URL"),
                ],
                default="click",
                max_length=20,
            ),
        ),
    ]
