# Generated by Django 5.1.15 on 2026-02-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp_automation", "0012_add_repeat_group_to_workflowstep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowstep",
            name="repeat_data_source",
        ),
        migrations.RemoveField(
            model_name="workflowstep",
            name="repeat_group",
        ),
    ]
