# Generated by Django 5.2.8 on 2025-12-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_equipmentcalibration"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="organization.department",
            ),
        ),
    ]
