# Generated by Django 5.1.15 on 2026-03-03 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.BigIntegerField()),
                ("revision_number", models.IntegerField()),
                (
                    "document_code",
                    models.CharField(
                        blank=True, help_text="e.g. QAS/005-1", max_length=50
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        default=dict, help_text="Full form data at this revision"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict, help_text="{field: {old: X, new: Y}}"
                    ),
                ),
                ("change_summary", models.CharField(blank=True, max_length=500)),
                ("revised_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Form Revision",
                "verbose_name_plural": "Form Revisions",
                "db_table": "form_revisions",
                "ordering": ["-revision_number"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"], name="notif_bell_idx"
            ),
        ),
        migrations.AddField(
            model_name="formrevision",
            name="revised_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="formrevision",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="form_revisi_entity__e793f2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formrevision",
            unique_together={("entity_type", "entity_id", "revision_number")},
        ),
    ]
