# Generated by Django 5.1.15 on 2026-04-03 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_actor_formrevision_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                blank=True,
                help_text="ActionType enum value for smart button rendering",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("BIT_RECEIVED", "Bit Received / Backloaded"),
                            ("INSPECTION_ACCEPTED", "Receiving Inspection: Accepted"),
                            ("INSPECTION_REJECTED", "Receiving Inspection: Rejected"),
                            (
                                "INSPECTION_CONDITIONAL",
                                "Receiving Inspection: Conditional",
                            ),
                            ("CEREBRO_DETECTED", "Cerebro Device Detected"),
                            ("ADDED_TO_PLAN", "Bit Added to Production Plan"),
                            ("WO_RELEASED", "Work Order Released"),
                            ("TRANSFER_CONFIRMED", "Bit Transfer Confirmed"),
                            ("WO_APPROVED", "Work Order Approved"),
                            ("WO_REJECTED", "Work Order Rejected"),
                            ("WO_DELETED", "Work Order Deleted"),
                            ("WO_STARTED", "Work Started on WO"),
                            ("STEP_COMPLETED", "Router Step Completed"),
                            ("STEP_ON_HOLD", "Step Put On Hold"),
                            ("STEP_WAITING_QC", "Step Waiting for QC"),
                            ("STEP_WAITING_APPROVAL", "Step Waiting for Approval"),
                            ("STEP_WAITING_TECH", "Step Waiting for Tech Review"),
                            ("STEP_RESUMED", "Step Resumed"),
                            ("ALL_STEPS_DONE", "All Router Steps Completed"),
                            ("DIE_CHECK_DECISION", "Die Check Needs Quality Decision"),
                            (
                                "SPECIAL_INSTRUCTION",
                                "Critical Special Instruction Active",
                            ),
                            ("WO_SENT_TO_QC", "WO Sent to QC"),
                            ("QC_PASSED", "QC Passed"),
                            ("QC_FAILED", "QC Failed — Rework Needed"),
                            ("WO_COMPLETED", "Work Order Completed"),
                            ("GRN_POSTED", "GRN Posted"),
                            ("EVALUATION_COMPLETED", "Bit Evaluation Completed"),
                            ("ROUTE_UPDATED", "Router Route Auto-Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "trigger_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Optional filter e.g. {"account_code": "ARAMCO"}',
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("ACTION", "Create Action Task Only"),
                            ("NOTIFICATION", "Send Notification Only"),
                            ("BOTH", "Create Action + Send Notification"),
                        ],
                        default="BOTH",
                        max_length=20,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INSPECT_BIT", "Start Receiving Inspection"),
                            ("ADD_TO_PLAN", "Add Bit to Production Plan"),
                            ("TRANSFER_BIT", "Transfer Bit (Physical Move)"),
                            ("APPROVE_WO", "Review & Approve Work Order"),
                            ("PRINT_RELEASE", "Print Release Paper"),
                            ("START_STEP", "Start First Router Step"),
                            ("REVIEW_HOLD", "Review Hold & Decide Next Action"),
                            ("QC_CHECK", "Perform QC Check"),
                            ("TECH_REVIEW", "Technical Review Required"),
                            ("QUALITY_DECISION", "Quality Decision on Cutters"),
                            ("CONFIRM_TRANSFER", "Confirm Bit Transfer to Destination"),
                            ("PREPARE_DISPATCH", "Prepare Bit for Shipping"),
                            ("MAKE_DECISION", "Decision Required"),
                            ("ACKNOWLEDGE", "Acknowledge / Information Only"),
                            ("REWORK", "Plan & Start Rework"),
                            ("ASSIGN_OPERATOR", "Assign Operator to WO"),
                            ("REPLAN", "Re-plan Bit in Production Planner"),
                            (
                                "REMOVE_DEVICE",
                                "Remove Cerebro Device Before Processing",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "assign_to_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECEIVING_INSPECTOR", "Receiving Inspector"),
                            ("PLANNER", "Planner"),
                            ("PRODUCTION_MANAGER", "Production Manager"),
                            ("PRODUCTION_LEAD", "Production Lead / Supervisor"),
                            ("OPERATOR", "Floor Operator"),
                            ("QC_INSPECTOR", "QC Inspector"),
                            ("TECHNICAL_LEAD", "Technical Lead"),
                            ("DISPATCH", "Dispatch / Shipping"),
                            ("MANAGEMENT", "Management (Info Only)"),
                            ("SYSTEM_ADMIN", "System Administrator"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_url_pattern",
                    models.CharField(
                        blank=True,
                        help_text="URL pattern with placeholders e.g. /work-orders/{wo_id}/",
                        max_length=500,
                    ),
                ),
                (
                    "action_description_template",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Transfer {serial} from {from_loc} to {to_loc}"',
                        max_length=500,
                    ),
                ),
                (
                    "deadline_hours",
                    models.IntegerField(
                        blank=True, help_text="Hours until action is overdue", null=True
                    ),
                ),
                (
                    "is_queue_action",
                    models.BooleanField(
                        default=False,
                        help_text="If True, any available user with the role can claim it",
                    ),
                ),
                ("escalate_after_hours", models.IntegerField(blank=True, null=True)),
                (
                    "escalate_to_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECEIVING_INSPECTOR", "Receiving Inspector"),
                            ("PLANNER", "Planner"),
                            ("PRODUCTION_MANAGER", "Production Manager"),
                            ("PRODUCTION_LEAD", "Production Lead / Supervisor"),
                            ("OPERATOR", "Floor Operator"),
                            ("QC_INSPECTOR", "QC Inspector"),
                            ("TECHNICAL_LEAD", "Technical Lead"),
                            ("DISPATCH", "Dispatch / Shipping"),
                            ("MANAGEMENT", "Management (Info Only)"),
                            ("SYSTEM_ADMIN", "System Administrator"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "notif_title_template",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "WO {wo_number} needs approval"',
                        max_length=200,
                    ),
                ),
                (
                    "notif_message_template",
                    models.TextField(
                        blank=True,
                        help_text="Supports {wo_number}, {serial}, {actor_name}, etc.",
                    ),
                ),
                (
                    "notif_recipients_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECEIVING_INSPECTOR", "Receiving Inspector"),
                            ("PLANNER", "Planner"),
                            ("PRODUCTION_MANAGER", "Production Manager"),
                            ("PRODUCTION_LEAD", "Production Lead / Supervisor"),
                            ("OPERATOR", "Floor Operator"),
                            ("QC_INSPECTOR", "QC Inspector"),
                            ("TECHNICAL_LEAD", "Technical Lead"),
                            ("DISPATCH", "Dispatch / Shipping"),
                            ("MANAGEMENT", "Management (Info Only)"),
                            ("SYSTEM_ADMIN", "System Administrator"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "notif_priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "depends_on_rule_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="PKs of sibling rules whose actions must complete first",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Execution order for same event"
                    ),
                ),
                (
                    "assign_to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override: assign to specific user instead of role",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_rule_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalate_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_escalation_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_rules",
                "ordering": ["trigger_event", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INSPECT_BIT", "Start Receiving Inspection"),
                            ("ADD_TO_PLAN", "Add Bit to Production Plan"),
                            ("TRANSFER_BIT", "Transfer Bit (Physical Move)"),
                            ("APPROVE_WO", "Review & Approve Work Order"),
                            ("PRINT_RELEASE", "Print Release Paper"),
                            ("START_STEP", "Start First Router Step"),
                            ("REVIEW_HOLD", "Review Hold & Decide Next Action"),
                            ("QC_CHECK", "Perform QC Check"),
                            ("TECH_REVIEW", "Technical Review Required"),
                            ("QUALITY_DECISION", "Quality Decision on Cutters"),
                            ("CONFIRM_TRANSFER", "Confirm Bit Transfer to Destination"),
                            ("PREPARE_DISPATCH", "Prepare Bit for Shipping"),
                            ("MAKE_DECISION", "Decision Required"),
                            ("ACKNOWLEDGE", "Acknowledge / Information Only"),
                            ("REWORK", "Plan & Start Rework"),
                            ("ASSIGN_OPERATOR", "Assign Operator to WO"),
                            ("REPLAN", "Re-plan Bit in Production Planner"),
                            (
                                "REMOVE_DEVICE",
                                "Remove Cerebro Device Before Processing",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("action_url", models.CharField(blank=True, max_length=500)),
                (
                    "trigger_event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BIT_RECEIVED", "Bit Received / Backloaded"),
                            ("INSPECTION_ACCEPTED", "Receiving Inspection: Accepted"),
                            ("INSPECTION_REJECTED", "Receiving Inspection: Rejected"),
                            (
                                "INSPECTION_CONDITIONAL",
                                "Receiving Inspection: Conditional",
                            ),
                            ("CEREBRO_DETECTED", "Cerebro Device Detected"),
                            ("ADDED_TO_PLAN", "Bit Added to Production Plan"),
                            ("WO_RELEASED", "Work Order Released"),
                            ("TRANSFER_CONFIRMED", "Bit Transfer Confirmed"),
                            ("WO_APPROVED", "Work Order Approved"),
                            ("WO_REJECTED", "Work Order Rejected"),
                            ("WO_DELETED", "Work Order Deleted"),
                            ("WO_STARTED", "Work Started on WO"),
                            ("STEP_COMPLETED", "Router Step Completed"),
                            ("STEP_ON_HOLD", "Step Put On Hold"),
                            ("STEP_WAITING_QC", "Step Waiting for QC"),
                            ("STEP_WAITING_APPROVAL", "Step Waiting for Approval"),
                            ("STEP_WAITING_TECH", "Step Waiting for Tech Review"),
                            ("STEP_RESUMED", "Step Resumed"),
                            ("ALL_STEPS_DONE", "All Router Steps Completed"),
                            ("DIE_CHECK_DECISION", "Die Check Needs Quality Decision"),
                            (
                                "SPECIAL_INSTRUCTION",
                                "Critical Special Instruction Active",
                            ),
                            ("WO_SENT_TO_QC", "WO Sent to QC"),
                            ("QC_PASSED", "QC Passed"),
                            ("QC_FAILED", "QC Failed — Rework Needed"),
                            ("WO_COMPLETED", "Work Order Completed"),
                            ("GRN_POSTED", "GRN Posted"),
                            ("EVALUATION_COMPLETED", "Bit Evaluation Completed"),
                            ("ROUTE_UPDATED", "Router Route Auto-Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "assigned_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECEIVING_INSPECTOR", "Receiving Inspector"),
                            ("PLANNER", "Planner"),
                            ("PRODUCTION_MANAGER", "Production Manager"),
                            ("PRODUCTION_LEAD", "Production Lead / Supervisor"),
                            ("OPERATOR", "Floor Operator"),
                            ("QC_INSPECTOR", "QC Inspector"),
                            ("TECHNICAL_LEAD", "Technical Lead"),
                            ("DISPATCH", "Dispatch / Shipping"),
                            ("MANAGEMENT", "Management (Info Only)"),
                            ("SYSTEM_ADMIN", "System Administrator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_queue_action", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLAIMED", "Claimed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ESCALATED", "Escalated"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, max_length=50)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "depends_on_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="PKs of WorkflowAction records that must complete first",
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("escalate_after_hours", models.IntegerField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalation_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_actions",
                        to="notifications.notification",
                    ),
                ),
                (
                    "source_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="notifications.workflowrule",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_actions",
                "ordering": ["is_blocked", "due_date", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="UserWorkflowRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RECEIVING_INSPECTOR", "Receiving Inspector"),
                            ("PLANNER", "Planner"),
                            ("PRODUCTION_MANAGER", "Production Manager"),
                            ("PRODUCTION_LEAD", "Production Lead / Supervisor"),
                            ("OPERATOR", "Floor Operator"),
                            ("QC_INSPECTOR", "QC Inspector"),
                            ("TECHNICAL_LEAD", "Technical Lead"),
                            ("DISPATCH", "Dispatch / Shipping"),
                            ("MANAGEMENT", "Management (Info Only)"),
                            ("SYSTEM_ADMIN", "System Administrator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="If False, user will not receive new role-based actions",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_workflow_roles",
                "indexes": [
                    models.Index(
                        fields=["role", "is_active", "is_available"],
                        name="idx_uwr_role_active_avail",
                    )
                ],
                "unique_together": {("user", "role")},
            },
        ),
        migrations.AddIndex(
            model_name="workflowrule",
            index=models.Index(
                fields=["trigger_event", "is_active", "order"],
                name="idx_wr_event_active_order",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["assigned_to", "status", "is_blocked"],
                name="idx_wa_user_status",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["assigned_role", "status", "is_blocked"],
                name="idx_wa_role_status",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="idx_wa_entity"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["trigger_event", "status"], name="idx_wa_event_status"
            ),
        ),
    ]
