# Generated by Django 5.1.15 on 2026-04-03 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_workflow_engine_models"),
        ("organization", "0002_alter_systemsetting_updated_by"),
        ("sales", "0008_alter_account_options_account_contract_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_position_derived",
                    models.BooleanField(
                        default=False,
                        help_text="True = auto-assigned from position. False = manually granted.",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to pause routing (leave, Ramadan hours)",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank for permanent. Set for acting/delegation.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Acting Operations Manager"',
                        max_length=200,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_capabilities",
            },
        ),
        migrations.CreateModel(
            name="WorkflowCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Uppercase code, e.g. QC_INSPECTOR",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_ar", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "has_full_visibility",
                    models.BooleanField(
                        default=False,
                        help_text="GM/Director level — full overview dashboard",
                    ),
                ),
                (
                    "is_system_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Can configure workflow rules and capabilities",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order in admin UI"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Workflow Capability",
                "verbose_name_plural": "Workflow Capabilities",
                "db_table": "workflow_capabilities",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="userworkflowrole",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userworkflowrole",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="userworkflowrole",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="workflowaction",
            name="idx_wa_role_status",
        ),
        migrations.RemoveField(
            model_name="workflowaction",
            name="assigned_role",
        ),
        migrations.RemoveField(
            model_name="workflowrule",
            name="assign_to_role",
        ),
        migrations.RemoveField(
            model_name="workflowrule",
            name="escalate_to_role",
        ),
        migrations.RemoveField(
            model_name="workflowrule",
            name="notif_recipients_role",
        ),
        migrations.AlterField(
            model_name="workflowrule",
            name="assign_to_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Override: assign to specific user instead of capability",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_rule_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowrule",
            name="is_queue_action",
            field=models.BooleanField(
                default=False,
                help_text="If True, any available user with the capability can claim it",
            ),
        ),
        migrations.AddField(
            model_name="usercapability",
            name="account_scope",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict to specific accounts. Empty = all accounts.",
                related_name="scoped_capabilities",
                to="sales.account",
            ),
        ),
        migrations.AddField(
            model_name="usercapability",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_capabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usercapability",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowcapability",
            name="positions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users assigned to these positions automatically receive this capability",
                related_name="default_capabilities",
                to="organization.position",
            ),
        ),
        migrations.AddField(
            model_name="usercapability",
            name="capability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assignments",
                to="notifications.workflowcapability",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="assigned_capability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="notifications.workflowcapability",
            ),
        ),
        migrations.AddField(
            model_name="workflowrule",
            name="assign_to_capability",
            field=models.ForeignKey(
                blank=True,
                help_text="Capability that determines who receives this action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rules_assigned",
                to="notifications.workflowcapability",
            ),
        ),
        migrations.AddField(
            model_name="workflowrule",
            name="escalate_to_capability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rules_escalation",
                to="notifications.workflowcapability",
            ),
        ),
        migrations.AddField(
            model_name="workflowrule",
            name="notif_recipients_capability",
            field=models.ForeignKey(
                blank=True,
                help_text="Capability that determines who receives this notification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rules_notification",
                to="notifications.workflowcapability",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["assigned_capability", "status", "is_blocked"],
                name="idx_wa_cap_status",
            ),
        ),
        migrations.DeleteModel(
            name="UserWorkflowRole",
        ),
        migrations.AddIndex(
            model_name="usercapability",
            index=models.Index(
                fields=["capability", "is_available"], name="idx_ucap_cap_avail"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercapability",
            unique_together={("user", "capability")},
        ),
    ]
