# Generated by Django 5.1.15 on 2026-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_drop_capability_models_use_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["due_date", "-priority"]},
        ),
        migrations.CreateModel(
            name="TriggerPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="URL name or unique code, e.g. workorders:api_router_step_scan",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable action name, e.g. "Start Router Step"',
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this action does"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RECEIVING", "Receiving Dock"),
                            ("PLANNING", "Production Planning"),
                            ("WORKORDER", "Work Order Management"),
                            ("PRODUCTION", "Router Sheet / Steps"),
                            ("EVALUATION", "Evaluations"),
                            ("QUALITY", "Quality & NCR"),
                            ("INVENTORY", "Inventory"),
                            ("DISPATCH", "Dispatch & Field"),
                            ("SALES", "Sales"),
                            ("HR", "HR & Admin"),
                            ("TECHNOLOGY", "Technology"),
                            ("ERP", "ERP Automation"),
                            ("COMPLIANCE", "Compliance"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SYSTEM", "System / Settings"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        blank=True,
                        help_text="Django app name, e.g. workorders",
                        max_length=50,
                    ),
                ),
                (
                    "page_name",
                    models.CharField(
                        blank=True,
                        help_text='Page where this action is performed, e.g. "Router Sheet"',
                        max_length=100,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="zap", help_text="Lucide icon name", max_length=50
                    ),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        blank=True,
                        help_text="URL pattern, e.g. /work-orders/<wo_pk>/router-sheet/<step>/api-scan/",
                        max_length=300,
                    ),
                ),
                (
                    "workflow_event",
                    models.CharField(
                        blank=True,
                        help_text="WorkflowEvent code if this trigger fires dispatch_event()",
                        max_length=50,
                    ),
                ),
                (
                    "has_workflow_rules",
                    models.BooleanField(
                        default=False,
                        help_text="Computed: does any WorkflowRule exist for this event?",
                    ),
                ),
                (
                    "typical_role",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Operator", "Manager", "System"',
                        max_length=100,
                    ),
                ),
                ("view_name", models.CharField(blank=True, max_length=100)),
                (
                    "http_methods",
                    models.CharField(
                        default="POST", help_text="GET, POST, or both", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trigger_points",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="trigger_poi_categor_4d23d2_idx",
                    ),
                    models.Index(
                        fields=["workflow_event"], name="trigger_poi_workflo_d69c2d_idx"
                    ),
                ],
            },
        ),
    ]
