# Generated by Django 5.1.15 on 2026-04-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_add_trigger_point_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="triggerpoint",
            name="context_variables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {variable} names available in this trigger context",
            ),
        ),
    ]
