# Generated by Django 5.1.15 on 2025-12-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "applications",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("size_inches", models.CharField(max_length=20)),
                (
                    "size_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Connection Size",
                "verbose_name_plural": "Connection Sizes",
                "db_table": "connection_sizes",
                "ordering": ["size_decimal"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Connection Type",
                "verbose_name_plural": "Connection Types",
                "db_table": "connection_types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FormationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "age",
                    models.CharField(
                        blank=True, help_text="Geological age", max_length=50
                    ),
                ),
                (
                    "rock_type",
                    models.CharField(
                        blank=True,
                        help_text="Carbonate, Sandstone, Shale",
                        max_length=50,
                    ),
                ),
                (
                    "hardness",
                    models.CharField(
                        blank=True, help_text="Soft, Medium, Hard", max_length=20
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Formation Type",
                "verbose_name_plural": "Formation Types",
                "db_table": "formation_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IADCCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "bit_type",
                    models.CharField(
                        choices=[
                            ("FC", "Fixed Cutter (PDC)"),
                            ("RC", "Roller Cone"),
                            ("MT", "Mill Tooth"),
                            ("TCI", "Tungsten Carbide Insert"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "body_material",
                    models.CharField(blank=True, help_text="M, S, D", max_length=1),
                ),
                (
                    "formation_hardness",
                    models.CharField(blank=True, help_text="1-8", max_length=1),
                ),
                (
                    "cutter_type",
                    models.CharField(blank=True, help_text="1-4", max_length=1),
                ),
                (
                    "profile",
                    models.CharField(blank=True, help_text="1-4", max_length=1),
                ),
                ("series", models.CharField(blank=True, help_text="1-8", max_length=1)),
                (
                    "type_code",
                    models.CharField(blank=True, help_text="1-4", max_length=1),
                ),
                (
                    "bearing",
                    models.CharField(blank=True, help_text="1-7", max_length=1),
                ),
                (
                    "feature",
                    models.CharField(blank=True, help_text="A-Z", max_length=1),
                ),
                ("description", models.CharField(max_length=200)),
                ("formation_description", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "IADC Code",
                "verbose_name_plural": "IADC Codes",
                "db_table": "iadc_codes",
                "ordering": ["bit_type", "code"],
            },
        ),
    ]
