# Generated by Django 5.1.15 on 2025-12-13 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0002_add_reference_tables"),
        ("workorders", "0006_bittype_phase2_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="design",
            options={
                "ordering": ["category", "series", "hdbs_type"],
                "verbose_name": "Design",
                "verbose_name_plural": "Designs",
            },
        ),
        migrations.AddField(
            model_name="design",
            name="application_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="technology.application",
                verbose_name="Application",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="ardt_item_no",
            field=models.CharField(
                blank=True,
                help_text="ARDT ERP item number",
                max_length=20,
                verbose_name="ARDT Item No.",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="body_material",
            field=models.CharField(
                blank=True,
                choices=[("M", "Matrix"), ("S", "Steel"), ("", "N/A")],
                max_length=1,
                verbose_name="Body Material",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="category",
            field=models.CharField(
                choices=[
                    ("FC", "Fixed Cutter"),
                    ("MT", "Mill Tooth"),
                    ("TCI", "Tri Cone Inserts"),
                ],
                default="FC",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="connection_size_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="technology.connectionsize",
                verbose_name="Connection Size",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="connection_type_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="technology.connectiontype",
                verbose_name="Connection Type",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="cutter_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Primary cutter size in mm",
                null=True,
                verbose_name="Cutter Size",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="formation_type_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="technology.formationtype",
                verbose_name="Formation Type",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="gage_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Gage Length",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="gage_relief",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Gage Relief"
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="hdbs_type",
            field=models.CharField(
                default="",
                help_text="Internal Halliburton type code (e.g., GT65RHS)",
                max_length=50,
                verbose_name="HDBS Type",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="iadc_code_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="technology.iadccode",
                verbose_name="IADC Code",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="mat_no",
            field=models.CharField(
                default="",
                help_text="HDBS Material Number (SAP)",
                max_length=20,
                unique=True,
                verbose_name="MAT No.",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="no_of_blades",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="No. of Blades"
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="nozzle_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nozzle Count"
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="nozzle_size",
            field=models.CharField(
                blank=True,
                help_text="e.g., 12/32, 14/32, or multiple sizes",
                max_length=50,
                verbose_name="Nozzle Size",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="order_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3", "Level 3 - No cutters, upper section separate"),
                    ("4", "Level 4 - No cutters, upper section welded/machined"),
                    ("5", "Level 5 - With cutters brazed"),
                    ("6", "Level 6 - Painted and ready for use"),
                ],
                max_length=5,
                verbose_name="Order Level",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="port_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Port Count"
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="port_size",
            field=models.CharField(blank=True, max_length=50, verbose_name="Port Size"),
        ),
        migrations.AddField(
            model_name="design",
            name="ref_mat_no",
            field=models.CharField(
                blank=True,
                help_text="Parent/reference MAT number",
                max_length=20,
                verbose_name="Ref MAT No.",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="series",
            field=models.CharField(
                blank=True,
                help_text="Product series (GT, HD, MM, EM, etc.)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="size_legacy",
            field=models.DecimalField(
                blank=True,
                db_column="size_decimal",
                decimal_places=3,
                help_text="Legacy: Use size FK instead",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="smi_type",
            field=models.CharField(
                blank=True,
                help_text="Client-facing type (may differ from HDBS Type)",
                max_length=50,
                verbose_name="SMI Type",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="application",
            field=models.CharField(
                blank=True, help_text="Legacy: Use application_ref FK", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="bit_type",
            field=models.CharField(
                blank=True, help_text="Legacy: Use category instead", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="blade_count",
            field=models.IntegerField(
                blank=True, help_text="Legacy: Use no_of_blades instead", null=True
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="code",
            field=models.CharField(
                blank=True, help_text="Legacy: Use mat_no instead", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="cone_count",
            field=models.IntegerField(
                blank=True, help_text="Legacy: For RC bits", null=True
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="connection_size",
            field=models.CharField(
                blank=True,
                help_text="Legacy: Use connection_size_ref FK",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="connection_type",
            field=models.CharField(
                blank=True,
                help_text="Legacy: Use connection_type_ref FK",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="formation_type",
            field=models.CharField(
                blank=True,
                help_text="Legacy: Use formation_type_ref FK",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="gauge_protection",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Gauge Protection"
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="iadc_code",
            field=models.CharField(
                blank=True,
                help_text="Legacy: Use iadc_code_ref FK instead",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="name",
            field=models.CharField(
                blank=True, help_text="Legacy: Use hdbs_type instead", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="nozzle_config",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nozzle Configuration"
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="revision",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="design",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workorders.bitsize",
                verbose_name="Size",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="tfa",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Total Flow Area (sq. inches)",
                max_digits=6,
                null=True,
                verbose_name="TFA",
            ),
        ),
    ]
