# Generated by Django 5.1.15 on 2025-12-13 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0004_design_phase2_enhancements"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpperSectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "can_replace_in_ksa",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this upper section type can be replaced/repaired in Saudi Arabia",
                        verbose_name="Can Replace in KSA",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Additional notes about this type"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Upper Section Type",
                "verbose_name_plural": "Upper Section Types",
                "db_table": "upper_section_types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="design",
            name="upper_section_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of upper section/shank (some cannot be replaced in KSA)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="technology.uppersectiontype",
                verbose_name="Upper Section Type",
            ),
        ),
    ]
