# Generated by Django 5.1.15 on 2025-12-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0007_breaker_slot_model"),
    ]

    operations = []
