# Generated by Django 5.1.15 on 2025-12-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0010_pocket_layout_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="pocket_layout_number",
            field=models.CharField(
                blank=True,
                help_text="Identifier for cloning pocket layouts between similar designs",
                max_length=20,
                verbose_name="Pocket Layout Number",
            ),
        ),
    ]
