# Generated by Django 5.1.15 on 2025-12-22
# Custom migration to move BitSize and BitType from workorders to technology
# Uses SeparateDatabaseAndState because tables already exist

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0013_add_blade_location_to_pocket"),
    ]

    operations = [
        # Create BitSize model (state-only - table already exists as bit_sizes)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="BitSize",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("code", models.CharField(help_text="e.g., '8.500'", max_length=20, unique=True)),
                        ("size_decimal", models.DecimalField(decimal_places=3, help_text="Size in decimal inches (e.g., 8.500)", max_digits=6)),
                        ("size_display", models.CharField(help_text="Display format (e.g., '8 1/2\"')", max_length=20)),
                        ("size_inches", models.CharField(help_text="Fraction format (e.g., '8 1/2')", max_length=20)),
                        ("is_active", models.BooleanField(default=True)),
                    ],
                    options={
                        "verbose_name": "Bit Size",
                        "verbose_name_plural": "Bit Sizes",
                        "db_table": "bit_sizes",
                        "ordering": ["size_decimal"],
                    },
                ),
            ],
            database_operations=[],
        ),
        # Update FKs to point to new technology.BitSize (state-only - same table)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="breakerslot",
                    name="compatible_sizes",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Bit sizes this breaker slot is compatible with",
                        related_name="breaker_slots",
                        to="technology.bitsize",
                        verbose_name="Compatible Bit Sizes",
                    ),
                ),
                migrations.AlterField(
                    model_name="design",
                    name="size",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="technology.bitsize",
                        verbose_name="Size",
                    ),
                ),
            ],
            database_operations=[],
        ),
        # Create BitType model (state-only - table already exists as bit_types)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="BitType",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("code", models.CharField(help_text="Model code (e.g., 'GT65RHS')", max_length=50, unique=True)),
                        ("name", models.CharField(blank=True, max_length=100)),
                        ("series", models.CharField(blank=True, help_text="Series (GT, HD, MM, FX, EM, etc.)", max_length=20)),
                        ("description", models.TextField(blank=True)),
                        ("is_active", models.BooleanField(default=True)),
                        ("category", models.CharField(choices=[("FC", "Fixed Cutter"), ("MT", "Mill Tooth"), ("TCI", "Tri Cone Inserts")], default="FC", help_text="FC=Fixed Cutter, MT=Mill Tooth, TCI=Tri Cone Inserts", max_length=10)),
                        ("smi_name", models.CharField(blank=True, help_text="SMI/Client-facing name (e.g., 'GT65RHs-1')", max_length=50)),
                        ("hdbs_name", models.CharField(blank=True, help_text="Internal HDBS name", max_length=50)),
                        ("hdbs_mn", models.CharField(blank=True, help_text="HDBS SAP Material Number", max_length=20)),
                        ("ref_hdbs_mn", models.CharField(blank=True, help_text="Parent/Reference HDBS Material Number", max_length=20)),
                        ("ardt_item_number", models.CharField(blank=True, help_text="ARDT ERP Item Number", max_length=20)),
                        ("body_material", models.CharField(blank=True, choices=[("M", "Matrix"), ("S", "Steel"), ("", "N/A")], default="", help_text="Body material: M=Matrix, S=Steel", max_length=1)),
                        ("no_of_blades", models.PositiveIntegerField(blank=True, help_text="Number of blades (FC only)", null=True)),
                        ("cutter_size", models.PositiveIntegerField(blank=True, help_text="Cutter size in mm (FC only)", null=True)),
                        ("gage_length", models.DecimalField(blank=True, decimal_places=1, help_text="Gage length in inches (FC only)", max_digits=4, null=True)),
                        ("order_level", models.CharField(blank=True, choices=[("3", "Level 3 - No cutters, upper section separate"), ("4", "Level 4 - No cutters, upper section welded/machined"), ("5", "Level 5 - With cutters brazed"), ("6", "Level 6 - Painted and ready for use")], help_text="JV Production Level: 3-6", max_length=5)),
                        ("size", models.ForeignKey(blank=True, help_text="Standard bit size", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="bit_types", to="technology.bitsize")),
                    ],
                    options={
                        "verbose_name": "Bit Type",
                        "verbose_name_plural": "Bit Types",
                        "db_table": "bit_types",
                        "ordering": ["category", "series", "smi_name", "code"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
