# Generated by Django 5.1.15 on 2025-12-22 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0014_bitsize_alter_breakerslot_compatible_sizes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitsize",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional remarks or description"
            ),
        ),
        migrations.CreateModel(
            name="HDBSType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hdbs_name",
                    models.CharField(
                        help_text="Internal HDBS type name (e.g., GT65RHS)",
                        max_length=50,
                        unique=True,
                        verbose_name="HDBS Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description or remarks"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sizes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Bit sizes this type is available in",
                        related_name="hdbs_types",
                        to="technology.bitsize",
                        verbose_name="Compatible Sizes",
                    ),
                ),
            ],
            options={
                "verbose_name": "HDBS Type",
                "verbose_name_plural": "HDBS Types",
                "db_table": "hdbs_types",
                "ordering": ["hdbs_name"],
            },
        ),
        migrations.CreateModel(
            name="SMIType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smi_name",
                    models.CharField(
                        help_text="Client-facing type name (e.g., GT65RHs-1)",
                        max_length=50,
                        verbose_name="SMI Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description or remarks"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hdbs_type",
                    models.ForeignKey(
                        help_text="The internal HDBS type this SMI name maps to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smi_types",
                        to="technology.hdbstype",
                        verbose_name="HDBS Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMI Type",
                "verbose_name_plural": "SMI Types",
                "db_table": "smi_types",
                "ordering": ["hdbs_type__hdbs_name", "smi_name"],
                "unique_together": {("smi_name", "hdbs_type")},
            },
        ),
    ]
