# Generated by Django 5.1.15 on 2025-12-23 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0015_add_hdbs_smi_type_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smitype",
            options={
                "ordering": ["hdbs_type__hdbs_name", "size__size_decimal", "smi_name"],
                "verbose_name": "SMI Type",
                "verbose_name_plural": "SMI Types",
            },
        ),
        migrations.AlterUniqueTogether(
            name="smitype",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="smitype",
            name="size",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific size for this SMI name (leave blank for all sizes)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="smi_types",
                to="technology.bitsize",
                verbose_name="Size",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="smitype",
            unique_together={("smi_name", "hdbs_type", "size")},
        ),
    ]
