# Generated by Django 5.1.15 on 2025-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0018_require_size_on_smitype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hdbstype",
            name="sizes",
            field=models.ManyToManyField(
                help_text="Bit sizes this type is available in (at least one required)",
                related_name="hdbs_types",
                to="technology.bitsize",
                verbose_name="Compatible Sizes",
            ),
        ),
    ]
