# Generated by Django 5.1.15 on 2026-01-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0021_bom_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="smi_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Client-facing type for this L5 BOM",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boms",
                to="technology.smitype",
                verbose_name="SMI Type",
            ),
        ),
    ]
