# Generated by Django 5.1.15 on 2026-01-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0023_add_pad_to_blade_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designpocket",
            name="blade_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Cone"),
                    ("N", "Nose"),
                    ("S", "Shoulder"),
                    ("G", "Gage"),
                    ("P", "Pad"),
                ],
                help_text="Location zone on blade: Cone, Nose, Taper, Shoulder, Gage",
                max_length=1,
                null=True,
                verbose_name="Blade Location",
            ),
        ),
    ]
