# Generated by Django 5.1.15 on 2026-01-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0024_remove_taper_from_blade_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="source_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete extracted/edited data from PDF (header, summary, blades)",
            ),
        ),
    ]
