# Generated by Django 5.1.15 on 2026-01-23 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0027_add_system_mat_no_to_bom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="original_source_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Original baseline source data (set on first creation, never modified)",
            ),
        ),
        migrations.CreateModel(
            name="BOMVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Initial Creation"),
                            ("UPDATED", "Updated"),
                            ("CUTTER_ADDED", "Cutter Added"),
                            ("CUTTER_REMOVED", "Cutter Removed"),
                            ("CUTTER_CHANGED", "Cutter Changed"),
                            ("LAYOUT_CHANGED", "Layout Changed"),
                            ("ACTIVATED", "Activated"),
                            ("OBSOLETED", "Made Obsolete"),
                        ],
                        default="UPDATED",
                        max_length=20,
                    ),
                ),
                (
                    "change_summary",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of changes",
                        max_length=500,
                    ),
                ),
                (
                    "source_data_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete source_data at the time of this version",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="technology.bom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bom_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM Version",
                "verbose_name_plural": "BOM Versions",
                "db_table": "bom_versions",
                "ordering": ["bom", "-version_number"],
                "unique_together": {("bom", "version_number")},
            },
        ),
    ]
