# Generated by Django 5.1.15 on 2026-01-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0028_add_bom_version_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="quantity_on_hand",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Current stock quantity from ERP On-hand",
                verbose_name="Qty On Hand",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="stock_last_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="When stock was last synced from ERP",
                null=True,
                verbose_name="Stock Last Updated",
            ),
        ),
    ]
