# Generated by Django 5.1.15 on 2026-01-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0029_add_design_stock_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="quantity_on_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordered in total from ERP",
                verbose_name="Qty On Order",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="quantity_on_hand",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Physical inventory from ERP",
                verbose_name="Qty On Hand",
            ),
        ),
    ]
