# Generated by Django 5.1.15 on 2026-01-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0030_add_quantity_on_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="is_original",
            field=models.BooleanField(
                default=False,
                help_text="Mark as Original (master template). Protected from serial-specific overwrites.",
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="parent_bom",
            field=models.ForeignKey(
                blank=True,
                help_text="Original BOM this was copied from (for serial-specific copies)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="serial_copies",
                to="technology.bom",
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Serial number this BOM was created for (empty = generic/original)",
                max_length=50,
            ),
        ),
    ]
