# Generated by Django 5.1.15 on 2026-02-26 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0033_remove_bom_work_order_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designpocket",
            name="pocket_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pockets",
                to="technology.designpocketconfig",
                verbose_name="Pocket Configuration",
            ),
        ),
    ]
