# Generated by Django 5.1.15 on 2026-03-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0034_fix_designpocket_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="designpocketconfig",
            name="length_code",
            field=models.CharField(
                blank=True,
                help_text="Raw length value from inventory (e.g., 08, 13, 16)",
                max_length=10,
                verbose_name="Length Code",
            ),
        ),
    ]
