# Generated by Django 5.1.15 on 2026-03-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0035_add_length_code_to_pocket_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bittype",
            name="order_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3", "Level 3 - No cutters, upper section separate"),
                    ("4", "Level 4 - No cutters, upper section welded/machined"),
                    ("5", "Level 5 - With cutters brazed"),
                    (
                        "5.5",
                        "Level 5.5 - Brazed head, unwelded upper (needs sub-arc welding + machining)",
                    ),
                    ("6", "Level 6 - Painted and ready for use"),
                ],
                help_text="JV Production Level: 3-6",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="order_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3", "Level 3 - No cutters, upper section separate"),
                    ("4", "Level 4 - No cutters, upper section welded/machined"),
                    ("5", "Level 5 - With cutters brazed"),
                    (
                        "5.5",
                        "Level 5.5 - Brazed head, unwelded upper (needs sub-arc welding + machining)",
                    ),
                    ("6", "Level 6 - Painted and ready for use"),
                ],
                max_length=5,
                verbose_name="Order Level",
            ),
        ),
    ]
