# Generated by Django 5.1.15 on 2026-03-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0036_add_level_5_5_order_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="fc_product_type",
            field=models.CharField(
                choices=[("DRILL_BIT", "Drill Bit"), ("CORE_HEAD", "Core Head")],
                default="DRILL_BIT",
                help_text="Drill Bit or Core Head — affects route (core grinding, insool wrap)",
                max_length=15,
                verbose_name="FC Product Type",
            ),
        ),
    ]
